mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-64a74f19
  type: vless
  server: 91.99.194.113
  port: 10195
  uuid: 913a8cd8-11ab-4d16-a6f7-c7b88d7a592e
  udp: true
  network: tcp
- name: vless-1b60b2bc
  type: vless
  server: 91.99.129.82
  port: 443
  uuid: f73e9865-80c3-45ba-8391-597139c37bdc
  udp: true
  network: tcp
- name: vless-348b2390
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: ss-0270f07e
  type: ss
  server: 74.177.202.58
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: ss-31593fea
  type: ss
  server: 131.145.34.231
  port: 443
  cipher: chacha20-ietf-poly1305
  password: Bog0ELmMM9DSxDdQ
  udp: true
- name: vless-1b8cc3cb
  type: vless
  server: 91.99.234.129
  port: 38385
  uuid: 85387693-7c6c-48f1-a8dd-48d67bfb4012
  udp: true
  network: tcp
- name: vless-f7cd8674
  type: vless
  server: 0ost.amazon-osishop.ir
  port: 8880
  uuid: 13dea011-7fe6-43db-a0cb-e9661cd86b25
  udp: true
  network: tcp
- name: vless-f2030ef8
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: سرورهایبیشتردرکانالvpn_mmdparsa-1dd707e9
  type: ss
  server: 131.145.34.231
  port: 443
  cipher: chacha20-ietf-poly1305
  password: Bog0ELmMM9DSxDdQ
  udp: true
- name: vpn_mmdparsaتمامنتها-543749bd
  type: vless
  server: bot.nimeshab-nabod.info
  port: 80
  uuid: b7ef3741-92f4-4302-9b06-9f943f3700e5
  udp: true
  network: ws
  ws-opts:
    path: /@itsproxy?ed=2560
    headers:
      Host: Behrfbot.global.ssl.fastly.net
- name: Sezar_Sec-1fbc771b
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-27fd1132
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-7271cba8
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-5e96656e
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-5f43a9fa
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-c30bf18f
  type: vmess
  server: 91.99.155.33
  port: 443
  uuid: f79903d3-8673-4e6e-b07f-1bc227fb1be8
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: مشتی_جوین_بده_ناموصا__xzjinx-073932f3
  type: vmess
  server: 91.99.155.33
  port: 443
  uuid: f79903d3-8673-4e6e-b07f-1bc227fb1be8
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: مشتی_جوین_بده_ناموصا__xzjinx-74b461c8
  type: vmess
  server: 87.107.144.71
  port: 46041
  uuid: a9f1b1db-47aa-44c2-d338-08166996605f
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: مشتی_جوین_بده_ناموصا__xzjinx-a6b64c5c
  type: vmess
  server: 87.107.144.71
  port: 46041
  uuid: a9f1b1db-47aa-44c2-d338-08166996605f
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: مشتی_جوین_بده_ناموصا__xzjinx-e2f45dc8
  type: vmess
  server: 91.99.155.33
  port: 443
  uuid: 44b5cbf9-95d9-4a08-88da-059cc9368e32
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: مشتی_جوین_بده_ناموصا__xzjinx-3d337fe4
  type: vmess
  server: 91.99.155.33
  port: 443
  uuid: 44b5cbf9-95d9-4a08-88da-059cc9368e32
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: مشتی_جوین_بده_ناموصا__xzjinx-513064a0
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: 10b1f4a3-63a7-46b4-f05a-023542f0dc11
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-f7fd0dc6
  type: vmess
  server: 185.18.214.174
  port: 8080
  uuid: baf451ee-ab34-4a28-de9f-1fa918d79fc1
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-7623a6ec
  type: vmess
  server: 185.18.214.174
  port: 8080
  uuid: baf451ee-ab34-4a28-de9f-1fa918d79fc1
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: vless-898d7624
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-ed323704
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-b568c5eb
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-454ad0dc
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-be4c5b2b
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-3e78199e
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-33a2cf26
  type: vless
  server: 91.99.172.196
  port: 28041
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: WpvjPUZ5x3SIvDzSr5q9v0bfhzo36obh3CXIqJVmnkY
    short-id: 91355b9b818617
- name: vless-f69de72c
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-64a74f19
  - vless-1b60b2bc
  - vless-348b2390
  - ss-0270f07e
  - ss-31593fea
  - vless-1b8cc3cb
  - vless-f7cd8674
  - vless-f2030ef8
  - سرورهایبیشتردرکانالvpn_mmdparsa-1dd707e9
  - vpn_mmdparsaتمامنتها-543749bd
  - Sezar_Sec-1fbc771b
  - Sezar_Sec-27fd1132
  - Sezar_Sec-7271cba8
  - Sezar_Sec-5e96656e
  - Sezar_Sec-5f43a9fa
  - مشتی_جوین_بده_ناموصا__xzjinx-c30bf18f
  - مشتی_جوین_بده_ناموصا__xzjinx-073932f3
  - مشتی_جوین_بده_ناموصا__xzjinx-74b461c8
  - مشتی_جوین_بده_ناموصا__xzjinx-a6b64c5c
  - مشتی_جوین_بده_ناموصا__xzjinx-e2f45dc8
  - مشتی_جوین_بده_ناموصا__xzjinx-3d337fe4
  - مشتی_جوین_بده_ناموصا__xzjinx-513064a0
  - مشتی_جوین_بده_ناموصا__xzjinx-f7fd0dc6
  - مشتی_جوین_بده_ناموصا__xzjinx-7623a6ec
  - vless-898d7624
  - vless-ed323704
  - vless-b568c5eb
  - vless-454ad0dc
  - vless-be4c5b2b
  - vless-3e78199e
  - vless-33a2cf26
  - vless-f69de72c
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
