mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-89c93b11
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-52e3a0f5
  type: vless
  server: 91.99.172.196
  port: 28041
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: WpvjPUZ5x3SIvDzSr5q9v0bfhzo36obh3CXIqJVmnkY
    short-id: 91355b9b818617
- name: vless-0aad03c8
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-255e17f6
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-8ce398b3
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-36f2c489
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-3e11c31f
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-20c67b6d
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-8774917a
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-ebff8957
  type: vless
  server: accounting.vinamarketcenter.ir
  port: 443
  uuid: 5cfba4ac-105a-452a-ac10-88b1adf784ee
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: T7Cwk-B3EvZqqRywIgN_TNotJiUOXYUI9bHqYKPnTi0
    short-id: 105e89ba3d2a1c3b
- name: trojan-97d4fc97
  type: trojan
  server: 91.107.163.173
  port: 27596
  password: OmqcThZWp1
  udp: true
  skip-cert-verify: true
- name: vless-0e6204c3
  type: vless
  server: 91.99.160.151
  port: 443
  uuid: 153ee04c-dcc1-4ef8-a146-8fb31cec1f48
  udp: true
  network: tcp
- name: vless-39ea83b6
  type: vless
  server: 62.60.223.6
  port: 2080
  uuid: bea34b73-3244-475b-b914-7bb80e1cda91
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: L3lJWdU7mHijSkNaNt-m29OYnKnHvHYRxg2Y8XXFdng
    short-id: bf517367267685
- name: vless-5707c2b2
  type: vless
  server: 91.99.195.6
  port: 80
  uuid: 91a5d5b3-4b88-4359-aeec-e1532f535fd6
  udp: true
  network: grpc
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZO276Z5WXIqCmNLXT8Lewzjhhgm365JUJXAKyKq8Rz4
    short-id: bc063769cb
  grpc-opts:
    grpc-service-name: refersion.com
- name: vless-02de2ff2
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /zula.ir
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: vless-aca54f23
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-48068c78
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-3ae7ca96
  type: vless
  server: 91.99.184.231
  port: 45103
  uuid: 6bdc18b7-a33f-46ae-a5e3-df7cb21f36b2
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: Channelalammzar-8fc4df5e
  type: vless
  server: safar64.ucpubg.org
  port: 8080
  uuid: c83a4cdf-d744-43c4-866a-f85957050391
  udp: true
  network: tcp
- name: قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-0e9c7e28
  type: vless
  server: real-all2.sdcards.ir
  port: 8509
  uuid: 1b3b7c47-2c50-4df0-952b-c50703876c69
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: LD--N4X5Fo6UKi8c6XIUGfFCuRWKmvLHk_bwacZVDD4
    short-id: 67ceba05200e42df
- name: xixv2ray__-_UK-6932c46f
  type: vless
  server: 194.147.35.250
  port: 443
  uuid: 2bc38bf1-e880-5b6b-8795-590c7a67258e
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: zula.ir
  ws-opts:
    path: /vless
    headers:
      Host: 194.147.35.250
- name: Golestan_VPN_-__خرید_کانفیگ-b4f6eb1e
  type: vmess
  server: 62.146.233.53
  port: 50678
  uuid: 5d1ec6e7-fd58-4e85-91c5-6335a86d2775
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: Golestan_VPN_-__خرید_کانفیگ-d3d3804b
  type: vmess
  server: 62.146.233.53
  port: 50678
  uuid: 5d1ec6e7-fd58-4e85-91c5-6335a86d2775
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: Golestan_VPN_-__خرید_کانفیگ-e6e17fb6
  type: vless
  server: 45.82.251.63
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: Golestan_VPN_-__خرید_کانفیگ-053e0e62
  type: vmess
  server: 91.99.158.148
  port: 52262
  uuid: af5a0d0c-c898-4a51-ba6a-47179d483e41
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: Golestan_VPN_-__خرید_کانفیگ-5b0f5027
  type: vmess
  server: 91.99.158.148
  port: 52262
  uuid: af5a0d0c-c898-4a51-ba6a-47179d483e41
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: Golestan_VPN_-__خرید_کانفیگ-1439dd79
  type: vmess
  server: 46.250.243.56
  port: 50394
  uuid: a75f3f95-ad4e-4498-fc72-dd740dd02bfc
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: Golestan_VPN_-__خرید_کانفیگ-9eaf7f90
  type: vmess
  server: 46.250.243.56
  port: 50394
  uuid: a75f3f95-ad4e-4498-fc72-dd740dd02bfc
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: Sezar_Sec-87cc85e9
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-fdbd2efc
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-f7338caa
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-8842dc07
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-ad40ab56
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: Sezar_Sec-806fb94d
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: مشتی_جوین_بده_ناموصا__xzjinx-7b6b0cbe
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: d64669fb-07e5-4d27-9995-63545fae16c2
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-800b68a7
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: d64669fb-07e5-4d27-9995-63545fae16c2
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-cc55bc72
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: f7255d17-4abc-4c54-84dd-e1e9e9c41dad
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-125f4295
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: 395bf21d-ea83-4d85-ad04-ad1f6b1431bf
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-ea7cb5d3
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: 395bf21d-ea83-4d85-ad04-ad1f6b1431bf
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-17936559
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: 49203d20-5f1b-4628-d526-9a6825c3f5f3
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-1beb206d
  type: vless
  server: 5.160.197.120
  port: 16644
  uuid: c2d3a355-e556-40e0-cd5a-41dff6eb525d
  udp: true
  network: tcp
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-89c93b11
  - vless-52e3a0f5
  - vless-0aad03c8
  - vless-255e17f6
  - vless-8ce398b3
  - vless-36f2c489
  - vless-3e11c31f
  - vless-20c67b6d
  - vless-8774917a
  - vless-ebff8957
  - trojan-97d4fc97
  - vless-0e6204c3
  - vless-39ea83b6
  - vless-5707c2b2
  - vless-02de2ff2
  - vless-aca54f23
  - vless-48068c78
  - vless-3ae7ca96
  - Channelalammzar-8fc4df5e
  - قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-0e9c7e28
  - xixv2ray__-_UK-6932c46f
  - Golestan_VPN_-__خرید_کانفیگ-b4f6eb1e
  - Golestan_VPN_-__خرید_کانفیگ-d3d3804b
  - Golestan_VPN_-__خرید_کانفیگ-e6e17fb6
  - Golestan_VPN_-__خرید_کانفیگ-053e0e62
  - Golestan_VPN_-__خرید_کانفیگ-5b0f5027
  - Golestan_VPN_-__خرید_کانفیگ-1439dd79
  - Golestan_VPN_-__خرید_کانفیگ-9eaf7f90
  - Sezar_Sec-87cc85e9
  - Sezar_Sec-fdbd2efc
  - Sezar_Sec-f7338caa
  - Sezar_Sec-8842dc07
  - Sezar_Sec-ad40ab56
  - Sezar_Sec-806fb94d
  - مشتی_جوین_بده_ناموصا__xzjinx-7b6b0cbe
  - مشتی_جوین_بده_ناموصا__xzjinx-800b68a7
  - مشتی_جوین_بده_ناموصا__xzjinx-cc55bc72
  - مشتی_جوین_بده_ناموصا__xzjinx-125f4295
  - مشتی_جوین_بده_ناموصا__xzjinx-ea7cb5d3
  - مشتی_جوین_بده_ناموصا__xzjinx-17936559
  - مشتیجوینبدهناموصاxzjinx-1beb206d
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
