mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 8.8.8.8
  - 1.1.1.1
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
proxies:
- name: vless-14dabd9e
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-96e59048
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-ccc5f06f
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-e2c4f21b
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-b53b8060
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-40bb1c9d
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-b790cd65
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-cf719199
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: مشتی_جوین_بده_ناموصا__xzjinx-12564dc2
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: e6daaeba-5a7c-4933-89b0-0078c14c50f1
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-cf69409e
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: b54eaa6b-d4fc-4bb3-b3c6-9d0b61da00f7
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-768dee0c
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  network: tcp
- name: vless-86cb2905
  type: vless
  server: vpconnect.ahadbala.ir
  port: 80
  uuid: 3f0c3cef-75c0-4253-a62e-d89f5a45dcc1
  udp: true
  network: tcp
- name: vless-b9801813
  type: vless
  server: fastlyeeeeee.fast.hosting-ip.com
  port: 80
  uuid: cdnfastlycash
  udp: true
  network: xhttp
- name: vless-db71f16e
  type: vless
  server: de1.cowjuice.me
  port: 443
  uuid: 955827fc-c729-4a1e-ba6c-d85754c8e937
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: thelocal.de
  reality-opts:
    public-key: O9DMPpwicRcMofaplcvpQStNRogPS_HJY0s5_4EaKQc
    short-id: aabbccdd
    fingerprint: chrome
- name: vless-0e008247
  type: vless
  server: de6.razercompany.com
  port: 33200
  uuid: c4389c70-1e5a-4bd2-934f-44fb2e62ccf5
  udp: true
  network: tcp
- name: vless-37d7e027
  type: vless
  server: real-all3.sdcards.ir
  port: 8501
  uuid: 9666ee62-d1f3-4f6e-8881-c17fee524e31
  udp: true
  network: tcp
  tls: true
  servername: tgju.org
  reality-opts:
    public-key: OJ0wA5wp55uZdD16dutlTZvx1x-rbMMXmiO9D_MMCHI
    short-id: e701a013553059ba
    fingerprint: firefox
- name: vless-6f7ba403
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: vless-7b98b524
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /zula.ir
    headers:
      Host: sub.divib.dynv6.net
- name: vless-ed581022
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-f0c628f0
  type: vless
  server: compose.fast.hosting-ip.com
  port: 80
  uuid: ab80613b-e04b-4af5-bad9-9ca5c448266e
  udp: true
  network: xhttp
- name: Music_raygan__کانفینگ_تل_سرچ_کن-bb87cdea
  type: vless
  server: 141.101.121.55
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: WANCLOUDFA-169e9408
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: 04327cef-1084-431a-d595-cfcf9593cbc3
  udp: true
  network: xhttp
- name: AbolfazlModiri85-10GB_Free-0738a5cc
  type: vmess
  server: 194.135.46.24
  port: 8585
  uuid: 96191481-7ba8-452c-8e2e-652783e99bbe
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: سرورهایرایگاندرکانالsatellitenewspersian-cd66919b
  type: vless
  server: 104.26.6.95
  port: 80
  uuid: 1f98b5cc-140f-46b4-987f-6936da9f2238
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: crxre.ribiwa9933.workers.dev
- name: Sezar_sec-3cf39e5c
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
    fingerprint: chrome
- name: Sezar_sec-505f2493
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: Sezar_sec-dffafd3f
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
  skip-cert-verify: true
proxy-groups:
- name: 🚀 PROXY
  type: select
  proxies:
  - ♻️ AUTO
  - DIRECT
  - vless-14dabd9e
  - vless-96e59048
  - vless-ccc5f06f
  - vless-e2c4f21b
  - vless-b53b8060
  - vless-40bb1c9d
  - vless-b790cd65
  - vless-cf719199
  - مشتی_جوین_بده_ناموصا__xzjinx-12564dc2
  - مشتی_جوین_بده_ناموصا__xzjinx-cf69409e
  - مشتی_جوین_بده_ناموصا__xzjinx-768dee0c
  - vless-86cb2905
  - vless-b9801813
  - vless-db71f16e
  - vless-0e008247
  - vless-37d7e027
  - vless-6f7ba403
  - vless-7b98b524
  - vless-ed581022
  - vless-f0c628f0
  - Music_raygan__کانفینگ_تل_سرچ_کن-bb87cdea
  - WANCLOUDFA-169e9408
  - AbolfazlModiri85-10GB_Free-0738a5cc
  - سرورهایرایگاندرکانالsatellitenewspersian-cd66919b
  - Sezar_sec-3cf39e5c
  - Sezar_sec-505f2493
  - Sezar_sec-dffafd3f
- name: ♻️ AUTO
  type: url-test
  proxies:
  - vless-14dabd9e
  - vless-96e59048
  - vless-ccc5f06f
  - vless-e2c4f21b
  - vless-b53b8060
  - vless-40bb1c9d
  - vless-b790cd65
  - vless-cf719199
  - مشتی_جوین_بده_ناموصا__xzjinx-12564dc2
  - مشتی_جوین_بده_ناموصا__xzjinx-cf69409e
  - مشتی_جوین_بده_ناموصا__xzjinx-768dee0c
  - vless-86cb2905
  - vless-b9801813
  - vless-db71f16e
  - vless-0e008247
  - vless-37d7e027
  - vless-6f7ba403
  - vless-7b98b524
  - vless-ed581022
  - vless-f0c628f0
  - Music_raygan__کانفینگ_تل_سرچ_کن-bb87cdea
  - WANCLOUDFA-169e9408
  - AbolfazlModiri85-10GB_Free-0738a5cc
  - سرورهایرایگاندرکانالsatellitenewspersian-cd66919b
  - Sezar_sec-3cf39e5c
  - Sezar_sec-505f2493
  - Sezar_sec-dffafd3f
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- GEOIP,IR,DIRECT
- MATCH,🚀 PROXY
