proxies:
- name: vless-70255c9b
  type: vless
  server: gsoowjowj.toppho.ir
  port: 8443
  uuid: Anty_Vpn-Anty_Vpn-Anty_Vpn
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-6a90026f
  type: vless
  server: rim.fullbodystore.com.tr
  port: 443
  uuid: 2406a224-ba26-43fb-99db-5da807253a5f
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: www.google.com
- name: vless-1cdcc611
  type: vless
  server: 212.86.94.101
  port: 33177
  uuid: a8ed95a6-7f54-48d6-bdcf-6c272851b81f
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
proxy-groups:
- name: 🚀 Auto Select
  type: url-test
  proxies:
  - vless-70255c9b
  - vless-6a90026f
  - vless-1cdcc611
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 Proxy
  type: select
  proxies:
  - 🚀 Auto Select
  - DIRECT
- name: 🎯 Domestic
  type: select
  proxies:
  - DIRECT
rules:
- DOMAIN-SUFFIX,ir,🎯 Domestic
- GEOIP,IR,🎯 Domestic
- MATCH,🔮 Proxy
