port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: vless-74f31512
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-368378c9
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: vless-08ea0b98
  type: vless
  server: real-all3.sdcards.ir
  port: 8501
  uuid: 9666ee62-d1f3-4f6e-8881-c17fee524e31
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: OJ0wA5wp55uZdD16dutlTZvx1x-rbMMXmiO9D_MMCHI
    short-id: e701a013553059ba
- name: Sezar_Sec-699019eb
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  tls: false
  network: tcp
- name: vless-7df83471
  type: vless
  server: de1.cowjuice.me
  port: 443
  uuid: 955827fc-c729-4a1e-ba6c-d85754c8e937
  udp: true
  tls: false
  network: tcp
  servername: thelocal.de
  reality-opts:
    public-key: O9DMPpwicRcMofaplcvpQStNRogPS_HJY0s5_4EaKQc
    short-id: aabbccdd
- name: vless-f49c5d0e
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-dd9d8947
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: net0n3_281-27160cc5
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: مشتی_جوین_بده_ناموصا__xzjinx-9c715eec
  type: vless
  server: 94.182.136.184
  port: 159
  uuid: 0af94a54-f5d8-43dd-8544-77a56559ea1c
  udp: true
  tls: false
  network: tcp
- name: vless-e7e56639
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: vless-52299866
  type: vless
  server: de6.razercompany.com
  port: 33200
  uuid: c4389c70-1e5a-4bd2-934f-44fb2e62ccf5
  udp: true
  tls: false
  network: tcp
- name: vless-4ae90365
  type: vless
  server: compose.fast.hosting-ip.com
  port: 80
  uuid: ab80613b-e04b-4af5-bad9-9ca5c448266e
  udp: true
  tls: false
  network: xhttp
- name: vless-226987d7
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-c1d6f715
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: YOOZCARD-39d66f19
  type: vless
  server: filim.hashtag.cinemaaliiiiii.top
  port: 2096
  uuid: 3eb40674-856d-449d-a321-c56b9675f127
  udp: true
  tls: false
  network: grpc
- name: vless-41e436f7
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-f895ff72
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-38a53638
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-15464ce4
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-e4f39300
  type: vless
  server: 91.99.172.196
  port: 28041
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: WpvjPUZ5x3SIvDzSr5q9v0bfhzo36obh3CXIqJVmnkY
    short-id: 91355b9b818617
- name: vless-ab63493a
  type: vless
  server: bam.erfann.shop
  port: 15807
  uuid: 8e4d0dba-884f-4bbd-9f1d-ea5ec78efe7d
  udp: true
  tls: false
  network: tcp
- name: تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-63999046
  type: ss
  server: series-a2-me.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: Bog0ELmMM9DSxDdQ
  udp: true
- name: vless-65ae85ec
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-f009ff12
  type: vless
  server: 154.92.9.30
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  servername: simorgh.hpcode.ir
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: Sezar_sec-bd6dfc2c
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: Sezar_Sec-94297ad8
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-ff0bb020
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: vless-72a624f5
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  tls: false
  network: tcp
- name: vless-60cb4dcb
  type: vless
  server: vpconnect.ahadbala.ir
  port: 80
  uuid: 3f0c3cef-75c0-4253-a62e-d89f5a45dcc1
  udp: true
  tls: false
  network: tcp
- name: Sezar_sec-9675a536
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
- name: vless-89bb2169
  type: vless
  server: hell.dl101movis.ir
  port: 80
  uuid: d601250a-e54f-46fe-a984-fb0f1d6d48ce
  udp: true
  tls: false
  network: xhttp
- name: تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-b91fada0
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: turboo-server
  udp: true
  tls: false
  network: xhttp
- name: مشتی_جوین_بده_ناموصا__xzjinx-ec4b3c6c
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  tls: false
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-951b61f5
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: b54eaa6b-d4fc-4bb3-b3c6-9d0b61da00f7
  udp: true
  tls: false
  network: tcp
- name: net0n3_283-bd7521c5
  type: ss
  server: 45.87.175.165
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: QCXDxuDlTTMD7jtgHUjIoj
  udp: true
- name: Sezar_Sec-85f82310
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: vless-b9d9ff7c
  type: vless
  server: fastlyeeeeee.fast.hosting-ip.com
  port: 80
  uuid: cdnfastlycash
  udp: true
  tls: false
  network: xhttp
- name: vless-69533fe6
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: Sezar_sec-310b982f
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  tls: false
  network: tcp
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: مشتی_جوین_بده_ناموصا__xzjinx-17aaf5e9
  type: vless
  server: 31.47.45.173
  port: 777
  uuid: ce55d3ed-618b-45b7-d879-368fbb465efd
  udp: true
  tls: false
  network: tcp
- name: vless-ab3bedb3
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: nginx.nscl.ir
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: TelegramMrsoulb-a60d96d3
  type: vless
  server: 91.107.180.100
  port: 45489
  uuid: 02690c4d-fa55-4bbe-9703-10e027562bf2
  udp: true
  tls: false
  network: tcp
- name: vless-42122a73
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-abb14b91
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sub.divib.dynv6.net
- name: مشتی_جوین_بده_ناموصا__xzjinx-dca7ee12
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: 09694965-369f-48b5-82fa-40aae0236746
  udp: true
  tls: false
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-f9634e8c
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: e6daaeba-5a7c-4933-89b0-0078c14c50f1
  udp: true
  tls: false
  network: tcp
- name: تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-183d3683
  type: vless
  server: 300232332.webnama.com.tr
  port: 1517
  uuid: 188f1242-b0c0-4992-b480-1da44dae1700
  udp: true
  tls: false
  network: tcp
- name: vless-55ab7375
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-3e03a295
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: Sezar_Sec-785a77ea
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: TelegramMrsoulb-4c018f6b
  type: ss
  server: join.vpncustomize.vpncustomize.reziazaran.ir
  port: 443
  cipher: chacha20-ietf-poly1305
  password: Bog0ELmMM9DSxDdQ
  udp: true
- name: vless-b15229f6
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - vless-74f31512
  - vless-368378c9
  - vless-08ea0b98
  - Sezar_Sec-699019eb
  - vless-7df83471
  - vless-f49c5d0e
  - vless-dd9d8947
  - net0n3_281-27160cc5
  - مشتی_جوین_بده_ناموصا__xzjinx-9c715eec
  - vless-e7e56639
  - vless-52299866
  - vless-4ae90365
  - vless-226987d7
  - vless-c1d6f715
  - YOOZCARD-39d66f19
  - vless-41e436f7
  - vless-f895ff72
  - vless-38a53638
  - vless-15464ce4
  - vless-e4f39300
  - vless-ab63493a
  - تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-63999046
  - vless-65ae85ec
  - تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-f009ff12
  - Sezar_sec-bd6dfc2c
  - Sezar_Sec-94297ad8
  - Sezar_Sec-ff0bb020
  - vless-72a624f5
  - vless-60cb4dcb
  - Sezar_sec-9675a536
  - vless-89bb2169
  - تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-b91fada0
  - مشتی_جوین_بده_ناموصا__xzjinx-ec4b3c6c
  - مشتی_جوین_بده_ناموصا__xzjinx-951b61f5
  - net0n3_283-bd7521c5
  - Sezar_Sec-85f82310
  - vless-b9d9ff7c
  - vless-69533fe6
  - Sezar_sec-310b982f
  - مشتی_جوین_بده_ناموصا__xzjinx-17aaf5e9
  - vless-ab3bedb3
  - TelegramMrsoulb-a60d96d3
  - vless-42122a73
  - vless-abb14b91
  - مشتی_جوین_بده_ناموصا__xzjinx-dca7ee12
  - مشتی_جوین_بده_ناموصا__xzjinx-f9634e8c
  - تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-183d3683
  - vless-55ab7375
  - vless-3e03a295
  - Sezar_Sec-785a77ea
  - TelegramMrsoulb-4c018f6b
  - vless-b15229f6
- name: AUTO
  type: url-test
  proxies:
  - vless-74f31512
  - vless-368378c9
  - vless-08ea0b98
  - Sezar_Sec-699019eb
  - vless-7df83471
  - vless-f49c5d0e
  - vless-dd9d8947
  - net0n3_281-27160cc5
  - مشتی_جوین_بده_ناموصا__xzjinx-9c715eec
  - vless-e7e56639
  - vless-52299866
  - vless-4ae90365
  - vless-226987d7
  - vless-c1d6f715
  - YOOZCARD-39d66f19
  - vless-41e436f7
  - vless-f895ff72
  - vless-38a53638
  - vless-15464ce4
  - vless-e4f39300
  - vless-ab63493a
  - تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-63999046
  - vless-65ae85ec
  - تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-f009ff12
  - Sezar_sec-bd6dfc2c
  - Sezar_Sec-94297ad8
  - Sezar_Sec-ff0bb020
  - vless-72a624f5
  - vless-60cb4dcb
  - Sezar_sec-9675a536
  - vless-89bb2169
  - تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-b91fada0
  - مشتی_جوین_بده_ناموصا__xzjinx-ec4b3c6c
  - مشتی_جوین_بده_ناموصا__xzjinx-951b61f5
  - net0n3_283-bd7521c5
  - Sezar_Sec-85f82310
  - vless-b9d9ff7c
  - vless-69533fe6
  - Sezar_sec-310b982f
  - مشتی_جوین_بده_ناموصا__xzjinx-17aaf5e9
  - vless-ab3bedb3
  - TelegramMrsoulb-a60d96d3
  - vless-42122a73
  - vless-abb14b91
  - مشتی_جوین_بده_ناموصا__xzjinx-dca7ee12
  - مشتی_جوین_بده_ناموصا__xzjinx-f9634e8c
  - تنها_کانالی_که_نت_ملی_شد_کانفیگ_رایگان_و_فعال_گذاشت_AhngLife-183d3683
  - vless-55ab7375
  - vless-3e03a295
  - Sezar_Sec-785a77ea
  - TelegramMrsoulb-4c018f6b
  - vless-b15229f6
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
