port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: عضو_شو__zibanabz-ec6d620d
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: عضو_شو__prroxyng-1fac6d36
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: GheychiAmoozesh-25-ed24b937
  type: ss
  server: 131.145.33.92
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
- name: vless-f37c5e4b
  type: vless
  server: 104.21.112.1
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: test2-f82d9879
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: 29cbae1c-0d29-4213-8220-d1302816c4b1
  udp: true
  tls: false
  network: xhttp
- name: GheychiAmoozesh-15-bc47740c
  type: vless
  server: 108.162.198.20
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: Sezar_Sec-b43cbc14
  type: vless
  server: 65.109.203.70
  port: 2096
  uuid: feea904b-d443-43e1-beaa-621ef7a3de3f
  udp: true
  tls: false
  network: tcp
- name: blacklife693_وصل_شد_عضو_کانالم_شو-8cc32a03
  type: vmess
  server: panel3.ipyar.org
  port: 32017
  uuid: c0ccdeb9-784c-4d67-b904-20dcaac9902a
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-7d07c5b6
  type: vless
  server: speedtest.net
  port: 80
  uuid: 3488f5ea-47f8-4d6c-b1af-289c010c57cd
  udp: true
  tls: false
  network: xhttp
- name: telegram_id__Viturey-dafb3190
  type: vless
  server: lingering-boat-0b47.vpnetwork3567.workers.dev
  port: 443
  uuid: 563B4029-2161-7E31-FA35-1B21441AE537
  udp: true
  tls: true
  network: ws
  servername: lingering-boat-0b47.vpnetwork3567.workers.dev
  ws-opts:
    path: /
    headers:
      Host: lingering-boat-0b47.vpnetwork3567.workers.dev
- name: GheychiAmoozesh-32-eeba61b8
  type: vless
  server: 188.114.96.3
  port: 8443
  uuid: 88d05a33-ff36-415d-9d2c-7e1e8468e7e8
  udp: true
  tls: true
  network: ws
  servername: w325.pAges.Dev
  ws-opts:
    path: /Tel-@V2ray_Alpha/?ed=2560
    headers:
      Host: w325.pages.dev
- name: vless-ee628981
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN-
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: vless-27c0eddf
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: test1-75cced96
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 29cbae1c-0d29-4213-8220-d1302816c4b1
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: vless-ff7ae052
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: Telegram--SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: عضو_شو__zibanabz-881a27c5
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: GheychiAmoozesh-22-4a669ced
  type: ss
  server: admin.c2.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: WstuSnlu4ieA9M0L
  udp: true
- name: GheychiAmoozesh-17-b8c4ca1e
  type: ss
  server: h110vpnch.outlinekeys.net
  port: 4248
  cipher: chacha20-ietf-poly1305
  password: SasawZo4g7WaqlK3a2mCol
  udp: true
- name: vless-b79b8a12
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: 63fa5580-1bb7-4cc1-a6ee-0ed4eaa52308
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: GheychiAmoozesh-19-5e8f1631
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: کانفیگرایگانجوینشوتلگرامConfVip-44e1fe6f
  type: vless
  server: 104.26.6.89
  port: 443
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: NpFzCqA01g.V2pLuSmLm.OrG
  ws-opts:
    path: /
    headers:
      Host: NpFzCqA01g.V2pLuSmLm.OrG
- name: Gp_Config__کانفیگ_های_بیشتر-a592408e
  type: ss
  server: flank3.g.edgeservers.org
  port: 54590
  cipher: chacha20-ietf-poly1305
  password: x9CLmvtStnUITovXBClxhu
  udp: true
- name: GheychiAmoozesh-33-d16ac236
  type: vless
  server: 104.21.112.1
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: GheychiAmoozesh-38-31a6c4a2
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
  udp: true
  tls: true
  network: ws
  servername: avtice.fullmargintraders.com
  ws-opts:
    path: /wsv/7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
    headers:
      Host: avtice.fullmargintraders.com
- name: vless-41cb0ddb
  type: vless
  server: 104.21.43.168
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /bDUGlAj9BFG7zebG?ed=2560
    headers:
      Host: 2.lINK-KoN.IR
- name: GheychiAmoozesh-27-024bfada
  type: ss
  server: series-a2-mec.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: Sezar_Sec-1a68ef95
  type: vmess
  server: panel1.ipyar.org
  port: 42684
  uuid: c4bd9eba-8aea-4d5e-a2ee-b5de65ac14e1
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: GheychiAmoozesh-36-2d077dcc
  type: vless
  server: 34.247.254.247
  port: 50768
  uuid: c7e4c202-cfdf-44df-85a7-a9e7b4545a74
  udp: true
  tls: false
  network: grpc
  servername: jetbrains.com
  reality-opts:
    public-key: 7kUu70kwGDQ65WQHCBXcQ-KLQa5V8VVxX3zMML7hSlQ
    short-id: 4e78519d
- name: عضو_شو__zibanabz-7a6a1aca
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: عضو_شو__zibanabz-e2ff1b55
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: GheychiAmoozesh-11-61d14acf
  type: vless
  server: sp4.god-ping.net
  port: 2051
  uuid: 2725451d-5f83-4998-9f2f-193e656e3bc7
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-20-01ca92d6
  type: ss
  server: series-a1.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
- name: GheychiAmoozesh-16-42236cdd
  type: vless
  server: c1.lightxpro.ir
  port: 35775
  uuid: 8c57716b-d545-47b3-981e-c3bbd5a09b3c
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: null
- name: چنل_عضو_شو_Pro_V10-3b083e90
  type: vmess
  server: 51.158.146.67
  port: 2086
  uuid: d44b03d8-bb52-f971-d4b9-b4ff78cce8c9
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: net0n3_409-e375ae51
  type: vless
  server: germany1.neeservers643.ir
  port: 7600
  uuid: 351ebc39-8032-449c-914f-14095fafa8c1
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: ZuogJRtuiVgad1NAmzjZUJqLnCCFnBogwdQufhhuf1A
    short-id: null
- name: vless-fd876b02
  type: vless
  server: 104.21.43.168
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  servername: 2.link-kon.ir
  ws-opts:
    path: /bDUGlAj9BFG7zebG?ed=2560
    headers:
      Host: 2.lINK-KoN.IR
- name: blacklife693-9f4a54d9
  type: vless
  server: 91.99.141.177
  port: 443
  uuid: 1a827c35-7a17-48d8-a9f5-eeed323ca57b
  udp: true
  tls: false
  network: tcp
  servername: refersion.com
  reality-opts:
    public-key: SJt4jAvhiR5MVRnl-OPj2BWUXZT6p4oH-Ugl3B0b-VA
    short-id: 8ad4b0d652d3e8
- name: GheychiAmoozesh-21-620ab244
  type: ss
  server: series-a2.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: GheychiAmoozesh-34-99f5630c
  type: vless
  server: 95.164.45.85
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  network: grpc
- name: test3-ea8791bd
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: baf334b7-f07e-420d-8efb-060cb3fff630
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: GheychiAmoozesh-37-4610c158
  type: vless
  server: 104.22.24.195
  port: 443
  uuid: 96479a22-9333-4b03-9912-4dd26acef75e
  udp: true
  tls: true
  network: ws
  servername: NExtfilmtOmovies.sitE
  ws-opts:
    path: /9EkfcCDedhvB19xj?ed=2560
    headers:
      Host: nextfilmtomovies.site
- name: GheychiAmoozesh-31-854d8b59
  type: vless
  server: 300232332.webnama.com.tr.privatepack.ir
  port: 1517
  uuid: 88f9173d-09b1-463a-99c8-e39852693cba
  udp: true
  tls: false
  network: tcp
- name: 300گیگ_39تومان_تسترایگانTickV2bot-67af1beb
  type: vmess
  server: movaghat20.funfil.link
  port: 48913
  uuid: 08a3bdd2-2167-4761-b547-e8bd1b4a44ec
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: GheychiAmoozesh-18-b0701180
  type: ss
  server: h110vpnus.outlinekeys.net
  port: 9483
  cipher: chacha20-ietf-poly1305
  password: nLwAl3svNCBPtG9I2FrVYI
  udp: true
- name: ProxySnipe_جوین_شید-1bf14598
  type: vless
  server: 185.231.205.253
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  network: grpc
- name: GheychiAmoozesh-26-8e611749
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: GheychiAmoozesh-12-0cf7bec6
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-14-4a691c95
  type: ss
  server: series-a2-mec.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: GheychiAmoozesh-35-177b0182
  type: vless
  server: 91.99.239.156
  port: 443
  uuid: d2d29254-ad3b-495a-b209-5ccc4f12c0a4
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-204976e1
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: GheychiAmoozesh-39-381b6746
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 6f6e8f09-c1b3-48fd-ab00-18f921d875ef
  udp: true
  tls: true
  network: ws
  servername: profit.fullmargintraders.com
  ws-opts:
    path: /wsv/6f6e8f09-c1b3-48fd-ab00-18f921d875ef
    headers:
      Host: profit.fullmargintraders.com
- name: GheychiAmoozesh-13-41cbe817
  type: ss
  server: dl.2046.shield-web.ir
  port: 2046
  cipher: chacha20-ietf-poly1305
  password: YZbYU8NosZCi7zuUI5hDlw
  udp: true
- name: net0n3_411-aeafdf85
  type: vless
  server: sr56.toast.sbs
  port: 2095
  uuid: 1d7a7eb0-5214-4a3f-8442-cc95e43a107f
  udp: true
  tls: false
  network: tcp
- name: net0n3_415-28c45d53
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: 8d93a84b-20cc-40af-a0a2-ad347e1af16e
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /ws/?ed=2048
    headers:
      Host: welcomtofreeboarders.com
- name: GheychiAmoozesh-23-d61c18fa
  type: vless
  server: 135.148.152.106
  port: 443
  uuid: ea286109-d20f-415e-849e-4af20ab04b65
  udp: true
  tls: true
  network: tcp
  servername: 147135001195.sec22org.com
- name: vless-3e85d320
  type: vless
  server: 172.66.44.253
  port: 8443
  uuid: efed37ed-37e5-4100-a540-049dc7929984
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /dy26vBaDi5RTblzP?ed=2560
    headers:
      Host: net-aCcOUNt02.Pages.DEv
- name: net0n3_410-8c664d23
  type: vless
  server: 104.26.6.89
  port: 80
  uuid: b360267f-81aa-4740-a9c0-9a64fe7f9775
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: onlytesla.xz027.com
- name: vless-b512b14e
  type: vless
  server: 104.26.6.89
  port: 443
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: NpFzCqA01g.V2pLuSmLm.OrG
  ws-opts:
    path: /
    headers:
      Host: NpFzCqA01g.V2pLuSmLm.OrG
- name: عضو_شو__zibanabz-3dcd2424
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: قطع_شدی_بیا_گروه_گوگولی_vpn_mmdparsa-40abc0d2
  type: vless
  server: 139.180.178.98
  port: 443
  uuid: e8f25e87-f17f-4b38-9ba8-3d3ffd345186
  udp: true
  tls: false
  network: tcp
  servername: ash.d50f6225-23b4-3a7b-9f15-a0fb2fc16803.googleapis.com
  reality-opts:
    public-key: hTweFDvbSucrGERtiiwDfoqD3vo_Z9cuaqboff3FTXQ
    short-id: null
- name: net0n3_413-251736a1
  type: vless
  server: 172.66.47.61
  port: 8443
  uuid: a396b860-11b7-4af3-9950-146caf79735e
  udp: true
  tls: true
  network: ws
  servername: gGHDFa.pAgeS.Dev
  ws-opts:
    path: /8WuhXm4QjK0L68Uf?ed=2560
    headers:
      Host: gghdfa.pages.dev
- name: net0n3_414-65a4efee
  type: vless
  server: 78.157.58.116
  port: 55699
  uuid: a01b7f97-04e1-4bfe-b6fb-68ac6eff28cb
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-24-74f2cf7a
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 2096
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: Ft77Ta8Q1m.EmShAbKhObE.oRg
  ws-opts:
    path: /
    headers:
      Host: Ft77Ta8Q1m.EmShAbKhObE.oRg
- name: عضو_شو__zibanabz-6951a545
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: Sezar_Sec-b50b09e2
  type: vless
  server: 31.7.73.146
  port: 17778
  uuid: 080ab9d1-66da-4711-96c6-9bdeb6c90093
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-19eda0c9
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: test4-6206f2bd
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: baf334b7-f07e-420d-8efb-060cb3fff630
  udp: true
  tls: false
  network: xhttp
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - عضو_شو__zibanabz-ec6d620d
  - عضو_شو__prroxyng-1fac6d36
  - GheychiAmoozesh-25-ed24b937
  - vless-f37c5e4b
  - test2-f82d9879
  - GheychiAmoozesh-15-bc47740c
  - Sezar_Sec-b43cbc14
  - blacklife693_وصل_شد_عضو_کانالم_شو-8cc32a03
  - vless-7d07c5b6
  - telegram_id__Viturey-dafb3190
  - GheychiAmoozesh-32-eeba61b8
  - vless-ee628981
  - vless-27c0eddf
  - test1-75cced96
  - vless-ff7ae052
  - عضو_شو__zibanabz-881a27c5
  - GheychiAmoozesh-22-4a669ced
  - GheychiAmoozesh-17-b8c4ca1e
  - vless-b79b8a12
  - GheychiAmoozesh-19-5e8f1631
  - کانفیگرایگانجوینشوتلگرامConfVip-44e1fe6f
  - Gp_Config__کانفیگ_های_بیشتر-a592408e
  - GheychiAmoozesh-33-d16ac236
  - GheychiAmoozesh-38-31a6c4a2
  - vless-41cb0ddb
  - GheychiAmoozesh-27-024bfada
  - Sezar_Sec-1a68ef95
  - GheychiAmoozesh-36-2d077dcc
  - عضو_شو__zibanabz-7a6a1aca
  - عضو_شو__zibanabz-e2ff1b55
  - GheychiAmoozesh-11-61d14acf
  - GheychiAmoozesh-20-01ca92d6
  - GheychiAmoozesh-16-42236cdd
  - چنل_عضو_شو_Pro_V10-3b083e90
  - net0n3_409-e375ae51
  - vless-fd876b02
  - blacklife693-9f4a54d9
  - GheychiAmoozesh-21-620ab244
  - GheychiAmoozesh-34-99f5630c
  - test3-ea8791bd
  - GheychiAmoozesh-37-4610c158
  - GheychiAmoozesh-31-854d8b59
  - 300گیگ_39تومان_تسترایگانTickV2bot-67af1beb
  - GheychiAmoozesh-18-b0701180
  - ProxySnipe_جوین_شید-1bf14598
  - GheychiAmoozesh-26-8e611749
  - GheychiAmoozesh-12-0cf7bec6
  - GheychiAmoozesh-14-4a691c95
  - GheychiAmoozesh-35-177b0182
  - عضو_شو__zibanabz-204976e1
  - GheychiAmoozesh-39-381b6746
  - GheychiAmoozesh-13-41cbe817
  - net0n3_411-aeafdf85
  - net0n3_415-28c45d53
  - GheychiAmoozesh-23-d61c18fa
  - vless-3e85d320
  - net0n3_410-8c664d23
  - vless-b512b14e
  - عضو_شو__zibanabz-3dcd2424
  - قطع_شدی_بیا_گروه_گوگولی_vpn_mmdparsa-40abc0d2
  - net0n3_413-251736a1
  - net0n3_414-65a4efee
  - GheychiAmoozesh-24-74f2cf7a
  - عضو_شو__zibanabz-6951a545
  - Sezar_Sec-b50b09e2
  - عضو_شو__zibanabz-19eda0c9
  - test4-6206f2bd
- name: AUTO
  type: url-test
  proxies:
  - عضو_شو__zibanabz-ec6d620d
  - عضو_شو__prroxyng-1fac6d36
  - GheychiAmoozesh-25-ed24b937
  - vless-f37c5e4b
  - test2-f82d9879
  - GheychiAmoozesh-15-bc47740c
  - Sezar_Sec-b43cbc14
  - blacklife693_وصل_شد_عضو_کانالم_شو-8cc32a03
  - vless-7d07c5b6
  - telegram_id__Viturey-dafb3190
  - GheychiAmoozesh-32-eeba61b8
  - vless-ee628981
  - vless-27c0eddf
  - test1-75cced96
  - vless-ff7ae052
  - عضو_شو__zibanabz-881a27c5
  - GheychiAmoozesh-22-4a669ced
  - GheychiAmoozesh-17-b8c4ca1e
  - vless-b79b8a12
  - GheychiAmoozesh-19-5e8f1631
  - کانفیگرایگانجوینشوتلگرامConfVip-44e1fe6f
  - Gp_Config__کانفیگ_های_بیشتر-a592408e
  - GheychiAmoozesh-33-d16ac236
  - GheychiAmoozesh-38-31a6c4a2
  - vless-41cb0ddb
  - GheychiAmoozesh-27-024bfada
  - Sezar_Sec-1a68ef95
  - GheychiAmoozesh-36-2d077dcc
  - عضو_شو__zibanabz-7a6a1aca
  - عضو_شو__zibanabz-e2ff1b55
  - GheychiAmoozesh-11-61d14acf
  - GheychiAmoozesh-20-01ca92d6
  - GheychiAmoozesh-16-42236cdd
  - چنل_عضو_شو_Pro_V10-3b083e90
  - net0n3_409-e375ae51
  - vless-fd876b02
  - blacklife693-9f4a54d9
  - GheychiAmoozesh-21-620ab244
  - GheychiAmoozesh-34-99f5630c
  - test3-ea8791bd
  - GheychiAmoozesh-37-4610c158
  - GheychiAmoozesh-31-854d8b59
  - 300گیگ_39تومان_تسترایگانTickV2bot-67af1beb
  - GheychiAmoozesh-18-b0701180
  - ProxySnipe_جوین_شید-1bf14598
  - GheychiAmoozesh-26-8e611749
  - GheychiAmoozesh-12-0cf7bec6
  - GheychiAmoozesh-14-4a691c95
  - GheychiAmoozesh-35-177b0182
  - عضو_شو__zibanabz-204976e1
  - GheychiAmoozesh-39-381b6746
  - GheychiAmoozesh-13-41cbe817
  - net0n3_411-aeafdf85
  - net0n3_415-28c45d53
  - GheychiAmoozesh-23-d61c18fa
  - vless-3e85d320
  - net0n3_410-8c664d23
  - vless-b512b14e
  - عضو_شو__zibanabz-3dcd2424
  - قطع_شدی_بیا_گروه_گوگولی_vpn_mmdparsa-40abc0d2
  - net0n3_413-251736a1
  - net0n3_414-65a4efee
  - GheychiAmoozesh-24-74f2cf7a
  - عضو_شو__zibanabz-6951a545
  - Sezar_Sec-b50b09e2
  - عضو_شو__zibanabz-19eda0c9
  - test4-6206f2bd
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
