mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-fb2a1e01
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-6a07e070
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-8c9672f9
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-b9ca0099
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-8387709c
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-73128290
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-4814a4ab
  type: vless
  server: 91.99.172.196
  port: 28041
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: WpvjPUZ5x3SIvDzSr5q9v0bfhzo36obh3CXIqJVmnkY
    short-id: 91355b9b818617
- name: vless-b1d5cfcc
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: Telegram_vpn_mmdparsa-5dd9f4ff
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: سرورهای_رایگان_و_پرسرعت__vpn_Sra-b69d153f
  type: ss
  server: 216.173.70.187
  port: 57456
  cipher: chacha20-ietf-poly1305
  password: 360e21d21977dc11
  udp: true
- name: V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-9b8c14fd
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: chanel__SRT_VPN-02e4da7a
  type: vless
  server: compose.fast.hosting-ip.com
  port: 80
  uuid: ab80613b-e04b-4af5-bad9-9ca5c448266e
  udp: true
  network: ws
  ws-opts:
    path: /GoodLuck?ed=2560
    headers:
      Host: Mastercloud.global.ssl.fastly.net.
- name: vless-f736469b
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 92f481b6-ad92-43e4-a683-2bb0aeaa9846
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: dw.alibichareh.dpdns.org
- name: vless-78258300
  type: vless
  server: 300232332.webnama.com.tr
  port: 1517
  uuid: 3d554bba-9c77-499f-9055-1eb42058ed00
  udp: true
  network: tcp
- name: ss-d9391abe
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-67cb30e0
  type: vless
  server: www.speedtest.net
  port: 2096
  uuid: dc80ee7e-bad0-450c-a218-f12e05680885
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /?ed=2096
    headers:
      Host: arm1.dollardoon.com
- name: vless-17c39a74
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 148709e4-402b-48dd-8892-ed39b55ea45c
  udp: true
  network: ws
  ws-opts:
    path: '@vpnserverrr'
    headers:
      Host: barayeiranmahsang.loseyourself.dpdns.org
- name: vless-8c65c47b
  type: vless
  server: snet.shbrad.info
  port: 8443
  uuid: 76c8f657-8186-4f40-cf6b-884fb7c632db
  udp: true
  network: tcp
- name: vless-e427f951
  type: vless
  server: 91.99.194.113
  port: 10195
  uuid: 913a8cd8-11ab-4d16-a6f7-c7b88d7a592e
  udp: true
  network: tcp
- name: vless-83336a89
  type: vless
  server: 91.99.129.82
  port: 443
  uuid: f73e9865-80c3-45ba-8391-597139c37bdc
  udp: true
  network: tcp
- name: vless-1a8b6b00
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: مشتی_جوین_بده_ناموصا__xzjinx-afe59431
  type: vless
  server: 94.182.136.184
  port: 159
  uuid: 0af94a54-f5d8-43dd-8544-77a56559ea1c
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-6f2f698b
  type: vless
  server: 31.47.45.173
  port: 777
  uuid: ce55d3ed-618b-45b7-d879-368fbb465efd
  udp: true
  network: tcp
- name: Sezar_Sec-1d99b0b5
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-c052132f
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-fd8b9528
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-36f850bc
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-d9a18591
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-fb2a1e01
  - vless-6a07e070
  - vless-8c9672f9
  - vless-b9ca0099
  - vless-8387709c
  - vless-73128290
  - vless-4814a4ab
  - vless-b1d5cfcc
  - Telegram_vpn_mmdparsa-5dd9f4ff
  - سرورهای_رایگان_و_پرسرعت__vpn_Sra-b69d153f
  - V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-9b8c14fd
  - chanel__SRT_VPN-02e4da7a
  - vless-f736469b
  - vless-78258300
  - ss-d9391abe
  - vless-67cb30e0
  - vless-17c39a74
  - vless-8c65c47b
  - vless-e427f951
  - vless-83336a89
  - vless-1a8b6b00
  - مشتی_جوین_بده_ناموصا__xzjinx-afe59431
  - مشتی_جوین_بده_ناموصا__xzjinx-6f2f698b
  - Sezar_Sec-1d99b0b5
  - Sezar_Sec-c052132f
  - Sezar_Sec-fd8b9528
  - Sezar_Sec-36f850bc
  - Sezar_Sec-d9a18591
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
