mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-0dfa3738
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-2d6d52ee
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-fef44f6f
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-e7ea126d
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-05e47dfd
  type: vless
  server: accounting.vinamarketcenter.ir
  port: 443
  uuid: 5cfba4ac-105a-452a-ac10-88b1adf784ee
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: T7Cwk-B3EvZqqRywIgN_TNotJiUOXYUI9bHqYKPnTi0
    short-id: 105e89ba3d2a1c3b
- name: SRCVPN-0709b9de
  type: vless
  server: 150.241.65.211
  port: 443
  uuid: be5fab84-5edb-4800-927e-243f6e4309bf
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: LYJ37EcS5jyaezTVaVAVCkBWCrjXioiJHI7argkEnCU
    short-id: 236ac31d02
- name: SRCVPN-8cc3fd82
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: a812a015-a65b-4003-ac5f-266e141c6405
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: Www.speedtest.net.developsp.ir.vegaskala.com.
- name: Telegram_Mrsoulh-df587a7c
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: Telegram_Mrsoulh-26ba2b89
  type: vless
  server: 62.60.179.100
  port: 54080
  uuid: 079291d7-2d5a-4dcc-b2a9-514cda7eb9f9
  udp: true
  network: tcp
- name: Telegram_Mrsoulh-7e56e8e9
  type: vless
  server: 104.19.245.206
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: Telegram_Mrsoulh-e8352617
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Telegram_Mrsoulh-74b6db30
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560/
    headers:
      Host: sib.sibzamini.dpdns.org
- name: برای_کانفیگ_های_بیشتر_mrsoulh-09d36887
  type: vless
  server: 91.99.160.210
  port: 443
  uuid: 2eaef053-5fd6-4def-b234-d760690355ff
  udp: true
  network: tcp
- name: Channel__VaslBemooon-34abebc0
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: bbd2882a-c158-4ae6-b53a-5ae6be8dbcb0
  udp: true
  network: ws
  ws-opts:
    path: /Telegram@V2ray_Alpha/?ed=2560
    headers:
      Host: barayeiran.nastaranh.dpdns.org
- name: configfree_1-11b4ce49
  type: vless
  server: 172.67.128.105
  port: 80
  uuid: 4179c595-08ca-45cd-b555-91b6f1faeadc
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: di.dibdibini.dpdns.org
- name: Gvtvtvyvtcw-aface827
  type: vless
  server: 77.72.80.143
  port: 8080
  uuid: 1a2880c5-c4dc-42df-8013-627584af81f4
  udp: true
  network: ws
  ws-opts:
    path: /
- name: vpnv2rayNGv_سرورای_بیشتر_داخل_چنل-00621262
  type: vmess
  server: 104.17.223.175
  port: 8080
  uuid: 6cbc9c78-1cb1-57d4-a999-e2f4e34c1e03
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /nasnet/cdn
    headers:
      Host: ke7hz36ewz-4515017473.mashallahbet.com
- name: vpnv2rayNGv_سرورای_بیشتر_داخل_چنل-304af441
  type: vmess
  server: 104.17.223.175
  port: 8080
  uuid: 6cbc9c78-1cb1-57d4-a999-e2f4e34c1e03
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /nasnet/cdn
    headers:
      Host: ke7hz36ewz-4515017473.mashallahbet.com
- name: vless-b985773b
  type: vless
  server: 91.107.154.77
  port: 2070
  uuid: 1c88c964-a039-4c9a-b1e5-5e93eef57fd8
  udp: true
  network: tcp
- name: vless-ce271c12
  type: vless
  server: 5.255.120.217
  port: 80
  uuid: 25eb0cf9-b6bc-475b-bda5-b76ac9b766f6
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: C4LNbOB3Ar0cntu528Jtn5ivsMZhyk9tkuAlU-jeCio
    short-id: 8c
  ws-opts:
    path: /pwp
    headers:
      Host: bleep.global.ssl.fastly.net
- name: vless-dd858c20
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-0d41a976
  type: vless
  server: 62.60.223.6
  port: 2080
  uuid: bea34b73-3244-475b-b914-7bb80e1cda91
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: L3lJWdU7mHijSkNaNt-m29OYnKnHvHYRxg2Y8XXFdng
    short-id: bf517367267685
- name: vless-83c1f267
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-4198e21d
  type: vless
  server: 91.99.231.102
  port: 443
  uuid: 8657fada-f21d-422b-9a2d-3c47d93c11bd
  udp: true
  network: tcp
- name: vless-b291e2fb
  type: vless
  server: 91.107.154.77
  port: 8787
  uuid: 1c88c964-a039-4c9a-b1e5-5e93eef57fd8
  udp: true
  network: tcp
- name: vless-e33bd3e7
  type: vless
  server: xpanel-ir.panelfreedom.com
  port: 2092
  uuid: 15cae74e-0103-499a-9ce5-6ecd63e846c3
  udp: true
  network: tcp
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-0dfa3738
  - vless-2d6d52ee
  - vless-fef44f6f
  - vless-e7ea126d
  - vless-05e47dfd
  - SRCVPN-0709b9de
  - SRCVPN-8cc3fd82
  - Telegram_Mrsoulh-df587a7c
  - Telegram_Mrsoulh-26ba2b89
  - Telegram_Mrsoulh-7e56e8e9
  - Telegram_Mrsoulh-e8352617
  - Telegram_Mrsoulh-74b6db30
  - برای_کانفیگ_های_بیشتر_mrsoulh-09d36887
  - Channel__VaslBemooon-34abebc0
  - configfree_1-11b4ce49
  - Gvtvtvyvtcw-aface827
  - vpnv2rayNGv_سرورای_بیشتر_داخل_چنل-00621262
  - vpnv2rayNGv_سرورای_بیشتر_داخل_چنل-304af441
  - vless-b985773b
  - vless-ce271c12
  - vless-dd858c20
  - vless-0d41a976
  - vless-83c1f267
  - vless-4198e21d
  - vless-b291e2fb
  - vless-e33bd3e7
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
