mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-b9b5cca6
  type: vless
  server: accounting.vinamarketcenter.ir
  port: 443
  uuid: 5cfba4ac-105a-452a-ac10-88b1adf784ee
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: T7Cwk-B3EvZqqRywIgN_TNotJiUOXYUI9bHqYKPnTi0
    short-id: 105e89ba3d2a1c3b
- name: SRCVPN-c33458fe
  type: vless
  server: 150.241.65.211
  port: 443
  uuid: be5fab84-5edb-4800-927e-243f6e4309bf
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: LYJ37EcS5jyaezTVaVAVCkBWCrjXioiJHI7argkEnCU
    short-id: 236ac31d02
- name: SRCVPN-aa3b390a
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: a812a015-a65b-4003-ac5f-266e141c6405
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: Www.speedtest.net.developsp.ir.vegaskala.com.
- name: vless-4edd5e5c
  type: vless
  server: 91.107.154.77
  port: 2070
  uuid: 1c88c964-a039-4c9a-b1e5-5e93eef57fd8
  udp: true
  network: tcp
- name: vless-9ffb8107
  type: vless
  server: 5.255.120.217
  port: 80
  uuid: 25eb0cf9-b6bc-475b-bda5-b76ac9b766f6
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: C4LNbOB3Ar0cntu528Jtn5ivsMZhyk9tkuAlU-jeCio
    short-id: 8c
  ws-opts:
    path: /pwp
    headers:
      Host: bleep.global.ssl.fastly.net
- name: vless-cd470765
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-0a520350
  type: vless
  server: 62.60.223.6
  port: 2080
  uuid: bea34b73-3244-475b-b914-7bb80e1cda91
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: L3lJWdU7mHijSkNaNt-m29OYnKnHvHYRxg2Y8XXFdng
    short-id: bf517367267685
- name: vless-14c195fe
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-e4aaf7b1
  type: vless
  server: 91.99.231.102
  port: 443
  uuid: 8657fada-f21d-422b-9a2d-3c47d93c11bd
  udp: true
  network: tcp
- name: vless-11666840
  type: vless
  server: 91.107.154.77
  port: 8787
  uuid: 1c88c964-a039-4c9a-b1e5-5e93eef57fd8
  udp: true
  network: tcp
- name: vless-ef405a6e
  type: vless
  server: xpanel-ir.panelfreedom.com
  port: 2092
  uuid: 15cae74e-0103-499a-9ce5-6ecd63e846c3
  udp: true
  network: tcp
- name: Capoit-aaadf7dd
  type: vless
  server: 91.99.198.174
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: Telegram_Mrsoulh-f1526bfe
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: Telegram_Mrsoulh-28d46327
  type: vless
  server: 62.60.179.100
  port: 54080
  uuid: 079291d7-2d5a-4dcc-b2a9-514cda7eb9f9
  udp: true
  network: tcp
- name: Telegram_Mrsoulh-b7ba1120
  type: vless
  server: 104.19.245.206
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: Telegram_Mrsoulh-ac266f6b
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Telegram_Mrsoulh-08fa3888
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560/
    headers:
      Host: sib.sibzamini.dpdns.org
- name: برای_کانفیگ_های_بیشتر_mrsoulh-1a3f3c9f
  type: vless
  server: 91.99.160.210
  port: 443
  uuid: 2eaef053-5fd6-4def-b234-d760690355ff
  udp: true
  network: tcp
- name: برای_کانفیگ_های_بیشتر_mrsoulh4-452ca2ce
  type: vless
  server: 91.99.162.239
  port: 443
  uuid: 2eaef053-5fd6-4def-b234-d760690355ff
  udp: true
  network: tcp
- name: mehrosaboran-402ccdd9
  type: vless
  server: 172.67.128.105
  port: 80
  uuid: 4179c595-08ca-45cd-b555-91b6f1faeadc
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: di.dibdibini.dpdns.org
- name: سرورهایبیشتردرکانالprrofile_purple-c1faad4e
  type: vless
  server: sd.mciickoir.ir
  port: 9620
  uuid: 3ed3966a-ca0e-4a46-a437-8000836fa495
  udp: true
  network: tcp
- name: سرورهایبیشتردرکانالprrofile_purple-f4ef7b8b
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: سرورهایبیشتردرکانالprrofile_purple-feba3877
  type: vless
  server: 45.76.140.111
  port: 443
  uuid: ae7d51f2-fd15-45d2-a77c-590f23788a52
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: rPomFaHQdUvIZ1CKylejYHXJ_ygI2rtPIZaVuaRXaVY
    short-id: 8a2c6af0c06f
  ws-opts:
    path: /443/moment@2.29.4
    headers:
      Host: cdn.skypack.dev
- name: سرورهایبیشتردرکانالprrofile_purple-ccba7170
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560/
    headers:
      Host: sib.sibzamini.dpdns.org
- name: Telegram_vpnbaz-50433d8a
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: redfree8mahsang6.redfree8.ir
- name: Telegram_vpnbaz-c875e5b0
  type: vless
  server: 172.67.17.195
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: Telegram_vpnbaz-a4f64284
  type: vless
  server: 104.16.104.151
  port: 80
  uuid: 1f431db3-1918-4e7b-a855-c93485e11694
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: pari.parinazz.dpdns.org
- name: Telegram_vpnbaz-1cbc645b
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: Telegram_vpnbaz-0a17cda8
  type: vless
  server: 172.67.67.92
  port: 80
  uuid: f78ce1bb-0fa6-4ef4-b4c9-b91014a7055d
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: delam.ahaysiahzangi.dpdns.org
- name: Telegram_vpnbaz-0aec49c7
  type: vless
  server: 104.24.31.150
  port: 80
  uuid: 9d6315f7-f272-4806-97c8-5fdaafad391e
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2570
    headers:
      Host: lot.sosant.dpdns.org
- name: Telegram_vpnbaz-57bc87fc
  type: ss
  server: api.namasha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: Telegram_vpnbaz-d10d7047
  type: ss
  server: series-a2.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-b9b5cca6
  - SRCVPN-c33458fe
  - SRCVPN-aa3b390a
  - vless-4edd5e5c
  - vless-9ffb8107
  - vless-cd470765
  - vless-0a520350
  - vless-14c195fe
  - vless-e4aaf7b1
  - vless-11666840
  - vless-ef405a6e
  - Capoit-aaadf7dd
  - Telegram_Mrsoulh-f1526bfe
  - Telegram_Mrsoulh-28d46327
  - Telegram_Mrsoulh-b7ba1120
  - Telegram_Mrsoulh-ac266f6b
  - Telegram_Mrsoulh-08fa3888
  - برای_کانفیگ_های_بیشتر_mrsoulh-1a3f3c9f
  - برای_کانفیگ_های_بیشتر_mrsoulh4-452ca2ce
  - mehrosaboran-402ccdd9
  - سرورهایبیشتردرکانالprrofile_purple-c1faad4e
  - سرورهایبیشتردرکانالprrofile_purple-f4ef7b8b
  - سرورهایبیشتردرکانالprrofile_purple-feba3877
  - سرورهایبیشتردرکانالprrofile_purple-ccba7170
  - Telegram_vpnbaz-50433d8a
  - Telegram_vpnbaz-c875e5b0
  - Telegram_vpnbaz-a4f64284
  - Telegram_vpnbaz-1cbc645b
  - Telegram_vpnbaz-0a17cda8
  - Telegram_vpnbaz-0aec49c7
  - Telegram_vpnbaz-57bc87fc
  - Telegram_vpnbaz-d10d7047
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
