port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: net0n3_317-9833e067
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 6bcb4f37-bba7-4ae0-afac-d43195c72c12
  udp: true
  tls: true
  network: ws
  servername: my.digikala.dynv6.net
  ws-opts:
    path: zula.ir
    headers:
      Host: my.digikala.dynv6.net
- name: عضو_شو__zibanabz-f4c7c4a4
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: V2ray1_Ng-2e262ef1
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /Telegram@V2ray_Alpha/?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: net0n3_322-5196a1a2
  type: vless
  server: nl01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: d3b13f31
- name: vless-7f7ae1a3
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: net0n3_323-a29b95a4
  type: vless
  server: gb01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: e499f276e7bd6420
- name: vless-f97764fc
  type: vless
  server: all97-vip.f-sub.com
  port: 1517
  uuid: 240052ac-0bf0-481f-adb4-f40a259fc189
  udp: true
  tls: false
  network: tcp
- name: net0n3_325-4a5b8d10
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 6bcb4f37-bba7-4ae0-afac-d43195c72c12
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: zula.ir?ed=2560
    headers:
      Host: my.digikala.dynv6.net
- name: net0n3_310-48361630
  type: vless
  server: 0ger.amazon-osishop.ir
  port: 8880
  uuid: 2066c2f3-bde1-429f-b083-fcfc7aee14b5
  udp: true
  tls: false
  network: tcp
- name: Sezar_sec-243cb2b1
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
- name: vless-589ea1a4
  type: vless
  server: russiatest-tap.servers807.ir
  port: 13796
  uuid: b646e0d6-137b-49e1-90bc-3b9ad8a6484a
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: AIUUKeq08usIla0uv-NTp5wVe4TMb3VkXWDLoutlFnM
    short-id: a3ac
- name: عضو_شو__zibanabz-0c42dd28
  type: vless
  server: 172.67.67.92
  port: 80
  uuid: f78ce1bb-0fa6-4ef4-b4c9-b91014a7055d
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: delam.ahaysiahzangi.dpdns.org
- name: GpConnectSho_کانکت_شو-88521ab5
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: 80d1fe59-60f4-4272-a280-820e1ef0a754
  udp: true
  tls: true
  network: ws
  servername: pages.dev
  ws-opts:
    path: /Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray?ed=2048
    headers:
      Host: tfs733.pages.dev
- name: عضو_شو__zibanabz-f512598b
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: PRX11-931e1d6a
  type: vless
  server: vip1.proxystore11.news
  port: 2052
  uuid: 22477fe4-249e-4c18-8986-74b0f1f0657e
  udp: true
  tls: false
  network: xhttp
  servername: vultr.com
  reality-opts:
    public-key: -4S95rjoZIG_AeUxIlwedx89e7C_X4jnePY3RsiF4io
    short-id: f8fcb589
- name: عضو_شو__zibanabz-93069c35
  type: vless
  server: 104.16.104.151
  port: 80
  uuid: 1f431db3-1918-4e7b-a855-c93485e11694
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: pari.parinazz.dpdns.org
- name: net0n3_309-3b5bb46b
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 546cc913-2825-4771-b713-a23905913141
  udp: true
  tls: true
  network: ws
  servername: 638874931195949050.kish-prx-dnraaaf.info
  ws-opts:
    path: /wjwqzaws
    headers:
      Host: 638874931195949050.kish-prx-dnraaaf.info
- name: عضو_شو__zibanabz-297f9c30
  type: vless
  server: 172.67.49.134
  port: 443
  uuid: 06e4425e-a8cb-4b63-929f-2105604ab0a9
  udp: true
  tls: true
  network: ws
  servername: rc.ylks0033.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: rc.ylks0033.dpdns.org
- name: V2ray1_Ng-6a7aee78
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: xhttp
- name: GpConnectSho_کانکت_شو-2acaac1f
  type: vless
  server: it.panelmarzban.com
  port: 3037
  uuid: a0a3e34d-87e4-4ff3-b04a-875c85325d62
  udp: true
  tls: false
  network: tcp
  servername: refersion.com
  reality-opts:
    public-key: 21V_VkMUD2XRbyRDg7hjpblUAwxHvlLmbarATdhhJQI
    short-id: null
- name: عضو_شو__zibanabz-031f87fa
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: net0n3_313-95547c0c
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
- name: V2ray1_Ng-7aa10503
  type: trojan
  server: 104.248.18.1
  port: 1935
  password: 6gZh2JbfhQ
  udp: true
  sni: x1-germany-digitalocean-v2.devefun.org
- name: عضو_شو__zibanabz-7aa71ed2
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: مولداوی-3350d1ff
  type: ss
  server: 45.153.124.90
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
  udp: true
- name: Sezar_sec-85e97035
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  tls: false
  network: tcp
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: GpConnectSho_کانکت_شو-d9f834c1
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: 50eefafc-ac7f-4890-9435-063d9911dda3
  udp: true
  tls: false
  network: xhttp
- name: هلند__۲-b7aa0dc7
  type: ss
  server: 45.87.175.190
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
- name: vless-27f2348d
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: xhttp
- name: V2ray1_Ng-266dead1
  type: vless
  server: www.speedtest.net
  port: 2096
  uuid: c819261a-ad50-4ded-b164-1eafed9885c2
  udp: true
  tls: true
  network: ws
  servername: 638868951946670036.amsterdam-prx-dnraaal.info
  ws-opts:
    path: /mmdhmrws
    headers:
      Host: 638868951946670036.amsterdam-prx-dnraaal.info
- name: GpConnectSho_کانکت_شو-6bca17c1
  type: vless
  server: all97-vip.f-sub.com
  port: 1517
  uuid: 240052ac-0bf0-481f-adb4-f40a259fc189
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-419c3303
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: عضو_شو__zibanabz-0569ddc9
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: net0n3_319-9b3f0d9c
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: zula.ir
    headers:
      Host: azadnet-7py.pages.dev
- name: عضو_شو__zibanabz-b8b95219
  type: vless
  server: 172.67.128.105
  port: 80
  uuid: 4179c595-08ca-45cd-b555-91b6f1faeadc
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: di.dibdibini.dpdns.org
- name: net0n3_321-c8263b7c
  type: ss
  server: 172.187.105.25
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: عضو_شو__prroxyng-9c86ff6b
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-88f476f7
  type: ss
  server: 74.177.199.135
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: vless-fa92d090
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: zula.ir
    headers:
      Host: azadnet-7py.pages.dev
- name: عضو_شو__zibanabz-e21754dc
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: Sezar_sec-091f672c
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: vless-9c3b2633
  type: vless
  server: s3.esrtz.onl
  port: 46470
  uuid: 3bcc6dbf-0ab4-4674-85c8-39bd994434f9
  udp: true
  tls: false
  network: tcp
- name: net0n3_316-60f9bc53
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: qeshmserver
  udp: true
  tls: false
  network: xhttp
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-337a742c
  type: trojan
  server: www.digitalocean.com
  port: 443
  password: trojan
  udp: true
  sni: azadnet-9ya.pages.dev
- name: V2ray1_Ng-4d2f9a8d
  type: vless
  server: 104.16.34.128
  port: 443
  uuid: 267613d7-f53f-4005-b642-d6f1f687b7cf
  udp: true
  tls: true
  network: ws
  servername: ensHOLP-91s.pageS.DEv
  ws-opts:
    path: /dQMN2VQLkaE52qWD?ed=2560
    headers:
      Host: ensHOLP-91s.pageS.DEv
- name: net0n3_318-7ea35b51
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: عضو_شو__zibanabz-4d52ec2a
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: net0n3_314-a60fd033
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
- name: عضو_شو__zibanabz-f101fabe
  type: vless
  server: 147.185.161.229
  port: 80
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: Telegram:@ShadowProxy66/?ed=2560
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
- name: عضو_شو__zibanabz-098b279b
  type: vless
  server: zula.ir
  port: 443
  uuid: 172ed5fd-83a6-469e-863c-50e251a6c17d
  udp: true
  tls: true
  network: ws
  servername: rayan-supra.parisa.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: rayan-supra.parisa.dpdns.org
- name: vless-fe18de90
  type: vless
  server: gb01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: e499f276e7bd6420
- name: vless-15699693
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-1ad54c5c
  type: vless
  server: nl01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: d3b13f31
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-05a3e58c
  type: vless
  server: 62.60.176.30
  port: 48356
  uuid: 0658d669-cf10-469e-a932-6d2144d58d48
  udp: true
  tls: false
  network: tcp
- name: V2ray1_Ng-541c8ed0
  type: ss
  server: 74.177.199.135
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - net0n3_317-9833e067
  - عضو_شو__zibanabz-f4c7c4a4
  - V2ray1_Ng-2e262ef1
  - net0n3_322-5196a1a2
  - vless-7f7ae1a3
  - net0n3_323-a29b95a4
  - vless-f97764fc
  - net0n3_325-4a5b8d10
  - net0n3_310-48361630
  - Sezar_sec-243cb2b1
  - vless-589ea1a4
  - عضو_شو__zibanabz-0c42dd28
  - GpConnectSho_کانکت_شو-88521ab5
  - عضو_شو__zibanabz-f512598b
  - PRX11-931e1d6a
  - عضو_شو__zibanabz-93069c35
  - net0n3_309-3b5bb46b
  - عضو_شو__zibanabz-297f9c30
  - V2ray1_Ng-6a7aee78
  - GpConnectSho_کانکت_شو-2acaac1f
  - عضو_شو__zibanabz-031f87fa
  - net0n3_313-95547c0c
  - V2ray1_Ng-7aa10503
  - عضو_شو__zibanabz-7aa71ed2
  - مولداوی-3350d1ff
  - Sezar_sec-85e97035
  - GpConnectSho_کانکت_شو-d9f834c1
  - هلند__۲-b7aa0dc7
  - vless-27f2348d
  - V2ray1_Ng-266dead1
  - GpConnectSho_کانکت_شو-6bca17c1
  - عضو_شو__zibanabz-419c3303
  - عضو_شو__zibanabz-0569ddc9
  - net0n3_319-9b3f0d9c
  - عضو_شو__zibanabz-b8b95219
  - net0n3_321-c8263b7c
  - عضو_شو__prroxyng-9c86ff6b
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-88f476f7
  - vless-fa92d090
  - عضو_شو__zibanabz-e21754dc
  - Sezar_sec-091f672c
  - vless-9c3b2633
  - net0n3_316-60f9bc53
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-337a742c
  - V2ray1_Ng-4d2f9a8d
  - net0n3_318-7ea35b51
  - عضو_شو__zibanabz-4d52ec2a
  - net0n3_314-a60fd033
  - عضو_شو__zibanabz-f101fabe
  - عضو_شو__zibanabz-098b279b
  - vless-fe18de90
  - vless-15699693
  - vless-1ad54c5c
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-05a3e58c
  - V2ray1_Ng-541c8ed0
- name: AUTO
  type: url-test
  proxies:
  - net0n3_317-9833e067
  - عضو_شو__zibanabz-f4c7c4a4
  - V2ray1_Ng-2e262ef1
  - net0n3_322-5196a1a2
  - vless-7f7ae1a3
  - net0n3_323-a29b95a4
  - vless-f97764fc
  - net0n3_325-4a5b8d10
  - net0n3_310-48361630
  - Sezar_sec-243cb2b1
  - vless-589ea1a4
  - عضو_شو__zibanabz-0c42dd28
  - GpConnectSho_کانکت_شو-88521ab5
  - عضو_شو__zibanabz-f512598b
  - PRX11-931e1d6a
  - عضو_شو__zibanabz-93069c35
  - net0n3_309-3b5bb46b
  - عضو_شو__zibanabz-297f9c30
  - V2ray1_Ng-6a7aee78
  - GpConnectSho_کانکت_شو-2acaac1f
  - عضو_شو__zibanabz-031f87fa
  - net0n3_313-95547c0c
  - V2ray1_Ng-7aa10503
  - عضو_شو__zibanabz-7aa71ed2
  - مولداوی-3350d1ff
  - Sezar_sec-85e97035
  - GpConnectSho_کانکت_شو-d9f834c1
  - هلند__۲-b7aa0dc7
  - vless-27f2348d
  - V2ray1_Ng-266dead1
  - GpConnectSho_کانکت_شو-6bca17c1
  - عضو_شو__zibanabz-419c3303
  - عضو_شو__zibanabz-0569ddc9
  - net0n3_319-9b3f0d9c
  - عضو_شو__zibanabz-b8b95219
  - net0n3_321-c8263b7c
  - عضو_شو__prroxyng-9c86ff6b
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-88f476f7
  - vless-fa92d090
  - عضو_شو__zibanabz-e21754dc
  - Sezar_sec-091f672c
  - vless-9c3b2633
  - net0n3_316-60f9bc53
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-337a742c
  - V2ray1_Ng-4d2f9a8d
  - net0n3_318-7ea35b51
  - عضو_شو__zibanabz-4d52ec2a
  - net0n3_314-a60fd033
  - عضو_شو__zibanabz-f101fabe
  - عضو_شو__zibanabz-098b279b
  - vless-fe18de90
  - vless-15699693
  - vless-1ad54c5c
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-05a3e58c
  - V2ray1_Ng-541c8ed0
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
