port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: GheychiAmoozesh-23-dfe615d9
  type: vless
  server: 135.148.152.106
  port: 443
  uuid: ea286109-d20f-415e-849e-4af20ab04b65
  udp: true
  tls: true
  network: tcp
  servername: 147135001195.sec22org.com
- name: GheychiAmoozesh-27-e6f724aa
  type: ss
  server: series-a2-mec.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: GheychiAmoozesh-25-3e1df9de
  type: ss
  server: 131.145.33.92
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
- name: GheychiAmoozesh-24-a6612205
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 2096
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: Ft77Ta8Q1m.EmShAbKhObE.oRg
  ws-opts:
    path: /
    headers:
      Host: Ft77Ta8Q1m.EmShAbKhObE.oRg
- name: GheychiAmoozesh-26-218ff5c1
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: عضو_شو__zibanabz-7ef246d6
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: GheychiAmoozesh-38-f84110dd
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
  udp: true
  tls: true
  network: ws
  servername: avtice.fullmargintraders.com
  ws-opts:
    path: /wsv/7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
    headers:
      Host: avtice.fullmargintraders.com
- name: reality-mamad_nl-868d2d34
  type: vless
  server: 185.214.101.118
  port: 20435
  uuid: cb2fe166-ac66-404d-aa4e-8d16fb2ef412
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: uob8UvGgvG-F3iz0PuOpam6nSh6789W7BQwtdbAS3S0
    short-id: a84ef4c84588b70d
- name: vless-95613a78
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: 2قطع_شد_بیا_اینجا_بردارV2GaMaBot-f4a866fe
  type: vless
  server: 95.38.104.183
  port: 17237
  uuid: e9ecdfb4-9da5-4f2f-8f96-ab700ca1961e
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-35-612f9423
  type: vless
  server: 91.99.239.156
  port: 443
  uuid: d2d29254-ad3b-495a-b209-5ccc4f12c0a4
  udp: true
  tls: false
  network: tcp
- name: net0n3_413-a4fede6d
  type: vless
  server: 172.66.47.61
  port: 8443
  uuid: a396b860-11b7-4af3-9950-146caf79735e
  udp: true
  tls: true
  network: ws
  servername: gGHDFa.pAgeS.Dev
  ws-opts:
    path: /8WuhXm4QjK0L68Uf?ed=2560
    headers:
      Host: gghdfa.pages.dev
- name: GheychiAmoozesh-31-3dd3db23
  type: vless
  server: 300232332.webnama.com.tr.privatepack.ir
  port: 1517
  uuid: 88f9173d-09b1-463a-99c8-e39852693cba
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-18-464265df
  type: ss
  server: h110vpnus.outlinekeys.net
  port: 9483
  cipher: chacha20-ietf-poly1305
  password: nLwAl3svNCBPtG9I2FrVYI
  udp: true
- name: vless-a6a6931b
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: Telegram--SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: GheychiAmoozesh-33-d694f805
  type: vless
  server: 104.21.112.1
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: GheychiAmoozesh-14-ecfe639f
  type: ss
  server: series-a2-mec.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: کانفیگرایگانجوینشوتلگرامConfVip-86f23bb0
  type: vless
  server: 104.26.6.89
  port: 443
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: NpFzCqA01g.V2pLuSmLm.OrG
  ws-opts:
    path: /
    headers:
      Host: NpFzCqA01g.V2pLuSmLm.OrG
- name: net0n3_414-0542b79a
  type: vless
  server: 78.157.58.116
  port: 55699
  uuid: a01b7f97-04e1-4bfe-b6fb-68ac6eff28cb
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-20-34cd2221
  type: ss
  server: series-a1.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
- name: GheychiAmoozesh-34-1cc4c312
  type: vless
  server: 95.164.45.85
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  network: grpc
- name: عضو_شو__zibanabz-19e37fc9
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: GheychiAmoozesh-16-7bda8b0d
  type: vless
  server: c1.lightxpro.ir
  port: 35775
  uuid: 8c57716b-d545-47b3-981e-c3bbd5a09b3c
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: null
- name: GheychiAmoozesh-15-80df857d
  type: vless
  server: 108.162.198.20
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: GheychiAmoozesh-21-d91355d5
  type: ss
  server: series-a2.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: net0n3_410-47ebdcb5
  type: vless
  server: 104.26.6.89
  port: 80
  uuid: b360267f-81aa-4740-a9c0-9a64fe7f9775
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: onlytesla.xz027.com
- name: GheychiAmoozesh-39-06009cdb
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 6f6e8f09-c1b3-48fd-ab00-18f921d875ef
  udp: true
  tls: true
  network: ws
  servername: profit.fullmargintraders.com
  ws-opts:
    path: /wsv/6f6e8f09-c1b3-48fd-ab00-18f921d875ef
    headers:
      Host: profit.fullmargintraders.com
- name: عضو_شو__zibanabz-c025831c
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: freevpnn11کانال_تلگرام_ما-f7a8f467
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: 1d7b8a06-5122-4d98-b31d-8887eabe78b3
  udp: true
  tls: false
  network: xhttp
- name: net0n3_415-7d1fe2e1
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: 8d93a84b-20cc-40af-a0a2-ad347e1af16e
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /ws/?ed=2048
    headers:
      Host: welcomtofreeboarders.com
- name: عضو_شو__zibanabz-93e1b6f3
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: vless-811969b6
  type: vless
  server: 104.21.43.168
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  servername: 2.link-kon.ir
  ws-opts:
    path: /bDUGlAj9BFG7zebG?ed=2560
    headers:
      Host: 2.lINK-KoN.IR
- name: GheychiAmoozesh-19-70912485
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: GheychiAmoozesh-32-ffb062cc
  type: vless
  server: 188.114.96.3
  port: 8443
  uuid: 88d05a33-ff36-415d-9d2c-7e1e8468e7e8
  udp: true
  tls: true
  network: ws
  servername: w325.pAges.Dev
  ws-opts:
    path: /Tel-@V2ray_Alpha/?ed=2560
    headers:
      Host: w325.pages.dev
- name: vless-da6aeb03
  type: vless
  server: 104.26.6.89
  port: 443
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: NpFzCqA01g.V2pLuSmLm.OrG
  ws-opts:
    path: /
    headers:
      Host: NpFzCqA01g.V2pLuSmLm.OrG
- name: vless-033c0de3
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN-
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: عضو_شو__zibanabz-ef473fca
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: GheychiAmoozesh-22-2a095dbd
  type: ss
  server: admin.c2.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: WstuSnlu4ieA9M0L
  udp: true
- name: چنل_عضو_شو_Pro_V10-82e714fb
  type: vmess
  server: 51.158.146.67
  port: 2086
  uuid: d44b03d8-bb52-f971-d4b9-b4ff78cce8c9
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-c0401941
  type: vless
  server: speedtest.net
  port: 80
  uuid: 3488f5ea-47f8-4d6c-b1af-289c010c57cd
  udp: true
  tls: false
  network: xhttp
- name: net0n3_411-d0658c0a
  type: vless
  server: sr56.toast.sbs
  port: 2095
  uuid: 1d7a7eb0-5214-4a3f-8442-cc95e43a107f
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-12-d0d17126
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: tcp
- name: vless-cd6861d7
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: 8d93a84b-20cc-40af-a0a2-ad347e1af16e
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /ws/?ed=2048
    headers:
      Host: welcomtofreeboarders.com
- name: vless-bbfb8ef4
  type: vless
  server: 172.66.47.61
  port: 8443
  uuid: a396b860-11b7-4af3-9950-146caf79735e
  udp: true
  tls: true
  network: ws
  servername: gGHDFa.pAgeS.Dev
  ws-opts:
    path: /8WuhXm4QjK0L68Uf?ed=2560
    headers:
      Host: gghdfa.pages.dev
- name: vless-b4b1f871
  type: vless
  server: 104.21.43.168
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /bDUGlAj9BFG7zebG?ed=2560
    headers:
      Host: 2.lINK-KoN.IR
- name: GheychiAmoozesh-36-d9d82f66
  type: vless
  server: 34.247.254.247
  port: 50768
  uuid: c7e4c202-cfdf-44df-85a7-a9e7b4545a74
  udp: true
  tls: false
  network: grpc
  servername: jetbrains.com
  reality-opts:
    public-key: 7kUu70kwGDQ65WQHCBXcQ-KLQa5V8VVxX3zMML7hSlQ
    short-id: 4e78519d
- name: عضو_شو__zibanabz-62d0e581
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: GheychiAmoozesh-17-12a9fef4
  type: ss
  server: h110vpnch.outlinekeys.net
  port: 4248
  cipher: chacha20-ietf-poly1305
  password: SasawZo4g7WaqlK3a2mCol
  udp: true
- name: Telegram_vpnbaz-55140891
  type: vless
  server: 213.176.121.239
  port: 57257
  uuid: 9359969a-f79b-47fd-9d79-c7397d10af3d
  udp: true
  tls: false
  network: tcp
- name: vless-02bf62cb
  type: vless
  server: 78.157.58.116
  port: 55699
  uuid: a01b7f97-04e1-4bfe-b6fb-68ac6eff28cb
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-13-71f72cc8
  type: ss
  server: dl.2046.shield-web.ir
  port: 2046
  cipher: chacha20-ietf-poly1305
  password: YZbYU8NosZCi7zuUI5hDlw
  udp: true
- name: GheychiAmoozesh-11-9595eb5c
  type: vless
  server: sp4.god-ping.net
  port: 2051
  uuid: 2725451d-5f83-4998-9f2f-193e656e3bc7
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-2cb8f153
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: 1قطع_شد_بیا_اینجا_بردارV2GaMaBot-d2807289
  type: vmess
  server: 95.38.104.181
  port: 2053
  uuid: 24fd9c3b-ca87-45dd-996d-a1be7778fd98
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: net0n3_409-2de72b23
  type: vless
  server: germany1.neeservers643.ir
  port: 7600
  uuid: 351ebc39-8032-449c-914f-14095fafa8c1
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: ZuogJRtuiVgad1NAmzjZUJqLnCCFnBogwdQufhhuf1A
    short-id: null
- name: IM_SOON-4d9aff57
  type: vmess
  server: www.speedtest.net
  port: 443
  uuid: 02800da0-6018-11f0-b336-205c6d5f5d78
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /3ok7zbsw#@Vip_fragment_v2ray-@Vip_fragment_v2ray-@Vip_fragment_v2ray-@Vip_fragment_v2ray-@Vip_fragment_v2ray-@Vip_fragment_v2ray-
    headers:
      Host: eu-2.hihu.net
- name: ProxySnipe_جوین_شید-b78f23c8
  type: vless
  server: 185.231.205.253
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  network: grpc
- name: عضو_شو__prroxyng-d68e7dba
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: عضو_شو__zibanabz-d4885067
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: GheychiAmoozesh-37-9bef625e
  type: vless
  server: 104.22.24.195
  port: 443
  uuid: 96479a22-9333-4b03-9912-4dd26acef75e
  udp: true
  tls: true
  network: ws
  servername: NExtfilmtOmovies.sitE
  ws-opts:
    path: /9EkfcCDedhvB19xj?ed=2560
    headers:
      Host: nextfilmtomovies.site
- name: test-ef855405
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 1d7b8a06-5122-4d98-b31d-8887eabe78b3
  udp: true
  tls: true
  network: ws
  servername: nlvipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: nlvipys.sevenploos.com
- name: vless-8fa876f8
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: 63fa5580-1bb7-4cc1-a6ee-0ed4eaa52308
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - GheychiAmoozesh-23-dfe615d9
  - GheychiAmoozesh-27-e6f724aa
  - GheychiAmoozesh-25-3e1df9de
  - GheychiAmoozesh-24-a6612205
  - GheychiAmoozesh-26-218ff5c1
  - عضو_شو__zibanabz-7ef246d6
  - GheychiAmoozesh-38-f84110dd
  - reality-mamad_nl-868d2d34
  - vless-95613a78
  - 2قطع_شد_بیا_اینجا_بردارV2GaMaBot-f4a866fe
  - GheychiAmoozesh-35-612f9423
  - net0n3_413-a4fede6d
  - GheychiAmoozesh-31-3dd3db23
  - GheychiAmoozesh-18-464265df
  - vless-a6a6931b
  - GheychiAmoozesh-33-d694f805
  - GheychiAmoozesh-14-ecfe639f
  - کانفیگرایگانجوینشوتلگرامConfVip-86f23bb0
  - net0n3_414-0542b79a
  - GheychiAmoozesh-20-34cd2221
  - GheychiAmoozesh-34-1cc4c312
  - عضو_شو__zibanabz-19e37fc9
  - GheychiAmoozesh-16-7bda8b0d
  - GheychiAmoozesh-15-80df857d
  - GheychiAmoozesh-21-d91355d5
  - net0n3_410-47ebdcb5
  - GheychiAmoozesh-39-06009cdb
  - عضو_شو__zibanabz-c025831c
  - freevpnn11کانال_تلگرام_ما-f7a8f467
  - net0n3_415-7d1fe2e1
  - عضو_شو__zibanabz-93e1b6f3
  - vless-811969b6
  - GheychiAmoozesh-19-70912485
  - GheychiAmoozesh-32-ffb062cc
  - vless-da6aeb03
  - vless-033c0de3
  - عضو_شو__zibanabz-ef473fca
  - GheychiAmoozesh-22-2a095dbd
  - چنل_عضو_شو_Pro_V10-82e714fb
  - vless-c0401941
  - net0n3_411-d0658c0a
  - GheychiAmoozesh-12-d0d17126
  - vless-cd6861d7
  - vless-bbfb8ef4
  - vless-b4b1f871
  - GheychiAmoozesh-36-d9d82f66
  - عضو_شو__zibanabz-62d0e581
  - GheychiAmoozesh-17-12a9fef4
  - Telegram_vpnbaz-55140891
  - vless-02bf62cb
  - GheychiAmoozesh-13-71f72cc8
  - GheychiAmoozesh-11-9595eb5c
  - عضو_شو__zibanabz-2cb8f153
  - 1قطع_شد_بیا_اینجا_بردارV2GaMaBot-d2807289
  - net0n3_409-2de72b23
  - IM_SOON-4d9aff57
  - ProxySnipe_جوین_شید-b78f23c8
  - عضو_شو__prroxyng-d68e7dba
  - عضو_شو__zibanabz-d4885067
  - GheychiAmoozesh-37-9bef625e
  - test-ef855405
  - vless-8fa876f8
- name: AUTO
  type: url-test
  proxies:
  - GheychiAmoozesh-23-dfe615d9
  - GheychiAmoozesh-27-e6f724aa
  - GheychiAmoozesh-25-3e1df9de
  - GheychiAmoozesh-24-a6612205
  - GheychiAmoozesh-26-218ff5c1
  - عضو_شو__zibanabz-7ef246d6
  - GheychiAmoozesh-38-f84110dd
  - reality-mamad_nl-868d2d34
  - vless-95613a78
  - 2قطع_شد_بیا_اینجا_بردارV2GaMaBot-f4a866fe
  - GheychiAmoozesh-35-612f9423
  - net0n3_413-a4fede6d
  - GheychiAmoozesh-31-3dd3db23
  - GheychiAmoozesh-18-464265df
  - vless-a6a6931b
  - GheychiAmoozesh-33-d694f805
  - GheychiAmoozesh-14-ecfe639f
  - کانفیگرایگانجوینشوتلگرامConfVip-86f23bb0
  - net0n3_414-0542b79a
  - GheychiAmoozesh-20-34cd2221
  - GheychiAmoozesh-34-1cc4c312
  - عضو_شو__zibanabz-19e37fc9
  - GheychiAmoozesh-16-7bda8b0d
  - GheychiAmoozesh-15-80df857d
  - GheychiAmoozesh-21-d91355d5
  - net0n3_410-47ebdcb5
  - GheychiAmoozesh-39-06009cdb
  - عضو_شو__zibanabz-c025831c
  - freevpnn11کانال_تلگرام_ما-f7a8f467
  - net0n3_415-7d1fe2e1
  - عضو_شو__zibanabz-93e1b6f3
  - vless-811969b6
  - GheychiAmoozesh-19-70912485
  - GheychiAmoozesh-32-ffb062cc
  - vless-da6aeb03
  - vless-033c0de3
  - عضو_شو__zibanabz-ef473fca
  - GheychiAmoozesh-22-2a095dbd
  - چنل_عضو_شو_Pro_V10-82e714fb
  - vless-c0401941
  - net0n3_411-d0658c0a
  - GheychiAmoozesh-12-d0d17126
  - vless-cd6861d7
  - vless-bbfb8ef4
  - vless-b4b1f871
  - GheychiAmoozesh-36-d9d82f66
  - عضو_شو__zibanabz-62d0e581
  - GheychiAmoozesh-17-12a9fef4
  - Telegram_vpnbaz-55140891
  - vless-02bf62cb
  - GheychiAmoozesh-13-71f72cc8
  - GheychiAmoozesh-11-9595eb5c
  - عضو_شو__zibanabz-2cb8f153
  - 1قطع_شد_بیا_اینجا_بردارV2GaMaBot-d2807289
  - net0n3_409-2de72b23
  - IM_SOON-4d9aff57
  - ProxySnipe_جوین_شید-b78f23c8
  - عضو_شو__prroxyng-d68e7dba
  - عضو_شو__zibanabz-d4885067
  - GheychiAmoozesh-37-9bef625e
  - test-ef855405
  - vless-8fa876f8
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
