mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: Msproxyx-e4149f72
  type: vless
  server: 91.99.1.218
  port: 443
  uuid: b25c9401-2854-49da-86f0-fe0f06ad256a
  udp: true
  network: tcp
- name: Msproxyx-f8531f12
  type: vless
  server: 91.99.237.10
  port: 443
  uuid: 15398933-070d-4ea2-9697-5fcd79793c97
  udp: true
  network: tcp
- name: Msproxyx-aa70a6bf
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: 941d092e-8313-452a-ba21-c9995dcba79d
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: havvas.shohreh.dpdns.org
  ws-opts:
    path: /?ed=2560/?@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-
    headers:
      Host: havvas.shohreh.dpdns.org
- name: Msproxyx-6afc9cb3
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: 941d092e-8313-452a-ba21-c9995dcba79d
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: havvas.shohreh.dpdns.org
  ws-opts:
    path: /?ed=@Selinc/?N
    headers:
      Host: havvas.shohreh.dpdns.org
- name: Msproxyx-c8fd1220
  type: vless
  server: 172.67.92.147
  port: 80
  uuid: b8be6118-0dd7-4402-ae1a-69b2816f3a7f
  udp: true
  network: ws
  ws-opts:
    path: Telegram@V2ray_Alpha/?ed=2560
    headers:
      Host: br.presskiwi.dpdns.org
- name: trojan-56acb72b
  type: trojan
  server: 91.107.163.173
  port: 27596
  password: OmqcThZWp1
  udp: true
  skip-cert-verify: true
- name: vless-f0076ef4
  type: vless
  server: 91.99.160.151
  port: 443
  uuid: 153ee04c-dcc1-4ef8-a146-8fb31cec1f48
  udp: true
  network: tcp
- name: vless-35d1be40
  type: vless
  server: 62.60.223.6
  port: 2080
  uuid: bea34b73-3244-475b-b914-7bb80e1cda91
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: L3lJWdU7mHijSkNaNt-m29OYnKnHvHYRxg2Y8XXFdng
    short-id: bf517367267685
- name: vless-cea50eaf
  type: vless
  server: 91.99.195.6
  port: 80
  uuid: 91a5d5b3-4b88-4359-aeec-e1532f535fd6
  udp: true
  network: grpc
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZO276Z5WXIqCmNLXT8Lewzjhhgm365JUJXAKyKq8Rz4
    short-id: bc063769cb
  grpc-opts:
    grpc-service-name: refersion.com
- name: vless-07482e28
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /zula.ir
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: vless-fc5e6cb7
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-5ef852d7
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-e00376b5
  type: vless
  server: 91.99.184.231
  port: 45103
  uuid: 6bdc18b7-a33f-46ae-a5e3-df7cb21f36b2
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: vless-55bc85c6
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-0e82be1e
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-e0e360a0
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-4e921c47
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-c255c653
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-53113c7d
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-3da05d6b
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-2956c16d
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-5f6ea273
  type: vless
  server: accounting.vinamarketcenter.ir
  port: 443
  uuid: 5cfba4ac-105a-452a-ac10-88b1adf784ee
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: T7Cwk-B3EvZqqRywIgN_TNotJiUOXYUI9bHqYKPnTi0
    short-id: 105e89ba3d2a1c3b
- name: Sezar_Sec-a274ab61
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-05b5f026
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-743bf80d
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: Sezar_Sec-845a3b65
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: Sezar_Sec-cf7db81c
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: barayeiranmahsang.sabzipolobamahi.dpdns.org
  ws-opts:
    path: /?ed=2560/?CHANEL@RK_VPS@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: مشتی_جوین_بده_ناموصا__xzjinx-d5a0dacc
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: d64669fb-07e5-4d27-9995-63545fae16c2
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-53a24ed4
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: d64669fb-07e5-4d27-9995-63545fae16c2
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-5a3b3591
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: f7255d17-4abc-4c54-84dd-e1e9e9c41dad
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-efd39b28
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: 395bf21d-ea83-4d85-ad04-ad1f6b1431bf
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-6a1c02e7
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: 395bf21d-ea83-4d85-ad04-ad1f6b1431bf
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-82436544
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: 49203d20-5f1b-4628-d526-9a6825c3f5f3
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-251ebf9c
  type: vless
  server: 5.160.197.120
  port: 16644
  uuid: c2d3a355-e556-40e0-cd5a-41dff6eb525d
  udp: true
  network: tcp
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - Msproxyx-e4149f72
  - Msproxyx-f8531f12
  - Msproxyx-aa70a6bf
  - Msproxyx-6afc9cb3
  - Msproxyx-c8fd1220
  - trojan-56acb72b
  - vless-f0076ef4
  - vless-35d1be40
  - vless-cea50eaf
  - vless-07482e28
  - vless-fc5e6cb7
  - vless-5ef852d7
  - vless-e00376b5
  - vless-55bc85c6
  - vless-0e82be1e
  - vless-e0e360a0
  - vless-4e921c47
  - vless-c255c653
  - vless-53113c7d
  - vless-3da05d6b
  - vless-2956c16d
  - vless-5f6ea273
  - Sezar_Sec-a274ab61
  - Sezar_Sec-05b5f026
  - Sezar_Sec-743bf80d
  - Sezar_Sec-845a3b65
  - Sezar_Sec-cf7db81c
  - مشتی_جوین_بده_ناموصا__xzjinx-d5a0dacc
  - مشتی_جوین_بده_ناموصا__xzjinx-53a24ed4
  - مشتی_جوین_بده_ناموصا__xzjinx-5a3b3591
  - مشتی_جوین_بده_ناموصا__xzjinx-efd39b28
  - مشتی_جوین_بده_ناموصا__xzjinx-6a1c02e7
  - مشتی_جوین_بده_ناموصا__xzjinx-82436544
  - مشتیجوینبدهناموصاxzjinx-251ebf9c
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
