port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: vless-674647eb
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: GheychiAmoozesh-39-251c4648
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 6f6e8f09-c1b3-48fd-ab00-18f921d875ef
  udp: true
  tls: true
  network: ws
  servername: profit.fullmargintraders.com
  ws-opts:
    path: /wsv/6f6e8f09-c1b3-48fd-ab00-18f921d875ef
    headers:
      Host: profit.fullmargintraders.com
- name: عضو_شو__zibanabz-72295176
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: عضو_شو__prroxyng-d26bdb4c
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: GheychiAmoozesh-32-c090c08b
  type: vless
  server: 188.114.96.3
  port: 8443
  uuid: 88d05a33-ff36-415d-9d2c-7e1e8468e7e8
  udp: true
  tls: true
  network: ws
  servername: w325.pAges.Dev
  ws-opts:
    path: /Tel-@V2ray_Alpha/?ed=2560
    headers:
      Host: w325.pages.dev
- name: عضو_شو__zibanabz-90402ab1
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: GheychiAmoozesh-19-278c9668
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: کانفیگرایگانجوینشوتلگرامConfVip-8278854c
  type: vless
  server: 104.26.6.89
  port: 443
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: NpFzCqA01g.V2pLuSmLm.OrG
  ws-opts:
    path: /
    headers:
      Host: NpFzCqA01g.V2pLuSmLm.OrG
- name: net0n3_414-30d2ab52
  type: vless
  server: 78.157.58.116
  port: 55699
  uuid: a01b7f97-04e1-4bfe-b6fb-68ac6eff28cb
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-21-0b22614e
  type: ss
  server: series-a2.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: GheychiAmoozesh-14-0db5f44b
  type: ss
  server: series-a2-mec.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: test4-3a3aabdb
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: baf334b7-f07e-420d-8efb-060cb3fff630
  udp: true
  tls: false
  network: xhttp
- name: vless-bcd5c8b7
  type: vless
  server: 104.21.112.1
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: GheychiAmoozesh-23-c6b45f45
  type: vless
  server: 135.148.152.106
  port: 443
  uuid: ea286109-d20f-415e-849e-4af20ab04b65
  udp: true
  tls: true
  network: tcp
  servername: 147135001195.sec22org.com
- name: GheychiAmoozesh-11-287fa550
  type: vless
  server: sp4.god-ping.net
  port: 2051
  uuid: 2725451d-5f83-4998-9f2f-193e656e3bc7
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-e5638244
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: GheychiAmoozesh-13-11a438ae
  type: ss
  server: dl.2046.shield-web.ir
  port: 2046
  cipher: chacha20-ietf-poly1305
  password: YZbYU8NosZCi7zuUI5hDlw
  udp: true
- name: GheychiAmoozesh-20-66c855c2
  type: ss
  server: series-a1.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
- name: GheychiAmoozesh-25-51a84aa3
  type: ss
  server: 131.145.33.92
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
- name: چنل_عضو_شو_Pro_V10-91753bf8
  type: vmess
  server: 51.158.146.67
  port: 2086
  uuid: d44b03d8-bb52-f971-d4b9-b4ff78cce8c9
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-29d3f1ce
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN-
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: GheychiAmoozesh-36-d4730bf3
  type: vless
  server: 34.247.254.247
  port: 50768
  uuid: c7e4c202-cfdf-44df-85a7-a9e7b4545a74
  udp: true
  tls: false
  network: grpc
  servername: jetbrains.com
  reality-opts:
    public-key: 7kUu70kwGDQ65WQHCBXcQ-KLQa5V8VVxX3zMML7hSlQ
    short-id: 4e78519d
- name: net0n3_409-b4f68baf
  type: vless
  server: germany1.neeservers643.ir
  port: 7600
  uuid: 351ebc39-8032-449c-914f-14095fafa8c1
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: ZuogJRtuiVgad1NAmzjZUJqLnCCFnBogwdQufhhuf1A
    short-id: null
- name: GheychiAmoozesh-22-d7170a1e
  type: ss
  server: admin.c2.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: WstuSnlu4ieA9M0L
  udp: true
- name: GheychiAmoozesh-26-894972c9
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: عضو_شو__zibanabz-847f6d43
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: Viturey_2-58684411
  type: vless
  server: 157.180.33.125
  port: 80
  uuid: 9603de7d-1248-a741-1d69-7e1a0fb9e693
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/
    headers:
      Host: null
- name: Sezar_Sec-bf5826e2
  type: vless
  server: 65.109.203.70
  port: 2096
  uuid: feea904b-d443-43e1-beaa-621ef7a3de3f
  udp: true
  tls: false
  network: tcp
- name: net0n3_410-79f91991
  type: vless
  server: 104.26.6.89
  port: 80
  uuid: b360267f-81aa-4740-a9c0-9a64fe7f9775
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: onlytesla.xz027.com
- name: vless-63d15274
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: 63fa5580-1bb7-4cc1-a6ee-0ed4eaa52308
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: vless-94607d53
  type: vless
  server: speedtest.net
  port: 80
  uuid: 3488f5ea-47f8-4d6c-b1af-289c010c57cd
  udp: true
  tls: false
  network: xhttp
- name: GheychiAmoozesh-34-a1bd4138
  type: vless
  server: 95.164.45.85
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  network: grpc
- name: vless-6dadeff0
  type: vless
  server: 104.21.32.1
  port: 2096
  uuid: 8ca4ca74-fa0c-4c18-86c5-ce6d0382ff14
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: DO-iTforyOu-E1P.PAgeS.dEV
- name: Channelvmessorg-18d1f8fb
  type: vless
  server: 104.21.43.168
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  servername: 2.link-kon.ir
  ws-opts:
    path: /bDUGlAj9BFG7zebG?ed=2560
    headers:
      Host: 2.lINK-KoN.IR
- name: GheychiAmoozesh-15-282cd46e
  type: vless
  server: 108.162.198.20
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: GheychiAmoozesh-35-4587affd
  type: vless
  server: 91.99.239.156
  port: 443
  uuid: d2d29254-ad3b-495a-b209-5ccc4f12c0a4
  udp: true
  tls: false
  network: tcp
- name: test1-b6af6118
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 29cbae1c-0d29-4213-8220-d1302816c4b1
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: vless-25dfc979
  type: vless
  server: 172.66.44.253
  port: 8443
  uuid: efed37ed-37e5-4100-a540-049dc7929984
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /dy26vBaDi5RTblzP?ed=2560
    headers:
      Host: net-aCcOUNt02.Pages.DEv
- name: ProxySnipe_جوین_شید-3b067d99
  type: vless
  server: 185.231.205.253
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  network: grpc
- name: test3-cd9152aa
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: baf334b7-f07e-420d-8efb-060cb3fff630
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: GheychiAmoozesh-16-4272fdb3
  type: vless
  server: c1.lightxpro.ir
  port: 35775
  uuid: 8c57716b-d545-47b3-981e-c3bbd5a09b3c
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: null
- name: vless-784e12a8
  type: vless
  server: 104.21.43.168
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  servername: 2.link-kon.ir
  ws-opts:
    path: /bDUGlAj9BFG7zebG?ed=2560
    headers:
      Host: 2.lINK-KoN.IR
- name: GheychiAmoozesh-12-cafc7d3d
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-2dd64858
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: GheychiAmoozesh-37-2fdf82f7
  type: vless
  server: 104.22.24.195
  port: 443
  uuid: 96479a22-9333-4b03-9912-4dd26acef75e
  udp: true
  tls: true
  network: ws
  servername: NExtfilmtOmovies.sitE
  ws-opts:
    path: /9EkfcCDedhvB19xj?ed=2560
    headers:
      Host: nextfilmtomovies.site
- name: GheychiAmoozesh-18-8e890185
  type: ss
  server: h110vpnus.outlinekeys.net
  port: 9483
  cipher: chacha20-ietf-poly1305
  password: nLwAl3svNCBPtG9I2FrVYI
  udp: true
- name: GheychiAmoozesh-31-7c2c1b1b
  type: vless
  server: 300232332.webnama.com.tr.privatepack.ir
  port: 1517
  uuid: 88f9173d-09b1-463a-99c8-e39852693cba
  udp: true
  tls: false
  network: tcp
- name: ChannelTelegram__CaptalVpn-e061d3ba
  type: vless
  server: 104.21.43.168
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  servername: 2.link-kon.ir
  ws-opts:
    path: /bDUGlAj9BFG7zebG?ed=2560
    headers:
      Host: 2.lINK-KoN.IR
- name: عضو_شو__zibanabz-240bf003
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: عضو_شو__zibanabz-cfab14df
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: Sezar_Sec-1e48031e
  type: vless
  server: 31.7.73.146
  port: 17778
  uuid: 080ab9d1-66da-4711-96c6-9bdeb6c90093
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-17-97859c93
  type: ss
  server: h110vpnch.outlinekeys.net
  port: 4248
  cipher: chacha20-ietf-poly1305
  password: SasawZo4g7WaqlK3a2mCol
  udp: true
- name: test2-902851e4
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: 29cbae1c-0d29-4213-8220-d1302816c4b1
  udp: true
  tls: false
  network: xhttp
- name: vless-db2660f4
  type: vless
  server: 91.99.141.177
  port: 443
  uuid: 1a827c35-7a17-48d8-a9f5-eeed323ca57b
  udp: true
  tls: false
  network: tcp
  servername: refersion.com
  reality-opts:
    public-key: SJt4jAvhiR5MVRnl-OPj2BWUXZT6p4oH-Ugl3B0b-VA
    short-id: 8ad4b0d652d3e8
- name: GheychiAmoozesh-27-ba578b82
  type: ss
  server: series-a2-mec.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: telegram_id__Viturey-a8ded9f8
  type: vless
  server: lingering-boat-0b47.vpnetwork3567.workers.dev
  port: 443
  uuid: 563B4029-2161-7E31-FA35-1B21441AE537
  udp: true
  tls: true
  network: ws
  servername: lingering-boat-0b47.vpnetwork3567.workers.dev
  ws-opts:
    path: /
    headers:
      Host: lingering-boat-0b47.vpnetwork3567.workers.dev
- name: عضو_شو__zibanabz-9ffdfe5d
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: net0n3_411-aa504461
  type: vless
  server: sr56.toast.sbs
  port: 2095
  uuid: 1d7a7eb0-5214-4a3f-8442-cc95e43a107f
  udp: true
  tls: false
  network: tcp
- name: Sezar_Sec-1b15aaa3
  type: vmess
  server: panel1.ipyar.org
  port: 42684
  uuid: c4bd9eba-8aea-4d5e-a2ee-b5de65ac14e1
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: ChannelTelegram__CaptalVpn-8f36aab3
  type: vless
  server: 91.107.150.172
  port: 443
  uuid: 9767a982-d18d-4634-ad2b-c93489cbffae
  udp: true
  tls: false
  network: tcp
- name: vless-c284aae3
  type: vless
  server: 104.21.43.168
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /bDUGlAj9BFG7zebG?ed=2560
    headers:
      Host: 2.lINK-KoN.IR
- name: GheychiAmoozesh-24-0d6fe6d4
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 2096
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: Ft77Ta8Q1m.EmShAbKhObE.oRg
  ws-opts:
    path: /
    headers:
      Host: Ft77Ta8Q1m.EmShAbKhObE.oRg
- name: vless-32ce53f1
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: Telegram--SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: vless-32d0d400
  type: vless
  server: 104.26.6.89
  port: 443
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: NpFzCqA01g.V2pLuSmLm.OrG
  ws-opts:
    path: /
    headers:
      Host: NpFzCqA01g.V2pLuSmLm.OrG
- name: net0n3_415-2832fce2
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: 8d93a84b-20cc-40af-a0a2-ad347e1af16e
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /ws/?ed=2048
    headers:
      Host: welcomtofreeboarders.com
- name: Channelvmessorg-a53b4072
  type: vless
  server: 91.107.150.172
  port: 443
  uuid: 9767a982-d18d-4634-ad2b-c93489cbffae
  udp: true
  tls: false
  network: tcp
- name: net0n3_413-9367d576
  type: vless
  server: 172.66.47.61
  port: 8443
  uuid: a396b860-11b7-4af3-9950-146caf79735e
  udp: true
  tls: true
  network: ws
  servername: gGHDFa.pAgeS.Dev
  ws-opts:
    path: /8WuhXm4QjK0L68Uf?ed=2560
    headers:
      Host: gghdfa.pages.dev
- name: GheychiAmoozesh-38-17dd6d93
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
  udp: true
  tls: true
  network: ws
  servername: avtice.fullmargintraders.com
  ws-opts:
    path: /wsv/7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
    headers:
      Host: avtice.fullmargintraders.com
- name: GheychiAmoozesh-33-ac539aaf
  type: vless
  server: 104.21.112.1
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - vless-674647eb
  - GheychiAmoozesh-39-251c4648
  - عضو_شو__zibanabz-72295176
  - عضو_شو__prroxyng-d26bdb4c
  - GheychiAmoozesh-32-c090c08b
  - عضو_شو__zibanabz-90402ab1
  - GheychiAmoozesh-19-278c9668
  - کانفیگرایگانجوینشوتلگرامConfVip-8278854c
  - net0n3_414-30d2ab52
  - GheychiAmoozesh-21-0b22614e
  - GheychiAmoozesh-14-0db5f44b
  - test4-3a3aabdb
  - vless-bcd5c8b7
  - GheychiAmoozesh-23-c6b45f45
  - GheychiAmoozesh-11-287fa550
  - عضو_شو__zibanabz-e5638244
  - GheychiAmoozesh-13-11a438ae
  - GheychiAmoozesh-20-66c855c2
  - GheychiAmoozesh-25-51a84aa3
  - چنل_عضو_شو_Pro_V10-91753bf8
  - vless-29d3f1ce
  - GheychiAmoozesh-36-d4730bf3
  - net0n3_409-b4f68baf
  - GheychiAmoozesh-22-d7170a1e
  - GheychiAmoozesh-26-894972c9
  - عضو_شو__zibanabz-847f6d43
  - Viturey_2-58684411
  - Sezar_Sec-bf5826e2
  - net0n3_410-79f91991
  - vless-63d15274
  - vless-94607d53
  - GheychiAmoozesh-34-a1bd4138
  - vless-6dadeff0
  - Channelvmessorg-18d1f8fb
  - GheychiAmoozesh-15-282cd46e
  - GheychiAmoozesh-35-4587affd
  - test1-b6af6118
  - vless-25dfc979
  - ProxySnipe_جوین_شید-3b067d99
  - test3-cd9152aa
  - GheychiAmoozesh-16-4272fdb3
  - vless-784e12a8
  - GheychiAmoozesh-12-cafc7d3d
  - عضو_شو__zibanabz-2dd64858
  - GheychiAmoozesh-37-2fdf82f7
  - GheychiAmoozesh-18-8e890185
  - GheychiAmoozesh-31-7c2c1b1b
  - ChannelTelegram__CaptalVpn-e061d3ba
  - عضو_شو__zibanabz-240bf003
  - عضو_شو__zibanabz-cfab14df
  - Sezar_Sec-1e48031e
  - GheychiAmoozesh-17-97859c93
  - test2-902851e4
  - vless-db2660f4
  - GheychiAmoozesh-27-ba578b82
  - telegram_id__Viturey-a8ded9f8
  - عضو_شو__zibanabz-9ffdfe5d
  - net0n3_411-aa504461
  - Sezar_Sec-1b15aaa3
  - ChannelTelegram__CaptalVpn-8f36aab3
  - vless-c284aae3
  - GheychiAmoozesh-24-0d6fe6d4
  - vless-32ce53f1
  - vless-32d0d400
  - net0n3_415-2832fce2
  - Channelvmessorg-a53b4072
  - net0n3_413-9367d576
  - GheychiAmoozesh-38-17dd6d93
  - GheychiAmoozesh-33-ac539aaf
- name: AUTO
  type: url-test
  proxies:
  - vless-674647eb
  - GheychiAmoozesh-39-251c4648
  - عضو_شو__zibanabz-72295176
  - عضو_شو__prroxyng-d26bdb4c
  - GheychiAmoozesh-32-c090c08b
  - عضو_شو__zibanabz-90402ab1
  - GheychiAmoozesh-19-278c9668
  - کانفیگرایگانجوینشوتلگرامConfVip-8278854c
  - net0n3_414-30d2ab52
  - GheychiAmoozesh-21-0b22614e
  - GheychiAmoozesh-14-0db5f44b
  - test4-3a3aabdb
  - vless-bcd5c8b7
  - GheychiAmoozesh-23-c6b45f45
  - GheychiAmoozesh-11-287fa550
  - عضو_شو__zibanabz-e5638244
  - GheychiAmoozesh-13-11a438ae
  - GheychiAmoozesh-20-66c855c2
  - GheychiAmoozesh-25-51a84aa3
  - چنل_عضو_شو_Pro_V10-91753bf8
  - vless-29d3f1ce
  - GheychiAmoozesh-36-d4730bf3
  - net0n3_409-b4f68baf
  - GheychiAmoozesh-22-d7170a1e
  - GheychiAmoozesh-26-894972c9
  - عضو_شو__zibanabz-847f6d43
  - Viturey_2-58684411
  - Sezar_Sec-bf5826e2
  - net0n3_410-79f91991
  - vless-63d15274
  - vless-94607d53
  - GheychiAmoozesh-34-a1bd4138
  - vless-6dadeff0
  - Channelvmessorg-18d1f8fb
  - GheychiAmoozesh-15-282cd46e
  - GheychiAmoozesh-35-4587affd
  - test1-b6af6118
  - vless-25dfc979
  - ProxySnipe_جوین_شید-3b067d99
  - test3-cd9152aa
  - GheychiAmoozesh-16-4272fdb3
  - vless-784e12a8
  - GheychiAmoozesh-12-cafc7d3d
  - عضو_شو__zibanabz-2dd64858
  - GheychiAmoozesh-37-2fdf82f7
  - GheychiAmoozesh-18-8e890185
  - GheychiAmoozesh-31-7c2c1b1b
  - ChannelTelegram__CaptalVpn-e061d3ba
  - عضو_شو__zibanabz-240bf003
  - عضو_شو__zibanabz-cfab14df
  - Sezar_Sec-1e48031e
  - GheychiAmoozesh-17-97859c93
  - test2-902851e4
  - vless-db2660f4
  - GheychiAmoozesh-27-ba578b82
  - telegram_id__Viturey-a8ded9f8
  - عضو_شو__zibanabz-9ffdfe5d
  - net0n3_411-aa504461
  - Sezar_Sec-1b15aaa3
  - ChannelTelegram__CaptalVpn-8f36aab3
  - vless-c284aae3
  - GheychiAmoozesh-24-0d6fe6d4
  - vless-32ce53f1
  - vless-32d0d400
  - net0n3_415-2832fce2
  - Channelvmessorg-a53b4072
  - net0n3_413-9367d576
  - GheychiAmoozesh-38-17dd6d93
  - GheychiAmoozesh-33-ac539aaf
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
