port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: vless-13996f46
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: zula.ir
    headers:
      Host: azadnet-7py.pages.dev
- name: عضو_شو__zibanabz-7c99d54c
  type: vless
  server: zula.ir
  port: 443
  uuid: 172ed5fd-83a6-469e-863c-50e251a6c17d
  udp: true
  tls: true
  network: ws
  servername: rayan-supra.parisa.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: rayan-supra.parisa.dpdns.org
- name: V2ray1_Ng-b23449c2
  type: ss
  server: 74.177.199.135
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: net0n3_321-eded4fec
  type: ss
  server: 172.187.105.25
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-a77133ef
  type: vless
  server: 62.60.176.30
  port: 48356
  uuid: 0658d669-cf10-469e-a932-6d2144d58d48
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-a8b6f2e3
  type: vless
  server: 104.16.104.151
  port: 80
  uuid: 1f431db3-1918-4e7b-a855-c93485e11694
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: pari.parinazz.dpdns.org
- name: Sezar_sec-c18af409
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
- name: vless-222b1a31
  type: vless
  server: nl01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: d3b13f31
- name: Sezar_sec-87718211
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: Sezar_sec-3c446f4d
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  tls: false
  network: tcp
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: عضو_شو__zibanabz-4bf4f2a8
  type: vless
  server: 172.67.128.105
  port: 80
  uuid: 4179c595-08ca-45cd-b555-91b6f1faeadc
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: di.dibdibini.dpdns.org
- name: V2ray1_Ng-c7a1c96f
  type: vless
  server: www.speedtest.net
  port: 2096
  uuid: c819261a-ad50-4ded-b164-1eafed9885c2
  udp: true
  tls: true
  network: ws
  servername: 638868951946670036.amsterdam-prx-dnraaal.info
  ws-opts:
    path: /mmdhmrws
    headers:
      Host: 638868951946670036.amsterdam-prx-dnraaal.info
- name: vless-2d6c6152
  type: vless
  server: gb01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: e499f276e7bd6420
- name: vless-6b573eb0
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: هلند__۲-67f14264
  type: ss
  server: 45.87.175.190
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
- name: مولداوی-f3bb92e9
  type: ss
  server: 45.153.124.90
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
  udp: true
- name: vless-1ace3863
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: V2ray1_Ng-1f8a8629
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: xhttp
- name: net0n3_318-e83e07c7
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: net0n3_323-c6b1d765
  type: vless
  server: gb01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: e499f276e7bd6420
- name: عضو_شو__prroxyng-4fefbba4
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: vless-5056a127
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 6bcb4f37-bba7-4ae0-afac-d43195c72c12
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: zula.ir?ed=2560
    headers:
      Host: my.digikala.dynv6.net
- name: عضو_شو__zibanabz-69164f77
  type: vless
  server: 172.67.67.92
  port: 80
  uuid: f78ce1bb-0fa6-4ef4-b4c9-b91014a7055d
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: delam.ahaysiahzangi.dpdns.org
- name: net0n3_317-01ce9271
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 6bcb4f37-bba7-4ae0-afac-d43195c72c12
  udp: true
  tls: true
  network: ws
  servername: my.digikala.dynv6.net
  ws-opts:
    path: zula.ir
    headers:
      Host: my.digikala.dynv6.net
- name: net0n3_316-9a24c3ab
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: qeshmserver
  udp: true
  tls: false
  network: xhttp
- name: vless-13c6b3cc
  type: vless
  server: russiatest-tap.servers807.ir
  port: 13796
  uuid: b646e0d6-137b-49e1-90bc-3b9ad8a6484a
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: AIUUKeq08usIla0uv-NTp5wVe4TMb3VkXWDLoutlFnM
    short-id: a3ac
- name: net0n3_322-12c68697
  type: vless
  server: nl01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: d3b13f31
- name: vless-60c1288a
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: xhttp
- name: vless-8ae4ba35
  type: vless
  server: s3.esrtz.onl
  port: 46470
  uuid: 3bcc6dbf-0ab4-4674-85c8-39bd994434f9
  udp: true
  tls: false
  network: tcp
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-d3272a9f
  type: vless
  server: 109.207.172.165
  port: 8443
  uuid: 0aec2ba3-6201-4605-83e9-3a4b1c88f04a
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-ecf7548a
  type: vless
  server: 147.185.161.229
  port: 80
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: Telegram:@ShadowProxy66/?ed=2560
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-63cca2f6
  type: trojan
  server: www.digitalocean.com
  port: 443
  password: trojan
  udp: true
  sni: azadnet-9ya.pages.dev
- name: V2ray1_Ng-c9b65986
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /Telegram@V2ray_Alpha/?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: V2ray1_Ng-ba529f66
  type: trojan
  server: 104.248.18.1
  port: 1935
  password: 6gZh2JbfhQ
  udp: true
  sni: x1-germany-digitalocean-v2.devefun.org
- name: net0n3_325-d123330c
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 6bcb4f37-bba7-4ae0-afac-d43195c72c12
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: zula.ir?ed=2560
    headers:
      Host: my.digikala.dynv6.net
- name: net0n3_313-6a228592
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
- name: net0n3_314-d8595b53
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
- name: عضو_شو__zibanabz-515f2cb3
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: net0n3_319-4c6c77d7
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: zula.ir
    headers:
      Host: azadnet-7py.pages.dev
- name: لهستان__۱-7827144d
  type: vless
  server: 104.17.2.63
  port: 443
  uuid: c98a16e4-0dc5-42f0-b3db-30f04525c123
  udp: true
  tls: true
  network: ws
  servername: vless1-bu3.pages.dev
  ws-opts:
    path: /
    headers:
      Host: vless1-bu3.pages.dev
- name: V2ray1_Ng-5892dfce
  type: vless
  server: 104.16.34.128
  port: 443
  uuid: 267613d7-f53f-4005-b642-d6f1f687b7cf
  udp: true
  tls: true
  network: ws
  servername: ensHOLP-91s.pageS.DEv
  ws-opts:
    path: /dQMN2VQLkaE52qWD?ed=2560
    headers:
      Host: ensHOLP-91s.pageS.DEv
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-56ad8cf9
  type: ss
  server: 74.177.199.135
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: هلند-69680bc6
  type: ss
  server: 109.201.152.181
  port: 443
  cipher: aes-128-cfb
  password: shadowsocks
  udp: true
- name: عضو_شو__zibanabz-be422f4a
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: عضو_شو__zibanabz-b980fb62
  type: vless
  server: 172.67.49.134
  port: 443
  uuid: 06e4425e-a8cb-4b63-929f-2105604ab0a9
  udp: true
  tls: true
  network: ws
  servername: rc.ylks0033.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: rc.ylks0033.dpdns.org
- name: net0n3_309-ba8cd9b5
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 546cc913-2825-4771-b713-a23905913141
  udp: true
  tls: true
  network: ws
  servername: 638874931195949050.kish-prx-dnraaaf.info
  ws-opts:
    path: /wjwqzaws
    headers:
      Host: 638874931195949050.kish-prx-dnraaaf.info
- name: net0n3_310-41bdf438
  type: vless
  server: 0ger.amazon-osishop.ir
  port: 8880
  uuid: 2066c2f3-bde1-429f-b083-fcfc7aee14b5
  udp: true
  tls: false
  network: tcp
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - vless-13996f46
  - عضو_شو__zibanabz-7c99d54c
  - V2ray1_Ng-b23449c2
  - net0n3_321-eded4fec
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-a77133ef
  - عضو_شو__zibanabz-a8b6f2e3
  - Sezar_sec-c18af409
  - vless-222b1a31
  - Sezar_sec-87718211
  - Sezar_sec-3c446f4d
  - عضو_شو__zibanabz-4bf4f2a8
  - V2ray1_Ng-c7a1c96f
  - vless-2d6c6152
  - vless-6b573eb0
  - هلند__۲-67f14264
  - مولداوی-f3bb92e9
  - vless-1ace3863
  - V2ray1_Ng-1f8a8629
  - net0n3_318-e83e07c7
  - net0n3_323-c6b1d765
  - عضو_شو__prroxyng-4fefbba4
  - vless-5056a127
  - عضو_شو__zibanabz-69164f77
  - net0n3_317-01ce9271
  - net0n3_316-9a24c3ab
  - vless-13c6b3cc
  - net0n3_322-12c68697
  - vless-60c1288a
  - vless-8ae4ba35
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-d3272a9f
  - عضو_شو__zibanabz-ecf7548a
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-63cca2f6
  - V2ray1_Ng-c9b65986
  - V2ray1_Ng-ba529f66
  - net0n3_325-d123330c
  - net0n3_313-6a228592
  - net0n3_314-d8595b53
  - عضو_شو__zibanabz-515f2cb3
  - net0n3_319-4c6c77d7
  - لهستان__۱-7827144d
  - V2ray1_Ng-5892dfce
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-56ad8cf9
  - هلند-69680bc6
  - عضو_شو__zibanabz-be422f4a
  - عضو_شو__zibanabz-b980fb62
  - net0n3_309-ba8cd9b5
  - net0n3_310-41bdf438
- name: AUTO
  type: url-test
  proxies:
  - vless-13996f46
  - عضو_شو__zibanabz-7c99d54c
  - V2ray1_Ng-b23449c2
  - net0n3_321-eded4fec
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-a77133ef
  - عضو_شو__zibanabz-a8b6f2e3
  - Sezar_sec-c18af409
  - vless-222b1a31
  - Sezar_sec-87718211
  - Sezar_sec-3c446f4d
  - عضو_شو__zibanabz-4bf4f2a8
  - V2ray1_Ng-c7a1c96f
  - vless-2d6c6152
  - vless-6b573eb0
  - هلند__۲-67f14264
  - مولداوی-f3bb92e9
  - vless-1ace3863
  - V2ray1_Ng-1f8a8629
  - net0n3_318-e83e07c7
  - net0n3_323-c6b1d765
  - عضو_شو__prroxyng-4fefbba4
  - vless-5056a127
  - عضو_شو__zibanabz-69164f77
  - net0n3_317-01ce9271
  - net0n3_316-9a24c3ab
  - vless-13c6b3cc
  - net0n3_322-12c68697
  - vless-60c1288a
  - vless-8ae4ba35
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-d3272a9f
  - عضو_شو__zibanabz-ecf7548a
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-63cca2f6
  - V2ray1_Ng-c9b65986
  - V2ray1_Ng-ba529f66
  - net0n3_325-d123330c
  - net0n3_313-6a228592
  - net0n3_314-d8595b53
  - عضو_شو__zibanabz-515f2cb3
  - net0n3_319-4c6c77d7
  - لهستان__۱-7827144d
  - V2ray1_Ng-5892dfce
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-56ad8cf9
  - هلند-69680bc6
  - عضو_شو__zibanabz-be422f4a
  - عضو_شو__zibanabz-b980fb62
  - net0n3_309-ba8cd9b5
  - net0n3_310-41bdf438
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
