port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: All¹-b77a2b35
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: 259923b6-756d-4b33-9ea9-73e55378018a
  udp: true
  tls: false
  network: xhttp
- name: vless-82082dde
  type: vless
  server: david2.lemoex.blog
  port: 443
  uuid: 737c9e58-379d-4654-9471-d60494b326bd
  udp: true
  tls: true
  network: httpupgrade
  servername: david2.lemoex.blog
- name: net0n3_352-b80892cc
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: Channelalammzar-7b73b8a3
  type: vless
  server: 104.19.245.206
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: By_EbraSha_vless-KR-144fe8f5
  type: vless
  server: 8.213.149.42
  port: 443
  uuid: 5c183802-747d-4d2f-a6f1-aff2d5d78401
  udp: true
  tls: false
  network: tcp
  servername: wwwimages2.adobe.com
  reality-opts:
    public-key: DNdTBHyztOVJOBJQX91YXEhNkWbSAntqUoTFBHc6Clw
    short-id: 6ba85179e30d4fc2
- name: VConfing-0ccf5e14
  type: vmess
  server: 81.12.33.180
  port: 8595
  uuid: 4e6e51d7-1234-4543-999f-0f54a428b77f
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-e00801d0
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 8443
  uuid: 96a1b724-68d2-4f4d-ab25-38ecd83577bc
  udp: true
  tls: true
  network: ws
  servername: IyFpLkXk10.jOoLaJoOlA.OrG
  ws-opts:
    path: /
    headers:
      Host: IyFpLkXk10.jOoLaJoOlA.OrG
- name: net0n3_344-23f3501c
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: عضو_شو__zibanabz-a52029bd
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: vless-68a148f4
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: net0n3_339-ad024f28
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: net0n3_238-0c707856
  type: vless
  server: all97-vip.f-sub.com
  port: 1517
  uuid: 240052ac-0bf0-481f-adb4-f40a259fc189
  udp: true
  tls: false
  network: tcp
- name: Marz_user2_vless_-_ws-a876ac6e
  type: vless
  server: 109.120.179.185
  port: 80
  uuid: a6d7f6b2-6192-a447-220f-7555732c913f
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/
    headers:
      Host: null
- name: Telegram203A20FarshidHUB20DAAFD8B1D988D98720D985D98620D8B4D985D8A720D8B1D8A720D985D8AAD8B5D98420D986DAAFD987E2808C20D985DB8CD8AFD8A7D8B1D985-c16f378c
  type: vless
  server: 141.101.121.55
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: By_EbraSha_ss-KZ-3b3a8d71
  type: ss
  server: ct.uigame.space
  port: 2024
  cipher: chacha20-ietf-poly1305
  password: 33LpoU8X/xHnCD+cbNe+7p0pK/JngDLM+5+RILrxyfVFRW/niKz5Eu0rWyVcDho=
  udp: true
- name: eli-289eaae1
  type: vless
  server: turboo-server-bot.aftabz.com
  port: 8080
  uuid: 92c79723-eb54-4c48-bb81-83423a0e6440
  udp: true
  tls: false
  network: grpc
  servername: tgju.org
  reality-opts:
    public-key: zLBoalJcQIgIUcegIx0_cCEBvAMJxIbotJA6y50CVHg
    short-id: 3bf4f5
- name: AZADNET-1634bcd3
  type: ss
  server: azad.net.vpn.digipedia.shop
  port: 48172
  cipher: chacha20-ietf-poly1305
  password: 51yloQC8D9w1Wae7FHtI65
  udp: true
- name: net0n3_359-286393f3
  type: vless
  server: 89.221.203.100
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: عضو_شو__prroxyng-3b831efc
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: VConfing-140262aa
  type: vmess
  server: nhel1-tu.mobstore.store
  port: 2083
  uuid: a9b68e36-eb35-1bbc-b958-ecd0e46ba428
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: By_EbraSha_vless-US-897b036d
  type: vless
  server: 185.236.232.136
  port: 1001
  uuid: c7c922da-ab54-433c-8046-1f9bf9d95c23
  udp: true
  tls: false
  network: tcp
  servername: telewebion.com
  reality-opts:
    public-key: 8Gunn8hjWbit5yLtTPcvLph0u2ovHLsGoXX4IJS1EQ0
    short-id: 5fab0deb
- name: عضو_شو__zibanabz-6bd5d5f4
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: عضو_شو__zibanabz-94847ed0
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: All²-93ffd962
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: 259923b6-756d-4b33-9ea9-73e55378018a
  udp: true
  tls: false
  network: xhttp
- name: net0n3_346-6f0aea18
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: vless-07b9ca4f
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: net0n3_332-b4699540
  type: vless
  server: s3.esrtz.onl
  port: 46470
  uuid: 3bcc6dbf-0ab4-4674-85c8-39bd994434f9
  udp: true
  tls: false
  network: tcp
- name: هـلند__رایگان_v2angbot-63843a00
  type: vless
  server: iran.fast.hosting-ip.com
  port: 80
  uuid: 48a2c4cb-b4ce-427d-8860-a512b1f2b849
  udp: true
  tls: false
  network: xhttp
- name: vless-13086cc1
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: By_EbraSha_vless-DE-b9a24e17
  type: vless
  server: vpn_proxy_channel_vpn_proxy_channel.hohod.ir
  port: 443
  uuid: 33707040-edcf-4185-94e4-2a071315c602
  udp: true
  tls: false
  network: tcp
  servername: vpn_proxy_channel_vpn_proxy_channel.hohod.ir
  reality-opts:
    public-key: GpgfsA-U8Y8M3LRcTfsaBViDtp2VlN5riSLLZ2kxEiQ
    short-id: 7def4dde
- name: By_EbraSha_vless-GB-c9e3bd76
  type: vless
  server: 54.36.162.84
  port: 8880
  uuid: 9beca423-b31d-496d-aee6-a1ab64f0bd81
  udp: true
  tls: false
  network: tcp
  servername: google.com
  reality-opts:
    public-key: Fa_dYaQoLgLjsk1jvSQcEKRNnAvMVJF4Br7YG5FT6zo
    short-id: 1e4072
- name: net0n3_335-b00aade6
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: xhttp
- name: proxy_v2ray_meli-635853b3
  type: vmess
  server: 188.227.84.174
  port: 2096
  uuid: aae9a898-82c1-411c-9d92-b88677f3b664
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: net0n3_348-db06caf7
  type: ss
  server: 45.87.175.183
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
- name: net0n3_358-2f961e87
  type: vless
  server: 83.217.9.233
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: net0n3_347-c5be8397
  type: ss
  server: 193.228.139.250
  port: 1080
  cipher: chacha20-ietf-poly1305
  password: yrZtUElGhL8xfeaN0hIIzQ
  udp: true
- name: vless-207ba19c
  type: vless
  server: 93.123.39.31
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: عضو_شو__zibanabz-76927dc3
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: vless-bf8fb60f
  type: vless
  server: russiatest-tap.servers807.ir
  port: 13796
  uuid: b646e0d6-137b-49e1-90bc-3b9ad8a6484a
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: AIUUKeq08usIla0uv-NTp5wVe4TMb3VkXWDLoutlFnM
    short-id: a3ac
- name: vless-a8af3578
  type: vless
  server: a.ru.maviks.ru
  port: 443
  uuid: c3afb549-2c79-4787-9d67-ccd1581fb70f
  udp: true
  tls: false
  network: tcp
  servername: maviks.ru
  reality-opts:
    public-key: cGzNRbN_zruI3CVTDukB2nOqWWEj7kgkay24f2fdLmQ
    short-id: 0f917152a871e9c0
- name: عضو_شو__zibanabz-3cd4ce9f
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: عضو_شو__zibanabz-a5b6b062
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: 'کانفینگ_جدید_خواستی_بیا_کانال_

    ROFLVPN-227978c8'
  type: vless
  server: ca.panelmarzban.com
  port: 3041
  uuid: bb33bbef-ae43-4937-b636-e9ba3edcad73
  udp: true
  tls: false
  network: tcp
  servername: refersion.com
  reality-opts:
    public-key: 21V_VkMUD2XRbyRDg7hjpblUAwxHvlLmbarATdhhJQI
    short-id: null
- name: vless-ab33f870
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: vless-38809455
  type: vless
  server: 83.217.9.233
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: net0n3_356-c9ba6f4f
  type: vless
  server: 93.123.39.31
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: عضو_شو__zibanabz-443cc1c7
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: net0n3_354-702de5a3
  type: vless
  server: david2.lemoex.blog
  port: 443
  uuid: 737c9e58-379d-4654-9471-d60494b326bd
  udp: true
  tls: true
  network: httpupgrade
  servername: david2.lemoex.blog
- name: configfree_1-77558611
  type: vless
  server: all.yasharteam.com
  port: 666
  uuid: f8e7410f-5984-4973-a02b-fde30761ba53
  udp: true
  tls: false
  network: tcp
- name: net0n3_336-82254c15
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: V2rayNGFreeeV2rayNGFreee
  udp: true
  tls: false
  network: xhttp
- name: عضو_شو__zibanabz-ad491622
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vmess-7d25cf4b
  type: vmess
  server: 62.60.246.86
  port: 16634
  uuid: 5026a4cf-27f5-4a37-b682-d2c1a4d11a4c
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-38c8d819
  type: vless
  server: 89.221.203.100
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - All¹-b77a2b35
  - vless-82082dde
  - net0n3_352-b80892cc
  - Channelalammzar-7b73b8a3
  - By_EbraSha_vless-KR-144fe8f5
  - VConfing-0ccf5e14
  - vless-e00801d0
  - net0n3_344-23f3501c
  - عضو_شو__zibanabz-a52029bd
  - vless-68a148f4
  - net0n3_339-ad024f28
  - net0n3_238-0c707856
  - Marz_user2_vless_-_ws-a876ac6e
  - Telegram203A20FarshidHUB20DAAFD8B1D988D98720D985D98620D8B4D985D8A720D8B1D8A720D985D8AAD8B5D98420D986DAAFD987E2808C20D985DB8CD8AFD8A7D8B1D985-c16f378c
  - By_EbraSha_ss-KZ-3b3a8d71
  - eli-289eaae1
  - AZADNET-1634bcd3
  - net0n3_359-286393f3
  - عضو_شو__prroxyng-3b831efc
  - VConfing-140262aa
  - By_EbraSha_vless-US-897b036d
  - عضو_شو__zibanabz-6bd5d5f4
  - عضو_شو__zibanabz-94847ed0
  - All²-93ffd962
  - net0n3_346-6f0aea18
  - vless-07b9ca4f
  - net0n3_332-b4699540
  - هـلند__رایگان_v2angbot-63843a00
  - vless-13086cc1
  - By_EbraSha_vless-DE-b9a24e17
  - By_EbraSha_vless-GB-c9e3bd76
  - net0n3_335-b00aade6
  - proxy_v2ray_meli-635853b3
  - net0n3_348-db06caf7
  - net0n3_358-2f961e87
  - net0n3_347-c5be8397
  - vless-207ba19c
  - عضو_شو__zibanabz-76927dc3
  - vless-bf8fb60f
  - vless-a8af3578
  - عضو_شو__zibanabz-3cd4ce9f
  - عضو_شو__zibanabz-a5b6b062
  - 'کانفینگ_جدید_خواستی_بیا_کانال_

    ROFLVPN-227978c8'
  - vless-ab33f870
  - vless-38809455
  - net0n3_356-c9ba6f4f
  - عضو_شو__zibanabz-443cc1c7
  - net0n3_354-702de5a3
  - configfree_1-77558611
  - net0n3_336-82254c15
  - عضو_شو__zibanabz-ad491622
  - vmess-7d25cf4b
  - vless-38c8d819
- name: AUTO
  type: url-test
  proxies:
  - All¹-b77a2b35
  - vless-82082dde
  - net0n3_352-b80892cc
  - Channelalammzar-7b73b8a3
  - By_EbraSha_vless-KR-144fe8f5
  - VConfing-0ccf5e14
  - vless-e00801d0
  - net0n3_344-23f3501c
  - عضو_شو__zibanabz-a52029bd
  - vless-68a148f4
  - net0n3_339-ad024f28
  - net0n3_238-0c707856
  - Marz_user2_vless_-_ws-a876ac6e
  - Telegram203A20FarshidHUB20DAAFD8B1D988D98720D985D98620D8B4D985D8A720D8B1D8A720D985D8AAD8B5D98420D986DAAFD987E2808C20D985DB8CD8AFD8A7D8B1D985-c16f378c
  - By_EbraSha_ss-KZ-3b3a8d71
  - eli-289eaae1
  - AZADNET-1634bcd3
  - net0n3_359-286393f3
  - عضو_شو__prroxyng-3b831efc
  - VConfing-140262aa
  - By_EbraSha_vless-US-897b036d
  - عضو_شو__zibanabz-6bd5d5f4
  - عضو_شو__zibanabz-94847ed0
  - All²-93ffd962
  - net0n3_346-6f0aea18
  - vless-07b9ca4f
  - net0n3_332-b4699540
  - هـلند__رایگان_v2angbot-63843a00
  - vless-13086cc1
  - By_EbraSha_vless-DE-b9a24e17
  - By_EbraSha_vless-GB-c9e3bd76
  - net0n3_335-b00aade6
  - proxy_v2ray_meli-635853b3
  - net0n3_348-db06caf7
  - net0n3_358-2f961e87
  - net0n3_347-c5be8397
  - vless-207ba19c
  - عضو_شو__zibanabz-76927dc3
  - vless-bf8fb60f
  - vless-a8af3578
  - عضو_شو__zibanabz-3cd4ce9f
  - عضو_شو__zibanabz-a5b6b062
  - 'کانفینگ_جدید_خواستی_بیا_کانال_

    ROFLVPN-227978c8'
  - vless-ab33f870
  - vless-38809455
  - net0n3_356-c9ba6f4f
  - عضو_شو__zibanabz-443cc1c7
  - net0n3_354-702de5a3
  - configfree_1-77558611
  - net0n3_336-82254c15
  - عضو_شو__zibanabz-ad491622
  - vmess-7d25cf4b
  - vless-38c8d819
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
