port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: vless-ad95f6a9
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: 10_دقیقه_دیگه_سرور_میبندم_اصلیش_میزارم_چنل_کانفینگ_proxygodratmand-df4f7034
  type: vmess
  server: channel.dollardoon.com
  port: 15709
  uuid: 4ac39e8a-6d5c-48bb-b0d0-f633c829113e
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-25e81632
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: Sezar_Sec-e39a2a15
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  tls: false
  network: tcp
- name: vless-5da1fe46
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-894067de
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
- name: قطع_شد_بیا_اینجا_بردار_V2GaMa-8529ba7e
  type: vless
  server: v2shop29.bing-net.com
  port: 4929
  uuid: 500886d4-57e9-4f7e-ae7b-b8ead55075a3
  udp: true
  tls: false
  network: tcp
- name: vless-3e2c78e8
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-fe8f1e06
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: مشتی_جوین_بده_ناموصا__xzjinx-53b30602
  type: vless
  server: 94.182.136.184
  port: 7878
  uuid: f2c134ea-e14d-43af-ea22-916d27ce14a9
  udp: true
  tls: false
  network: tcp
- name: vless-23d89627
  type: vless
  server: 0ger.amazon-osishop.ir
  port: 8880
  uuid: 2066c2f3-bde1-429f-b083-fcfc7aee14b5
  udp: true
  tls: false
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-ce420918
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: 09694965-369f-48b5-82fa-40aae0236746
  udp: true
  tls: false
  network: tcp
- name: vless-4e357c79
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: zula.ir
    headers:
      Host: azadnet-7py.pages.dev
- name: Sezar_Sec-f58bada6
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: net0n3_287-796b95ac
  type: vless
  server: compose.fast.hosting-ip.com
  port: 80
  uuid: ab80613b-e04b-4af5-bad9-9ca5c448266e
  udp: true
  tls: false
  network: xhttp
- name: Sezar_sec-ee6b1459
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  tls: false
  network: tcp
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: مشتی_جوین_بده_ناموصا__xzjinx-e84bd50d
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 2f6b3367-a0cc-4b06-c4d5-35b42ea24da0
  udp: true
  tls: false
  network: tcp
- name: vless-e58ec901
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 546cc913-2825-4771-b713-a23905913141
  udp: true
  tls: true
  network: ws
  servername: 638874931195949050.kish-prx-dnraaaf.info
  ws-opts:
    path: /wjwqzaws
    headers:
      Host: 638874931195949050.kish-prx-dnraaaf.info
- name: vless-9131b925
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: qeshmserver
  udp: true
  tls: false
  network: xhttp
- name: net0n3_296-d89e7c9d
  type: vless
  server: de6.razercompany.com
  port: 33200
  uuid: c4389c70-1e5a-4bd2-934f-44fb2e62ccf5
  udp: true
  tls: false
  network: tcp
- name: net0n3_298-2ba8adc6
  type: vless
  server: fastlyeeeeee.fast.hosting-ip.com
  port: 80
  uuid: cdnfastlycash
  udp: true
  tls: false
  network: xhttp
- name: vless-f204d900
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-bb6139cb
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: vless-4fc9aaa4
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
- name: vless-a1dfb21c
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: مشتی_جوین_بده_ناموصا__xzjinx-91834b13
  type: vless
  server: 94.182.136.184
  port: 1212
  uuid: bcebeb42-74fb-4c13-9067-c0c7fcb82707
  udp: true
  tls: false
  network: tcp
- name: vless-68bdf958
  type: vless
  server: gb01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: e499f276e7bd6420
- name: vless-280bd0fa
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  tls: false
  network: tcp
- name: Sezar_Sec-253ab216
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: مشتی_جوین_بده_ناموصا__xzjinx-74f5bd71
  type: vless
  server: 94.182.136.184
  port: 1217
  uuid: c50a0271-6cd4-4ef4-a2d2-f03e7e8a1537
  udp: true
  tls: false
  network: tcp
- name: net0n3_283-cbd067c5
  type: ss
  server: 45.87.175.165
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: QCXDxuDlTTMD7jtgHUjIoj
  udp: true
- name: مشتی_جوین_بده_ناموصا__xzjinx-91d796d6
  type: vmess
  server: 175.208.112.99
  port: 16374
  uuid: 4b590b1e-2d3d-4a40-b075-cf1e93a576af
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  udp: true
- name: vless-b3275fa4
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: Sezar_Sec-fb995a53
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: net0n3_300-ff509d70
  type: vless
  server: vpconnect.ahadbala.ir
  port: 80
  uuid: 3f0c3cef-75c0-4253-a62e-d89f5a45dcc1
  udp: true
  tls: false
  network: tcp
- name: net0n3_285-de82200b
  type: vless
  server: bam.erfann.shop
  port: 15807
  uuid: 8e4d0dba-884f-4bbd-9f1d-ea5ec78efe7d
  udp: true
  tls: false
  network: tcp
- name: vless-9af55308
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_282-ee628dbd
  type: vless
  server: hell.dl101movis.ir
  port: 80
  uuid: d601250a-e54f-46fe-a984-fb0f1d6d48ce
  udp: true
  tls: false
  network: xhttp
- name: vless-81d3323b
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-3e9e46d7
  type: vless
  server: nl01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: d3b13f31
- name: مشتی_جوین_بده_ناموصا__xzjinx-92e23787
  type: ss
  server: 4.223.106.151
  port: 48172
  cipher: chacha20-ietf-poly1305
  password: 51yloQC8D9w1Wae7FHtI65
  udp: true
- name: net0n3_294-6291e426
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_297-0796547f
  type: vless
  server: real-all3.sdcards.ir
  port: 8501
  uuid: 9666ee62-d1f3-4f6e-8881-c17fee524e31
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: OJ0wA5wp55uZdD16dutlTZvx1x-rbMMXmiO9D_MMCHI
    short-id: e701a013553059ba
- name: net0n3_295-558fa091
  type: vless
  server: de1.cowjuice.me
  port: 443
  uuid: 955827fc-c729-4a1e-ba6c-d85754c8e937
  udp: true
  tls: false
  network: tcp
  servername: thelocal.de
  reality-opts:
    public-key: O9DMPpwicRcMofaplcvpQStNRogPS_HJY0s5_4EaKQc
    short-id: aabbccdd
- name: net0n3_290-6805b35f
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sub.divib.dynv6.net
- name: 100G-Hexagon-connectix-8bdc0c9d
  type: vless
  server: vnodepro.vgyop.com
  port: 80
  uuid: fe1b055b-0881-4a65-a996-b8c758966137
  udp: true
  tls: false
  network: xhttp
- name: vless-aa65ed87
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: Sezar_Sec-b3239ed8
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-98d856b6
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 6bcb4f37-bba7-4ae0-afac-d43195c72c12
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: zula.ir?ed=2560
    headers:
      Host: my.digikala.dynv6.net
- name: net0n3_281-4677c430
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: net0n3_321-675ae660
  type: ss
  server: 172.187.105.25
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: vless-a849d1c1
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 6bcb4f37-bba7-4ae0-afac-d43195c72c12
  udp: true
  tls: true
  network: ws
  servername: my.digikala.dynv6.net
  ws-opts:
    path: zula.ir
    headers:
      Host: my.digikala.dynv6.net
- name: Sezar_sec-94c9459f
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
- name: مشتی_جوین_بده_ناموصا__xzjinx-33ea35c4
  type: vmess
  server: 64.176.208.71
  port: 443
  uuid: 7dbb7311-8ee4-4fd3-95bb-1010cbd84c5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  udp: true
  ws-opts:
    path: /64b9614b
    headers:
      Host: ''
- name: Sezar_sec-c927d7e2
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: net0n3_289-c6b0dfab
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: vless-df19915b
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: مشتیجوینبدهناموصاxzjinx-938ed9e8
  type: vless
  server: 106.180.225.73
  port: 32606
  uuid: e510ef59-8e87-4b7a-bd9e-bf2277aa01e2
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: H-nBYFMFdZInbzrieFTqt6Gsf8EhE2VT1qV855VQNg8
    short-id: 984ba8d9
- name: مشتی_جوین_بده_ناموصا__xzjinx-f20848a1
  type: vmess
  server: 220.87.205.139
  port: 57115
  uuid: 815be33a-3999-48c0-eee7-13ef7c73369a
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - vless-ad95f6a9
  - 10_دقیقه_دیگه_سرور_میبندم_اصلیش_میزارم_چنل_کانفینگ_proxygodratmand-df4f7034
  - vless-25e81632
  - Sezar_Sec-e39a2a15
  - vless-5da1fe46
  - vless-894067de
  - قطع_شد_بیا_اینجا_بردار_V2GaMa-8529ba7e
  - vless-3e2c78e8
  - vless-fe8f1e06
  - مشتی_جوین_بده_ناموصا__xzjinx-53b30602
  - vless-23d89627
  - مشتی_جوین_بده_ناموصا__xzjinx-ce420918
  - vless-4e357c79
  - Sezar_Sec-f58bada6
  - net0n3_287-796b95ac
  - Sezar_sec-ee6b1459
  - مشتی_جوین_بده_ناموصا__xzjinx-e84bd50d
  - vless-e58ec901
  - vless-9131b925
  - net0n3_296-d89e7c9d
  - net0n3_298-2ba8adc6
  - vless-f204d900
  - vless-bb6139cb
  - vless-4fc9aaa4
  - vless-a1dfb21c
  - مشتی_جوین_بده_ناموصا__xzjinx-91834b13
  - vless-68bdf958
  - vless-280bd0fa
  - Sezar_Sec-253ab216
  - مشتی_جوین_بده_ناموصا__xzjinx-74f5bd71
  - net0n3_283-cbd067c5
  - مشتی_جوین_بده_ناموصا__xzjinx-91d796d6
  - vless-b3275fa4
  - Sezar_Sec-fb995a53
  - net0n3_300-ff509d70
  - net0n3_285-de82200b
  - vless-9af55308
  - net0n3_282-ee628dbd
  - vless-81d3323b
  - vless-3e9e46d7
  - مشتی_جوین_بده_ناموصا__xzjinx-92e23787
  - net0n3_294-6291e426
  - net0n3_297-0796547f
  - net0n3_295-558fa091
  - net0n3_290-6805b35f
  - 100G-Hexagon-connectix-8bdc0c9d
  - vless-aa65ed87
  - Sezar_Sec-b3239ed8
  - vless-98d856b6
  - net0n3_281-4677c430
  - net0n3_321-675ae660
  - vless-a849d1c1
  - Sezar_sec-94c9459f
  - مشتی_جوین_بده_ناموصا__xzjinx-33ea35c4
  - Sezar_sec-c927d7e2
  - net0n3_289-c6b0dfab
  - vless-df19915b
  - مشتیجوینبدهناموصاxzjinx-938ed9e8
  - مشتی_جوین_بده_ناموصا__xzjinx-f20848a1
- name: AUTO
  type: url-test
  proxies:
  - vless-ad95f6a9
  - 10_دقیقه_دیگه_سرور_میبندم_اصلیش_میزارم_چنل_کانفینگ_proxygodratmand-df4f7034
  - vless-25e81632
  - Sezar_Sec-e39a2a15
  - vless-5da1fe46
  - vless-894067de
  - قطع_شد_بیا_اینجا_بردار_V2GaMa-8529ba7e
  - vless-3e2c78e8
  - vless-fe8f1e06
  - مشتی_جوین_بده_ناموصا__xzjinx-53b30602
  - vless-23d89627
  - مشتی_جوین_بده_ناموصا__xzjinx-ce420918
  - vless-4e357c79
  - Sezar_Sec-f58bada6
  - net0n3_287-796b95ac
  - Sezar_sec-ee6b1459
  - مشتی_جوین_بده_ناموصا__xzjinx-e84bd50d
  - vless-e58ec901
  - vless-9131b925
  - net0n3_296-d89e7c9d
  - net0n3_298-2ba8adc6
  - vless-f204d900
  - vless-bb6139cb
  - vless-4fc9aaa4
  - vless-a1dfb21c
  - مشتی_جوین_بده_ناموصا__xzjinx-91834b13
  - vless-68bdf958
  - vless-280bd0fa
  - Sezar_Sec-253ab216
  - مشتی_جوین_بده_ناموصا__xzjinx-74f5bd71
  - net0n3_283-cbd067c5
  - مشتی_جوین_بده_ناموصا__xzjinx-91d796d6
  - vless-b3275fa4
  - Sezar_Sec-fb995a53
  - net0n3_300-ff509d70
  - net0n3_285-de82200b
  - vless-9af55308
  - net0n3_282-ee628dbd
  - vless-81d3323b
  - vless-3e9e46d7
  - مشتی_جوین_بده_ناموصا__xzjinx-92e23787
  - net0n3_294-6291e426
  - net0n3_297-0796547f
  - net0n3_295-558fa091
  - net0n3_290-6805b35f
  - 100G-Hexagon-connectix-8bdc0c9d
  - vless-aa65ed87
  - Sezar_Sec-b3239ed8
  - vless-98d856b6
  - net0n3_281-4677c430
  - net0n3_321-675ae660
  - vless-a849d1c1
  - Sezar_sec-94c9459f
  - مشتی_جوین_بده_ناموصا__xzjinx-33ea35c4
  - Sezar_sec-c927d7e2
  - net0n3_289-c6b0dfab
  - vless-df19915b
  - مشتیجوینبدهناموصاxzjinx-938ed9e8
  - مشتی_جوین_بده_ناموصا__xzjinx-f20848a1
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
