mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-8cb29263
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-9de977a9
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-1f809280
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-0f71eec8
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-0e39c545
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-1bbf34f2
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-77a661a3
  type: vless
  server: accounting.vinamarketcenter.ir
  port: 443
  uuid: 5cfba4ac-105a-452a-ac10-88b1adf784ee
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: T7Cwk-B3EvZqqRywIgN_TNotJiUOXYUI9bHqYKPnTi0
    short-id: 105e89ba3d2a1c3b
- name: SRCVPN-8ce7421d
  type: vless
  server: 150.241.65.211
  port: 443
  uuid: be5fab84-5edb-4800-927e-243f6e4309bf
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: LYJ37EcS5jyaezTVaVAVCkBWCrjXioiJHI7argkEnCU
    short-id: 236ac31d02
- name: SRCVPN-3339aebd
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: a812a015-a65b-4003-ac5f-266e141c6405
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: Www.speedtest.net.developsp.ir.vegaskala.com.
- name: httpstmeKANFIG_Poroksi__لینک_چنلمون-cbe887f4
  type: vless
  server: srv5.raykaservers.com
  port: 10215
  uuid: 6bb8cb48-c5d7-4016-b671-4367a56e299a
  udp: true
  network: ws
  ws-opts:
    path: /
- name: V2RAYROZ-829caaf2
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: 350_Telegram_jdboy9oli-f3f5cda4
  type: vless
  server: mtn.venzo.com.tr
  port: 2095
  uuid: 92f2eeeb-b4b7-491e-ad91-a4a9ec0afcf8
  udp: true
  network: httpupgrade
- name: jcod234-38-21836345
  type: vmess
  server: pnl.shod-jjcod.com
  port: 443
  uuid: 596b01fe-7832-44b8-9163-2a92259154ba
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: jcod234-38-cbe0a322
  type: vmess
  server: pnl.shod-jjcod.com
  port: 443
  uuid: 596b01fe-7832-44b8-9163-2a92259154ba
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: jcod234-39-089c82d5
  type: vmess
  server: pnl.shod-jjcod.com
  port: 443
  uuid: eadd18e8-8d53-43d3-966b-9bcebd0e116e
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: jcod234-39-802f0d54
  type: vmess
  server: pnl.shod-jjcod.com
  port: 443
  uuid: eadd18e8-8d53-43d3-966b-9bcebd0e116e
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: Spotify_Porteghali_1818-3a4d0f5f
  type: vless
  server: 104.16.53.11
  port: 2053
  uuid: 68fd2dc5-b1fc-49b0-8ff6-d070133ee270
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: ah15.ai351.com
  ws-opts:
    path: /containers/de
    headers:
      Host: ah15.ai351.com
- name: vless-bd471329
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /zula.ir
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: vless-f54afdbf
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-bb210e7d
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-69313228
  type: vless
  server: 91.99.184.231
  port: 45103
  uuid: 6bdc18b7-a33f-46ae-a5e3-df7cb21f36b2
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: vless-68506ab9
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: turboo-server
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: turboo-server1.game
- name: vless-8e1b8044
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: 941d092e-8313-452a-ba21-c9995dcba79d
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: havvas.shohreh.dpdns.org
  ws-opts:
    path: /zula.ir/
    headers:
      Host: havvas.shohreh.dpdns.org
- name: vless-caab0169
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /zula.ir/
    headers:
      Host: sub.divib.dynv6.net
- name: vless-ec384ee3
  type: vless
  server: 91.107.154.77
  port: 2070
  uuid: 1c88c964-a039-4c9a-b1e5-5e93eef57fd8
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-d586e249
  type: vless
  server: 5.160.197.120
  port: 16644
  uuid: c2d3a355-e556-40e0-cd5a-41dff6eb525d
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-703eb6f9
  type: vless
  server: 91.107.144.102
  port: 443
  uuid: edf3ab50-46b4-4046-eaf9-db12fe598cd1
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-3bb1fa28
  type: vless
  server: chrom3.infospeedtest.com
  port: 13096
  uuid: bb497033-e322-4316-ce08-b8a9716b6a3d
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-d06aa26f
  type: vless
  server: esi.infospeedtest.com
  port: 13286
  uuid: 2ee55469-d026-410b-f4bc-844a63a1342d
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-e281e5e4
  type: vless
  server: chrom3.infospeedtest.com
  port: 13096
  uuid: b8b81afb-c24b-43b7-e816-0b7dcaf4ce67
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-04b6f810
  type: vless
  server: 91.107.144.102
  port: 443
  uuid: 75542618-2a4e-4e94-cd5d-f2866e284901
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-a13bd135
  type: vless
  server: 5.160.197.120
  port: 13048
  uuid: de0de0a3-501a-4d4b-b3e0-97324aefcc13
  udp: true
  network: tcp
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-8cb29263
  - vless-9de977a9
  - vless-1f809280
  - vless-0f71eec8
  - vless-0e39c545
  - vless-1bbf34f2
  - vless-77a661a3
  - SRCVPN-8ce7421d
  - SRCVPN-3339aebd
  - httpstmeKANFIG_Poroksi__لینک_چنلمون-cbe887f4
  - V2RAYROZ-829caaf2
  - 350_Telegram_jdboy9oli-f3f5cda4
  - jcod234-38-21836345
  - jcod234-38-cbe0a322
  - jcod234-39-089c82d5
  - jcod234-39-802f0d54
  - Spotify_Porteghali_1818-3a4d0f5f
  - vless-bd471329
  - vless-f54afdbf
  - vless-bb210e7d
  - vless-69313228
  - vless-68506ab9
  - vless-8e1b8044
  - vless-caab0169
  - vless-ec384ee3
  - مشتیجوینبدهناموصاxzjinx-d586e249
  - مشتیجوینبدهناموصاxzjinx-703eb6f9
  - مشتیجوینبدهناموصاxzjinx-3bb1fa28
  - مشتی_جوین_بده_ناموصا__xzjinx-d06aa26f
  - مشتی_جوین_بده_ناموصا__xzjinx-e281e5e4
  - مشتی_جوین_بده_ناموصا__xzjinx-04b6f810
  - مشتی_جوین_بده_ناموصا__xzjinx-a13bd135
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
