port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: VConfing-e42a5a53
  type: vmess
  server: 81.12.33.180
  port: 8595
  uuid: 4e6e51d7-1234-4543-999f-0f54a428b77f
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: By_EbraSha_vless-GB-9e2b42d7
  type: vless
  server: 54.36.162.84
  port: 8880
  uuid: 9beca423-b31d-496d-aee6-a1ab64f0bd81
  udp: true
  tls: false
  network: tcp
  servername: google.com
  reality-opts:
    public-key: Fa_dYaQoLgLjsk1jvSQcEKRNnAvMVJF4Br7YG5FT6zo
    short-id: 1e4072
- name: net0n3_358-87874257
  type: vless
  server: 83.217.9.233
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: vless-f7fbeb6c
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: vless-291eca9f
  type: vless
  server: a.ru.maviks.ru
  port: 443
  uuid: c3afb549-2c79-4787-9d67-ccd1581fb70f
  udp: true
  tls: false
  network: tcp
  servername: maviks.ru
  reality-opts:
    public-key: cGzNRbN_zruI3CVTDukB2nOqWWEj7kgkay24f2fdLmQ
    short-id: 0f917152a871e9c0
- name: MCONFIGVPN-554b0527
  type: vless
  server: 62.60.163.77
  port: 3333
  uuid: 7d283c1a-3a5b-4b2a-a924-0bd256e89726
  udp: true
  tls: false
  network: tcp
- name: AZADNET-4c8ddc93
  type: ss
  server: azad.net.vpn.digipedia.shop
  port: 48172
  cipher: chacha20-ietf-poly1305
  password: 51yloQC8D9w1Wae7FHtI65
  udp: true
- name: net0n3_352-1bfe1e8e
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: net0n3_336-24f5e998
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: V2rayNGFreeeV2rayNGFreee
  udp: true
  tls: false
  network: xhttp
- name: tmeiProxy_Channel_4-a977ca66
  type: vless
  server: 141.101.121.55
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=#TELEGRAM---MARAMBASHI---TELEGRAM---MARAMBASHI---TELEGRAM---MARAMBASHI---TELEGRAM---MARAMBASHI?ed=2560
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: عضو_شو__zibanabz-ca71a261
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: By_EbraSha_ss-KZ-6872ded2
  type: ss
  server: ct.uigame.space
  port: 2024
  cipher: chacha20-ietf-poly1305
  password: 33LpoU8X/xHnCD+cbNe+7p0pK/JngDLM+5+RILrxyfVFRW/niKz5Eu0rWyVcDho=
  udp: true
- name: vless-6a2d0d65
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: net0n3_354-7b1934af
  type: vless
  server: david2.lemoex.blog
  port: 443
  uuid: 737c9e58-379d-4654-9471-d60494b326bd
  udp: true
  tls: true
  network: httpupgrade
  servername: david2.lemoex.blog
- name: هـلند__رایگان_v2angbot-41472132
  type: vless
  server: iran.fast.hosting-ip.com
  port: 80
  uuid: 48a2c4cb-b4ce-427d-8860-a512b1f2b849
  udp: true
  tls: false
  network: xhttp
- name: net0n3_335-6e7385fd
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: xhttp
- name: عضو_شو__zibanabz-75725531
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: net0n3_359-55327c5a
  type: vless
  server: 89.221.203.100
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: vless-701ac16f
  type: vless
  server: 89.221.203.100
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: By_EbraSha_vless-KR-7ebeeb5b
  type: vless
  server: 8.213.149.42
  port: 443
  uuid: 5c183802-747d-4d2f-a6f1-aff2d5d78401
  udp: true
  tls: false
  network: tcp
  servername: wwwimages2.adobe.com
  reality-opts:
    public-key: DNdTBHyztOVJOBJQX91YXEhNkWbSAntqUoTFBHc6Clw
    short-id: 6ba85179e30d4fc2
- name: عضو_شو__zibanabz-76d91118
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: VConfing-a7121f72
  type: vmess
  server: nhel1-tu.mobstore.store
  port: 2083
  uuid: a9b68e36-eb35-1bbc-b958-ecd0e46ba428
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: عضو_شو__prroxyng-0912a7b9
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: عضو_شو__zibanabz-6458bd80
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: vless-bc302335
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 8443
  uuid: 96a1b724-68d2-4f4d-ab25-38ecd83577bc
  udp: true
  tls: true
  network: ws
  servername: IyFpLkXk10.jOoLaJoOlA.OrG
  ws-opts:
    path: /
    headers:
      Host: IyFpLkXk10.jOoLaJoOlA.OrG
- name: vless-45b573c8
  type: vless
  server: 83.217.9.233
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: عضو_شو__zibanabz-7a6fc54c
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: By_EbraSha_vless-DE-65526607
  type: vless
  server: vpn_proxy_channel_vpn_proxy_channel.hohod.ir
  port: 443
  uuid: 33707040-edcf-4185-94e4-2a071315c602
  udp: true
  tls: false
  network: tcp
  servername: vpn_proxy_channel_vpn_proxy_channel.hohod.ir
  reality-opts:
    public-key: GpgfsA-U8Y8M3LRcTfsaBViDtp2VlN5riSLLZ2kxEiQ
    short-id: 7def4dde
- name: vmess-5f9145e1
  type: vmess
  server: 62.60.246.86
  port: 16634
  uuid: 5026a4cf-27f5-4a37-b682-d2c1a4d11a4c
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-0e17db7b
  type: vless
  server: david2.lemoex.blog
  port: 443
  uuid: 737c9e58-379d-4654-9471-d60494b326bd
  udp: true
  tls: true
  network: httpupgrade
  servername: david2.lemoex.blog
- name: By_EbraSha_vless-US-c461c264
  type: vless
  server: 185.236.232.136
  port: 1001
  uuid: c7c922da-ab54-433c-8046-1f9bf9d95c23
  udp: true
  tls: false
  network: tcp
  servername: telewebion.com
  reality-opts:
    public-key: 8Gunn8hjWbit5yLtTPcvLph0u2ovHLsGoXX4IJS1EQ0
    short-id: 5fab0deb
- name: net0n3_339-d4b50442
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: net0n3_344-f3bcc2af
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: net0n3_347-0099a2dd
  type: ss
  server: 193.228.139.250
  port: 1080
  cipher: chacha20-ietf-poly1305
  password: yrZtUElGhL8xfeaN0hIIzQ
  udp: true
- name: vless-aafc38e0
  type: vless
  server: russiatest-tap.servers807.ir
  port: 13796
  uuid: b646e0d6-137b-49e1-90bc-3b9ad8a6484a
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: AIUUKeq08usIla0uv-NTp5wVe4TMb3VkXWDLoutlFnM
    short-id: a3ac
- name: net0n3_356-2048e31f
  type: vless
  server: 93.123.39.31
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: eli-b6e2fe51
  type: vless
  server: turboo-server-bot.aftabz.com
  port: 8080
  uuid: 92c79723-eb54-4c48-bb81-83423a0e6440
  udp: true
  tls: false
  network: grpc
  servername: tgju.org
  reality-opts:
    public-key: zLBoalJcQIgIUcegIx0_cCEBvAMJxIbotJA6y50CVHg
    short-id: 3bf4f5
- name: عضو_شو__zibanabz-e9e45608
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: net0n3_332-826ea0a4
  type: vless
  server: s3.esrtz.onl
  port: 46470
  uuid: 3bcc6dbf-0ab4-4674-85c8-39bd994434f9
  udp: true
  tls: false
  network: tcp
- name: net0n3_346-954bbce4
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: net0n3_238-3f5fadf0
  type: vless
  server: all97-vip.f-sub.com
  port: 1517
  uuid: 240052ac-0bf0-481f-adb4-f40a259fc189
  udp: true
  tls: false
  network: tcp
- name: V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-4c7b118f
  type: vless
  server: 62.60.163.77
  port: 3333
  uuid: 7d283c1a-3a5b-4b2a-a924-0bd256e89726
  udp: true
  tls: false
  network: tcp
- name: proxy_v2ray_meli-372d5c79
  type: vmess
  server: 188.227.84.174
  port: 2096
  uuid: aae9a898-82c1-411c-9d92-b88677f3b664
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: عضو_شو__zibanabz-b1c2a727
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: vless-87cc5472
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: vless-572294c7
  type: vless
  server: 93.123.39.31
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: عضو_شو__zibanabz-6fe3e91f
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: configfree_1-9eabd124
  type: vless
  server: all.yasharteam.com
  port: 666
  uuid: f8e7410f-5984-4973-a02b-fde30761ba53
  udp: true
  tls: false
  network: tcp
- name: net0n3_348-ae89d797
  type: ss
  server: 45.87.175.183
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
- name: Marz_user2_vless_-_ws-734391ab
  type: vless
  server: 109.120.179.185
  port: 80
  uuid: a6d7f6b2-6192-a447-220f-7555732c913f
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/
    headers:
      Host: null
- name: vless-8fb524ac
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - VConfing-e42a5a53
  - By_EbraSha_vless-GB-9e2b42d7
  - net0n3_358-87874257
  - vless-f7fbeb6c
  - vless-291eca9f
  - MCONFIGVPN-554b0527
  - AZADNET-4c8ddc93
  - net0n3_352-1bfe1e8e
  - net0n3_336-24f5e998
  - tmeiProxy_Channel_4-a977ca66
  - عضو_شو__zibanabz-ca71a261
  - By_EbraSha_ss-KZ-6872ded2
  - vless-6a2d0d65
  - net0n3_354-7b1934af
  - هـلند__رایگان_v2angbot-41472132
  - net0n3_335-6e7385fd
  - عضو_شو__zibanabz-75725531
  - net0n3_359-55327c5a
  - vless-701ac16f
  - By_EbraSha_vless-KR-7ebeeb5b
  - عضو_شو__zibanabz-76d91118
  - VConfing-a7121f72
  - عضو_شو__prroxyng-0912a7b9
  - عضو_شو__zibanabz-6458bd80
  - vless-bc302335
  - vless-45b573c8
  - عضو_شو__zibanabz-7a6fc54c
  - By_EbraSha_vless-DE-65526607
  - vmess-5f9145e1
  - vless-0e17db7b
  - By_EbraSha_vless-US-c461c264
  - net0n3_339-d4b50442
  - net0n3_344-f3bcc2af
  - net0n3_347-0099a2dd
  - vless-aafc38e0
  - net0n3_356-2048e31f
  - eli-b6e2fe51
  - عضو_شو__zibanabz-e9e45608
  - net0n3_332-826ea0a4
  - net0n3_346-954bbce4
  - net0n3_238-3f5fadf0
  - V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-4c7b118f
  - proxy_v2ray_meli-372d5c79
  - عضو_شو__zibanabz-b1c2a727
  - vless-87cc5472
  - vless-572294c7
  - عضو_شو__zibanabz-6fe3e91f
  - configfree_1-9eabd124
  - net0n3_348-ae89d797
  - Marz_user2_vless_-_ws-734391ab
  - vless-8fb524ac
- name: AUTO
  type: url-test
  proxies:
  - VConfing-e42a5a53
  - By_EbraSha_vless-GB-9e2b42d7
  - net0n3_358-87874257
  - vless-f7fbeb6c
  - vless-291eca9f
  - MCONFIGVPN-554b0527
  - AZADNET-4c8ddc93
  - net0n3_352-1bfe1e8e
  - net0n3_336-24f5e998
  - tmeiProxy_Channel_4-a977ca66
  - عضو_شو__zibanabz-ca71a261
  - By_EbraSha_ss-KZ-6872ded2
  - vless-6a2d0d65
  - net0n3_354-7b1934af
  - هـلند__رایگان_v2angbot-41472132
  - net0n3_335-6e7385fd
  - عضو_شو__zibanabz-75725531
  - net0n3_359-55327c5a
  - vless-701ac16f
  - By_EbraSha_vless-KR-7ebeeb5b
  - عضو_شو__zibanabz-76d91118
  - VConfing-a7121f72
  - عضو_شو__prroxyng-0912a7b9
  - عضو_شو__zibanabz-6458bd80
  - vless-bc302335
  - vless-45b573c8
  - عضو_شو__zibanabz-7a6fc54c
  - By_EbraSha_vless-DE-65526607
  - vmess-5f9145e1
  - vless-0e17db7b
  - By_EbraSha_vless-US-c461c264
  - net0n3_339-d4b50442
  - net0n3_344-f3bcc2af
  - net0n3_347-0099a2dd
  - vless-aafc38e0
  - net0n3_356-2048e31f
  - eli-b6e2fe51
  - عضو_شو__zibanabz-e9e45608
  - net0n3_332-826ea0a4
  - net0n3_346-954bbce4
  - net0n3_238-3f5fadf0
  - V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-4c7b118f
  - proxy_v2ray_meli-372d5c79
  - عضو_شو__zibanabz-b1c2a727
  - vless-87cc5472
  - vless-572294c7
  - عضو_شو__zibanabz-6fe3e91f
  - configfree_1-9eabd124
  - net0n3_348-ae89d797
  - Marz_user2_vless_-_ws-734391ab
  - vless-8fb524ac
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
