port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: vless-d4bc6179
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: net0n3_321-3ebf176c
  type: ss
  server: 172.187.105.25
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: 248MMad-H-56c7876c
  type: vless
  server: david2.lemoex.blog
  port: 443
  uuid: 737c9e58-379d-4654-9471-d60494b326bd
  udp: true
  tls: true
  network: httpupgrade
  servername: david2.lemoex.blog
- name: vless-64c889db
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: zula.ir
    headers:
      Host: azadnet-7py.pages.dev
- name: V2ray1_Ng-bc8c70a7
  type: vless
  server: 104.16.34.128
  port: 443
  uuid: 267613d7-f53f-4005-b642-d6f1f687b7cf
  udp: true
  tls: true
  network: ws
  servername: ensHOLP-91s.pageS.DEv
  ws-opts:
    path: /dQMN2VQLkaE52qWD?ed=2560
    headers:
      Host: ensHOLP-91s.pageS.DEv
- name: V2ray1_Ng-260a7a1e
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: xhttp
- name: هلند__۲-dcf97fe8
  type: ss
  server: 45.87.175.190
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-48619966
  type: vless
  server: 109.207.172.165
  port: 8443
  uuid: 0aec2ba3-6201-4605-83e9-3a4b1c88f04a
  udp: true
  tls: false
  network: tcp
- name: Sezar_sec-349b4721
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  tls: false
  network: tcp
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-6564fc64
  type: trojan
  server: www.digitalocean.com
  port: 443
  password: trojan
  udp: true
  sni: azadnet-9ya.pages.dev
- name: V2ray1_Ng-40c3396d
  type: ss
  server: 74.177.199.135
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: Sezar_sec-550ce1aa
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
- name: 248MMad-WS-7c8e1ddc
  type: vless
  server: david2.lemoex.blog
  port: 443
  uuid: 2953f047-4e41-478b-8f37-459de7b02120
  udp: true
  tls: true
  network: ws
  servername: david2.lemoex.blog
  ws-opts:
    path: /15674/wsmmad
    headers:
      Host: david2.lemoex.blog
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-860f08d1
  type: ss
  server: 74.177.199.135
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: vless-0085d498
  type: vless
  server: russiatest-tap.servers807.ir
  port: 13796
  uuid: b646e0d6-137b-49e1-90bc-3b9ad8a6484a
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: AIUUKeq08usIla0uv-NTp5wVe4TMb3VkXWDLoutlFnM
    short-id: a3ac
- name: vless-66ea8cbc
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: V2ray1_Ng-e0095cc7
  type: vless
  server: www.speedtest.net
  port: 2096
  uuid: c819261a-ad50-4ded-b164-1eafed9885c2
  udp: true
  tls: true
  network: ws
  servername: 638868951946670036.amsterdam-prx-dnraaal.info
  ws-opts:
    path: /mmdhmrws
    headers:
      Host: 638868951946670036.amsterdam-prx-dnraaal.info
- name: vless-3ae0d312
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: V2ray1_Ng-5e4482db
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /Telegram@V2ray_Alpha/?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: هلند-4cdf9cc4
  type: ss
  server: 109.201.152.181
  port: 443
  cipher: aes-128-cfb
  password: shadowsocks
  udp: true
- name: vless-aca1bd04
  type: vless
  server: nl01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: d3b13f31
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-d81e4153
  type: vless
  server: 62.60.176.30
  port: 48356
  uuid: 0658d669-cf10-469e-a932-6d2144d58d48
  udp: true
  tls: false
  network: tcp
- name: مولداوی-172cbe74
  type: ss
  server: 45.153.124.90
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
  udp: true
- name: vless-8f810a21
  type: vless
  server: gb01-vlr01.tcp-reset-club.net
  port: 443
  uuid: 39028f63-4adc-4a2c-9a57-9f583cd284e9
  udp: true
  tls: false
  network: tcp
  servername: hls-svod.itunes.apple.com
  reality-opts:
    public-key: mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg
    short-id: e499f276e7bd6420
- name: vless-cab7ad93
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 6bcb4f37-bba7-4ae0-afac-d43195c72c12
  udp: true
  tls: true
  network: ws
  servername: my.digikala.dynv6.net
  ws-opts:
    path: zula.ir
    headers:
      Host: my.digikala.dynv6.net
- name: لهستان__۱-02d82579
  type: vless
  server: 104.17.2.63
  port: 443
  uuid: c98a16e4-0dc5-42f0-b3db-30f04525c123
  udp: true
  tls: true
  network: ws
  servername: vless1-bu3.pages.dev
  ws-opts:
    path: /
    headers:
      Host: vless1-bu3.pages.dev
- name: V2ray1_Ng-aaf39fb4
  type: trojan
  server: 104.248.18.1
  port: 1935
  password: 6gZh2JbfhQ
  udp: true
  sni: x1-germany-digitalocean-v2.devefun.org
- name: vless-d43197aa
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: qeshmserver
  udp: true
  tls: false
  network: xhttp
- name: Sezar_sec-bca1c81b
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: 248MMad-Reality-9a69d16d
  type: vless
  server: david2.lemoex.blog
  port: 2053
  uuid: cc08501f-47b9-4fc8-a1c6-315dc797b21b
  udp: true
  tls: false
  network: xhttp
  servername: david2.lemoex.blog
  reality-opts:
    public-key: po5XxOfaSooi7FbECg_rxGIKWpcu1ql2QcglwuJ3MlI
    short-id: 6bcacd775e
- name: vless-dd65ba22
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 6bcb4f37-bba7-4ae0-afac-d43195c72c12
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: zula.ir?ed=2560
    headers:
      Host: my.digikala.dynv6.net
- name: vless-2e95a87d
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - vless-d4bc6179
  - net0n3_321-3ebf176c
  - 248MMad-H-56c7876c
  - vless-64c889db
  - V2ray1_Ng-bc8c70a7
  - V2ray1_Ng-260a7a1e
  - هلند__۲-dcf97fe8
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-48619966
  - Sezar_sec-349b4721
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-6564fc64
  - V2ray1_Ng-40c3396d
  - Sezar_sec-550ce1aa
  - 248MMad-WS-7c8e1ddc
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-860f08d1
  - vless-0085d498
  - vless-66ea8cbc
  - V2ray1_Ng-e0095cc7
  - vless-3ae0d312
  - V2ray1_Ng-5e4482db
  - هلند-4cdf9cc4
  - vless-aca1bd04
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-d81e4153
  - مولداوی-172cbe74
  - vless-8f810a21
  - vless-cab7ad93
  - لهستان__۱-02d82579
  - V2ray1_Ng-aaf39fb4
  - vless-d43197aa
  - Sezar_sec-bca1c81b
  - 248MMad-Reality-9a69d16d
  - vless-dd65ba22
  - vless-2e95a87d
- name: AUTO
  type: url-test
  proxies:
  - vless-d4bc6179
  - net0n3_321-3ebf176c
  - 248MMad-H-56c7876c
  - vless-64c889db
  - V2ray1_Ng-bc8c70a7
  - V2ray1_Ng-260a7a1e
  - هلند__۲-dcf97fe8
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-48619966
  - Sezar_sec-349b4721
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-6564fc64
  - V2ray1_Ng-40c3396d
  - Sezar_sec-550ce1aa
  - 248MMad-WS-7c8e1ddc
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-860f08d1
  - vless-0085d498
  - vless-66ea8cbc
  - V2ray1_Ng-e0095cc7
  - vless-3ae0d312
  - V2ray1_Ng-5e4482db
  - هلند-4cdf9cc4
  - vless-aca1bd04
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-d81e4153
  - مولداوی-172cbe74
  - vless-8f810a21
  - vless-cab7ad93
  - لهستان__۱-02d82579
  - V2ray1_Ng-aaf39fb4
  - vless-d43197aa
  - Sezar_sec-bca1c81b
  - 248MMad-Reality-9a69d16d
  - vless-dd65ba22
  - vless-2e95a87d
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
