mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: Mahdi2000_m_ql_2535-0afd690d
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: NGINX.NSCl.IR
- name: Mahdi2000_m_ql_5281-3efba094
  type: vless
  server: 154.92.9.151
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: simorgh.hpcode.ir
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: Mahdi2000_m_ql_5283-d1fc65cb
  type: vless
  server: 154.92.9.176
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: simorgh.hpcode.ir
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed
    headers:
      Host: simorgh.hpcode.ir
- name: Mahdi2000_m_ql_29904-6ad00c9f
  type: vmess
  server: shamo.shnovps.click
  port: 44185
  uuid: 6e0bdb9d-058a-4c36-aa58-44a782caec4f
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /
    headers:
      Host: shamo.shnovps.click
- name: Mahdi2000_m_ql_29904-1fc7bd66
  type: vmess
  server: shamo.shnovps.click
  port: 44185
  uuid: 6e0bdb9d-058a-4c36-aa58-44a782caec4f
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /
    headers:
      Host: shamo.shnovps.click
- name: vless-60c06d55
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-1e40fa15
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-6d415fe3
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-43c2aea7
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-bd9476c5
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-315acffa
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-6d3ca7a4
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-110a77e6
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: مشتی_جوین_بده_ناموصا__xzjinx-17a9104e
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-b6ef36a2
  type: vless
  server: 94.182.136.184
  port: 159
  uuid: 0af94a54-f5d8-43dd-8544-77a56559ea1c
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-b764813a
  type: vless
  server: 31.47.45.173
  port: 777
  uuid: ce55d3ed-618b-45b7-d879-368fbb465efd
  udp: true
  network: tcp
- name: vless-7b5b5ceb
  type: vless
  server: hell.dl101movis.ir
  port: 80
  uuid: d601250a-e54f-46fe-a984-fb0f1d6d48ce
  udp: true
  network: xhttp
- name: vless-0acfa426
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  network: tcp
- name: vless-bfbb452c
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-aba4be9a
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_281-3ff2b755
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-fc32e4a8
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: nginx.nscl.ir
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_276-ed56359a
  type: ss
  server: h110vpnnl.outlinekeys.net
  port: 52571
  cipher: chacha20-ietf-poly1305
  password: 2nvtG6pl4Om1G0cWlnyXHl
  udp: true
- name: vless-b20a8d5d
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 92f481b6-ad92-43e4-a683-2bb0aeaa9846
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: dw.alibichareh.dpdns.org
- name: vless-05e31164
  type: vless
  server: 300232332.webnama.com.tr
  port: 1517
  uuid: 3d554bba-9c77-499f-9055-1eb42058ed00
  udp: true
  network: tcp
- name: net0n3_274-b31ffe0e
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: Sezar_sec-bd22875e
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: Sezar_sec-9b1f3b7b
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: aes-128-gcm
  tls: true
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: Sezar_sec-5c4526c6
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
  skip-cert-verify: true
- name: Sezar_sec-5c43c574
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: aes-128-gcm
  tls: true
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: Sezar_Sec-894529c3
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-60508f55
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-6f5882df
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-36c90584
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-7fe99f4d
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - DIRECT
  - Mahdi2000_m_ql_2535-0afd690d
  - Mahdi2000_m_ql_5281-3efba094
  - Mahdi2000_m_ql_5283-d1fc65cb
  - Mahdi2000_m_ql_29904-6ad00c9f
  - Mahdi2000_m_ql_29904-1fc7bd66
  - vless-60c06d55
  - vless-1e40fa15
  - vless-6d415fe3
  - vless-43c2aea7
  - vless-bd9476c5
  - vless-315acffa
  - vless-6d3ca7a4
  - vless-110a77e6
  - مشتی_جوین_بده_ناموصا__xzjinx-17a9104e
  - مشتی_جوین_بده_ناموصا__xzjinx-b6ef36a2
  - مشتی_جوین_بده_ناموصا__xzjinx-b764813a
  - vless-7b5b5ceb
  - vless-0acfa426
  - vless-bfbb452c
  - vless-aba4be9a
  - net0n3_281-3ff2b755
  - vless-fc32e4a8
  - net0n3_276-ed56359a
  - vless-b20a8d5d
  - vless-05e31164
  - net0n3_274-b31ffe0e
  - Sezar_sec-bd22875e
  - Sezar_sec-9b1f3b7b
  - Sezar_sec-5c4526c6
  - Sezar_sec-5c43c574
  - Sezar_Sec-894529c3
  - Sezar_Sec-60508f55
  - Sezar_Sec-6f5882df
  - Sezar_Sec-36c90584
  - Sezar_Sec-7fe99f4d
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - Mahdi2000_m_ql_2535-0afd690d
  - Mahdi2000_m_ql_5281-3efba094
  - Mahdi2000_m_ql_5283-d1fc65cb
  - Mahdi2000_m_ql_29904-6ad00c9f
  - Mahdi2000_m_ql_29904-1fc7bd66
  - vless-60c06d55
  - vless-1e40fa15
  - vless-6d415fe3
  - vless-43c2aea7
  - vless-bd9476c5
  - vless-315acffa
  - vless-6d3ca7a4
  - vless-110a77e6
  - مشتی_جوین_بده_ناموصا__xzjinx-17a9104e
  - مشتی_جوین_بده_ناموصا__xzjinx-b6ef36a2
  - مشتی_جوین_بده_ناموصا__xzjinx-b764813a
  - vless-7b5b5ceb
  - vless-0acfa426
  - vless-bfbb452c
  - vless-aba4be9a
  - net0n3_281-3ff2b755
  - vless-fc32e4a8
  - net0n3_276-ed56359a
  - vless-b20a8d5d
  - vless-05e31164
  - net0n3_274-b31ffe0e
  - Sezar_sec-bd22875e
  - Sezar_sec-9b1f3b7b
  - Sezar_sec-5c4526c6
  - Sezar_sec-5c43c574
  - Sezar_Sec-894529c3
  - Sezar_Sec-60508f55
  - Sezar_Sec-6f5882df
  - Sezar_Sec-36c90584
  - Sezar_Sec-7fe99f4d
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,IR,DIRECT
- MATCH,🚀 Proxy
