mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-ff7c9838
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-b7f3d847
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-ec61c609
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-2b3b2f1c
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-ee7d577d
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-5250a9a8
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-14eab48f
  type: vless
  server: vpconnect.ahadbala.ir
  port: 80
  uuid: 3f0c3cef-75c0-4253-a62e-d89f5a45dcc1
  udp: true
  network: tcp
- name: vless-f7600adb
  type: vless
  server: fastlyeeeeee.fast.hosting-ip.com
  port: 80
  uuid: cdnfastlycash
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cdnfastlycash.io
- name: vless-e0b48d2f
  type: vless
  server: de1.cowjuice.me
  port: 443
  uuid: 955827fc-c729-4a1e-ba6c-d85754c8e937
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: O9DMPpwicRcMofaplcvpQStNRogPS_HJY0s5_4EaKQc
    short-id: aabbccdd
- name: vless-79ac3c81
  type: vless
  server: de6.razercompany.com
  port: 33200
  uuid: c4389c70-1e5a-4bd2-934f-44fb2e62ccf5
  udp: true
  network: tcp
- name: vless-43a0e69d
  type: vless
  server: real-all3.sdcards.ir
  port: 8501
  uuid: 9666ee62-d1f3-4f6e-8881-c17fee524e31
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: OJ0wA5wp55uZdD16dutlTZvx1x-rbMMXmiO9D_MMCHI
    short-id: e701a013553059ba
- name: vless-27335e99
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: vless-687e4ded
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /zula.ir
    headers:
      Host: sub.divib.dynv6.net
- name: vless-35fbb753
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-7c6b08e0
  type: vless
  server: compose.fast.hosting-ip.com
  port: 80
  uuid: ab80613b-e04b-4af5-bad9-9ca5c448266e
  udp: true
  network: ws
  ws-opts:
    path: /GoodLuck?ed=2560
    headers:
      Host: Mastercloud.global.ssl.fastly.net.
- name: نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-9201c807
  type: vmess
  server: gr1.nspay.top
  port: 35600
  uuid: 60bcea81-b98f-4319-9e0b-58318d9f46b0
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-aacf4181
  type: vmess
  server: gr1.nspay.top
  port: 35600
  uuid: 60bcea81-b98f-4319-9e0b-58318d9f46b0
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: Sezar_sec-378bfd1e
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: Sezar_sec-50edad49
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: aes-128-gcm
  tls: true
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: Sezar_sec-e35abcc7
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
  skip-cert-verify: true
- name: Sezar_sec-9d9cfa08
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: aes-128-gcm
  tls: true
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: مشتی_جوین_بده_ناموصا__xzjinx-bb56ce8a
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: e6daaeba-5a7c-4933-89b0-0078c14c50f1
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-8ef52f4b
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: b54eaa6b-d4fc-4bb3-b3c6-9d0b61da00f7
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-5760cfd9
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  network: tcp
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies:
  - vless-ff7c9838
  - vless-b7f3d847
  - vless-ec61c609
  - vless-2b3b2f1c
  - vless-ee7d577d
  - vless-5250a9a8
  - vless-14eab48f
  - vless-f7600adb
  - vless-e0b48d2f
  - vless-79ac3c81
  - vless-43a0e69d
  - vless-27335e99
  - vless-687e4ded
  - vless-35fbb753
  - vless-7c6b08e0
  - نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-9201c807
  - نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-aacf4181
  - Sezar_sec-378bfd1e
  - Sezar_sec-50edad49
  - Sezar_sec-e35abcc7
  - Sezar_sec-9d9cfa08
  - مشتی_جوین_بده_ناموصا__xzjinx-bb56ce8a
  - مشتی_جوین_بده_ناموصا__xzjinx-8ef52f4b
  - مشتی_جوین_بده_ناموصا__xzjinx-5760cfd9
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies:
  - vless-ff7c9838
  - vless-b7f3d847
  - vless-ec61c609
  - vless-2b3b2f1c
  - vless-ee7d577d
  - vless-5250a9a8
  - vless-14eab48f
  - vless-f7600adb
  - vless-e0b48d2f
  - vless-79ac3c81
  - vless-43a0e69d
  - vless-27335e99
  - vless-687e4ded
  - vless-35fbb753
  - vless-7c6b08e0
  - نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-9201c807
  - نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-aacf4181
  - Sezar_sec-378bfd1e
  - Sezar_sec-50edad49
  - Sezar_sec-e35abcc7
  - Sezar_sec-9d9cfa08
  - مشتی_جوین_بده_ناموصا__xzjinx-bb56ce8a
  - مشتی_جوین_بده_ناموصا__xzjinx-8ef52f4b
  - مشتی_جوین_بده_ناموصا__xzjinx-5760cfd9
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies:
  - vless-ff7c9838
  - vless-b7f3d847
  - vless-ec61c609
  - vless-2b3b2f1c
  - vless-ee7d577d
  - vless-5250a9a8
  - vless-14eab48f
  - vless-f7600adb
  - vless-e0b48d2f
  - vless-79ac3c81
  - vless-43a0e69d
  - vless-27335e99
  - vless-687e4ded
  - vless-35fbb753
  - vless-7c6b08e0
  - نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-9201c807
  - نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-aacf4181
  - Sezar_sec-378bfd1e
  - Sezar_sec-50edad49
  - Sezar_sec-e35abcc7
  - Sezar_sec-9d9cfa08
  - مشتی_جوین_بده_ناموصا__xzjinx-bb56ce8a
  - مشتی_جوین_بده_ناموصا__xzjinx-8ef52f4b
  - مشتی_جوین_بده_ناموصا__xzjinx-5760cfd9
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
