mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-b204d274
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-18edf1a3
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-7ca07745
  type: vless
  server: 91.99.172.196
  port: 28041
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: WpvjPUZ5x3SIvDzSr5q9v0bfhzo36obh3CXIqJVmnkY
    short-id: 91355b9b818617
- name: vless-b475f451
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-c5bdc60a
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-c6e1a0a9
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-62592284
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-515e8f67
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-018faa06
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-5f92690b
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-58b75ddb
  type: vless
  server: accounting.vinamarketcenter.ir
  port: 443
  uuid: 5cfba4ac-105a-452a-ac10-88b1adf784ee
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: T7Cwk-B3EvZqqRywIgN_TNotJiUOXYUI9bHqYKPnTi0
    short-id: 105e89ba3d2a1c3b
- name: vless-8967230f
  type: vless
  server: 0000:0000:0000:0000:0000:ffff:5b63:9012
  port: 20600
  uuid: 884bead8-301f-4be8-a40a-1e273d2d0fe3
  udp: true
  network: grpc
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: b14Nibi1pMPwFPqgiyZRS3a6-Y-Q8EsE5urKnA-RkAc
    short-id: adf8a1f5689177a2
  grpc-opts:
    grpc-service-name: ''
- name: vless-671ddf53
  type: vless
  server: 91.99.178.189
  port: 443
  uuid: 15398933-070d-4ea2-9697-5fcd79793c97
  udp: true
  network: tcp
- name: vless-3f50f5b1
  type: vless
  server: nl.ir.tekcloud.site
  port: 45431
  uuid: 60978be7-0ab8-4167-9883-db983114d4d1
  udp: true
  network: tcp
- name: trojan-97cfb844
  type: trojan
  server: 91.107.163.173
  port: 27596
  password: OmqcThZWp1
  udp: true
  skip-cert-verify: true
- name: vless-f4b10294
  type: vless
  server: 91.99.160.151
  port: 443
  uuid: 153ee04c-dcc1-4ef8-a146-8fb31cec1f48
  udp: true
  network: tcp
- name: vless-3814ed3a
  type: vless
  server: 62.60.223.6
  port: 2080
  uuid: bea34b73-3244-475b-b914-7bb80e1cda91
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: L3lJWdU7mHijSkNaNt-m29OYnKnHvHYRxg2Y8XXFdng
    short-id: bf517367267685
- name: vless-18c18cdc
  type: vless
  server: 91.99.195.6
  port: 80
  uuid: 91a5d5b3-4b88-4359-aeec-e1532f535fd6
  udp: true
  network: grpc
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZO276Z5WXIqCmNLXT8Lewzjhhgm365JUJXAKyKq8Rz4
    short-id: bc063769cb
  grpc-opts:
    grpc-service-name: refersion.com
- name: vless-e98ebade
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /zula.ir
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: 300گیگ_39تومان_تسترایگانTickV2bot-f6fc5af9
  type: vmess
  server: clean.gdjkhwgedhujkgwehkudadasdasdas.ir
  port: 2095
  uuid: 08296657-a67a-45e4-a517-6ad3ac1a82fb
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: httpupgrade
  udp: true
- name: 300گیگ_39تومان_تسترایگانTickV2bot-259d8f04
  type: vmess
  server: clean.gdjkhwgedhujkgwehkudadasdasdas.ir
  port: 2095
  uuid: 08296657-a67a-45e4-a517-6ad3ac1a82fb
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: httpupgrade
  udp: true
- name: proxygodratmand__قطع_شدی_بیا_چنل_بیا_چنل_بازم_هست-fa957384
  type: vless
  server: 161.35.17.146
  port: 6775
  uuid: b1061a7b-c92c-42a6-826b-aa1f19554089
  udp: true
  network: tcp
- name: DarisPROXY-a09ad410
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: ZetaTech_iR2-e9f0fc43
  type: ss
  server: series-a2-me.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: Bog0ELmMM9DSxDdQ
  udp: true
- name: مشتی_جوین_بده_ناموصا__xzjinx-a8a4d188
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: 10b1f4a3-63a7-46b4-f05a-023542f0dc11
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-52c74a33
  type: vmess
  server: 185.18.214.174
  port: 8080
  uuid: baf451ee-ab34-4a28-de9f-1fa918d79fc1
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-00b60ed5
  type: vmess
  server: 185.18.214.174
  port: 8080
  uuid: baf451ee-ab34-4a28-de9f-1fa918d79fc1
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-1f5952ae
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: d64669fb-07e5-4d27-9995-63545fae16c2
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-1a702233
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: d64669fb-07e5-4d27-9995-63545fae16c2
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-76f41fc2
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: f7255d17-4abc-4c54-84dd-e1e9e9c41dad
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-3782bb8e
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: 395bf21d-ea83-4d85-ad04-ad1f6b1431bf
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-9fc5a8c9
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: 395bf21d-ea83-4d85-ad04-ad1f6b1431bf
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: Sezar_Sec-af240dee
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-41570ff6
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-97bc3ef8
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-fa9b3606
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-226cdaee
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: Sezar_Sec-3baf5673
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-b204d274
  - vless-18edf1a3
  - vless-7ca07745
  - vless-b475f451
  - vless-c5bdc60a
  - vless-c6e1a0a9
  - vless-62592284
  - vless-515e8f67
  - vless-018faa06
  - vless-5f92690b
  - vless-58b75ddb
  - vless-8967230f
  - vless-671ddf53
  - vless-3f50f5b1
  - trojan-97cfb844
  - vless-f4b10294
  - vless-3814ed3a
  - vless-18c18cdc
  - vless-e98ebade
  - 300گیگ_39تومان_تسترایگانTickV2bot-f6fc5af9
  - 300گیگ_39تومان_تسترایگانTickV2bot-259d8f04
  - proxygodratmand__قطع_شدی_بیا_چنل_بیا_چنل_بازم_هست-fa957384
  - DarisPROXY-a09ad410
  - ZetaTech_iR2-e9f0fc43
  - مشتی_جوین_بده_ناموصا__xzjinx-a8a4d188
  - مشتی_جوین_بده_ناموصا__xzjinx-52c74a33
  - مشتی_جوین_بده_ناموصا__xzjinx-00b60ed5
  - مشتی_جوین_بده_ناموصا__xzjinx-1f5952ae
  - مشتی_جوین_بده_ناموصا__xzjinx-1a702233
  - مشتی_جوین_بده_ناموصا__xzjinx-76f41fc2
  - مشتی_جوین_بده_ناموصا__xzjinx-3782bb8e
  - مشتی_جوین_بده_ناموصا__xzjinx-9fc5a8c9
  - Sezar_Sec-af240dee
  - Sezar_Sec-41570ff6
  - Sezar_Sec-97bc3ef8
  - Sezar_Sec-fa9b3606
  - Sezar_Sec-226cdaee
  - Sezar_Sec-3baf5673
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
