port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: net0n3_296-eadb8ad1
  type: vless
  server: de6.razercompany.com
  port: 33200
  uuid: c4389c70-1e5a-4bd2-934f-44fb2e62ccf5
  udp: true
  tls: false
  network: tcp
- name: کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-c04ec233
  type: vless
  server: 199.34.228.178
  port: 2095
  uuid: 46ea256c-48e4-41b2-abe5-ec9b9b233333
  udp: true
  tls: false
  network: httpupgrade
- name: net0n3_282-33f397a5
  type: vless
  server: hell.dl101movis.ir
  port: 80
  uuid: d601250a-e54f-46fe-a984-fb0f1d6d48ce
  udp: true
  tls: false
  network: xhttp
- name: net0n3_295-8d0593af
  type: vless
  server: de1.cowjuice.me
  port: 443
  uuid: 955827fc-c729-4a1e-ba6c-d85754c8e937
  udp: true
  tls: false
  network: tcp
  servername: thelocal.de
  reality-opts:
    public-key: O9DMPpwicRcMofaplcvpQStNRogPS_HJY0s5_4EaKQc
    short-id: aabbccdd
- name: net0n3_289-9c0e30bb
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: vless-511e8347
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: vless-c7d4b223
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: مشتی_جوین_بده_ناموصا__xzjinx-b9513d27
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: e6daaeba-5a7c-4933-89b0-0078c14c50f1
  udp: true
  tls: false
  network: tcp
- name: Sezar_sec-fffebd47
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
- name: net0n3_283-6956f6fb
  type: ss
  server: 45.87.175.165
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: QCXDxuDlTTMD7jtgHUjIoj
  udp: true
- name: vless-b475514b
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: مشتی_جوین_بده_ناموصا__xzjinx-ba5a1f3f
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: b54eaa6b-d4fc-4bb3-b3c6-9d0b61da00f7
  udp: true
  tls: false
  network: tcp
- name: vless-27564de3
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  tls: false
  network: tcp
- name: vless-653ef42c
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: nginx.nscl.ir
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-02db4365
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
- name: Sezar_Sec-5a53005f
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: vless-07804d46
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_297-6fcb95aa
  type: vless
  server: real-all3.sdcards.ir
  port: 8501
  uuid: 9666ee62-d1f3-4f6e-8881-c17fee524e31
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: OJ0wA5wp55uZdD16dutlTZvx1x-rbMMXmiO9D_MMCHI
    short-id: e701a013553059ba
- name: vless-3b59f026
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: net0n3_300-821856d8
  type: vless
  server: vpconnect.ahadbala.ir
  port: 80
  uuid: 3f0c3cef-75c0-4253-a62e-d89f5a45dcc1
  udp: true
  tls: false
  network: tcp
- name: vless-2d2c4dea
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 148709e4-402b-48dd-8892-ed39b55ea45c
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: '@vpnserverrr'
    headers:
      Host: barayeiranmahsang.loseyourself.dpdns.org
- name: کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-8616f112
  type: vless
  server: pishgam.sdcards.ir
  port: 2095
  uuid: 46ea256c-48e4-41b2-abe5-ec9b9b233333
  udp: true
  tls: false
  network: httpupgrade
- name: کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-7f0c687b
  type: vless
  server: 199.34.228.178
  port: 2095
  uuid: 46ea256c-48e4-41b2-abe5-ec9b9b233333
  udp: true
  tls: false
  network: httpupgrade
- name: vless-ef7b18c8
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-e14c7c70
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: net0n3_290-378c844e
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sub.divib.dynv6.net
- name: vless-89e7dee5
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-62aa7e3b
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: مشتی_جوین_بده_ناموصا__xzjinx-820e351d
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: 09694965-369f-48b5-82fa-40aae0236746
  udp: true
  tls: false
  network: tcp
- name: IRANCELL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-220fc5b6
  type: vless
  server: 00064.mutee.com.tr
  port: 4471
  uuid: 9c6ae346-c50f-47cb-891a-4e5ac5981e7e
  udp: true
  tls: false
  network: tcp
- name: vless-4a67b012
  type: vless
  server: 91.99.172.196
  port: 28041
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: WpvjPUZ5x3SIvDzSr5q9v0bfhzo36obh3CXIqJVmnkY
    short-id: 91355b9b818617
- name: vless-c4a1510f
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_285-9b221e89
  type: vless
  server: bam.erfann.shop
  port: 15807
  uuid: 8e4d0dba-884f-4bbd-9f1d-ea5ec78efe7d
  udp: true
  tls: false
  network: tcp
- name: vless-c642b4d0
  type: vless
  server: www.speedtest.net
  port: 2096
  uuid: dc80ee7e-bad0-450c-a218-f12e05680885
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2096
    headers:
      Host: arm1.dollardoon.com
- name: کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-043bac89
  type: vless
  server: hub.atomamoz.ir
  port: 33450
  uuid: 46ea256c-48e4-41b2-abe5-ec9b9b233333
  udp: true
  tls: false
  network: tcp
  servername: de.atomamoz.ir
  reality-opts:
    public-key: Y3h3cOAkz3j_CbseRzm3EAkVq9HMkqv-gnwcXI2TI0Q
    short-id: null
- name: net0n3_294-b54efae5
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-fd839257
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: vless-8e7bcd11
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: net0n3_281-18a0c59c
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-918e6a4e
  type: vless
  server: 0ger.amazon-osishop.ir
  port: 8880
  uuid: 2066c2f3-bde1-429f-b083-fcfc7aee14b5
  udp: true
  tls: false
  network: tcp
- name: vless-21b8923f
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 546cc913-2825-4771-b713-a23905913141
  udp: true
  tls: true
  network: ws
  servername: 638874931195949050.kish-prx-dnraaaf.info
  ws-opts:
    path: /wjwqzaws
    headers:
      Host: 638874931195949050.kish-prx-dnraaaf.info
- name: vless-a011407b
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: HamrahAVAL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-0a901ad7
  type: vless
  server: 00074.mutee.com.tr
  port: 4471
  uuid: 9c6ae346-c50f-47cb-891a-4e5ac5981e7e
  udp: true
  tls: false
  network: tcp
- name: net0n3_298-74b4abbb
  type: vless
  server: fastlyeeeeee.fast.hosting-ip.com
  port: 80
  uuid: cdnfastlycash
  udp: true
  tls: false
  network: xhttp
- name: Sezar_Sec-d8bf2295
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  tls: false
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-d37240b8
  type: vless
  server: 94.182.136.184
  port: 159
  uuid: 0af94a54-f5d8-43dd-8544-77a56559ea1c
  udp: true
  tls: false
  network: tcp
- name: Sezar_sec-1ce64a0a
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  tls: false
  network: tcp
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: net0n3_287-96a6bd0b
  type: vless
  server: compose.fast.hosting-ip.com
  port: 80
  uuid: ab80613b-e04b-4af5-bad9-9ca5c448266e
  udp: true
  tls: false
  network: xhttp
- name: vless-a5a49cb0
  type: vless
  server: 300232332.webnama.com.tr
  port: 1517
  uuid: 3d554bba-9c77-499f-9055-1eb42058ed00
  udp: true
  tls: false
  network: tcp
- name: Sezar_Sec-4f4952c3
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-6a2f367c
  type: vless
  server: 104.18.26.90
  port: 2095
  uuid: 46ea256c-48e4-41b2-abe5-ec9b9b233333
  udp: true
  tls: false
  network: httpupgrade
- name: مشتی_جوین_بده_ناموصا__xzjinx-cd6c85eb
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  tls: false
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-a2839669
  type: vless
  server: 31.47.45.173
  port: 777
  uuid: ce55d3ed-618b-45b7-d879-368fbb465efd
  udp: true
  tls: false
  network: tcp
- name: Sezar_Sec-6d13a0eb
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-6962d325
  type: ss
  server: 4.223.106.151
  port: 48172
  cipher: chacha20-ietf-poly1305
  password: 51yloQC8D9w1Wae7FHtI65
  udp: true
- name: Sezar_Sec-56195bee
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: vless-e55855f8
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: net0n3_276-4fee75c4
  type: ss
  server: h110vpnnl.outlinekeys.net
  port: 52571
  cipher: chacha20-ietf-poly1305
  password: 2nvtG6pl4Om1G0cWlnyXHl
  udp: true
- name: vless-8d7f1c42
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 92f481b6-ad92-43e4-a683-2bb0aeaa9846
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: dw.alibichareh.dpdns.org
- name: vless-0e2db598
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: Sezar_sec-cd682e01
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - net0n3_296-eadb8ad1
  - کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-c04ec233
  - net0n3_282-33f397a5
  - net0n3_295-8d0593af
  - net0n3_289-9c0e30bb
  - vless-511e8347
  - vless-c7d4b223
  - مشتی_جوین_بده_ناموصا__xzjinx-b9513d27
  - Sezar_sec-fffebd47
  - net0n3_283-6956f6fb
  - vless-b475514b
  - مشتی_جوین_بده_ناموصا__xzjinx-ba5a1f3f
  - vless-27564de3
  - vless-653ef42c
  - vless-02db4365
  - Sezar_Sec-5a53005f
  - vless-07804d46
  - net0n3_297-6fcb95aa
  - vless-3b59f026
  - net0n3_300-821856d8
  - vless-2d2c4dea
  - کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-8616f112
  - کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-7f0c687b
  - vless-ef7b18c8
  - vless-e14c7c70
  - net0n3_290-378c844e
  - vless-89e7dee5
  - vless-62aa7e3b
  - مشتی_جوین_بده_ناموصا__xzjinx-820e351d
  - IRANCELL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-220fc5b6
  - vless-4a67b012
  - vless-c4a1510f
  - net0n3_285-9b221e89
  - vless-c642b4d0
  - کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-043bac89
  - net0n3_294-b54efae5
  - vless-fd839257
  - vless-8e7bcd11
  - net0n3_281-18a0c59c
  - vless-918e6a4e
  - vless-21b8923f
  - vless-a011407b
  - HamrahAVAL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-0a901ad7
  - net0n3_298-74b4abbb
  - Sezar_Sec-d8bf2295
  - مشتی_جوین_بده_ناموصا__xzjinx-d37240b8
  - Sezar_sec-1ce64a0a
  - net0n3_287-96a6bd0b
  - vless-a5a49cb0
  - Sezar_Sec-4f4952c3
  - کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-6a2f367c
  - مشتی_جوین_بده_ناموصا__xzjinx-cd6c85eb
  - مشتی_جوین_بده_ناموصا__xzjinx-a2839669
  - Sezar_Sec-6d13a0eb
  - مشتی_جوین_بده_ناموصا__xzjinx-6962d325
  - Sezar_Sec-56195bee
  - vless-e55855f8
  - net0n3_276-4fee75c4
  - vless-8d7f1c42
  - vless-0e2db598
  - Sezar_sec-cd682e01
- name: AUTO
  type: url-test
  proxies:
  - net0n3_296-eadb8ad1
  - کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-c04ec233
  - net0n3_282-33f397a5
  - net0n3_295-8d0593af
  - net0n3_289-9c0e30bb
  - vless-511e8347
  - vless-c7d4b223
  - مشتی_جوین_بده_ناموصا__xzjinx-b9513d27
  - Sezar_sec-fffebd47
  - net0n3_283-6956f6fb
  - vless-b475514b
  - مشتی_جوین_بده_ناموصا__xzjinx-ba5a1f3f
  - vless-27564de3
  - vless-653ef42c
  - vless-02db4365
  - Sezar_Sec-5a53005f
  - vless-07804d46
  - net0n3_297-6fcb95aa
  - vless-3b59f026
  - net0n3_300-821856d8
  - vless-2d2c4dea
  - کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-8616f112
  - کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-7f0c687b
  - vless-ef7b18c8
  - vless-e14c7c70
  - net0n3_290-378c844e
  - vless-89e7dee5
  - vless-62aa7e3b
  - مشتی_جوین_بده_ناموصا__xzjinx-820e351d
  - IRANCELL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-220fc5b6
  - vless-4a67b012
  - vless-c4a1510f
  - net0n3_285-9b221e89
  - vless-c642b4d0
  - کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-043bac89
  - net0n3_294-b54efae5
  - vless-fd839257
  - vless-8e7bcd11
  - net0n3_281-18a0c59c
  - vless-918e6a4e
  - vless-21b8923f
  - vless-a011407b
  - HamrahAVAL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-0a901ad7
  - net0n3_298-74b4abbb
  - Sezar_Sec-d8bf2295
  - مشتی_جوین_بده_ناموصا__xzjinx-d37240b8
  - Sezar_sec-1ce64a0a
  - net0n3_287-96a6bd0b
  - vless-a5a49cb0
  - Sezar_Sec-4f4952c3
  - کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-6a2f367c
  - مشتی_جوین_بده_ناموصا__xzjinx-cd6c85eb
  - مشتی_جوین_بده_ناموصا__xzjinx-a2839669
  - Sezar_Sec-6d13a0eb
  - مشتی_جوین_بده_ناموصا__xzjinx-6962d325
  - Sezar_Sec-56195bee
  - vless-e55855f8
  - net0n3_276-4fee75c4
  - vless-8d7f1c42
  - vless-0e2db598
  - Sezar_sec-cd682e01
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
