proxies:
- name: vless-416a0285
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: yahoo.com
  flow: xtls-rprx-vision
- name: vless-fb38c314
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: stripe.com
  flow: xtls-rprx-vision
- name: vless-f1846e51
  type: vless
  server: accounting.vinamarketcenter.ir
  port: 443
  uuid: 5cfba4ac-105a-452a-ac10-88b1adf784ee
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: www.tgju.org
  flow: xtls-rprx-vision
- name: vless-667c5ed9
  type: vless
  server: 150.241.65.211
  port: 443
  uuid: be5fab84-5edb-4800-927e-243f6e4309bf
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: www.latimes.com
- name: vless-900bd74e
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: a812a015-a65b-4003-ac5f-266e141c6405
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2048
    headers:
      Host: Www.speedtest.net.developsp.ir.vegaskala.com.
- name: vless-b5811c25
  type: vless
  server: srcvpn.fast.hosting-ip.com
  port: 80
  uuid: 3ec5186b-d636-48b0-9a0a-30d824f63078
  tls: false
  skip-cert-verify: false
  udp: true
  network: xhttp
  servername: ''
- name: vless-941db218
  type: vless
  server: srcvpn.fast.hosting-ip.com
  port: 80
  uuid: '%54%45%4C%45%47%52%41%4D%2D%4E%55%46%69%4C%54%45%52'
  tls: false
  skip-cert-verify: false
  udp: true
  network: xhttp
  servername: ''
- name: vless-d75189af
  type: vless
  server: 5.75.193.253
  port: 443
  uuid: f998b63e-bfbe-4a7d-a6c0-800d8febb806
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: journalofbigdata.springeropen.com
- name: vless-f1205faa
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560
    headers:
      Host: redfree8mahsang6.redfree8.ir
- name: vless-6a9b4780
  type: vless
  server: 172.67.17.195
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-1237b069
  type: vless
  server: 104.16.104.151
  port: 80
  uuid: 1f431db3-1918-4e7b-a855-c93485e11694
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560
    headers:
      Host: pari.parinazz.dpdns.org
- name: vless-44a7a60f
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: vless-883a2e2e
  type: vless
  server: 172.67.67.92
  port: 80
  uuid: f78ce1bb-0fa6-4ef4-b4c9-b91014a7055d
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560
    headers:
      Host: delam.ahaysiahzangi.dpdns.org
- name: vless-5c745290
  type: vless
  server: 104.24.31.150
  port: 80
  uuid: 9d6315f7-f272-4806-97c8-5fdaafad391e
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2570
    headers:
      Host: lot.sosant.dpdns.org
- name: vless-a9f0700d
  type: vless
  server: 212.33.201.231
  port: 2054
  uuid: d843b700-0e0d-5ad9-72d9-46ced5785cd1
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-9be9d90a
  type: vless
  server: 85.133.201.45
  port: 18818
  uuid: 8b4c316e-f05a-413e-bda5-a7383a123a77
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-6438bb10
  type: vless
  server: 212.33.201.222
  port: 2054
  uuid: d843b700-0e0d-5ad9-72d9-46ced5785cd1
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-859551b1
  type: vless
  server: 212.86.94.101
  port: 33177
  uuid: a8ed95a6-7f54-48d6-bdcf-6c272851b81f
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
proxy-groups:
- name: 🚀 Auto Select
  type: url-test
  proxies:
  - vless-416a0285
  - vless-fb38c314
  - vless-f1846e51
  - vless-667c5ed9
  - vless-900bd74e
  - vless-b5811c25
  - vless-941db218
  - vless-d75189af
  - vless-f1205faa
  - vless-6a9b4780
  - vless-1237b069
  - vless-44a7a60f
  - vless-883a2e2e
  - vless-5c745290
  - vless-a9f0700d
  - vless-9be9d90a
  - vless-6438bb10
  - vless-859551b1
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 Proxy
  type: select
  proxies:
  - 🚀 Auto Select
  - DIRECT
- name: 🎯 Domestic
  type: select
  proxies:
  - DIRECT
rules:
- DOMAIN-SUFFIX,ir,🎯 Domestic
- GEOIP,IR,🎯 Domestic
- MATCH,🔮 Proxy
