port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-46bef410
  type: vless
  server: 188.227.84.171
  port: 8443
  uuid: 9418d05f-4943-4c50-8ced-d1df192daedf
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-ec2a9a38
  type: vless
  server: 172.67.49.134
  port: 443
  uuid: 06e4425e-a8cb-4b63-929f-2105604ab0a9
  udp: true
  tls: true
  network: ws
  servername: rc.ylks0033.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: rc.ylks0033.dpdns.org
- name: vless-4eb37f84
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: net0n3_347-0c18c945
  type: ss
  server: 193.228.139.250
  port: 1080
  cipher: chacha20-ietf-poly1305
  password: yrZtUElGhL8xfeaN0hIIzQ
  udp: true
- name: vless-979ff339
  type: vless
  server: david2.lemoex.blog
  port: 443
  uuid: 737c9e58-379d-4654-9471-d60494b326bd
  udp: true
  tls: true
  network: httpupgrade
  servername: david2.lemoex.blog
- name: VConfing-f1189acf
  type: vmess
  server: 81.12.33.180
  port: 8595
  uuid: 4e6e51d7-1234-4543-999f-0f54a428b77f
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-4cff1fc6
  type: vless
  server: 93.123.39.31
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: net0n3_352-a57f9799
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: عضو_شو__zibanabz-c9175e26
  type: vless
  server: zula.ir
  port: 443
  uuid: 172ed5fd-83a6-469e-863c-50e251a6c17d
  udp: true
  tls: true
  network: ws
  servername: rayan-supra.parisa.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: rayan-supra.parisa.dpdns.org
- name: عضو_شو__zibanabz-68c2f25e
  type: vless
  server: 172.67.128.105
  port: 80
  uuid: 4179c595-08ca-45cd-b555-91b6f1faeadc
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: di.dibdibini.dpdns.org
- name: sw_vpnbot-336a4b1e
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /Telegram@AZADIIIVPN/?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: sw_vpnbot-b3eaee92
  type: vless
  server: 45.131.211.135
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: '/Channel id: @AZADIIIVPN?ed=2560'
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: عضو_شو__zibanabz-6608f70d
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: عضو_شو__zibanabz-eeca71ca
  type: vless
  server: 172.67.67.92
  port: 80
  uuid: f78ce1bb-0fa6-4ef4-b4c9-b91014a7055d
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: delam.ahaysiahzangi.dpdns.org
- name: V2rex_Network_حتما_داخل_چنل_عضو_بشید-57181d0d
  type: vless
  server: v2rex.sanaei1.milxbywkaiwnx.xyz
  port: 3333
  uuid: 7c05bfbb-2884-4b6e-a523-0b7f5bbd07f4
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-2db05ef9
  type: vless
  server: 147.185.161.229
  port: 80
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: Telegram:@ShadowProxy66/?ed=2560
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
- name: vless-d7c1122d
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: V2rayNGFreeeV2rayNGFreee
  udp: true
  tls: false
  network: xhttp
- name: عضو_شو__zibanabz-9534a102
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: قطع_شدی_بیا_چنل__proxygodratmand-da560d01
  type: vmess
  server: gr1.nspay.top
  port: 35600
  uuid: c931a205-3f5b-46d7-9889-846f4b287ddf
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: sw_vpnbot-6eefe23b
  type: vless
  server: 45.80.111.147
  port: 80
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@AZADIIIVPN/?ed=2560
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: VConfing-fcf732d5
  type: vmess
  server: 103.249.133.8
  port: 53921
  uuid: f33a9661-d7a2-4f28-9170-c844c47916a0
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: sw_vpnbot-eaea60d8
  type: vless
  server: 185.148.106.242
  port: 80
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: 'Telegram🇮🇷Channel id: @AZADIIIVPN /?ed=2560'
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: vless-bf1385d1
  type: vless
  server: russiatest-tap.servers807.ir
  port: 13796
  uuid: b646e0d6-137b-49e1-90bc-3b9ad8a6484a
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: AIUUKeq08usIla0uv-NTp5wVe4TMb3VkXWDLoutlFnM
    short-id: a3ac
- name: vless-3153da38
  type: vless
  server: all97-vip.f-sub.com
  port: 1517
  uuid: 240052ac-0bf0-481f-adb4-f40a259fc189
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-2050b08b
  type: vless
  server: 104.16.104.151
  port: 80
  uuid: 1f431db3-1918-4e7b-a855-c93485e11694
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: pari.parinazz.dpdns.org
- name: vless-4d099640
  type: vless
  server: 83.217.9.233
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: عضو_شو__zibanabz-56ec6cce
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: FreeV2BoxBot-b6022cda
  type: vmess
  server: bluevpn2.bibak.bz
  port: 3030
  uuid: 20c86f6d-4e65-4477-93e6-4b11cf1fd09d
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: 美国机场推荐httpsa0axyz50-6dff8d27
  type: ss
  server: admin.c2.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: WstuSnlu4ieA9M0L
  udp: true
- name: عضو_شو__zibanabz-1b1b643f
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: عضو_شو__zibanabz-2c99bfec
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: عضو_شو__zibanabz-00caac21
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: telegram-788aa39d
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 8443
  uuid: 96a1b724-68d2-4f4d-ab25-38ecd83577bc
  udp: true
  tls: true
  network: ws
  servername: IyFpLkXk10.jOoLaJoOlA.OrG
  ws-opts:
    path: /
    headers:
      Host: IyFpLkXk10.jOoLaJoOlA.OrG
- name: 美国机场推荐httpsa0axyz63-9f0733f0
  type: ss
  server: series-a2-mec.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: net0n3_348-9e6462de
  type: ss
  server: 45.87.175.183
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
- name: sw_vpnbot-7b2ef93a
  type: vless
  server: www.speedtest.net
  port: 2095
  uuid: 49f10318-3e61-462b-b57d-0bfa25b77d94
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /hajmi?ed=2050/?AZADIIIVPNBIA_CHANEL@AZADIIIVPN
    headers:
      Host: dbe661d5a761ff6c.s-5HU09JDF-97SHS.WWWrubika.irto.xn--ls8haaaaaaaaaaaaaaaaaa.la.which.xn--ls8haaaaaaaaaaaaaaaaaa.xn-ls8faaaaaaaaaa.speedtest.net.google.com.eu.ir.nl.aparat.com.komak.IR.Nb-De.85858599.xYz.
- name: عضو_شو__zibanabz-1f26ba9f
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: V2rex_Network-af53d9a0
  type: vless
  server: v2rex.sanaei1.milxbywkaiwnx.xyz
  port: 3333
  uuid: 804aaf8d-0dc6-41ae-983e-4e1d3265ae5f
  udp: true
  tls: false
  network: tcp
- name: vpnv2rayNGv_سرورای_بیشتر_با_سرعت_بالا-69bbd5ae
  type: vmess
  server: 47.92.152.169
  port: 50002
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-1b0edc4c
  type: vless
  server: 89.221.203.100
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: sw_vpnbot-5a335ae8
  type: vless
  server: 104.26.13.54
  port: 80
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@AZADIIIVPN/?ed=2560
    headers:
      Host: REEdfREe8MahSaNg2.rEDOrG.IR
- name: sw_vpnbot-8391bf27
  type: vless
  server: www.speedtest.net
  port: 2095
  uuid: 49f10318-3e61-462b-b57d-0bfa25b77d94
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /hajmi?*aiojefoijeafiojaoifjoaijfoieajfea4502542---452525252525082850924520759275942592429465265926359832oiejfiaoiefoieaioaeoifiofeaiofeiofeoijeoijfaeoifja7773422834798732498327498huafuawugfuayufu476942652?ed=2050/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: dbe661d5a761ff6c.s-5HU09JDF-97SHS.WWWrubika.irto.xn--ls8haaaaaaaaaaaaaaaaaa.la.which.xn--ls8haaaaaaaaaaaaaaaaaa.xn-ls8faaaaaaaaaa.speedtest.net.google.com.eu.ir.nl.aparat.com.komak.IR.Nb-Fi.85858599.xYz.
- name: 乌克兰机场推荐httpsa0axyz3-a746eb9b
  type: ss
  server: switcher-nick-croquet.freesocks.work
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 9tqhMdIrTkgQ46PvhyAtMH
  udp: true
- name: vless-147287a7
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: vless-94ba567a
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: عضو_شو__zibanabz-e3cdfee3
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: عضو_شو__prroxyng-a9140139
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-46bef410
  - عضو_شو__zibanabz-ec2a9a38
  - vless-4eb37f84
  - net0n3_347-0c18c945
  - vless-979ff339
  - VConfing-f1189acf
  - vless-4cff1fc6
  - net0n3_352-a57f9799
  - عضو_شو__zibanabz-c9175e26
  - عضو_شو__zibanabz-68c2f25e
  - sw_vpnbot-336a4b1e
  - sw_vpnbot-b3eaee92
  - عضو_شو__zibanabz-6608f70d
  - عضو_شو__zibanabz-eeca71ca
  - V2rex_Network_حتما_داخل_چنل_عضو_بشید-57181d0d
  - عضو_شو__zibanabz-2db05ef9
  - vless-d7c1122d
  - عضو_شو__zibanabz-9534a102
  - قطع_شدی_بیا_چنل__proxygodratmand-da560d01
  - sw_vpnbot-6eefe23b
  - VConfing-fcf732d5
  - sw_vpnbot-eaea60d8
  - vless-bf1385d1
  - vless-3153da38
  - عضو_شو__zibanabz-2050b08b
  - vless-4d099640
  - عضو_شو__zibanabz-56ec6cce
  - FreeV2BoxBot-b6022cda
  - 美国机场推荐httpsa0axyz50-6dff8d27
  - عضو_شو__zibanabz-1b1b643f
  - عضو_شو__zibanabz-2c99bfec
  - عضو_شو__zibanabz-00caac21
  - telegram-788aa39d
  - 美国机场推荐httpsa0axyz63-9f0733f0
  - net0n3_348-9e6462de
  - sw_vpnbot-7b2ef93a
  - عضو_شو__zibanabz-1f26ba9f
  - V2rex_Network-af53d9a0
  - vpnv2rayNGv_سرورای_بیشتر_با_سرعت_بالا-69bbd5ae
  - vless-1b0edc4c
  - sw_vpnbot-5a335ae8
  - sw_vpnbot-8391bf27
  - 乌克兰机场推荐httpsa0axyz3-a746eb9b
  - vless-147287a7
  - vless-94ba567a
  - عضو_شو__zibanabz-e3cdfee3
  - عضو_شو__prroxyng-a9140139
- name: AUTO
  type: url-test
  proxies:
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-46bef410
  - عضو_شو__zibanabz-ec2a9a38
  - vless-4eb37f84
  - net0n3_347-0c18c945
  - vless-979ff339
  - VConfing-f1189acf
  - vless-4cff1fc6
  - net0n3_352-a57f9799
  - عضو_شو__zibanabz-c9175e26
  - عضو_شو__zibanabz-68c2f25e
  - sw_vpnbot-336a4b1e
  - sw_vpnbot-b3eaee92
  - عضو_شو__zibanabz-6608f70d
  - عضو_شو__zibanabz-eeca71ca
  - V2rex_Network_حتما_داخل_چنل_عضو_بشید-57181d0d
  - عضو_شو__zibanabz-2db05ef9
  - vless-d7c1122d
  - عضو_شو__zibanabz-9534a102
  - قطع_شدی_بیا_چنل__proxygodratmand-da560d01
  - sw_vpnbot-6eefe23b
  - VConfing-fcf732d5
  - sw_vpnbot-eaea60d8
  - vless-bf1385d1
  - vless-3153da38
  - عضو_شو__zibanabz-2050b08b
  - vless-4d099640
  - عضو_شو__zibanabz-56ec6cce
  - FreeV2BoxBot-b6022cda
  - 美国机场推荐httpsa0axyz50-6dff8d27
  - عضو_شو__zibanabz-1b1b643f
  - عضو_شو__zibanabz-2c99bfec
  - عضو_شو__zibanabz-00caac21
  - telegram-788aa39d
  - 美国机场推荐httpsa0axyz63-9f0733f0
  - net0n3_348-9e6462de
  - sw_vpnbot-7b2ef93a
  - عضو_شو__zibanabz-1f26ba9f
  - V2rex_Network-af53d9a0
  - vpnv2rayNGv_سرورای_بیشتر_با_سرعت_بالا-69bbd5ae
  - vless-1b0edc4c
  - sw_vpnbot-5a335ae8
  - sw_vpnbot-8391bf27
  - 乌克兰机场推荐httpsa0axyz3-a746eb9b
  - vless-147287a7
  - vless-94ba567a
  - عضو_شو__zibanabz-e3cdfee3
  - عضو_شو__prroxyng-a9140139
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
