port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: Sezar_sec-32d20176
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
- name: سرورهایبیشتردرکانالVPN_MMDParSa-dda47b89
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: net0n3_297-107a3e9a
  type: vless
  server: real-all3.sdcards.ir
  port: 8501
  uuid: 9666ee62-d1f3-4f6e-8881-c17fee524e31
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: OJ0wA5wp55uZdD16dutlTZvx1x-rbMMXmiO9D_MMCHI
    short-id: e701a013553059ba
- name: net0n3_294-155b48b1
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-5959b1c0
  type: vless
  server: 91.99.172.196
  port: 28041
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: WpvjPUZ5x3SIvDzSr5q9v0bfhzo36obh3CXIqJVmnkY
    short-id: 91355b9b818617
- name: vless-6a970364
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: HamrahAVAL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-c7544bf4
  type: vless
  server: 00074.mutee.com.tr
  port: 4471
  uuid: 4a283770-51a9-4de6-969c-f46bde69092d
  udp: true
  tls: false
  network: tcp
- name: vless-0ef02e83
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
- name: vless-9f02b25d
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: vless-68d8cfc4
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: net0n3_281-a905e51c
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: مشتی_جوین_بده_ناموصا__xzjinx-89db319a
  type: vless
  server: 94.182.136.184
  port: 159
  uuid: 0af94a54-f5d8-43dd-8544-77a56559ea1c
  udp: true
  tls: false
  network: tcp
- name: vless-84259603
  type: vless
  server: 300232332.webnama.com.tr
  port: 1517
  uuid: 3d554bba-9c77-499f-9055-1eb42058ed00
  udp: true
  tls: false
  network: tcp
- name: net0n3_285-ad944394
  type: vless
  server: bam.erfann.shop
  port: 15807
  uuid: 8e4d0dba-884f-4bbd-9f1d-ea5ec78efe7d
  udp: true
  tls: false
  network: tcp
- name: net0n3_287-c235c036
  type: vless
  server: compose.fast.hosting-ip.com
  port: 80
  uuid: ab80613b-e04b-4af5-bad9-9ca5c448266e
  udp: true
  tls: false
  network: xhttp
- name: Sezar_sec-4925031b
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: مشتی_جوین_بده_ناموصا__xzjinx-a0b58479
  type: ss
  server: 4.223.106.151
  port: 48172
  cipher: chacha20-ietf-poly1305
  password: 51yloQC8D9w1Wae7FHtI65
  udp: true
- name: vless-576a3ace
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 546cc913-2825-4771-b713-a23905913141
  udp: true
  tls: true
  network: ws
  servername: 638874931195949050.kish-prx-dnraaaf.info
  ws-opts:
    path: /wjwqzaws
    headers:
      Host: 638874931195949050.kish-prx-dnraaaf.info
- name: مشتی_جوین_بده_ناموصا__xzjinx-844429ee
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: e6daaeba-5a7c-4933-89b0-0078c14c50f1
  udp: true
  tls: false
  network: tcp
- name: vless-920d419d
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: nginx.nscl.ir
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_295-a261a656
  type: vless
  server: de1.cowjuice.me
  port: 443
  uuid: 955827fc-c729-4a1e-ba6c-d85754c8e937
  udp: true
  tls: false
  network: tcp
  servername: thelocal.de
  reality-opts:
    public-key: O9DMPpwicRcMofaplcvpQStNRogPS_HJY0s5_4EaKQc
    short-id: aabbccdd
- name: مشتی_جوین_بده_ناموصا__xzjinx-1fb981d4
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: 09694965-369f-48b5-82fa-40aae0236746
  udp: true
  tls: false
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-7b809746
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  tls: false
  network: tcp
- name: Sezar_Sec-6a35a408
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: vless-4c693c94
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-5354a41f
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: Sezar_Sec-eec7a43a
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  tls: false
  network: tcp
- name: Sezar_Sec-9ccb45b8
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-ce18ffd4
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-ea651e53
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-f3780651
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: net0n3_276-d0158d89
  type: ss
  server: h110vpnnl.outlinekeys.net
  port: 52571
  cipher: chacha20-ietf-poly1305
  password: 2nvtG6pl4Om1G0cWlnyXHl
  udp: true
- name: vless-be1aff61
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  tls: false
  network: tcp
- name: vless-a78f849a
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-f5b58d16
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: V2RayTheKyo_وصل_شدی_عضو_شو-8242ffc1
  type: ss
  server: 2.59.163.106
  port: 2222
  cipher: chacha20-ietf-poly1305
  password: qscavF5UviIL-8V-E4raBA
  udp: true
- name: net0n3_296-05d7d6fb
  type: vless
  server: de6.razercompany.com
  port: 33200
  uuid: c4389c70-1e5a-4bd2-934f-44fb2e62ccf5
  udp: true
  tls: false
  network: tcp
- name: V2RayTheKyo_وصل_شدی_عضو_شو-d2c2eac7
  type: vless
  server: 25.129.197.77
  port: 8880
  uuid: 40c708ca-42e4-4224-a12d-1dbd7ef1e0b7
  udp: true
  tls: false
  network: ws
  servername: Telegram-channel-WangCai2
  ws-opts:
    path: /TelegramU0001F1E8U0001F1F3 @WangCai2 /?ed
    headers:
      Host: free.cfdns.online
- name: Sezar_sec-9bbca1f5
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  tls: false
  network: tcp
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: vless-f60f23ea
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 92f481b6-ad92-43e4-a683-2bb0aeaa9846
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: dw.alibichareh.dpdns.org
- name: vpn_mmdparsa__قطع_شدی_بیا_چنل_بیا_چنل_بازم_هست-d876be68
  type: vless
  server: 142.132.227.65
  port: 14832
  uuid: a7316bc8-4169-4547-bf1b-8b5a5bfcd59a
  udp: true
  tls: false
  network: tcp
- name: vless-8d965ffd
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
- name: vless-e9757756
  type: vless
  server: 0ger.amazon-osishop.ir
  port: 8880
  uuid: 2066c2f3-bde1-429f-b083-fcfc7aee14b5
  udp: true
  tls: false
  network: tcp
- name: V2RayTheKyo_وصل_شدی_عضو_شو-56712d91
  type: vless
  server: 62.60.233.250
  port: 443
  uuid: fd0cdd44-2361-11f0-9970-45e1d80c4039
  udp: true
  tls: false
  network: tcp
  servername: images.apple.com
  reality-opts:
    public-key: MFsbnsNQsSpZwP-_Ohzako6aHpfK4-rbssxhr3eywWw
    short-id: 4476a3
- name: net0n3_300-19317839
  type: vless
  server: vpconnect.ahadbala.ir
  port: 80
  uuid: 3f0c3cef-75c0-4253-a62e-d89f5a45dcc1
  udp: true
  tls: false
  network: tcp
- name: vless-ff105a57
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-04394101
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: net0n3_289-345ec0f8
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: net0n3_290-a1ba7ead
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sub.divib.dynv6.net
- name: IRANCELL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-716b5589
  type: vless
  server: 00064.mutee.com.tr
  port: 4471
  uuid: 4a283770-51a9-4de6-969c-f46bde69092d
  udp: true
  tls: false
  network: tcp
- name: Sezar_Sec-7110fbab
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: vless-562d37ea
  type: vless
  server: www.speedtest.net
  port: 2096
  uuid: dc80ee7e-bad0-450c-a218-f12e05680885
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2096
    headers:
      Host: arm1.dollardoon.com
- name: net0n3_298-46919e22
  type: vless
  server: fastlyeeeeee.fast.hosting-ip.com
  port: 80
  uuid: cdnfastlycash
  udp: true
  tls: false
  network: xhttp
- name: net0n3_283-b5299209
  type: ss
  server: 45.87.175.165
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: QCXDxuDlTTMD7jtgHUjIoj
  udp: true
- name: vless-806ad067
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-cfe174e0
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: سرورای_بیشتر_با_پینگ_پایین_داخل_چنل__vpnv2rayNGv-ad6259dd
  type: vmess
  server: 94.182.223.8
  port: 20883
  uuid: 03b00f51-91fd-403e-9b23-1a136464b864
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: net0n3_282-beb7f5f0
  type: vless
  server: hell.dl101movis.ir
  port: 80
  uuid: d601250a-e54f-46fe-a984-fb0f1d6d48ce
  udp: true
  tls: false
  network: xhttp
- name: Sezar_Sec-5ba627de
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: vless-8069308d
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: مشتی_جوین_بده_ناموصا__xzjinx-3bfa3f58
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: b54eaa6b-d4fc-4bb3-b3c6-9d0b61da00f7
  udp: true
  tls: false
  network: tcp
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - Sezar_sec-32d20176
  - سرورهایبیشتردرکانالVPN_MMDParSa-dda47b89
  - net0n3_297-107a3e9a
  - net0n3_294-155b48b1
  - vless-5959b1c0
  - vless-6a970364
  - HamrahAVAL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-c7544bf4
  - vless-0ef02e83
  - vless-9f02b25d
  - vless-68d8cfc4
  - net0n3_281-a905e51c
  - مشتی_جوین_بده_ناموصا__xzjinx-89db319a
  - vless-84259603
  - net0n3_285-ad944394
  - net0n3_287-c235c036
  - Sezar_sec-4925031b
  - مشتی_جوین_بده_ناموصا__xzjinx-a0b58479
  - vless-576a3ace
  - مشتی_جوین_بده_ناموصا__xzjinx-844429ee
  - vless-920d419d
  - net0n3_295-a261a656
  - مشتی_جوین_بده_ناموصا__xzjinx-1fb981d4
  - مشتی_جوین_بده_ناموصا__xzjinx-7b809746
  - Sezar_Sec-6a35a408
  - vless-4c693c94
  - vless-5354a41f
  - Sezar_Sec-eec7a43a
  - Sezar_Sec-9ccb45b8
  - vless-ce18ffd4
  - vless-ea651e53
  - vless-f3780651
  - net0n3_276-d0158d89
  - vless-be1aff61
  - vless-a78f849a
  - vless-f5b58d16
  - V2RayTheKyo_وصل_شدی_عضو_شو-8242ffc1
  - net0n3_296-05d7d6fb
  - V2RayTheKyo_وصل_شدی_عضو_شو-d2c2eac7
  - Sezar_sec-9bbca1f5
  - vless-f60f23ea
  - vpn_mmdparsa__قطع_شدی_بیا_چنل_بیا_چنل_بازم_هست-d876be68
  - vless-8d965ffd
  - vless-e9757756
  - V2RayTheKyo_وصل_شدی_عضو_شو-56712d91
  - net0n3_300-19317839
  - vless-ff105a57
  - vless-04394101
  - net0n3_289-345ec0f8
  - net0n3_290-a1ba7ead
  - IRANCELL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-716b5589
  - Sezar_Sec-7110fbab
  - vless-562d37ea
  - net0n3_298-46919e22
  - net0n3_283-b5299209
  - vless-806ad067
  - vless-cfe174e0
  - سرورای_بیشتر_با_پینگ_پایین_داخل_چنل__vpnv2rayNGv-ad6259dd
  - net0n3_282-beb7f5f0
  - Sezar_Sec-5ba627de
  - vless-8069308d
  - مشتی_جوین_بده_ناموصا__xzjinx-3bfa3f58
- name: AUTO
  type: url-test
  proxies:
  - Sezar_sec-32d20176
  - سرورهایبیشتردرکانالVPN_MMDParSa-dda47b89
  - net0n3_297-107a3e9a
  - net0n3_294-155b48b1
  - vless-5959b1c0
  - vless-6a970364
  - HamrahAVAL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-c7544bf4
  - vless-0ef02e83
  - vless-9f02b25d
  - vless-68d8cfc4
  - net0n3_281-a905e51c
  - مشتی_جوین_بده_ناموصا__xzjinx-89db319a
  - vless-84259603
  - net0n3_285-ad944394
  - net0n3_287-c235c036
  - Sezar_sec-4925031b
  - مشتی_جوین_بده_ناموصا__xzjinx-a0b58479
  - vless-576a3ace
  - مشتی_جوین_بده_ناموصا__xzjinx-844429ee
  - vless-920d419d
  - net0n3_295-a261a656
  - مشتی_جوین_بده_ناموصا__xzjinx-1fb981d4
  - مشتی_جوین_بده_ناموصا__xzjinx-7b809746
  - Sezar_Sec-6a35a408
  - vless-4c693c94
  - vless-5354a41f
  - Sezar_Sec-eec7a43a
  - Sezar_Sec-9ccb45b8
  - vless-ce18ffd4
  - vless-ea651e53
  - vless-f3780651
  - net0n3_276-d0158d89
  - vless-be1aff61
  - vless-a78f849a
  - vless-f5b58d16
  - V2RayTheKyo_وصل_شدی_عضو_شو-8242ffc1
  - net0n3_296-05d7d6fb
  - V2RayTheKyo_وصل_شدی_عضو_شو-d2c2eac7
  - Sezar_sec-9bbca1f5
  - vless-f60f23ea
  - vpn_mmdparsa__قطع_شدی_بیا_چنل_بیا_چنل_بازم_هست-d876be68
  - vless-8d965ffd
  - vless-e9757756
  - V2RayTheKyo_وصل_شدی_عضو_شو-56712d91
  - net0n3_300-19317839
  - vless-ff105a57
  - vless-04394101
  - net0n3_289-345ec0f8
  - net0n3_290-a1ba7ead
  - IRANCELL__WIFI_کانفینگ_جدید_خواستی_بیا_کانال_ROFLVPN-716b5589
  - Sezar_Sec-7110fbab
  - vless-562d37ea
  - net0n3_298-46919e22
  - net0n3_283-b5299209
  - vless-806ad067
  - vless-cfe174e0
  - سرورای_بیشتر_با_پینگ_پایین_داخل_چنل__vpnv2rayNGv-ad6259dd
  - net0n3_282-beb7f5f0
  - Sezar_Sec-5ba627de
  - vless-8069308d
  - مشتی_جوین_بده_ناموصا__xzjinx-3bfa3f58
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
