mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: Mahdi2000_m_ql_2535-a242c1b8
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: NGINX.NSCl.IR
- name: Mahdi2000_m_ql_5281-c6cc8a30
  type: vless
  server: 154.92.9.151
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: simorgh.hpcode.ir
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: Mahdi2000_m_ql_5283-a2ba626d
  type: vless
  server: 154.92.9.176
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: simorgh.hpcode.ir
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed
    headers:
      Host: simorgh.hpcode.ir
- name: vless-3aab9799
  type: vless
  server: hell.dl101movis.ir
  port: 80
  uuid: d601250a-e54f-46fe-a984-fb0f1d6d48ce
  udp: true
  network: xhttp
- name: vless-9ed01d07
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  network: tcp
- name: vless-061111d5
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-9f7b3648
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_281-1e4039fa
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-0c5be179
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: nginx.nscl.ir
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_276-d511c9eb
  type: ss
  server: h110vpnnl.outlinekeys.net
  port: 52571
  cipher: chacha20-ietf-poly1305
  password: 2nvtG6pl4Om1G0cWlnyXHl
  udp: true
- name: vless-3c7e2068
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 92f481b6-ad92-43e4-a683-2bb0aeaa9846
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: dw.alibichareh.dpdns.org
- name: vless-81ba8769
  type: vless
  server: 300232332.webnama.com.tr
  port: 1517
  uuid: 3d554bba-9c77-499f-9055-1eb42058ed00
  udp: true
  network: tcp
- name: net0n3_274-c97a5181
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-c8ef9329
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-11196069
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-5831a7e0
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-1748f3c3
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-2cd17b92
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-e80d1263
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-6c8a5e98
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-abdc54bf
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: Sezar_sec-13457667
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: Sezar_sec-e88c8243
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: aes-128-gcm
  tls: true
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: Sezar_sec-ccf14adf
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
  skip-cert-verify: true
- name: Sezar_sec-62841ff8
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: aes-128-gcm
  tls: true
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: Sezar_Sec-018fda3b
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-ee45750f
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-3dc9ff4f
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-51ca69a0
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-dabbf569
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-419cf1f7
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-cd7b0397
  type: vless
  server: 94.182.136.184
  port: 159
  uuid: 0af94a54-f5d8-43dd-8544-77a56559ea1c
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-84a12ed9
  type: vless
  server: 31.47.45.173
  port: 777
  uuid: ce55d3ed-618b-45b7-d879-368fbb465efd
  udp: true
  network: tcp
- name: G0Dv2ray-946fe425
  type: vless
  server: 172.66.137.85
  port: 80
  uuid: 26bc13af-e442-4956-afd4-b8f85744d26f
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: fggerlad.gerald81.dpdns.org
- name: V2ray1_Ng-4ffb976e
  type: vless
  server: 45.131.208.130
  port: 80
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  udp: true
  network: ws
  ws-opts:
    path: Telegram@V2ray_Alpha/?ed=2560
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
- name: V2ray1_Ng-e16257ea
  type: vless
  server: 104.16.0.113
  port: 80
  uuid: bbd2882a-c158-4ae6-b53a-5ae6be8dbcb0
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560/?JOKERRVPN
    headers:
      Host: barayeiran.nastaranh.dpdns.org
- name: G0Dv2ray-720042b1
  type: vless
  server: 99823232.webnama.com.tr
  port: 1517
  uuid: 3d554bba-9c77-499f-9055-1eb42058ed00
  udp: true
  network: tcp
- name: FreeV2BoxBot-56df5c0b
  type: vless
  server: 104.19.245.206
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: FreeV2BoxBot-912f53e7
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: 80d1fe59-60f4-4272-a280-820e1ef0a754
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: pages.dev
  ws-opts:
    path: /?ed=2048
    headers:
      Host: tfs733.pages.dev
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - DIRECT
  - Mahdi2000_m_ql_2535-a242c1b8
  - Mahdi2000_m_ql_5281-c6cc8a30
  - Mahdi2000_m_ql_5283-a2ba626d
  - vless-3aab9799
  - vless-9ed01d07
  - vless-061111d5
  - vless-9f7b3648
  - net0n3_281-1e4039fa
  - vless-0c5be179
  - net0n3_276-d511c9eb
  - vless-3c7e2068
  - vless-81ba8769
  - net0n3_274-c97a5181
  - vless-c8ef9329
  - vless-11196069
  - vless-5831a7e0
  - vless-1748f3c3
  - vless-2cd17b92
  - vless-e80d1263
  - vless-6c8a5e98
  - vless-abdc54bf
  - Sezar_sec-13457667
  - Sezar_sec-e88c8243
  - Sezar_sec-ccf14adf
  - Sezar_sec-62841ff8
  - Sezar_Sec-018fda3b
  - Sezar_Sec-ee45750f
  - Sezar_Sec-3dc9ff4f
  - Sezar_Sec-51ca69a0
  - Sezar_Sec-dabbf569
  - مشتی_جوین_بده_ناموصا__xzjinx-419cf1f7
  - مشتی_جوین_بده_ناموصا__xzjinx-cd7b0397
  - مشتی_جوین_بده_ناموصا__xzjinx-84a12ed9
  - G0Dv2ray-946fe425
  - V2ray1_Ng-4ffb976e
  - V2ray1_Ng-e16257ea
  - G0Dv2ray-720042b1
  - FreeV2BoxBot-56df5c0b
  - FreeV2BoxBot-912f53e7
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - Mahdi2000_m_ql_2535-a242c1b8
  - Mahdi2000_m_ql_5281-c6cc8a30
  - Mahdi2000_m_ql_5283-a2ba626d
  - vless-3aab9799
  - vless-9ed01d07
  - vless-061111d5
  - vless-9f7b3648
  - net0n3_281-1e4039fa
  - vless-0c5be179
  - net0n3_276-d511c9eb
  - vless-3c7e2068
  - vless-81ba8769
  - net0n3_274-c97a5181
  - vless-c8ef9329
  - vless-11196069
  - vless-5831a7e0
  - vless-1748f3c3
  - vless-2cd17b92
  - vless-e80d1263
  - vless-6c8a5e98
  - vless-abdc54bf
  - Sezar_sec-13457667
  - Sezar_sec-e88c8243
  - Sezar_sec-ccf14adf
  - Sezar_sec-62841ff8
  - Sezar_Sec-018fda3b
  - Sezar_Sec-ee45750f
  - Sezar_Sec-3dc9ff4f
  - Sezar_Sec-51ca69a0
  - Sezar_Sec-dabbf569
  - مشتی_جوین_بده_ناموصا__xzjinx-419cf1f7
  - مشتی_جوین_بده_ناموصا__xzjinx-cd7b0397
  - مشتی_جوین_بده_ناموصا__xzjinx-84a12ed9
  - G0Dv2ray-946fe425
  - V2ray1_Ng-4ffb976e
  - V2ray1_Ng-e16257ea
  - G0Dv2ray-720042b1
  - FreeV2BoxBot-56df5c0b
  - FreeV2BoxBot-912f53e7
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,IR,DIRECT
- MATCH,🚀 Proxy
