proxies:
- name: vless-e94a141c
  type: vless
  server: ping.amirhossein.info
  port: 8443
  uuid: 89938a70-b39b-4255-b436-17e703cf5460
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /Telegram@Green_WPN@Vijra_dev/?ed=2560
    headers:
      Host: ping.amirhossein.info
- name: vless-eacc74b9
  type: vless
  server: 91.99.207.21
  port: 443
  uuid: 153ee04c-dcc1-4ef8-a146-8fb31cec1f48
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-b4dd066e
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: a812a015-a65b-4003-ac5f-266e141c6405
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2048
    headers:
      Host: Www.speedtest.net.developsp.ir.vegaskala.com.
- name: vless-cb3413b4
  type: vless
  server: 91.99.182.117
  port: 443
  uuid: 36ee3f5a-3816-4c03-a324-47531167e53b
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-bc86021b
  type: vless
  server: 172.66.138.99
  port: 80
  uuid: 68b48eeb-5770-4eb3-9b77-deeb77a41ccf
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2570
    headers:
      Host: varzesh3.varzesh.dpdns.org
proxy-groups:
- name: 🚀 Auto Select
  type: url-test
  proxies:
  - vless-e94a141c
  - vless-eacc74b9
  - vless-b4dd066e
  - vless-cb3413b4
  - vless-bc86021b
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 Proxy
  type: select
  proxies:
  - 🚀 Auto Select
  - DIRECT
- name: 🎯 Domestic
  type: select
  proxies:
  - DIRECT
rules:
- DOMAIN-SUFFIX,ir,🎯 Domestic
- GEOIP,IR,🎯 Domestic
- MATCH,🔮 Proxy
