port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: عضو_شو__zibanabz-37c81eeb
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: عضو_شو__prroxyng-0cc72e82
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: عضو_شو__zibanabz-26cec939
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: عضو_شو__zibanabz-5f5f9be2
  type: vless
  server: zula.ir
  port: 443
  uuid: 172ed5fd-83a6-469e-863c-50e251a6c17d
  udp: true
  tls: true
  network: ws
  servername: rayan-supra.parisa.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: rayan-supra.parisa.dpdns.org
- name: vless-27c1028a
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: IRAN_234_Outline_Vpn_free-cf8c3868
  type: vless
  server: 104.19.245.206
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: IRAN_237_Outline_Vpn_free-f1675604
  type: ss
  server: war.ssvpnapp.win
  port: 57456
  cipher: chacha20-ietf-poly1305
  password: d3837224ed465f00
  udp: true
- name: vless-49b3cb52
  type: vless
  server: s3.esrtz.onl
  port: 46470
  uuid: 3bcc6dbf-0ab4-4674-85c8-39bd994434f9
  udp: true
  tls: false
  network: tcp
- name: vless-d0a973b5
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: xhttp
- name: عضو_شو__zibanabz-2051dc21
  type: vless
  server: 104.16.104.151
  port: 80
  uuid: 1f431db3-1918-4e7b-a855-c93485e11694
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: pari.parinazz.dpdns.org
- name: net0n3_348-c6d16d2d
  type: ss
  server: 45.87.175.183
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
- name: sw_vpnbot-08b3a66a
  type: vless
  server: 104.26.13.54
  port: 80
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@AZADIIIVPN/?ed=2560
    headers:
      Host: REEdfREe8MahSaNg2.rEDOrG.IR
- name: عضو_شو__zibanabz-4f9742b6
  type: vless
  server: 172.67.128.105
  port: 80
  uuid: 4179c595-08ca-45cd-b555-91b6f1faeadc
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: di.dibdibini.dpdns.org
- name: عضو_شو__zibanabz-693bfbdf
  type: vless
  server: 172.67.49.134
  port: 443
  uuid: 06e4425e-a8cb-4b63-929f-2105604ab0a9
  udp: true
  tls: true
  network: ws
  servername: rc.ylks0033.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: rc.ylks0033.dpdns.org
- name: sw_vpnbot-eb8438ba
  type: vless
  server: 45.131.211.135
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: '/Channel id: @AZADIIIVPN?ed=2560'
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: sw_vpnbot-14e5cb1d
  type: vless
  server: 185.148.106.242
  port: 80
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: 'Telegram🇮🇷Channel id: @AZADIIIVPN /?ed=2560'
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: عضو_شو__zibanabz-47c5b514
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: IRAN_236_Outline_Vpn_free-70951186
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: vless-246f19fe
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: V2rayNGFreeeV2rayNGFreee
  udp: true
  tls: false
  network: xhttp
- name: عضو_شو__zibanabz-0adc73ca
  type: vless
  server: 147.185.161.229
  port: 80
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: Telegram:@ShadowProxy66/?ed=2560
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
- name: عضو_شو__zibanabz-d39502f0
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: net0n3_347-3e4e7c56
  type: ss
  server: 193.228.139.250
  port: 1080
  cipher: chacha20-ietf-poly1305
  password: yrZtUElGhL8xfeaN0hIIzQ
  udp: true
- name: عضو_شو__zibanabz-043c16ec
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: sw_vpnbot-3437a406
  type: vless
  server: www.speedtest.net
  port: 2095
  uuid: 49f10318-3e61-462b-b57d-0bfa25b77d94
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /hajmi?ed=2050/?AZADIIIVPNBIA_CHANEL@AZADIIIVPN
    headers:
      Host: dbe661d5a761ff6c.s-5HU09JDF-97SHS.WWWrubika.irto.xn--ls8haaaaaaaaaaaaaaaaaa.la.which.xn--ls8haaaaaaaaaaaaaaaaaa.xn-ls8faaaaaaaaaa.speedtest.net.google.com.eu.ir.nl.aparat.com.komak.IR.Nb-De.85858599.xYz.
- name: sw_vpnbot-37bd8d87
  type: vless
  server: 45.80.111.147
  port: 80
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@AZADIIIVPN/?ed=2560
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: عضو_شو__zibanabz-9973f4fb
  type: vless
  server: 172.67.67.92
  port: 80
  uuid: f78ce1bb-0fa6-4ef4-b4c9-b91014a7055d
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: delam.ahaysiahzangi.dpdns.org
- name: sw_vpnbot-b08ecc99
  type: vless
  server: www.speedtest.net
  port: 2095
  uuid: 49f10318-3e61-462b-b57d-0bfa25b77d94
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /hajmi?*aiojefoijeafiojaoifjoaijfoieajfea4502542---452525252525082850924520759275942592429465265926359832oiejfiaoiefoieaioaeoifiofeaiofeiofeoijeoijfaeoifja7773422834798732498327498huafuawugfuayufu476942652?ed=2050/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: dbe661d5a761ff6c.s-5HU09JDF-97SHS.WWWrubika.irto.xn--ls8haaaaaaaaaaaaaaaaaa.la.which.xn--ls8haaaaaaaaaaaaaaaaaa.xn-ls8faaaaaaaaaa.speedtest.net.google.com.eu.ir.nl.aparat.com.komak.IR.Nb-Fi.85858599.xYz.
- name: FreeV2BoxBot-0105c8de
  type: vmess
  server: bluevpn2.bibak.bz
  port: 3030
  uuid: 20c86f6d-4e65-4477-93e6-4b11cf1fd09d
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: عضو_شو__zibanabz-06612b07
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: vless-fadd1e30
  type: vless
  server: russiatest-tap.servers807.ir
  port: 13796
  uuid: b646e0d6-137b-49e1-90bc-3b9ad8a6484a
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: AIUUKeq08usIla0uv-NTp5wVe4TMb3VkXWDLoutlFnM
    short-id: a3ac
- name: یدونهvipدیگهدرچنلمهستجویینشوبردار-99e799a9
  type: vless
  server: 188.227.84.171
  port: 8443
  uuid: 9418d05f-4943-4c50-8ced-d1df192daedf
  udp: true
  tls: false
  network: tcp
- name: vless-0cca0700
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: vless-ac46b4a5
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: sw_vpnbot-edec0c7f
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /Telegram@AZADIIIVPN/?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: net0n3_352-29a4f9d9
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: VConfing-6032b1d6
  type: vmess
  server: 103.249.133.8
  port: 53921
  uuid: f33a9661-d7a2-4f28-9170-c844c47916a0
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-e309fa92
  type: vless
  server: all97-vip.f-sub.com
  port: 1517
  uuid: 240052ac-0bf0-481f-adb4-f40a259fc189
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-2db6ba46
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: IRAN_235_Outline_Vpn_free-e45439a4
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: قطع_شدی_بیا_چنل__proxygodratmand-9029a7e5
  type: vless
  server: world1.royalping.org
  port: 44283
  uuid: 310dffcd-5f4b-43eb-ba9b-6d74eab01a40
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-b5b6134e
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - عضو_شو__zibanabz-37c81eeb
  - عضو_شو__prroxyng-0cc72e82
  - عضو_شو__zibanabz-26cec939
  - عضو_شو__zibanabz-5f5f9be2
  - vless-27c1028a
  - IRAN_234_Outline_Vpn_free-cf8c3868
  - IRAN_237_Outline_Vpn_free-f1675604
  - vless-49b3cb52
  - vless-d0a973b5
  - عضو_شو__zibanabz-2051dc21
  - net0n3_348-c6d16d2d
  - sw_vpnbot-08b3a66a
  - عضو_شو__zibanabz-4f9742b6
  - عضو_شو__zibanabz-693bfbdf
  - sw_vpnbot-eb8438ba
  - sw_vpnbot-14e5cb1d
  - عضو_شو__zibanabz-47c5b514
  - IRAN_236_Outline_Vpn_free-70951186
  - vless-246f19fe
  - عضو_شو__zibanabz-0adc73ca
  - عضو_شو__zibanabz-d39502f0
  - net0n3_347-3e4e7c56
  - عضو_شو__zibanabz-043c16ec
  - sw_vpnbot-3437a406
  - sw_vpnbot-37bd8d87
  - عضو_شو__zibanabz-9973f4fb
  - sw_vpnbot-b08ecc99
  - FreeV2BoxBot-0105c8de
  - عضو_شو__zibanabz-06612b07
  - vless-fadd1e30
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-99e799a9
  - vless-0cca0700
  - vless-ac46b4a5
  - sw_vpnbot-edec0c7f
  - net0n3_352-29a4f9d9
  - VConfing-6032b1d6
  - vless-e309fa92
  - عضو_شو__zibanabz-2db6ba46
  - IRAN_235_Outline_Vpn_free-e45439a4
  - قطع_شدی_بیا_چنل__proxygodratmand-9029a7e5
  - عضو_شو__zibanabz-b5b6134e
- name: AUTO
  type: url-test
  proxies:
  - عضو_شو__zibanabz-37c81eeb
  - عضو_شو__prroxyng-0cc72e82
  - عضو_شو__zibanabz-26cec939
  - عضو_شو__zibanabz-5f5f9be2
  - vless-27c1028a
  - IRAN_234_Outline_Vpn_free-cf8c3868
  - IRAN_237_Outline_Vpn_free-f1675604
  - vless-49b3cb52
  - vless-d0a973b5
  - عضو_شو__zibanabz-2051dc21
  - net0n3_348-c6d16d2d
  - sw_vpnbot-08b3a66a
  - عضو_شو__zibanabz-4f9742b6
  - عضو_شو__zibanabz-693bfbdf
  - sw_vpnbot-eb8438ba
  - sw_vpnbot-14e5cb1d
  - عضو_شو__zibanabz-47c5b514
  - IRAN_236_Outline_Vpn_free-70951186
  - vless-246f19fe
  - عضو_شو__zibanabz-0adc73ca
  - عضو_شو__zibanabz-d39502f0
  - net0n3_347-3e4e7c56
  - عضو_شو__zibanabz-043c16ec
  - sw_vpnbot-3437a406
  - sw_vpnbot-37bd8d87
  - عضو_شو__zibanabz-9973f4fb
  - sw_vpnbot-b08ecc99
  - FreeV2BoxBot-0105c8de
  - عضو_شو__zibanabz-06612b07
  - vless-fadd1e30
  - یدونهvipدیگهدرچنلمهستجویینشوبردار-99e799a9
  - vless-0cca0700
  - vless-ac46b4a5
  - sw_vpnbot-edec0c7f
  - net0n3_352-29a4f9d9
  - VConfing-6032b1d6
  - vless-e309fa92
  - عضو_شو__zibanabz-2db6ba46
  - IRAN_235_Outline_Vpn_free-e45439a4
  - قطع_شدی_بیا_چنل__proxygodratmand-9029a7e5
  - عضو_شو__zibanabz-b5b6134e
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
