mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-bb15615c
  type: vless
  server: 91.99.160.151
  port: 443
  uuid: 153ee04c-dcc1-4ef8-a146-8fb31cec1f48
  udp: true
  network: tcp
- name: vless-d830b4a1
  type: vless
  server: 62.60.223.6
  port: 2080
  uuid: bea34b73-3244-475b-b914-7bb80e1cda91
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: L3lJWdU7mHijSkNaNt-m29OYnKnHvHYRxg2Y8XXFdng
    short-id: bf517367267685
- name: vless-f20978bb
  type: vless
  server: 91.99.195.6
  port: 80
  uuid: 91a5d5b3-4b88-4359-aeec-e1532f535fd6
  udp: true
  network: grpc
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZO276Z5WXIqCmNLXT8Lewzjhhgm365JUJXAKyKq8Rz4
    short-id: bc063769cb
  grpc-opts:
    grpc-service-name: refersion.com
- name: vless-0103e89c
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /zula.ir
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: vless-5ead97b9
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-0655f066
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-24b02023
  type: vless
  server: 91.99.184.231
  port: 45103
  uuid: 6bdc18b7-a33f-46ae-a5e3-df7cb21f36b2
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: vless-c28ae655
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: turboo-server
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: turboo-server1.game
- name: V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-9271dc4b
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 148709e4-402b-48dd-8892-ed39b55ea45c
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560/?@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-@V2WRAY-
    headers:
      Host: barayeiranmahsang.loseyourself.dpdns.org
- name: مشتی_جوین_بده_ناموصا__xzjinx-fffbdffa
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: f7255d17-4abc-4c54-84dd-e1e9e9c41dad
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-55723125
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: 395bf21d-ea83-4d85-ad04-ad1f6b1431bf
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: مشتی_جوین_بده_ناموصا__xzjinx-939dbfeb
  type: vmess
  server: ddns1.rghstore.ir
  port: 8080
  uuid: 395bf21d-ea83-4d85-ad04-ad1f6b1431bf
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /rgh
    headers:
      Host: Telewebion.com
- name: pl-v2rayipracevpncom-mpt85hc6-4d310e31
  type: vmess
  server: pl-v2ray.ipracevpn.com
  port: 2083
  uuid: 1ee06e46-332d-46ed-8ff1-c0a04c47d25a
  alterId: 0
  cipher: aes-128-gcm
  tls: true
  skip-cert-verify: false
  network: tcp
  udp: true
- name: pl-v2rayipracevpncom-mpt85hc6-fcabd126
  type: vmess
  server: pl-v2ray.ipracevpn.com
  port: 2083
  uuid: 1ee06e46-332d-46ed-8ff1-c0a04c47d25a
  alterId: 0
  cipher: aes-128-gcm
  tls: true
  skip-cert-verify: false
  network: tcp
  udp: true
- name: 𝟭__amirelftestvpn18-c6fb07cd
  type: vless
  server: mtn.venzo.com.tr
  port: 80
  uuid: be0d237d-9b3a-4217-a88a-7b6f0d818a72
  udp: true
  network: httpupgrade
- name: FG_Link-c5e3163c
  type: vless
  server: add.ski1plag.ir
  port: 80
  uuid: 7c9e3c1d-a360-4429-9189-e45a98de7fde
  udp: true
  network: ws
  ws-opts:
    path: /download
    headers:
      Host: my.ski1plag.ir
- name: FG_Link-095a6227
  type: vless
  server: add.ski1plag.ir
  port: 80
  uuid: 7c9e3c1d-a360-4429-9189-e45a98de7fde
  udp: true
  network: ws
  ws-opts:
    path: /upload
    headers:
      Host: my.ski1plag.ir
- name: vless-7ada3360
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-1eb811cd
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-417356ec
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-55496a92
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-4968c175
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-92330ccd
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-26eed238
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-b8055501
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-cf13c7d4
  type: vless
  server: accounting.vinamarketcenter.ir
  port: 443
  uuid: 5cfba4ac-105a-452a-ac10-88b1adf784ee
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: T7Cwk-B3EvZqqRywIgN_TNotJiUOXYUI9bHqYKPnTi0
    short-id: 105e89ba3d2a1c3b
- name: مشتی_جوین_بده_ناموصا__xzjinx-b2d39eb1
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: 49203d20-5f1b-4628-d526-9a6825c3f5f3
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-dce96f99
  type: vless
  server: 5.160.197.120
  port: 16644
  uuid: c2d3a355-e556-40e0-cd5a-41dff6eb525d
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-ac269513
  type: vless
  server: 91.107.144.102
  port: 443
  uuid: edf3ab50-46b4-4046-eaf9-db12fe598cd1
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-e88048a2
  type: vless
  server: chrom3.infospeedtest.com
  port: 13096
  uuid: bb497033-e322-4316-ce08-b8a9716b6a3d
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-ff58f585
  type: vless
  server: esi.infospeedtest.com
  port: 13286
  uuid: 2ee55469-d026-410b-f4bc-844a63a1342d
  udp: true
  network: tcp
- name: Sezar_Sec-0b79f426
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-119fde2a
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-ae2ce1ee
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: Sezar_Sec-4919a325
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: Sezar_Sec-4dba5ad6
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: barayeiranmahsang.sabzipolobamahi.dpdns.org
  ws-opts:
    path: /?ed=2560/?CHANEL@RK_VPS@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-bb15615c
  - vless-d830b4a1
  - vless-f20978bb
  - vless-0103e89c
  - vless-5ead97b9
  - vless-0655f066
  - vless-24b02023
  - vless-c28ae655
  - V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-9271dc4b
  - مشتی_جوین_بده_ناموصا__xzjinx-fffbdffa
  - مشتی_جوین_بده_ناموصا__xzjinx-55723125
  - مشتی_جوین_بده_ناموصا__xzjinx-939dbfeb
  - pl-v2rayipracevpncom-mpt85hc6-4d310e31
  - pl-v2rayipracevpncom-mpt85hc6-fcabd126
  - 𝟭__amirelftestvpn18-c6fb07cd
  - FG_Link-c5e3163c
  - FG_Link-095a6227
  - vless-7ada3360
  - vless-1eb811cd
  - vless-417356ec
  - vless-55496a92
  - vless-4968c175
  - vless-92330ccd
  - vless-26eed238
  - vless-b8055501
  - vless-cf13c7d4
  - مشتی_جوین_بده_ناموصا__xzjinx-b2d39eb1
  - مشتیجوینبدهناموصاxzjinx-dce96f99
  - مشتیجوینبدهناموصاxzjinx-ac269513
  - مشتیجوینبدهناموصاxzjinx-e88048a2
  - مشتی_جوین_بده_ناموصا__xzjinx-ff58f585
  - Sezar_Sec-0b79f426
  - Sezar_Sec-119fde2a
  - Sezar_Sec-ae2ce1ee
  - Sezar_Sec-4919a325
  - Sezar_Sec-4dba5ad6
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
