mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 8.8.8.8
  - 1.1.1.1
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
proxies:
- name: vless-aebadb3f
  type: vless
  server: hell.dl101movis.ir
  port: 80
  uuid: d601250a-e54f-46fe-a984-fb0f1d6d48ce
  udp: true
  network: xhttp
- name: vless-ca7125ce
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  network: tcp
- name: vless-61f0e44f
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  servername: NGINX.NSCl.IR
  skip-cert-verify: true
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-ea349724
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  servername: NGINX.NSCl.IR
  skip-cert-verify: true
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_281-099a99d7
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-b7459d54
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  servername: nginx.nscl.ir
  skip-cert-verify: true
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_276-28a7587c
  type: ss
  server: h110vpnnl.outlinekeys.net
  port: 52571
  cipher: chacha20-ietf-poly1305
  password: 2nvtG6pl4Om1G0cWlnyXHl
  udp: true
- name: vless-016246ec
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 92f481b6-ad92-43e4-a683-2bb0aeaa9846
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: dw.alibichareh.dpdns.org
- name: vless-73faa525
  type: vless
  server: 300232332.webnama.com.tr
  port: 1517
  uuid: 3d554bba-9c77-499f-9055-1eb42058ed00
  udp: true
  network: tcp
- name: net0n3_274-3fe8ddf5
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-80833367
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-c63492bb
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-cc5b4fda
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-a1c6a804
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-f8d9af24
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-405dede2
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-de212e2b
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-26daf97a
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: مشتی_جوین_بده_ناموصا__xzjinx-81fe6911
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-0d37ab43
  type: vless
  server: 94.182.136.184
  port: 159
  uuid: 0af94a54-f5d8-43dd-8544-77a56559ea1c
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-c3e81464
  type: vless
  server: 31.47.45.173
  port: 777
  uuid: ce55d3ed-618b-45b7-d879-368fbb465efd
  udp: true
  network: tcp
- name: parsproxy_ir-4bbc2ad0
  type: vless
  server: test.fast.hosting-ip.com
  port: 80
  uuid: 0c594034-4210-49c0-99ab-b52ec0df0f6c
  udp: true
  network: xhttp
- name: D986DB8CD98520D8B3D8A7D8B9D8AA20D8AFDB8CDAAFD98720D982D8B7D8B920D985DB8CDAA9D986D98520D982D8B7D8B920D8B4D8AFDB8C20D8A8DB8CD8A720DA86D986D98420proxygodratmand40-0d766136
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  servername: sub.divib.dynv6.net
  skip-cert-verify: true
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Mahdi2000_m_ql_2535-b5ec666c
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  servername: NGINX.NSCl.IR
  skip-cert-verify: true
  ws-opts:
    path: /assets
    headers:
      Host: NGINX.NSCl.IR
- name: Sezar_sec-3104adfd
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
    fingerprint: chrome
- name: Sezar_sec-fffa0469
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: Sezar_sec-06be3b9b
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
  skip-cert-verify: true
- name: Sezar_sec-d66b8780
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: Sezar_Sec-e1d60e27
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
  skip-cert-verify: true
- name: Sezar_Sec-bd29b2ce
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
  skip-cert-verify: true
- name: Sezar_Sec-c7cc5747
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  servername: NGINX.NSCl.IR
  skip-cert-verify: true
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-8cbd6046
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  servername: sub.divib.dynv6.net
  skip-cert-verify: true
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-cbac7ae2
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: Sezar_Sec-c913a273
  type: ss
  server: 92.63.193.243
  port: 20
  cipher: aes-256-gcm
  password: 1KssbuTybQDBYgDju5nNSg
  udp: true
- name: G0Dv2ray-66e0aee1
  type: vless
  server: 172.66.137.85
  port: 80
  uuid: 26bc13af-e442-4956-afd4-b8f85744d26f
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: fggerlad.gerald81.dpdns.org
- name: V2ray1_Ng-40afbe7f
  type: vless
  server: 45.131.208.130
  port: 80
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  udp: true
  network: ws
  ws-opts:
    path: Telegram@V2ray_Alpha/?ed=2560
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
- name: V2ray1_Ng-c8488203
  type: vless
  server: 104.16.0.113
  port: 80
  uuid: bbd2882a-c158-4ae6-b53a-5ae6be8dbcb0
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560/?JOKERRVPN
    headers:
      Host: barayeiran.nastaranh.dpdns.org
- name: G0Dv2ray-821577f3
  type: vless
  server: 99823232.webnama.com.tr
  port: 1517
  uuid: 3d554bba-9c77-499f-9055-1eb42058ed00
  udp: true
  network: tcp
- name: FreeV2BoxBot-3f929a1f
  type: vless
  server: 104.19.245.206
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  network: ws
  tls: true
  servername: kawaiifreevpn-7ds.pages.dev
  skip-cert-verify: true
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: FreeV2BoxBot-bb306326
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: 80d1fe59-60f4-4272-a280-820e1ef0a754
  udp: true
  network: ws
  tls: true
  servername: pages.dev
  skip-cert-verify: true
  ws-opts:
    path: /?ed=2048
    headers:
      Host: tfs733.pages.dev
proxy-groups:
- name: 🚀 PROXY
  type: select
  proxies:
  - ♻️ AUTO
  - DIRECT
  - vless-aebadb3f
  - vless-ca7125ce
  - vless-61f0e44f
  - vless-ea349724
  - net0n3_281-099a99d7
  - vless-b7459d54
  - net0n3_276-28a7587c
  - vless-016246ec
  - vless-73faa525
  - net0n3_274-3fe8ddf5
  - vless-80833367
  - vless-c63492bb
  - vless-cc5b4fda
  - vless-a1c6a804
  - vless-f8d9af24
  - vless-405dede2
  - vless-de212e2b
  - vless-26daf97a
  - مشتی_جوین_بده_ناموصا__xzjinx-81fe6911
  - مشتی_جوین_بده_ناموصا__xzjinx-0d37ab43
  - مشتی_جوین_بده_ناموصا__xzjinx-c3e81464
  - parsproxy_ir-4bbc2ad0
  - D986DB8CD98520D8B3D8A7D8B9D8AA20D8AFDB8CDAAFD98720D982D8B7D8B920D985DB8CDAA9D986D98520D982D8B7D8B920D8B4D8AFDB8C20D8A8DB8CD8A720DA86D986D98420proxygodratmand40-0d766136
  - Mahdi2000_m_ql_2535-b5ec666c
  - Sezar_sec-3104adfd
  - Sezar_sec-fffa0469
  - Sezar_sec-06be3b9b
  - Sezar_sec-d66b8780
  - Sezar_Sec-e1d60e27
  - Sezar_Sec-bd29b2ce
  - Sezar_Sec-c7cc5747
  - Sezar_Sec-8cbd6046
  - Sezar_Sec-cbac7ae2
  - Sezar_Sec-c913a273
  - G0Dv2ray-66e0aee1
  - V2ray1_Ng-40afbe7f
  - V2ray1_Ng-c8488203
  - G0Dv2ray-821577f3
  - FreeV2BoxBot-3f929a1f
  - FreeV2BoxBot-bb306326
- name: ♻️ AUTO
  type: url-test
  proxies:
  - vless-aebadb3f
  - vless-ca7125ce
  - vless-61f0e44f
  - vless-ea349724
  - net0n3_281-099a99d7
  - vless-b7459d54
  - net0n3_276-28a7587c
  - vless-016246ec
  - vless-73faa525
  - net0n3_274-3fe8ddf5
  - vless-80833367
  - vless-c63492bb
  - vless-cc5b4fda
  - vless-a1c6a804
  - vless-f8d9af24
  - vless-405dede2
  - vless-de212e2b
  - vless-26daf97a
  - مشتی_جوین_بده_ناموصا__xzjinx-81fe6911
  - مشتی_جوین_بده_ناموصا__xzjinx-0d37ab43
  - مشتی_جوین_بده_ناموصا__xzjinx-c3e81464
  - parsproxy_ir-4bbc2ad0
  - D986DB8CD98520D8B3D8A7D8B9D8AA20D8AFDB8CDAAFD98720D982D8B7D8B920D985DB8CDAA9D986D98520D982D8B7D8B920D8B4D8AFDB8C20D8A8DB8CD8A720DA86D986D98420proxygodratmand40-0d766136
  - Mahdi2000_m_ql_2535-b5ec666c
  - Sezar_sec-3104adfd
  - Sezar_sec-fffa0469
  - Sezar_sec-06be3b9b
  - Sezar_sec-d66b8780
  - Sezar_Sec-e1d60e27
  - Sezar_Sec-bd29b2ce
  - Sezar_Sec-c7cc5747
  - Sezar_Sec-8cbd6046
  - Sezar_Sec-cbac7ae2
  - Sezar_Sec-c913a273
  - G0Dv2ray-66e0aee1
  - V2ray1_Ng-40afbe7f
  - V2ray1_Ng-c8488203
  - G0Dv2ray-821577f3
  - FreeV2BoxBot-3f929a1f
  - FreeV2BoxBot-bb306326
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- GEOIP,IR,DIRECT
- MATCH,🚀 PROXY
