port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: Sezar_sec-f97460a4
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  tls: false
  network: tcp
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: vless-7a2454e8
  type: vless
  server: vpconnect.ahadbala.ir
  port: 80
  uuid: 3f0c3cef-75c0-4253-a62e-d89f5a45dcc1
  udp: true
  tls: false
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-0b87c3c6
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: 09694965-369f-48b5-82fa-40aae0236746
  udp: true
  tls: false
  network: tcp
- name: Sezar_sec-c5326daf
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
- name: vless-a316e238
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: Sezar_Sec-152540db
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  tls: false
  network: tcp
- name: vless-2aab6b6a
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sub.divib.dynv6.net
- name: vless-db7a6aa9
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: مشتی_جوین_بده_ناموصا__xzjinx-86fb9027
  type: vless
  server: 31.47.45.173
  port: 777
  uuid: ce55d3ed-618b-45b7-d879-368fbb465efd
  udp: true
  tls: false
  network: tcp
- name: vless-384eb038
  type: vless
  server: real-all3.sdcards.ir
  port: 8501
  uuid: 9666ee62-d1f3-4f6e-8881-c17fee524e31
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: OJ0wA5wp55uZdD16dutlTZvx1x-rbMMXmiO9D_MMCHI
    short-id: e701a013553059ba
- name: vless-ddd7a021
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: Sezar_Sec-279f80a6
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: ByaToBad_boyx_x666-96f61a51
  type: vless
  server: 5.10.214.123
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@server_free2/?ed=2560
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-484c1213
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: 80d1fe59-60f4-4272-a280-820e1ef0a754
  udp: true
  tls: true
  network: ws
  servername: pages.dev
  ws-opts:
    path: /Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray---Telegram-XV2ray?ed=2048
    headers:
      Host: tfs733.pages.dev
- name: Sezar_sec-c9850293
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: vless-1f8ef9b9
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: nginx.nscl.ir
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-2e980256
  type: vless
  server: bam.erfann.shop
  port: 15807
  uuid: 8e4d0dba-884f-4bbd-9f1d-ea5ec78efe7d
  udp: true
  tls: false
  network: tcp
- name: vless-a9acbf75
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-935f23da
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: vless-bd7507c6
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  tls: false
  network: tcp
- name: vless-d44f9c81
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-cb312186
  type: vless
  server: de6.razercompany.com
  port: 33200
  uuid: c4389c70-1e5a-4bd2-934f-44fb2e62ccf5
  udp: true
  tls: false
  network: tcp
- name: vless-1e2e7c6d
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-ff291566
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-b9d84725
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-4576a7ec
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-253477f6
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: vless-f1c34709
  type: vless
  server: fastlyeeeeee.fast.hosting-ip.com
  port: 80
  uuid: cdnfastlycash
  udp: true
  tls: false
  network: xhttp
- name: vless-7e3327de
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: Sezar_Sec-e9c28611
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: vless-27a05d78
  type: vless
  server: de1.cowjuice.me
  port: 443
  uuid: 955827fc-c729-4a1e-ba6c-d85754c8e937
  udp: true
  tls: false
  network: tcp
  servername: thelocal.de
  reality-opts:
    public-key: O9DMPpwicRcMofaplcvpQStNRogPS_HJY0s5_4EaKQc
    short-id: aabbccdd
- name: مشتی_جوین_بده_ناموصا__xzjinx-f8d37f8f
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: b54eaa6b-d4fc-4bb3-b3c6-9d0b61da00f7
  udp: true
  tls: false
  network: tcp
- name: vless-c8adb7b9
  type: vless
  server: compose.fast.hosting-ip.com
  port: 80
  uuid: ab80613b-e04b-4af5-bad9-9ca5c448266e
  udp: true
  tls: false
  network: xhttp
- name: مشتی_جوین_بده_ناموصا__xzjinx-701cf467
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: e6daaeba-5a7c-4933-89b0-0078c14c50f1
  udp: true
  tls: false
  network: tcp
- name: vless-20fbe4c3
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: vless-d82b78ec
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: Sezar_Sec-5bd8b7c4
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-22c5116e
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: مشتی_جوین_بده_ناموصا__xzjinx-ffe9904d
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  tls: false
  network: tcp
- name: net0n3_283-de6f811d
  type: ss
  server: 45.87.175.165
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: QCXDxuDlTTMD7jtgHUjIoj
  udp: true
- name: vless-f83f3d96
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: vless-6da8debc
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-bb76df72
  type: vless
  server: 91.99.172.196
  port: 28041
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: WpvjPUZ5x3SIvDzSr5q9v0bfhzo36obh3CXIqJVmnkY
    short-id: 91355b9b818617
- name: مشتی_جوین_بده_ناموصا__xzjinx-9ebb701d
  type: vless
  server: 94.182.136.184
  port: 159
  uuid: 0af94a54-f5d8-43dd-8544-77a56559ea1c
  udp: true
  tls: false
  network: tcp
- name: vless-de2e4e8d
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-37162c73
  type: vless
  server: hell.dl101movis.ir
  port: 80
  uuid: d601250a-e54f-46fe-a984-fb0f1d6d48ce
  udp: true
  tls: false
  network: xhttp
- name: net0n3_281-b11fe79e
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - Sezar_sec-f97460a4
  - vless-7a2454e8
  - مشتی_جوین_بده_ناموصا__xzjinx-0b87c3c6
  - Sezar_sec-c5326daf
  - vless-a316e238
  - Sezar_Sec-152540db
  - vless-2aab6b6a
  - vless-db7a6aa9
  - مشتی_جوین_بده_ناموصا__xzjinx-86fb9027
  - vless-384eb038
  - vless-ddd7a021
  - Sezar_Sec-279f80a6
  - ByaToBad_boyx_x666-96f61a51
  - قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-484c1213
  - Sezar_sec-c9850293
  - vless-1f8ef9b9
  - vless-2e980256
  - vless-a9acbf75
  - Sezar_Sec-935f23da
  - vless-bd7507c6
  - vless-d44f9c81
  - vless-cb312186
  - vless-1e2e7c6d
  - vless-ff291566
  - vless-b9d84725
  - vless-4576a7ec
  - vless-253477f6
  - vless-f1c34709
  - vless-7e3327de
  - Sezar_Sec-e9c28611
  - vless-27a05d78
  - مشتی_جوین_بده_ناموصا__xzjinx-f8d37f8f
  - vless-c8adb7b9
  - مشتی_جوین_بده_ناموصا__xzjinx-701cf467
  - vless-20fbe4c3
  - vless-d82b78ec
  - Sezar_Sec-5bd8b7c4
  - vless-22c5116e
  - مشتی_جوین_بده_ناموصا__xzjinx-ffe9904d
  - net0n3_283-de6f811d
  - vless-f83f3d96
  - vless-6da8debc
  - vless-bb76df72
  - مشتی_جوین_بده_ناموصا__xzjinx-9ebb701d
  - vless-de2e4e8d
  - vless-37162c73
  - net0n3_281-b11fe79e
- name: AUTO
  type: url-test
  proxies:
  - Sezar_sec-f97460a4
  - vless-7a2454e8
  - مشتی_جوین_بده_ناموصا__xzjinx-0b87c3c6
  - Sezar_sec-c5326daf
  - vless-a316e238
  - Sezar_Sec-152540db
  - vless-2aab6b6a
  - vless-db7a6aa9
  - مشتی_جوین_بده_ناموصا__xzjinx-86fb9027
  - vless-384eb038
  - vless-ddd7a021
  - Sezar_Sec-279f80a6
  - ByaToBad_boyx_x666-96f61a51
  - قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-484c1213
  - Sezar_sec-c9850293
  - vless-1f8ef9b9
  - vless-2e980256
  - vless-a9acbf75
  - Sezar_Sec-935f23da
  - vless-bd7507c6
  - vless-d44f9c81
  - vless-cb312186
  - vless-1e2e7c6d
  - vless-ff291566
  - vless-b9d84725
  - vless-4576a7ec
  - vless-253477f6
  - vless-f1c34709
  - vless-7e3327de
  - Sezar_Sec-e9c28611
  - vless-27a05d78
  - مشتی_جوین_بده_ناموصا__xzjinx-f8d37f8f
  - vless-c8adb7b9
  - مشتی_جوین_بده_ناموصا__xzjinx-701cf467
  - vless-20fbe4c3
  - vless-d82b78ec
  - Sezar_Sec-5bd8b7c4
  - vless-22c5116e
  - مشتی_جوین_بده_ناموصا__xzjinx-ffe9904d
  - net0n3_283-de6f811d
  - vless-f83f3d96
  - vless-6da8debc
  - vless-bb76df72
  - مشتی_جوین_بده_ناموصا__xzjinx-9ebb701d
  - vless-de2e4e8d
  - vless-37162c73
  - net0n3_281-b11fe79e
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
