port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: By_EbraSha_vless-GB-d103ed0b
  type: vless
  server: 54.36.162.84
  port: 8880
  uuid: 9beca423-b31d-496d-aee6-a1ab64f0bd81
  udp: true
  tls: false
  network: tcp
  servername: google.com
  reality-opts:
    public-key: Fa_dYaQoLgLjsk1jvSQcEKRNnAvMVJF4Br7YG5FT6zo
    short-id: 1e4072
- name: vless-3daa0812
  type: vless
  server: bot.nimeshab-nabod.info
  port: 80
  uuid: itsproxy
  udp: true
  tls: false
  network: xhttp
- name: Telegramvmessorg-7394bc27
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: net0n3_354-3435eddb
  type: vless
  server: david2.lemoex.blog
  port: 443
  uuid: 737c9e58-379d-4654-9471-d60494b326bd
  udp: true
  tls: true
  network: httpupgrade
  servername: david2.lemoex.blog
- name: عضو_شو__zibanabz-1a0560f1
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: VConfing-018c600c
  type: vmess
  server: gift.dl3movies.ir
  port: 8443
  uuid: 6d13e5e4-7589-4819-b92f-982ee89edcab
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  udp: true
  ws-opts:
    path: ''
    headers:
      Host: ''
- name: Telegramvmessorg-664be3ad
  type: ss
  server: series-a2-mec.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: عضو_شو__zibanabz-f097ff32
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: net0n3_356-b789446d
  type: vless
  server: 93.123.39.31
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: net0n3_347-4311bab3
  type: ss
  server: 193.228.139.250
  port: 1080
  cipher: chacha20-ietf-poly1305
  password: yrZtUElGhL8xfeaN0hIIzQ
  udp: true
- name: V2rex_Network-عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-f85d234d
  type: vless
  server: somebody.sanaei1.milxbywkaiwnx.xyz
  port: 443
  uuid: b4b1a001-e35f-48b9-a732-988bce565096
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__prroxyng-6dce44dc
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: net0n3_339-5d197bf0
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: vless-39c74f2b
  type: vless
  server: fbi22.wizard2shop.com
  port: 8085
  uuid: 96ed1f2d-8b93-4ea2-961e-570cd2dc99eb
  udp: true
  tls: false
  network: tcp
- name: eli-test-08406a0c
  type: vless
  server: nuo.fast.hosting-ip.com
  port: 80
  uuid: 17d40078-cb50-4716-8771-f00d033dc2f0
  udp: true
  tls: false
  network: xhttp
- name: By_EbraSha_vless-DE-6b7e953e
  type: vless
  server: vpn_proxy_channel_vpn_proxy_channel.hohod.ir
  port: 443
  uuid: 33707040-edcf-4185-94e4-2a071315c602
  udp: true
  tls: false
  network: tcp
  servername: vpn_proxy_channel_vpn_proxy_channel.hohod.ir
  reality-opts:
    public-key: GpgfsA-U8Y8M3LRcTfsaBViDtp2VlN5riSLLZ2kxEiQ
    short-id: 7def4dde
- name: عضو_شو__zibanabz-f6a43074
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: Turboo-b13a63d3
  type: vless
  server: 146.75.55.82
  port: 80
  uuid: turboo-server
  udp: true
  tls: false
  network: xhttp
- name: V2rayNG2008-de2b130d
  type: ss
  server: series-a2-mec.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: net0n3_348-3e66e87c
  type: ss
  server: 45.87.175.183
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
- name: Telegramvmessorg-5263a189
  type: ss
  server: 131.145.33.92
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
- name: vless-5bdc1ce3
  type: vless
  server: 104.26.6.89
  port: 80
  uuid: b360267f-81aa-4740-a9c0-9a64fe7f9775
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: onlytesla1.xz027.com
- name: Tint-37d6e37f
  type: vless
  server: hf.tin9.ir
  port: 2052
  uuid: f3242907-f8e4-4166-8156-c773430bd8a4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: null
- name: net0n3_378-1a1ae3d0
  type: ss
  server: 131.145.33.92
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
- name: telegram__ataconnect__server_85-3bacb0e0
  type: vmess
  server: ee1.daallygold.com
  port: 52262
  uuid: af5a0d0c-c898-4a51-ba6a-47179d483e41
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: net0n3_335-177c2bba
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: xhttp
- name: هـلند__رایگان_v2angbot-cae66d33
  type: vless
  server: iran.fast.hosting-ip.com
  port: 80
  uuid: 48a2c4cb-b4ce-427d-8860-a512b1f2b849
  udp: true
  tls: false
  network: xhttp
- name: V2rayNG2008-600306f4
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: vless-4a166117
  type: vless
  server: 78234873823.webnama.com.tr
  port: 3789
  uuid: c148156c-dcad-4697-a2a9-6f4432581a78
  udp: true
  tls: false
  network: tcp
- name: net0n3_346-01bfe22f
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: عضو_شو__zibanabz-d4052714
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: عضو_شو__zibanabz-f0ff4f30
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: Marz_user2_vless_-_ws-3800a20e
  type: vless
  server: 109.120.179.185
  port: 80
  uuid: a6d7f6b2-6192-a447-220f-7555732c913f
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/
    headers:
      Host: null
- name: عضو_شو__zibanabz-48eca05d
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: By_EbraSha_vless-US-dd3372f8
  type: vless
  server: 185.236.232.136
  port: 1001
  uuid: c7c922da-ab54-433c-8046-1f9bf9d95c23
  udp: true
  tls: false
  network: tcp
  servername: telewebion.com
  reality-opts:
    public-key: 8Gunn8hjWbit5yLtTPcvLph0u2ovHLsGoXX4IJS1EQ0
    short-id: 5fab0deb
- name: net0n3_336-3963ad71
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: V2rayNGFreeeV2rayNGFreee
  udp: true
  tls: false
  network: xhttp
- name: vless-32106bed
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: net0n3_358-8e50190d
  type: vless
  server: 83.217.9.233
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: vless-b7afb58a
  type: vless
  server: a.ru.maviks.ru
  port: 443
  uuid: c3afb549-2c79-4787-9d67-ccd1581fb70f
  udp: true
  tls: false
  network: tcp
  servername: maviks.ru
  reality-opts:
    public-key: cGzNRbN_zruI3CVTDukB2nOqWWEj7kgkay24f2fdLmQ
    short-id: 0f917152a871e9c0
- name: vless-247a1766
  type: vless
  server: de2.pokerad.top
  port: 8080
  uuid: 1d845272-528e-4d76-a721-9de31bf1326f
  udp: true
  tls: false
  network: tcp
- name: vless-14c56216
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 2096
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: Ft77Ta8Q1m.EmShAbKhObE.oRg
  ws-opts:
    path: /
    headers:
      Host: Ft77Ta8Q1m.EmShAbKhObE.oRg
- name: NamiraNet_____847695-7930bc6f
  type: vless
  server: 8.47.69.5
  port: 2052
  uuid: 038416de-dc40-4dc0-8c8e-10de534c7cc0
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /@XS_VPNROBOT
    headers:
      Host: xsvpn-ch.90908585.ir
- name: net0n3_344-cdd6aed4
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: vless-52f9b27a
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 8443
  uuid: 96a1b724-68d2-4f4d-ab25-38ecd83577bc
  udp: true
  tls: true
  network: ws
  servername: IyFpLkXk10.jOoLaJoOlA.OrG
  ws-opts:
    path: /
    headers:
      Host: IyFpLkXk10.jOoLaJoOlA.OrG
- name: By_EbraSha_ss-KZ-45e74d74
  type: ss
  server: ct.uigame.space
  port: 2024
  cipher: chacha20-ietf-poly1305
  password: 33LpoU8X/xHnCD+cbNe+7p0pK/JngDLM+5+RILrxyfVFRW/niKz5Eu0rWyVcDho=
  udp: true
- name: عضو_شو__zibanabz-ef2c2fe8
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-52b2878f
  type: vless
  server: 99823232.webnama.com.tr
  port: 1517
  uuid: c148156c-dcad-4697-a2a9-6f4432581a78
  udp: true
  tls: false
  network: tcp
- name: net0n3_359-a534dd27
  type: vless
  server: 89.221.203.100
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: net0n3_352-d9a9b47a
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: عضو_شو__zibanabz-406fce66
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: vless-20386252
  type: vless
  server: russiatest-tap.servers807.ir
  port: 13796
  uuid: b646e0d6-137b-49e1-90bc-3b9ad8a6484a
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: AIUUKeq08usIla0uv-NTp5wVe4TMb3VkXWDLoutlFnM
    short-id: a3ac
- name: By_EbraSha_vless-KR-71735fa0
  type: vless
  server: 8.213.149.42
  port: 443
  uuid: 5c183802-747d-4d2f-a6f1-aff2d5d78401
  udp: true
  tls: false
  network: tcp
  servername: wwwimages2.adobe.com
  reality-opts:
    public-key: DNdTBHyztOVJOBJQX91YXEhNkWbSAntqUoTFBHc6Clw
    short-id: 6ba85179e30d4fc2
- name: net0n3_332-2d7a73f0
  type: vless
  server: s3.esrtz.onl
  port: 46470
  uuid: 3bcc6dbf-0ab4-4674-85c8-39bd994434f9
  udp: true
  tls: false
  network: tcp
- name: net0n3_238-7c7e7b97
  type: vless
  server: all97-vip.f-sub.com
  port: 1517
  uuid: 240052ac-0bf0-481f-adb4-f40a259fc189
  udp: true
  tls: false
  network: tcp
- name: eliii-2ea98d02
  type: vless
  server: s1.aparat-movies-download.ir
  port: 4450
  uuid: 5d7edf75-ec86-4ff0-9b63-5f30b88f1be5
  udp: true
  tls: false
  network: tcp
  servername: zhaket.com
  reality-opts:
    public-key: y6JSkggQ__RA_nmCJpX1_ddSQC6vzDUPaN7KyvjVuic
    short-id: null
- name: MCONFIGVPN-468b9ddf
  type: vless
  server: 62.60.163.77
  port: 3333
  uuid: 7d283c1a-3a5b-4b2a-a924-0bd256e89726
  udp: true
  tls: false
  network: tcp
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - By_EbraSha_vless-GB-d103ed0b
  - vless-3daa0812
  - Telegramvmessorg-7394bc27
  - net0n3_354-3435eddb
  - عضو_شو__zibanabz-1a0560f1
  - VConfing-018c600c
  - Telegramvmessorg-664be3ad
  - عضو_شو__zibanabz-f097ff32
  - net0n3_356-b789446d
  - net0n3_347-4311bab3
  - V2rex_Network-عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-f85d234d
  - عضو_شو__prroxyng-6dce44dc
  - net0n3_339-5d197bf0
  - vless-39c74f2b
  - eli-test-08406a0c
  - By_EbraSha_vless-DE-6b7e953e
  - عضو_شو__zibanabz-f6a43074
  - Turboo-b13a63d3
  - V2rayNG2008-de2b130d
  - net0n3_348-3e66e87c
  - Telegramvmessorg-5263a189
  - vless-5bdc1ce3
  - Tint-37d6e37f
  - net0n3_378-1a1ae3d0
  - telegram__ataconnect__server_85-3bacb0e0
  - net0n3_335-177c2bba
  - هـلند__رایگان_v2angbot-cae66d33
  - V2rayNG2008-600306f4
  - vless-4a166117
  - net0n3_346-01bfe22f
  - عضو_شو__zibanabz-d4052714
  - عضو_شو__zibanabz-f0ff4f30
  - Marz_user2_vless_-_ws-3800a20e
  - عضو_شو__zibanabz-48eca05d
  - By_EbraSha_vless-US-dd3372f8
  - net0n3_336-3963ad71
  - vless-32106bed
  - net0n3_358-8e50190d
  - vless-b7afb58a
  - vless-247a1766
  - vless-14c56216
  - NamiraNet_____847695-7930bc6f
  - net0n3_344-cdd6aed4
  - vless-52f9b27a
  - By_EbraSha_ss-KZ-45e74d74
  - عضو_شو__zibanabz-ef2c2fe8
  - vless-52b2878f
  - net0n3_359-a534dd27
  - net0n3_352-d9a9b47a
  - عضو_شو__zibanabz-406fce66
  - vless-20386252
  - By_EbraSha_vless-KR-71735fa0
  - net0n3_332-2d7a73f0
  - net0n3_238-7c7e7b97
  - eliii-2ea98d02
  - MCONFIGVPN-468b9ddf
- name: AUTO
  type: url-test
  proxies:
  - By_EbraSha_vless-GB-d103ed0b
  - vless-3daa0812
  - Telegramvmessorg-7394bc27
  - net0n3_354-3435eddb
  - عضو_شو__zibanabz-1a0560f1
  - VConfing-018c600c
  - Telegramvmessorg-664be3ad
  - عضو_شو__zibanabz-f097ff32
  - net0n3_356-b789446d
  - net0n3_347-4311bab3
  - V2rex_Network-عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-f85d234d
  - عضو_شو__prroxyng-6dce44dc
  - net0n3_339-5d197bf0
  - vless-39c74f2b
  - eli-test-08406a0c
  - By_EbraSha_vless-DE-6b7e953e
  - عضو_شو__zibanabz-f6a43074
  - Turboo-b13a63d3
  - V2rayNG2008-de2b130d
  - net0n3_348-3e66e87c
  - Telegramvmessorg-5263a189
  - vless-5bdc1ce3
  - Tint-37d6e37f
  - net0n3_378-1a1ae3d0
  - telegram__ataconnect__server_85-3bacb0e0
  - net0n3_335-177c2bba
  - هـلند__رایگان_v2angbot-cae66d33
  - V2rayNG2008-600306f4
  - vless-4a166117
  - net0n3_346-01bfe22f
  - عضو_شو__zibanabz-d4052714
  - عضو_شو__zibanabz-f0ff4f30
  - Marz_user2_vless_-_ws-3800a20e
  - عضو_شو__zibanabz-48eca05d
  - By_EbraSha_vless-US-dd3372f8
  - net0n3_336-3963ad71
  - vless-32106bed
  - net0n3_358-8e50190d
  - vless-b7afb58a
  - vless-247a1766
  - vless-14c56216
  - NamiraNet_____847695-7930bc6f
  - net0n3_344-cdd6aed4
  - vless-52f9b27a
  - By_EbraSha_ss-KZ-45e74d74
  - عضو_شو__zibanabz-ef2c2fe8
  - vless-52b2878f
  - net0n3_359-a534dd27
  - net0n3_352-d9a9b47a
  - عضو_شو__zibanabz-406fce66
  - vless-20386252
  - By_EbraSha_vless-KR-71735fa0
  - net0n3_332-2d7a73f0
  - net0n3_238-7c7e7b97
  - eliii-2ea98d02
  - MCONFIGVPN-468b9ddf
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
