port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: vless-b7f38bf1
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: مشتی_جوین_بده_ناموصا__xzjinx-6813bdf6
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  tls: false
  network: tcp
- name: Sezar_sec-82e65279
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  tls: false
  network: tcp
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: net0n3_281-ccf77eea
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-4b596887
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: net0n3_289-aad4546e
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: vless-6dd646cf
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
- name: Sezar_sec-4477a5aa
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: vless-06a41033
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: vless-5d143fc5
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-34ced997
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: nginx.nscl.ir
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: NETMelliAnti_بیا_چنل-21902cef
  type: vless
  server: 216.22.5.79
  port: 443
  uuid: e1c32bed-b458-4273-a953-a74eff15d54c
  udp: true
  tls: false
  network: tcp
- name: vless-f212987f
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 6bcb4f37-bba7-4ae0-afac-d43195c72c12
  udp: true
  tls: true
  network: ws
  servername: my.digikala.dynv6.net
  ws-opts:
    path: zula.ir
    headers:
      Host: my.digikala.dynv6.net
- name: net0n3_276-5cf0158e
  type: ss
  server: h110vpnnl.outlinekeys.net
  port: 52571
  cipher: chacha20-ietf-poly1305
  password: 2nvtG6pl4Om1G0cWlnyXHl
  udp: true
- name: vless-15204de8
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: qeshmserver
  udp: true
  tls: false
  network: xhttp
- name: vless-f24be30b
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: NETMelliAnti_دوتای_بالارو_تست_کن-0e18863d
  type: vless
  server: 91.107.164.201
  port: 443
  uuid: 8fc13a32-42db-4303-9bb4-cd30d456a3a6
  udp: true
  tls: false
  network: tcp
- name: Turkeys_-_MTN__RTL-f64fb5b9
  type: vless
  server: api.loadbal.xpnvip.ir
  port: 2764
  uuid: 60d68718-0605-4693-b1b8-96e187398561
  udp: true
  tls: false
  network: grpc
  servername: refersion.com
  reality-opts:
    public-key: pPyt_X3DrYLSXbuQhlLFeXxdPTsnS7Owwzr8n5CYSj0
    short-id: 8c6f2f28b3364ea7
- name: Sezar_Sec-f06ae1b6
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  tls: false
  network: tcp
- name: vless-d57657c3
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: net0n3_294-3a1f424c
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-340272a5
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_295-2743b05b
  type: vless
  server: de1.cowjuice.me
  port: 443
  uuid: 955827fc-c729-4a1e-ba6c-d85754c8e937
  udp: true
  tls: false
  network: tcp
  servername: thelocal.de
  reality-opts:
    public-key: O9DMPpwicRcMofaplcvpQStNRogPS_HJY0s5_4EaKQc
    short-id: aabbccdd
- name: net0n3_296-3120aa57
  type: vless
  server: de6.razercompany.com
  port: 33200
  uuid: c4389c70-1e5a-4bd2-934f-44fb2e62ccf5
  udp: true
  tls: false
  network: tcp
- name: vless-13211c09
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: مشتی_جوین_بده_ناموصا__xzjinx-ac31bc68
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: 09694965-369f-48b5-82fa-40aae0236746
  udp: true
  tls: false
  network: tcp
- name: Sezar_Sec-358f6416
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: vless-4e5f7a66
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 92f481b6-ad92-43e4-a683-2bb0aeaa9846
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: dw.alibichareh.dpdns.org
- name: NETMelliAnti_جوین_نزنی_آف_میشه-c45a67dc
  type: vless
  server: 159.89.110.200
  port: 56503
  uuid: 1028a73a-e0a6-4d91-b834-e151f9a47fce
  udp: true
  tls: false
  network: tcp
- name: vless-d8276fc9
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-caca6dfc
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: vless-9880c71a
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  tls: false
  network: tcp
- name: Sezar_Sec-7fbc6015
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: vless-a66e1c2b
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 147d63c1-2f68-4f45-b3ea-cb3172fab133
  udp: true
  tls: true
  network: ws
  servername: 638874929583954786.zagreb-prx-dnraaad.info
  ws-opts:
    path: /jmgjhhws
    headers:
      Host: 638874929583954786.zagreb-prx-dnraaad.info
- name: NETMelliAnti-27dbef76
  type: vmess
  server: 81.12.33.180
  port: 8595
  uuid: ef0b85e8-d3f2-4e7d-8935-dffc6447f639
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-84ab5ea8
  type: vless
  server: 0ger.amazon-osishop.ir
  port: 8880
  uuid: 2066c2f3-bde1-429f-b083-fcfc7aee14b5
  udp: true
  tls: false
  network: tcp
- name: ip6proxy__سرور_بیشتر_در-d50d700a
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 653ded5e-50bc-4fe4-807b-1230a017c304
  udp: true
  tls: true
  network: ws
  servername: 638874931195382804.kish-prx-dnraaaf.info
  ws-opts:
    path: /eccmnews
    headers:
      Host: 638874931195382804.kish-prx-dnraaaf.info
- name: Sezar_Sec-b32fd547
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Music_raygan__کانفینگ_تل_سرچ_کن-d72d10a6
  type: vless
  server: api.loadbal.xpnvip.ir
  port: 2764
  uuid: 60d68718-0605-4693-b1b8-96e187398561
  udp: true
  tls: false
  network: grpc
  servername: refersion.com
  reality-opts:
    public-key: pPyt_X3DrYLSXbuQhlLFeXxdPTsnS7Owwzr8n5CYSj0
    short-id: 8c6f2f28b3364ea7
- name: Sezar_sec-b2b40aeb
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
- name: YOOZCARD-5c17c627
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: 04327cef-1084-431a-d595-cfcf9593cbc3
  udp: true
  tls: false
  network: xhttp
- name: net0n3_282-5e0c9127
  type: vless
  server: hell.dl101movis.ir
  port: 80
  uuid: d601250a-e54f-46fe-a984-fb0f1d6d48ce
  udp: true
  tls: false
  network: xhttp
- name: net0n3_287-e08c9cf5
  type: vless
  server: compose.fast.hosting-ip.com
  port: 80
  uuid: ab80613b-e04b-4af5-bad9-9ca5c448266e
  udp: true
  tls: false
  network: xhttp
- name: net0n3_300-946a2ee4
  type: vless
  server: vpconnect.ahadbala.ir
  port: 80
  uuid: 3f0c3cef-75c0-4253-a62e-d89f5a45dcc1
  udp: true
  tls: false
  network: tcp
- name: vless-9ef21e74
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: مشتی_جوین_بده_ناموصا__xzjinx-c445876f
  type: ss
  server: 4.223.106.151
  port: 48172
  cipher: chacha20-ietf-poly1305
  password: 51yloQC8D9w1Wae7FHtI65
  udp: true
- name: vless-6af4069f
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-2190d780
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: vless-81979088
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: net0n3_285-77ff0520
  type: vless
  server: bam.erfann.shop
  port: 15807
  uuid: 8e4d0dba-884f-4bbd-9f1d-ea5ec78efe7d
  udp: true
  tls: false
  network: tcp
- name: vless-93e21880
  type: vless
  server: 91.99.172.196
  port: 28041
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: WpvjPUZ5x3SIvDzSr5q9v0bfhzo36obh3CXIqJVmnkY
    short-id: 91355b9b818617
- name: vless-b00808c3
  type: vless
  server: 300232332.webnama.com.tr
  port: 1517
  uuid: 3d554bba-9c77-499f-9055-1eb42058ed00
  udp: true
  tls: false
  network: tcp
- name: net0n3_298-934e8c27
  type: vless
  server: fastlyeeeeee.fast.hosting-ip.com
  port: 80
  uuid: cdnfastlycash
  udp: true
  tls: false
  network: xhttp
- name: vless-b3ad6eff
  type: vless
  server: 104.18.26.90
  port: 2096
  uuid: 546cc913-2825-4771-b713-a23905913141
  udp: true
  tls: true
  network: ws
  servername: 638874931195949050.kish-prx-dnraaaf.info
  ws-opts:
    path: /wjwqzaws
    headers:
      Host: 638874931195949050.kish-prx-dnraaaf.info
- name: net0n3_290-81a52bd6
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sub.divib.dynv6.net
- name: net0n3_297-75a756b3
  type: vless
  server: real-all3.sdcards.ir
  port: 8501
  uuid: 9666ee62-d1f3-4f6e-8881-c17fee524e31
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: OJ0wA5wp55uZdD16dutlTZvx1x-rbMMXmiO9D_MMCHI
    short-id: e701a013553059ba
- name: vless-dd00e823
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: مشتی_جوین_بده_ناموصا__xzjinx-19f6ab48
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: e6daaeba-5a7c-4933-89b0-0078c14c50f1
  udp: true
  tls: false
  network: tcp
- name: net0n3_283-dccb37e4
  type: ss
  server: 45.87.175.165
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: QCXDxuDlTTMD7jtgHUjIoj
  udp: true
- name: vless-6defd84d
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: مشتی_جوین_بده_ناموصا__xzjinx-ae977864
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: b54eaa6b-d4fc-4bb3-b3c6-9d0b61da00f7
  udp: true
  tls: false
  network: tcp
- name: vless-dcaed2ee
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - vless-b7f38bf1
  - مشتی_جوین_بده_ناموصا__xzjinx-6813bdf6
  - Sezar_sec-82e65279
  - net0n3_281-ccf77eea
  - vless-4b596887
  - net0n3_289-aad4546e
  - vless-6dd646cf
  - Sezar_sec-4477a5aa
  - vless-06a41033
  - vless-5d143fc5
  - vless-34ced997
  - NETMelliAnti_بیا_چنل-21902cef
  - vless-f212987f
  - net0n3_276-5cf0158e
  - vless-15204de8
  - vless-f24be30b
  - NETMelliAnti_دوتای_بالارو_تست_کن-0e18863d
  - Turkeys_-_MTN__RTL-f64fb5b9
  - Sezar_Sec-f06ae1b6
  - vless-d57657c3
  - net0n3_294-3a1f424c
  - Sezar_Sec-340272a5
  - net0n3_295-2743b05b
  - net0n3_296-3120aa57
  - vless-13211c09
  - مشتی_جوین_بده_ناموصا__xzjinx-ac31bc68
  - Sezar_Sec-358f6416
  - vless-4e5f7a66
  - NETMelliAnti_جوین_نزنی_آف_میشه-c45a67dc
  - vless-d8276fc9
  - vless-caca6dfc
  - vless-9880c71a
  - Sezar_Sec-7fbc6015
  - vless-a66e1c2b
  - NETMelliAnti-27dbef76
  - vless-84ab5ea8
  - ip6proxy__سرور_بیشتر_در-d50d700a
  - Sezar_Sec-b32fd547
  - Music_raygan__کانفینگ_تل_سرچ_کن-d72d10a6
  - Sezar_sec-b2b40aeb
  - YOOZCARD-5c17c627
  - net0n3_282-5e0c9127
  - net0n3_287-e08c9cf5
  - net0n3_300-946a2ee4
  - vless-9ef21e74
  - مشتی_جوین_بده_ناموصا__xzjinx-c445876f
  - vless-6af4069f
  - vless-2190d780
  - vless-81979088
  - net0n3_285-77ff0520
  - vless-93e21880
  - vless-b00808c3
  - net0n3_298-934e8c27
  - vless-b3ad6eff
  - net0n3_290-81a52bd6
  - net0n3_297-75a756b3
  - vless-dd00e823
  - مشتی_جوین_بده_ناموصا__xzjinx-19f6ab48
  - net0n3_283-dccb37e4
  - vless-6defd84d
  - مشتی_جوین_بده_ناموصا__xzjinx-ae977864
  - vless-dcaed2ee
- name: AUTO
  type: url-test
  proxies:
  - vless-b7f38bf1
  - مشتی_جوین_بده_ناموصا__xzjinx-6813bdf6
  - Sezar_sec-82e65279
  - net0n3_281-ccf77eea
  - vless-4b596887
  - net0n3_289-aad4546e
  - vless-6dd646cf
  - Sezar_sec-4477a5aa
  - vless-06a41033
  - vless-5d143fc5
  - vless-34ced997
  - NETMelliAnti_بیا_چنل-21902cef
  - vless-f212987f
  - net0n3_276-5cf0158e
  - vless-15204de8
  - vless-f24be30b
  - NETMelliAnti_دوتای_بالارو_تست_کن-0e18863d
  - Turkeys_-_MTN__RTL-f64fb5b9
  - Sezar_Sec-f06ae1b6
  - vless-d57657c3
  - net0n3_294-3a1f424c
  - Sezar_Sec-340272a5
  - net0n3_295-2743b05b
  - net0n3_296-3120aa57
  - vless-13211c09
  - مشتی_جوین_بده_ناموصا__xzjinx-ac31bc68
  - Sezar_Sec-358f6416
  - vless-4e5f7a66
  - NETMelliAnti_جوین_نزنی_آف_میشه-c45a67dc
  - vless-d8276fc9
  - vless-caca6dfc
  - vless-9880c71a
  - Sezar_Sec-7fbc6015
  - vless-a66e1c2b
  - NETMelliAnti-27dbef76
  - vless-84ab5ea8
  - ip6proxy__سرور_بیشتر_در-d50d700a
  - Sezar_Sec-b32fd547
  - Music_raygan__کانفینگ_تل_سرچ_کن-d72d10a6
  - Sezar_sec-b2b40aeb
  - YOOZCARD-5c17c627
  - net0n3_282-5e0c9127
  - net0n3_287-e08c9cf5
  - net0n3_300-946a2ee4
  - vless-9ef21e74
  - مشتی_جوین_بده_ناموصا__xzjinx-c445876f
  - vless-6af4069f
  - vless-2190d780
  - vless-81979088
  - net0n3_285-77ff0520
  - vless-93e21880
  - vless-b00808c3
  - net0n3_298-934e8c27
  - vless-b3ad6eff
  - net0n3_290-81a52bd6
  - net0n3_297-75a756b3
  - vless-dd00e823
  - مشتی_جوین_بده_ناموصا__xzjinx-19f6ab48
  - net0n3_283-dccb37e4
  - vless-6defd84d
  - مشتی_جوین_بده_ناموصا__xzjinx-ae977864
  - vless-dcaed2ee
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
