port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: By_EbraSha_vless-KR-fe4a29ae
  type: vless
  server: 8.213.149.42
  port: 443
  uuid: 5c183802-747d-4d2f-a6f1-aff2d5d78401
  udp: true
  tls: false
  network: tcp
  servername: wwwimages2.adobe.com
  reality-opts:
    public-key: DNdTBHyztOVJOBJQX91YXEhNkWbSAntqUoTFBHc6Clw
    short-id: 6ba85179e30d4fc2
- name: vless-4c392421
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: عضو_شو__zibanabz-09fc6383
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: عضو_شو__zibanabz-ebc04598
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: عضو_شو__zibanabz-7c494481
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: vless-1e3503ee
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: V2rayNGFreeeV2rayNGFreee
  udp: true
  tls: false
  network: xhttp
- name: proxygodratmand_سرورای_بیشتر_با_سرعت_خوب_داخل_چنل-e7fe2cd7
  type: vless
  server: 188.227.84.173
  port: 8443
  uuid: cb024589-f32e-4022-b325-56ab0eeff33f
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__prroxyng-f87733f2
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: By_EbraSha_vless-DE-5ecaaacb
  type: vless
  server: vpn_proxy_channel_vpn_proxy_channel.hohod.ir
  port: 443
  uuid: 33707040-edcf-4185-94e4-2a071315c602
  udp: true
  tls: false
  network: tcp
  servername: vpn_proxy_channel_vpn_proxy_channel.hohod.ir
  reality-opts:
    public-key: GpgfsA-U8Y8M3LRcTfsaBViDtp2VlN5riSLLZ2kxEiQ
    short-id: 7def4dde
- name: proxy_v2ray_meli-772ace66
  type: vmess
  server: 188.227.84.174
  port: 2096
  uuid: aae9a898-82c1-411c-9d92-b88677f3b664
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: VConfing-2c59153c
  type: vmess
  server: 81.12.33.180
  port: 8595
  uuid: 4e6e51d7-1234-4543-999f-0f54a428b77f
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: By_EbraSha_ss-KZ-ae3f3b7a
  type: ss
  server: ct.uigame.space
  port: 2024
  cipher: chacha20-ietf-poly1305
  password: 33LpoU8X/xHnCD+cbNe+7p0pK/JngDLM+5+RILrxyfVFRW/niKz5Eu0rWyVcDho=
  udp: true
- name: net0n3_352-2030c0ab
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: vless-d1e275d0
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: v2rayngcustom__عضو_شو-6147624a
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: c55ef976-d9f5-41d9-8bfb-c57853a66327
  udp: true
  tls: true
  network: ws
  servername: skYNet.ZIStArviNBiOtEch.Ir
  ws-opts:
    path: /qp8ihoxMLXPfQWaw?ed=2560
    headers:
      Host: skynet.zistarvinbiotech.ir
- name: ModiriVpnBot-400GB_Free-e15e5517
  type: vless
  server: 194.135.46.24
  port: 443
  uuid: bda515f9-b3d8-4756-bca1-3423ac5ff9a0
  udp: true
  tls: false
  network: tcp
- name: vless-59194f01
  type: vless
  server: russiatest-tap.servers807.ir
  port: 13796
  uuid: b646e0d6-137b-49e1-90bc-3b9ad8a6484a
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: AIUUKeq08usIla0uv-NTp5wVe4TMb3VkXWDLoutlFnM
    short-id: a3ac
- name: vless-594e6406
  type: vless
  server: all97-vip.f-sub.com
  port: 1517
  uuid: 240052ac-0bf0-481f-adb4-f40a259fc189
  udp: true
  tls: false
  network: tcp
- name: NETMelliAnti_جوین_نزنی_آف_میشه-86f75b02
  type: vless
  server: 85.198.10.188
  port: 8080
  uuid: e1dbdac2-ba11-415e-80ec-f295169a3728
  udp: true
  tls: false
  network: tcp
- name: vless-641b6c1f
  type: vless
  server: 83.217.9.233
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: vless-6e92e0ff
  type: vless
  server: 89.221.203.100
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: عضو_شو__zibanabz-d13b8420
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: عضو_شو__zibanabz-935e41ec
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: By_EbraSha_vless-US-fb94bb65
  type: vless
  server: 185.236.232.136
  port: 1001
  uuid: c7c922da-ab54-433c-8046-1f9bf9d95c23
  udp: true
  tls: false
  network: tcp
  servername: telewebion.com
  reality-opts:
    public-key: 8Gunn8hjWbit5yLtTPcvLph0u2ovHLsGoXX4IJS1EQ0
    short-id: 5fab0deb
- name: vless-fb433ccc
  type: vless
  server: david2.lemoex.blog
  port: 443
  uuid: 737c9e58-379d-4654-9471-d60494b326bd
  udp: true
  tls: true
  network: httpupgrade
  servername: david2.lemoex.blog
- name: eli-f8c74ce5
  type: vless
  server: turboo-server-bot.aftabz.com
  port: 8080
  uuid: 92c79723-eb54-4c48-bb81-83423a0e6440
  udp: true
  tls: false
  network: grpc
  servername: tgju.org
  reality-opts:
    public-key: zLBoalJcQIgIUcegIx0_cCEBvAMJxIbotJA6y50CVHg
    short-id: 3bf4f5
- name: vless-585c53b9
  type: vless
  server: 154.92.9.46
  port: 443
  uuid: ec8a65ad-aafc-4095-9b8c-ea10890ca629
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/?ed=2560
    headers:
      Host: simorgh.hpcode.ir
- name: AZADNET-72e95720
  type: ss
  server: azad.net.vpn.digipedia.shop
  port: 48172
  cipher: chacha20-ietf-poly1305
  password: 51yloQC8D9w1Wae7FHtI65
  udp: true
- name: net0n3_347-0fffa4fc
  type: ss
  server: 193.228.139.250
  port: 1080
  cipher: chacha20-ietf-poly1305
  password: yrZtUElGhL8xfeaN0hIIzQ
  udp: true
- name: عضو_شو__zibanabz-51bfbf73
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: configfree_1-fe57b20c
  type: vless
  server: all.yasharteam.com
  port: 666
  uuid: f8e7410f-5984-4973-a02b-fde30761ba53
  udp: true
  tls: false
  network: tcp
- name: VConfing-08e179dd
  type: vmess
  server: nhel1-tu.mobstore.store
  port: 2083
  uuid: a9b68e36-eb35-1bbc-b958-ecd0e46ba428
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: net0n3_348-9fa12603
  type: ss
  server: 45.87.175.183
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
- name: ²_قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-09cd09d1
  type: vless
  server: log.twixspace.com
  port: 443
  uuid: 923e670e-647d-4e42-bf53-63c27d6c99a0
  udp: true
  tls: false
  network: grpc
  servername: wordpress.org
  reality-opts:
    public-key: dUCso1FAr-zors9NhEC__IqYI3fEjyfLvRqksj9lmxw
    short-id: f99c4b933314ec6d
- name: عضو_شو__zibanabz-9886e78c
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: By_EbraSha_vless-GB-daa03545
  type: vless
  server: 54.36.162.84
  port: 8880
  uuid: 9beca423-b31d-496d-aee6-a1ab64f0bd81
  udp: true
  tls: false
  network: tcp
  servername: google.com
  reality-opts:
    public-key: Fa_dYaQoLgLjsk1jvSQcEKRNnAvMVJF4Br7YG5FT6zo
    short-id: 1e4072
- name: عضو_شو__zibanabz-24a12e2f
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: vless-dce8060a
  type: vless
  server: 93.123.39.31
  port: 443
  uuid: 00e92112-b43b-4757-a56a-fa7b53ad3419
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - By_EbraSha_vless-KR-fe4a29ae
  - vless-4c392421
  - عضو_شو__zibanabz-09fc6383
  - عضو_شو__zibanabz-ebc04598
  - عضو_شو__zibanabz-7c494481
  - vless-1e3503ee
  - proxygodratmand_سرورای_بیشتر_با_سرعت_خوب_داخل_چنل-e7fe2cd7
  - عضو_شو__prroxyng-f87733f2
  - By_EbraSha_vless-DE-5ecaaacb
  - proxy_v2ray_meli-772ace66
  - VConfing-2c59153c
  - By_EbraSha_ss-KZ-ae3f3b7a
  - net0n3_352-2030c0ab
  - vless-d1e275d0
  - v2rayngcustom__عضو_شو-6147624a
  - ModiriVpnBot-400GB_Free-e15e5517
  - vless-59194f01
  - vless-594e6406
  - NETMelliAnti_جوین_نزنی_آف_میشه-86f75b02
  - vless-641b6c1f
  - vless-6e92e0ff
  - عضو_شو__zibanabz-d13b8420
  - عضو_شو__zibanabz-935e41ec
  - By_EbraSha_vless-US-fb94bb65
  - vless-fb433ccc
  - eli-f8c74ce5
  - vless-585c53b9
  - AZADNET-72e95720
  - net0n3_347-0fffa4fc
  - عضو_شو__zibanabz-51bfbf73
  - configfree_1-fe57b20c
  - VConfing-08e179dd
  - net0n3_348-9fa12603
  - ²_قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-09cd09d1
  - عضو_شو__zibanabz-9886e78c
  - By_EbraSha_vless-GB-daa03545
  - عضو_شو__zibanabz-24a12e2f
  - vless-dce8060a
- name: AUTO
  type: url-test
  proxies:
  - By_EbraSha_vless-KR-fe4a29ae
  - vless-4c392421
  - عضو_شو__zibanabz-09fc6383
  - عضو_شو__zibanabz-ebc04598
  - عضو_شو__zibanabz-7c494481
  - vless-1e3503ee
  - proxygodratmand_سرورای_بیشتر_با_سرعت_خوب_داخل_چنل-e7fe2cd7
  - عضو_شو__prroxyng-f87733f2
  - By_EbraSha_vless-DE-5ecaaacb
  - proxy_v2ray_meli-772ace66
  - VConfing-2c59153c
  - By_EbraSha_ss-KZ-ae3f3b7a
  - net0n3_352-2030c0ab
  - vless-d1e275d0
  - v2rayngcustom__عضو_شو-6147624a
  - ModiriVpnBot-400GB_Free-e15e5517
  - vless-59194f01
  - vless-594e6406
  - NETMelliAnti_جوین_نزنی_آف_میشه-86f75b02
  - vless-641b6c1f
  - vless-6e92e0ff
  - عضو_شو__zibanabz-d13b8420
  - عضو_شو__zibanabz-935e41ec
  - By_EbraSha_vless-US-fb94bb65
  - vless-fb433ccc
  - eli-f8c74ce5
  - vless-585c53b9
  - AZADNET-72e95720
  - net0n3_347-0fffa4fc
  - عضو_شو__zibanabz-51bfbf73
  - configfree_1-fe57b20c
  - VConfing-08e179dd
  - net0n3_348-9fa12603
  - ²_قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-09cd09d1
  - عضو_شو__zibanabz-9886e78c
  - By_EbraSha_vless-GB-daa03545
  - عضو_شو__zibanabz-24a12e2f
  - vless-dce8060a
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
