port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: GheychiAmoozesh-23-6e80beb5
  type: vless
  server: 135.148.152.106
  port: 443
  uuid: ea286109-d20f-415e-849e-4af20ab04b65
  udp: true
  tls: true
  network: tcp
  servername: 147135001195.sec22org.com
- name: Germany-a2c845e4
  type: vless
  server: de.pixvpn.app
  port: 8443
  uuid: d6aa457d-8214-40d0-b5fe-3f7b551cb1c6
  udp: true
  tls: false
  network: grpc
  servername: jd.com
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: c13a37127db7ebd0
- name: eli2-ee7a1fa7
  type: vless
  server: turboo-server.sadafspace.com
  port: 48723
  uuid: turboo-server
  udp: true
  tls: false
  network: grpc
  servername: tgju.org
  reality-opts:
    public-key: 1WQPNVCS8laWlmbHO-WnqXCqvlPcKQkb_hK_5eBmrH0
    short-id: b3
- name: vip2_2-f37b195f
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: 6f9da396-2b23-4880-9a38-57de11db5630
  udp: true
  tls: false
  network: xhttp
- name: vless-93c9e493
  type: vless
  server: 84.32.230.122
  port: 17349
  uuid: 7a8aeefb-808b-4dec-b7ce-9fecfaac0320
  udp: true
  tls: false
  network: grpc
  servername: zula.ir
  reality-opts:
    public-key: I70amIvHB8SOaROuXBtonD9N1n9ph1qIvu-TOp4lWwU
    short-id: a9bb
- name: MTProxynew3-c52642e3
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 289a4e03-317f-4bf8-97d3-e33200df6a2b
  udp: true
  tls: true
  network: ws
  servername: simoWEbsiTESPEedTEST.ir
  ws-opts:
    path: /KFh3HO76VUQPJDgM/OC4yMjAuMTM0LjEzNg
    headers:
      Host: simowebsitespeedtest.ir
- name: GheychiAmoozesh-22-14f27aae
  type: ss
  server: admin.c2.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: WstuSnlu4ieA9M0L
  udp: true
- name: vless-069c66ce
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 8443
  uuid: 24a4aa9b-b341-4717-9d4a-00d74c2b84e0
  udp: true
  tls: true
  network: ws
  servername: D324vSmBvE.aAaZzZaAa-89.InFo
  ws-opts:
    path: /
    headers:
      Host: D324vSmBvE.aAaZzZaAa-89.InFo
- name: Channel__v2rayconfigsNN-9a395326
  type: vless
  server: statue.lnmarketplace.net
  port: 443
  uuid: 7c63f43f-f526-49bb-b5c8-2be26e11ef00
  udp: true
  tls: true
  network: xhttp
  servername: statue.lnmarketplace.net
- name: عضو_شو__zibanabz-041ee9a6
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: England-e536e3c6
  type: vless
  server: uk.pixvpn.app
  port: 8443
  uuid: d6aa457d-8214-40d0-b5fe-3f7b551cb1c6
  udp: true
  tls: false
  network: grpc
  servername: jd.com
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: c13a37127db7ebd0
- name: USA-38bec72a
  type: vless
  server: em-4.webnama.com.tr
  port: 3789
  uuid: e1bb70ee-8ac0-4440-8bc9-c5a86ba442fb
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__prroxyng-bff957df
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: vip3_2-ae9ed72f
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: 57a7a089-f014-4983-98bb-0c0839f3f826
  udp: true
  tls: false
  network: xhttp
- name: GheychiAmoozesh-34-c6ec19da
  type: vless
  server: 95.164.45.85
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  network: grpc
- name: GheychiAmoozesh-37-26884597
  type: vless
  server: 104.22.24.195
  port: 443
  uuid: 96479a22-9333-4b03-9912-4dd26acef75e
  udp: true
  tls: true
  network: ws
  servername: NExtfilmtOmovies.sitE
  ws-opts:
    path: /9EkfcCDedhvB19xj?ed=2560
    headers:
      Host: nextfilmtomovies.site
- name: چنل_عضو_شو_v2ra_config-391985ed
  type: vless
  server: zula.ir
  port: 2087
  uuid: 554e89e9-5d47-408a-ee92-2fa8506bc78c
  udp: true
  tls: true
  network: ws
  servername: Hopev2.hopebook75zulawu.online
  ws-opts:
    path: /
    headers:
      Host: Hopev2.hopebook75zulawu.online.
- name: vless-bd1a856d
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: Telegram-SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: config_v2ray_vpnسرورهای_بیشتر-8f357460
  type: vless
  server: 94.183.158.13
  port: 8083
  uuid: 80a8dd9e-9e71-407e-9f31-1f488cea081f
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: null
- name: MTProxynew3-b69d196a
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  servername: gEtaSa.IR
  ws-opts:
    path: /WrQunvc9WRIaU32H?ed=2560
    headers:
      Host: getasa.ir
- name: چنل_عضو_شو_v2ra_config-453d2630
  type: vless
  server: turbooserver.sadafspace.com
  port: 55990
  uuid: turboo-server
  udp: true
  tls: false
  network: tcp
  servername: canva.com
  reality-opts:
    public-key: TbZDTzAIogOy-LWQjdqXElxPlUd6xdcwd9xxCqhbj04
    short-id: eebcfab3
- name: عضو_شو__zibanabz-0050154c
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: config_v2ray_vpnسرورهای_بیشتر-2dc939bb
  type: vless
  server: 94.183.158.11
  port: 8083
  uuid: 1cfbf08c-6e6f-4f2f-9345-c513a8e1b916
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: null
- name: چنل_عضو_شو_v2ra_config-de803d72
  type: vless
  server: 108.162.192.201
  port: 443
  uuid: turboo-server
  udp: true
  tls: true
  network: ws
  servername: cdn.sadafspace.com
  ws-opts:
    path: /
    headers:
      Host: cdn.sadafspace.com
- name: GheychiAmoozesh-31-1378545e
  type: vless
  server: 300232332.webnama.com.tr.privatepack.ir
  port: 1517
  uuid: 88f9173d-09b1-463a-99c8-e39852693cba
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-a4bd40bc
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: eli1-3ba0c223
  type: vless
  server: 108.162.192.201
  port: 443
  uuid: turboo-server
  udp: true
  tls: true
  network: ws
  servername: cdn.sadafspace.com
  ws-opts:
    path: /
    headers:
      Host: cdn.sadafspace.com
- name: CF随机节点06-ff58326d
  type: trojan
  server: 104.24.16.186
  port: 2083
  password: havij-koloche-holo
  udp: true
  sni: broken-queen-dfb7.mehdizx35.workers.dev
- name: عضو_شو__zibanabz-a2fad72a
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: vip1_1-218ec5bc
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 9f0b9ab6-f501-4892-b8e9-d0a19ea469f8
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: vip1_2-d4d9be2e
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: 9f0b9ab6-f501-4892-b8e9-d0a19ea469f8
  udp: true
  tls: false
  network: xhttp
- name: GheychiAmoozesh-27-f8523c44
  type: ss
  server: series-a2-mec.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: GheychiAmoozesh-26-2d94014b
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: Channel__v2rayconfigsNN-42f8aa04
  type: vless
  server: www.speedtest.net.cdn.cloudflare.net
  port: 8080
  uuid: 813d7c7e-d2ea-460f-9bf7-e6fa6a073b67
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: TW.kKpopH4Zmc.ZUlaIr.orG
- name: vip2_1-464b74e1
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 6f9da396-2b23-4880-9a38-57de11db5630
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: GheychiAmoozesh-36-a435c98a
  type: vless
  server: 34.247.254.247
  port: 50768
  uuid: c7e4c202-cfdf-44df-85a7-a9e7b4545a74
  udp: true
  tls: false
  network: grpc
  servername: jetbrains.com
  reality-opts:
    public-key: 7kUu70kwGDQ65WQHCBXcQ-KLQa5V8VVxX3zMML7hSlQ
    short-id: 4e78519d
- name: vless-78b7326a
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: GheychiAmoozesh-24-a20b22b4
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 2096
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: Ft77Ta8Q1m.EmShAbKhObE.oRg
  ws-opts:
    path: /
    headers:
      Host: Ft77Ta8Q1m.EmShAbKhObE.oRg
- name: vless-403c6efa
  type: vless
  server: 83.217.9.233
  port: 443
  uuid: 0e64b00f-b722-47d4-aff3-b94c293680ae
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: GheychiAmoozesh-33-635cfe67
  type: vless
  server: 104.21.112.1
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: FreeV2BoxBot_بهمون_سر_بزن-7218259b
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: 43e99f82-3f83-49d6-a625-2d420f6aa317
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=80
    headers:
      Host: www.speedtest.net.c.1.avaacado.ir
- name: GheychiAmoozesh-39-11555bcb
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 6f6e8f09-c1b3-48fd-ab00-18f921d875ef
  udp: true
  tls: true
  network: ws
  servername: profit.fullmargintraders.com
  ws-opts:
    path: /wsv/6f6e8f09-c1b3-48fd-ab00-18f921d875ef
    headers:
      Host: profit.fullmargintraders.com
- name: GheychiAmoozesh-21-c499fbd5
  type: ss
  server: series-a2.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: عضو_شو__zibanabz-e6e9291e
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: config_v2ray_vpnسرورهای_بیشتر-26d49b3d
  type: vless
  server: 104.26.15.69
  port: 2096
  uuid: 30f2d443-af46-4dd6-83c9-b5e17299ebd2
  udp: true
  tls: true
  network: ws
  servername: carlotta.shoorekeeper.cloudns.org
  ws-opts:
    path: /proxyip=zani.yaemiko.ggff.net
    headers:
      Host: carlotta.shoorekeeper.cloudns.org
- name: GheychiAmoozesh-32-4432336b
  type: vless
  server: 188.114.96.3
  port: 8443
  uuid: 88d05a33-ff36-415d-9d2c-7e1e8468e7e8
  udp: true
  tls: true
  network: ws
  servername: w325.pAges.Dev
  ws-opts:
    path: /Tel-@V2ray_Alpha/?ed=2560
    headers:
      Host: w325.pages.dev
- name: vless-86051eba
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN-
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: vip3_1-6babb43f
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 57a7a089-f014-4983-98bb-0c0839f3f826
  udp: true
  tls: true
  network: ws
  servername: fn2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: fn2vipys.sevenploos.com
- name: GheychiAmoozesh-35-3e6ba5c9
  type: vless
  server: 91.99.239.156
  port: 443
  uuid: d2d29254-ad3b-495a-b209-5ccc4f12c0a4
  udp: true
  tls: false
  network: tcp
- name: config_v2ray_vpnسرورهای_بیشتر-617e2d0f
  type: vless
  server: 94.183.158.16
  port: 8083
  uuid: 73ef9961-ad5d-4b2f-ad84-60b965b42ac9
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: null
- name: France-2da9af37
  type: vless
  server: fr.pixvpn.app
  port: 8443
  uuid: d6aa457d-8214-40d0-b5fe-3f7b551cb1c6
  udp: true
  tls: false
  network: grpc
  servername: jd.com
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: c13a37127db7ebd0
- name: GheychiAmoozesh-25-5e17cb97
  type: ss
  server: 131.145.33.92
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
- name: 50GB-97db8cc2
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 29cbae1c-0d29-4213-8220-d1302816c4b1
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: Poland-fece5ed2
  type: vless
  server: em-2.webnama.com.tr
  port: 3799
  uuid: e1bb70ee-8ac0-4440-8bc9-c5a86ba442fb
  udp: true
  tls: false
  network: tcp
- name: vless-3ea3eac7
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: 63fa5580-1bb7-4cc1-a6ee-0ed4eaa52308
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: عضو_شو__zibanabz-feb682ef
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: GheychiAmoozesh-38-ef81dc6d
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
  udp: true
  tls: true
  network: ws
  servername: avtice.fullmargintraders.com
  ws-opts:
    path: /wsv/7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
    headers:
      Host: avtice.fullmargintraders.com
- name: عضو_شو__zibanabz-f9aa91da
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: config_v2ray_vpnسرورهای_بیشتر-90fc9b20
  type: vless
  server: 94.183.158.10
  port: 8083
  uuid: 0ac2cfd0-9ff1-4b82-882b-8c651c464ae9
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: null
- name: vless-8a6bb120
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram-SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: عضو_شو__zibanabz-0f19ad81
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: eli4-a9ea6d41
  type: vless
  server: turbooserver.sadafspace.com
  port: 55990
  uuid: turboo-server
  udp: true
  tls: false
  network: tcp
  servername: canva.com
  reality-opts:
    public-key: TbZDTzAIogOy-LWQjdqXElxPlUd6xdcwd9xxCqhbj04
    short-id: eebcfab3
- name: چنل_عضو_شو_v2ra_config-bbe064fd
  type: vless
  server: turboo-server.sadafspace.com
  port: 48723
  uuid: turboo-server
  udp: true
  tls: false
  network: grpc
  servername: tgju.org
  reality-opts:
    public-key: 1WQPNVCS8laWlmbHO-WnqXCqvlPcKQkb_hK_5eBmrH0
    short-id: b3
- name: vless-23096fcf
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: Telegram--SRCVPN
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - GheychiAmoozesh-23-6e80beb5
  - Germany-a2c845e4
  - eli2-ee7a1fa7
  - vip2_2-f37b195f
  - vless-93c9e493
  - MTProxynew3-c52642e3
  - GheychiAmoozesh-22-14f27aae
  - vless-069c66ce
  - Channel__v2rayconfigsNN-9a395326
  - عضو_شو__zibanabz-041ee9a6
  - England-e536e3c6
  - USA-38bec72a
  - عضو_شو__prroxyng-bff957df
  - vip3_2-ae9ed72f
  - GheychiAmoozesh-34-c6ec19da
  - GheychiAmoozesh-37-26884597
  - چنل_عضو_شو_v2ra_config-391985ed
  - vless-bd1a856d
  - config_v2ray_vpnسرورهای_بیشتر-8f357460
  - MTProxynew3-b69d196a
  - چنل_عضو_شو_v2ra_config-453d2630
  - عضو_شو__zibanabz-0050154c
  - config_v2ray_vpnسرورهای_بیشتر-2dc939bb
  - چنل_عضو_شو_v2ra_config-de803d72
  - GheychiAmoozesh-31-1378545e
  - عضو_شو__zibanabz-a4bd40bc
  - eli1-3ba0c223
  - CF随机节点06-ff58326d
  - عضو_شو__zibanabz-a2fad72a
  - vip1_1-218ec5bc
  - vip1_2-d4d9be2e
  - GheychiAmoozesh-27-f8523c44
  - GheychiAmoozesh-26-2d94014b
  - Channel__v2rayconfigsNN-42f8aa04
  - vip2_1-464b74e1
  - GheychiAmoozesh-36-a435c98a
  - vless-78b7326a
  - GheychiAmoozesh-24-a20b22b4
  - vless-403c6efa
  - GheychiAmoozesh-33-635cfe67
  - FreeV2BoxBot_بهمون_سر_بزن-7218259b
  - GheychiAmoozesh-39-11555bcb
  - GheychiAmoozesh-21-c499fbd5
  - عضو_شو__zibanabz-e6e9291e
  - config_v2ray_vpnسرورهای_بیشتر-26d49b3d
  - GheychiAmoozesh-32-4432336b
  - vless-86051eba
  - vip3_1-6babb43f
  - GheychiAmoozesh-35-3e6ba5c9
  - config_v2ray_vpnسرورهای_بیشتر-617e2d0f
  - France-2da9af37
  - GheychiAmoozesh-25-5e17cb97
  - 50GB-97db8cc2
  - Poland-fece5ed2
  - vless-3ea3eac7
  - عضو_شو__zibanabz-feb682ef
  - GheychiAmoozesh-38-ef81dc6d
  - عضو_شو__zibanabz-f9aa91da
  - config_v2ray_vpnسرورهای_بیشتر-90fc9b20
  - vless-8a6bb120
  - عضو_شو__zibanabz-0f19ad81
  - eli4-a9ea6d41
  - چنل_عضو_شو_v2ra_config-bbe064fd
  - vless-23096fcf
- name: AUTO
  type: url-test
  proxies:
  - GheychiAmoozesh-23-6e80beb5
  - Germany-a2c845e4
  - eli2-ee7a1fa7
  - vip2_2-f37b195f
  - vless-93c9e493
  - MTProxynew3-c52642e3
  - GheychiAmoozesh-22-14f27aae
  - vless-069c66ce
  - Channel__v2rayconfigsNN-9a395326
  - عضو_شو__zibanabz-041ee9a6
  - England-e536e3c6
  - USA-38bec72a
  - عضو_شو__prroxyng-bff957df
  - vip3_2-ae9ed72f
  - GheychiAmoozesh-34-c6ec19da
  - GheychiAmoozesh-37-26884597
  - چنل_عضو_شو_v2ra_config-391985ed
  - vless-bd1a856d
  - config_v2ray_vpnسرورهای_بیشتر-8f357460
  - MTProxynew3-b69d196a
  - چنل_عضو_شو_v2ra_config-453d2630
  - عضو_شو__zibanabz-0050154c
  - config_v2ray_vpnسرورهای_بیشتر-2dc939bb
  - چنل_عضو_شو_v2ra_config-de803d72
  - GheychiAmoozesh-31-1378545e
  - عضو_شو__zibanabz-a4bd40bc
  - eli1-3ba0c223
  - CF随机节点06-ff58326d
  - عضو_شو__zibanabz-a2fad72a
  - vip1_1-218ec5bc
  - vip1_2-d4d9be2e
  - GheychiAmoozesh-27-f8523c44
  - GheychiAmoozesh-26-2d94014b
  - Channel__v2rayconfigsNN-42f8aa04
  - vip2_1-464b74e1
  - GheychiAmoozesh-36-a435c98a
  - vless-78b7326a
  - GheychiAmoozesh-24-a20b22b4
  - vless-403c6efa
  - GheychiAmoozesh-33-635cfe67
  - FreeV2BoxBot_بهمون_سر_بزن-7218259b
  - GheychiAmoozesh-39-11555bcb
  - GheychiAmoozesh-21-c499fbd5
  - عضو_شو__zibanabz-e6e9291e
  - config_v2ray_vpnسرورهای_بیشتر-26d49b3d
  - GheychiAmoozesh-32-4432336b
  - vless-86051eba
  - vip3_1-6babb43f
  - GheychiAmoozesh-35-3e6ba5c9
  - config_v2ray_vpnسرورهای_بیشتر-617e2d0f
  - France-2da9af37
  - GheychiAmoozesh-25-5e17cb97
  - 50GB-97db8cc2
  - Poland-fece5ed2
  - vless-3ea3eac7
  - عضو_شو__zibanabz-feb682ef
  - GheychiAmoozesh-38-ef81dc6d
  - عضو_شو__zibanabz-f9aa91da
  - config_v2ray_vpnسرورهای_بیشتر-90fc9b20
  - vless-8a6bb120
  - عضو_شو__zibanabz-0f19ad81
  - eli4-a9ea6d41
  - چنل_عضو_شو_v2ra_config-bbe064fd
  - vless-23096fcf
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
