port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: vless-64f5a568
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: 63fa5580-1bb7-4cc1-a6ee-0ed4eaa52308
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: عضو_شو__zibanabz-fba32647
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: eli1-bbd6afba
  type: vless
  server: 108.162.192.201
  port: 443
  uuid: turboo-server
  udp: true
  tls: true
  network: ws
  servername: cdn.sadafspace.com
  ws-opts:
    path: /
    headers:
      Host: cdn.sadafspace.com
- name: عضو_شو__zibanabz-6f325bce
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: 50GB-66f8236a
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 29cbae1c-0d29-4213-8220-d1302816c4b1
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: NETMelliAnti__چنل_کانفیگ-e8f9c8f3
  type: vmess
  server: 104.21.0.0
  port: 80
  uuid: 9c28e484-55ed-4756-a6dc-64a9ec7141da
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  udp: true
  ws-opts:
    path: /9c28e484-55ed-4756-a6dc-64a9ec7141da-vm?ed=2048
    headers:
      Host: asks-refers-zshops-journalists.trycloudflare.com
- name: GheychiAmoozesh-38-73605ba6
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
  udp: true
  tls: true
  network: ws
  servername: avtice.fullmargintraders.com
  ws-opts:
    path: /wsv/7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
    headers:
      Host: avtice.fullmargintraders.com
- name: net0n3_450-823a8629
  type: vless
  server: ip.sb
  port: 443
  uuid: 70f8697b-f9f3-4692-8e0a-3d1834fd76dc
  udp: true
  tls: true
  network: ws
  servername: 0fD5019a.FL-8hB.paGEs.deV
  ws-opts:
    path: /2PSWRwLal7xZQFnL/MzUuMjI4LjM2Ljgy?ed=2560
    headers:
      Host: 0fd5019a.fl-8hb.pages.dev
- name: net0n3_449-c1542117
  type: vless
  server: 45.82.251.121
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  udp: true
  tls: false
  network: grpc
- name: چنل_عضو_شو_v2ra_config-bb09388d
  type: vless
  server: 108.162.192.201
  port: 443
  uuid: turboo-server
  udp: true
  tls: true
  network: ws
  servername: cdn.sadafspace.com
  ws-opts:
    path: /
    headers:
      Host: cdn.sadafspace.com
- name: عضو_شو__zibanabz-16ca1f22
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: GheychiAmoozesh-34-14065e14
  type: vless
  server: 95.164.45.85
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  network: grpc
- name: تلگرامMCONFIGVPN-ecb7e5e0
  type: vless
  server: 141.101.121.108
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: Channel__v2rayconfigsNN-52ccaff2
  type: vless
  server: www.speedtest.net.cdn.cloudflare.net
  port: 8080
  uuid: 813d7c7e-d2ea-460f-9bf7-e6fa6a073b67
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: TW.kKpopH4Zmc.ZUlaIr.orG
- name: net0n3_473-e43d65b0
  type: vless
  server: 83.217.9.233
  port: 443
  uuid: 0e64b00f-b722-47d4-aff3-b94c293680ae
  udp: true
  tls: false
  network: tcp
  servername: cdnjs.com
  reality-opts:
    public-key: 9F7JxyyP-TNLt0dY2xOB0_34I8W0xXIpFY7rZ7-L0Gg
    short-id: 0a6ba2716a409da6
- name: vip1_1-f24b7f5e
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 9f0b9ab6-f501-4892-b8e9-d0a19ea469f8
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: MTProxynew3-5b0e646e
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  servername: gEtaSa.IR
  ws-opts:
    path: /WrQunvc9WRIaU32H?ed=2560
    headers:
      Host: getasa.ir
- name: vip3_2-04aa7973
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: 57a7a089-f014-4983-98bb-0c0839f3f826
  udp: true
  tls: false
  network: xhttp
- name: عضو_شو__prroxyng-3eef4986
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: eli4-7244235c
  type: vless
  server: turbooserver.sadafspace.com
  port: 55990
  uuid: turboo-server
  udp: true
  tls: false
  network: tcp
  servername: canva.com
  reality-opts:
    public-key: TbZDTzAIogOy-LWQjdqXElxPlUd6xdcwd9xxCqhbj04
    short-id: eebcfab3
- name: Poland-9b2de142
  type: vless
  server: em-2.webnama.com.tr
  port: 3799
  uuid: e1bb70ee-8ac0-4440-8bc9-c5a86ba442fb
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-32-7eff5e34
  type: vless
  server: 188.114.96.3
  port: 8443
  uuid: 88d05a33-ff36-415d-9d2c-7e1e8468e7e8
  udp: true
  tls: true
  network: ws
  servername: w325.pAges.Dev
  ws-opts:
    path: /Tel-@V2ray_Alpha/?ed=2560
    headers:
      Host: w325.pages.dev
- name: vip3_1-c6dbbafe
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 57a7a089-f014-4983-98bb-0c0839f3f826
  udp: true
  tls: true
  network: ws
  servername: fn2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: fn2vipys.sevenploos.com
- name: vless-34c32aa6
  type: vless
  server: 104.21.64.1
  port: 443
  uuid: 35d6531f-93ad-4dfe-b5ba-b8c3ef8698d4
  udp: true
  tls: true
  network: ws
  servername: 2-7Uo.PagEs.DEv
  ws-opts:
    path: /xlGoN1XjOZ8DpxrA?ed=2560
    headers:
      Host: 2-7uo.pages.dev
- name: vless-ae6340e1
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: Telegram--SRCVPN
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: چنل_عضو_شو_v2ra_config-5951c0fb
  type: vless
  server: turbooserver.sadafspace.com
  port: 55990
  uuid: turboo-server
  udp: true
  tls: false
  network: tcp
  servername: canva.com
  reality-opts:
    public-key: TbZDTzAIogOy-LWQjdqXElxPlUd6xdcwd9xxCqhbj04
    short-id: eebcfab3
- name: عضو_شو__zibanabz-228db75b
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: NETMelliAnti_جوین_نزنی_آف_میشه-1d2e4ee7
  type: vless
  server: specxtech.ticketdatabase.info
  port: 15416
  uuid: 9c28e484-55ed-4756-a6dc-64a9ec7141da
  udp: true
  tls: false
  network: xhttp
  servername: www.yahoo.com
  reality-opts:
    public-key: xxlEy493Vsha05CKs_07jt2MFaxLejTx4Ab1xFNAlno
    short-id: 1ed94ed9
- name: vless-7007a217
  type: vless
  server: 23.227.38.32
  port: 2053
  uuid: 39f9a4f4-f2c6-4aea-b6ce-0c6a3e410051
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /homepage?ed=2560
    headers:
      Host: mojito.djjw8292n.ir
- name: عضو_شو__zibanabz-2aee3b26
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: Channel__v2rayconfigsNN-eb7e95d3
  type: vless
  server: statue.lnmarketplace.net
  port: 443
  uuid: 7c63f43f-f526-49bb-b5c8-2be26e11ef00
  udp: true
  tls: true
  network: xhttp
  servername: statue.lnmarketplace.net
- name: eli2-dffe794a
  type: vless
  server: turboo-server.sadafspace.com
  port: 48723
  uuid: turboo-server
  udp: true
  tls: false
  network: grpc
  servername: tgju.org
  reality-opts:
    public-key: 1WQPNVCS8laWlmbHO-WnqXCqvlPcKQkb_hK_5eBmrH0
    short-id: b3
- name: vip1_2-7e49f2e1
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: 9f0b9ab6-f501-4892-b8e9-d0a19ea469f8
  udp: true
  tls: false
  network: xhttp
- name: vless-6027cf5c
  type: vless
  server: rep.neth.electroluxxv.ir
  port: 2689
  uuid: f11e1c5d-eb79-4ed7-822a-b3c22b4c45db
  udp: true
  tls: false
  network: grpc
  servername: tgju.org
  reality-opts:
    public-key: L4WAAdlTv7i2tDZwPcvYrCfZg2IDCI_sp5LElu3u91U
    short-id: b6c24852f86067a6
- name: England-8550227f
  type: vless
  server: uk.pixvpn.app
  port: 8443
  uuid: d6aa457d-8214-40d0-b5fe-3f7b551cb1c6
  udp: true
  tls: false
  network: grpc
  servername: jd.com
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: c13a37127db7ebd0
- name: vip2_1-c340b315
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 6f9da396-2b23-4880-9a38-57de11db5630
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: USA-844536c1
  type: vless
  server: em-4.webnama.com.tr
  port: 3789
  uuid: e1bb70ee-8ac0-4440-8bc9-c5a86ba442fb
  udp: true
  tls: false
  network: tcp
- name: vless-f1491bc9
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram-SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: GheychiAmoozesh-31-c0510138
  type: vless
  server: 300232332.webnama.com.tr.privatepack.ir
  port: 1517
  uuid: 88f9173d-09b1-463a-99c8-e39852693cba
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-92533339
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: GheychiAmoozesh-37-9de54b1e
  type: vless
  server: 104.22.24.195
  port: 443
  uuid: 96479a22-9333-4b03-9912-4dd26acef75e
  udp: true
  tls: true
  network: ws
  servername: NExtfilmtOmovies.sitE
  ws-opts:
    path: /9EkfcCDedhvB19xj?ed=2560
    headers:
      Host: nextfilmtomovies.site
- name: NETMelliAntiسرورجدید_داخل_چنل-a2633ee1
  type: vmess
  server: 104.16.0.0
  port: 443
  uuid: 9c28e484-55ed-4756-a6dc-64a9ec7141da
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /9c28e484-55ed-4756-a6dc-64a9ec7141da-vm?ed=2048
    headers:
      Host: asks-refers-zshops-journalists.trycloudflare.com
- name: net0n3_459-d599665b
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  servername: gEtasa.IR
  ws-opts:
    path: /WrQunvc9WRIaU32H?ed=2560
    headers:
      Host: getasa.ir
- name: France-ba68e9dc
  type: vless
  server: fr.pixvpn.app
  port: 8443
  uuid: d6aa457d-8214-40d0-b5fe-3f7b551cb1c6
  udp: true
  tls: false
  network: grpc
  servername: jd.com
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: c13a37127db7ebd0
- name: vip2_2-2ddba663
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: 6f9da396-2b23-4880-9a38-57de11db5630
  udp: true
  tls: false
  network: xhttp
- name: net0n3_460-f64011ce
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 8443
  uuid: 24a4aa9b-b341-4717-9d4a-00d74c2b84e0
  udp: true
  tls: true
  network: ws
  servername: D324vSmBvE.aAaZzZaAa-89.InFo
  ws-opts:
    path: /
    headers:
      Host: D324vSmBvE.aAaZzZaAa-89.InFo
- name: چنل_عضو_شو_v2ra_config-9ca9eddf
  type: vless
  server: turboo-server.sadafspace.com
  port: 48723
  uuid: turboo-server
  udp: true
  tls: false
  network: grpc
  servername: tgju.org
  reality-opts:
    public-key: 1WQPNVCS8laWlmbHO-WnqXCqvlPcKQkb_hK_5eBmrH0
    short-id: b3
- name: net0n3_451-7a752d8c
  type: vless
  server: www.speedtest.net
  port: 443
  uuid: 38046915-6d82-4d86-8510-b5bcc569d0ea
  udp: true
  tls: true
  network: ws
  servername: PaGes.deV
  ws-opts:
    path: /v2ray_configs_pools?ed=2560
    headers:
      Host: MydigiKala.pAges.dEv
- name: vless-f5df6372
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  servername: gEtaSa.IR
  ws-opts:
    path: /WrQunvc9WRIaU32H?ed=2560
    headers:
      Host: getasa.ir
- name: vless-412a8fa3
  type: vless
  server: 104.21.43.168
  port: 443
  uuid: bddacae3-5a9f-4406-a650-52614396a2f0
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /index.html?ed=2560
    headers:
      Host: s1.sUbUrl.OrG
- name: GheychiAmoozesh-35-0d02530a
  type: vless
  server: 91.99.239.156
  port: 443
  uuid: d2d29254-ad3b-495a-b209-5ccc4f12c0a4
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-33-6b364130
  type: vless
  server: 104.21.112.1
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: Germany-f554b253
  type: vless
  server: de.pixvpn.app
  port: 8443
  uuid: d6aa457d-8214-40d0-b5fe-3f7b551cb1c6
  udp: true
  tls: false
  network: grpc
  servername: jd.com
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: c13a37127db7ebd0
- name: vless-903481ea
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: Telegram-SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: عضو_شو__zibanabz-f9615b77
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: چنل_عضو_شو_v2ra_config-e386fc5f
  type: vless
  server: zula.ir
  port: 2087
  uuid: 554e89e9-5d47-408a-ee92-2fa8506bc78c
  udp: true
  tls: true
  network: ws
  servername: Hopev2.hopebook75zulawu.online
  ws-opts:
    path: /
    headers:
      Host: Hopev2.hopebook75zulawu.online.
- name: yejoriconfigجوین_شیدyejoriconfig-625784e9
  type: vless
  server: 65.109.184.141
  port: 2052
  uuid: 06618506-461f-46dc-a16d-1742e25e7f41
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-974a7002
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: GheychiAmoozesh-36-6a8b5872
  type: vless
  server: 34.247.254.247
  port: 50768
  uuid: c7e4c202-cfdf-44df-85a7-a9e7b4545a74
  udp: true
  tls: false
  network: grpc
  servername: jetbrains.com
  reality-opts:
    public-key: 7kUu70kwGDQ65WQHCBXcQ-KLQa5V8VVxX3zMML7hSlQ
    short-id: 4e78519d
- name: vless-7a5f487c
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN-
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: vless-a4d1c068
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: GheychiAmoozesh-39-464ab039
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 6f6e8f09-c1b3-48fd-ab00-18f921d875ef
  udp: true
  tls: true
  network: ws
  servername: profit.fullmargintraders.com
  ws-opts:
    path: /wsv/6f6e8f09-c1b3-48fd-ab00-18f921d875ef
    headers:
      Host: profit.fullmargintraders.com
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - vless-64f5a568
  - عضو_شو__zibanabz-fba32647
  - eli1-bbd6afba
  - عضو_شو__zibanabz-6f325bce
  - 50GB-66f8236a
  - NETMelliAnti__چنل_کانفیگ-e8f9c8f3
  - GheychiAmoozesh-38-73605ba6
  - net0n3_450-823a8629
  - net0n3_449-c1542117
  - چنل_عضو_شو_v2ra_config-bb09388d
  - عضو_شو__zibanabz-16ca1f22
  - GheychiAmoozesh-34-14065e14
  - تلگرامMCONFIGVPN-ecb7e5e0
  - Channel__v2rayconfigsNN-52ccaff2
  - net0n3_473-e43d65b0
  - vip1_1-f24b7f5e
  - MTProxynew3-5b0e646e
  - vip3_2-04aa7973
  - عضو_شو__prroxyng-3eef4986
  - eli4-7244235c
  - Poland-9b2de142
  - GheychiAmoozesh-32-7eff5e34
  - vip3_1-c6dbbafe
  - vless-34c32aa6
  - vless-ae6340e1
  - چنل_عضو_شو_v2ra_config-5951c0fb
  - عضو_شو__zibanabz-228db75b
  - NETMelliAnti_جوین_نزنی_آف_میشه-1d2e4ee7
  - vless-7007a217
  - عضو_شو__zibanabz-2aee3b26
  - Channel__v2rayconfigsNN-eb7e95d3
  - eli2-dffe794a
  - vip1_2-7e49f2e1
  - vless-6027cf5c
  - England-8550227f
  - vip2_1-c340b315
  - USA-844536c1
  - vless-f1491bc9
  - GheychiAmoozesh-31-c0510138
  - عضو_شو__zibanabz-92533339
  - GheychiAmoozesh-37-9de54b1e
  - NETMelliAntiسرورجدید_داخل_چنل-a2633ee1
  - net0n3_459-d599665b
  - France-ba68e9dc
  - vip2_2-2ddba663
  - net0n3_460-f64011ce
  - چنل_عضو_شو_v2ra_config-9ca9eddf
  - net0n3_451-7a752d8c
  - vless-f5df6372
  - vless-412a8fa3
  - GheychiAmoozesh-35-0d02530a
  - GheychiAmoozesh-33-6b364130
  - Germany-f554b253
  - vless-903481ea
  - عضو_شو__zibanabz-f9615b77
  - چنل_عضو_شو_v2ra_config-e386fc5f
  - yejoriconfigجوین_شیدyejoriconfig-625784e9
  - عضو_شو__zibanabz-974a7002
  - GheychiAmoozesh-36-6a8b5872
  - vless-7a5f487c
  - vless-a4d1c068
  - GheychiAmoozesh-39-464ab039
- name: AUTO
  type: url-test
  proxies:
  - vless-64f5a568
  - عضو_شو__zibanabz-fba32647
  - eli1-bbd6afba
  - عضو_شو__zibanabz-6f325bce
  - 50GB-66f8236a
  - NETMelliAnti__چنل_کانفیگ-e8f9c8f3
  - GheychiAmoozesh-38-73605ba6
  - net0n3_450-823a8629
  - net0n3_449-c1542117
  - چنل_عضو_شو_v2ra_config-bb09388d
  - عضو_شو__zibanabz-16ca1f22
  - GheychiAmoozesh-34-14065e14
  - تلگرامMCONFIGVPN-ecb7e5e0
  - Channel__v2rayconfigsNN-52ccaff2
  - net0n3_473-e43d65b0
  - vip1_1-f24b7f5e
  - MTProxynew3-5b0e646e
  - vip3_2-04aa7973
  - عضو_شو__prroxyng-3eef4986
  - eli4-7244235c
  - Poland-9b2de142
  - GheychiAmoozesh-32-7eff5e34
  - vip3_1-c6dbbafe
  - vless-34c32aa6
  - vless-ae6340e1
  - چنل_عضو_شو_v2ra_config-5951c0fb
  - عضو_شو__zibanabz-228db75b
  - NETMelliAnti_جوین_نزنی_آف_میشه-1d2e4ee7
  - vless-7007a217
  - عضو_شو__zibanabz-2aee3b26
  - Channel__v2rayconfigsNN-eb7e95d3
  - eli2-dffe794a
  - vip1_2-7e49f2e1
  - vless-6027cf5c
  - England-8550227f
  - vip2_1-c340b315
  - USA-844536c1
  - vless-f1491bc9
  - GheychiAmoozesh-31-c0510138
  - عضو_شو__zibanabz-92533339
  - GheychiAmoozesh-37-9de54b1e
  - NETMelliAntiسرورجدید_داخل_چنل-a2633ee1
  - net0n3_459-d599665b
  - France-ba68e9dc
  - vip2_2-2ddba663
  - net0n3_460-f64011ce
  - چنل_عضو_شو_v2ra_config-9ca9eddf
  - net0n3_451-7a752d8c
  - vless-f5df6372
  - vless-412a8fa3
  - GheychiAmoozesh-35-0d02530a
  - GheychiAmoozesh-33-6b364130
  - Germany-f554b253
  - vless-903481ea
  - عضو_شو__zibanabz-f9615b77
  - چنل_عضو_شو_v2ra_config-e386fc5f
  - yejoriconfigجوین_شیدyejoriconfig-625784e9
  - عضو_شو__zibanabz-974a7002
  - GheychiAmoozesh-36-6a8b5872
  - vless-7a5f487c
  - vless-a4d1c068
  - GheychiAmoozesh-39-464ab039
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
