mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-78bdc90d
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-a41fa107
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-8c2871d1
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-edaf744a
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-9eabc911
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-06d27722
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-ea9f82da
  type: vless
  server: accounting.vinamarketcenter.ir
  port: 443
  uuid: 5cfba4ac-105a-452a-ac10-88b1adf784ee
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: T7Cwk-B3EvZqqRywIgN_TNotJiUOXYUI9bHqYKPnTi0
    short-id: 105e89ba3d2a1c3b
- name: vless-4d74082a
  type: vless
  server: 91.99.160.151
  port: 443
  uuid: 153ee04c-dcc1-4ef8-a146-8fb31cec1f48
  udp: true
  network: tcp
- name: vless-3bd29d0d
  type: vless
  server: 62.60.223.6
  port: 2080
  uuid: bea34b73-3244-475b-b914-7bb80e1cda91
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: L3lJWdU7mHijSkNaNt-m29OYnKnHvHYRxg2Y8XXFdng
    short-id: bf517367267685
- name: vless-594c9727
  type: vless
  server: 91.99.195.6
  port: 80
  uuid: 91a5d5b3-4b88-4359-aeec-e1532f535fd6
  udp: true
  network: grpc
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZO276Z5WXIqCmNLXT8Lewzjhhgm365JUJXAKyKq8Rz4
    short-id: bc063769cb
  grpc-opts:
    grpc-service-name: refersion.com
- name: vless-08aac2c0
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /zula.ir
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: vless-a8acf328
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-f6c38bb6
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-cde65998
  type: vless
  server: 91.99.184.231
  port: 45103
  uuid: 6bdc18b7-a33f-46ae-a5e3-df7cb21f36b2
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: vless-94b025a4
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: turboo-server
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: turboo-server1.game
- name: httpstmeV2ry_Proxy-c554f29c
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: telegram-id-ArV2ray
  udp: true
  network: ws
  ws-opts:
    path: /-Arfilter%
    headers:
      Host: www.speedtest.net.a.3.speedtest2029.com.
- name: httpstmeV2ry_Proxy-1f12f45c
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: telegram-id-ArV2ray
  udp: true
  network: ws
  ws-opts:
    path: /-Arfilter@Arfilter-TEL--@Arfilter-TEL--@Arfilter-TEL--@Arfilter-JOIN-@Arfilter-TEL--@Arfilter-JOIN-@Arfilter-TEL-@Arfilter-TEL--@Arfilter-JOIN-@Arfilter-TEL--@Arfilter?ed=80
    headers:
      Host: www.speedtest.net.a.3.speedtest2029.com.
- name: httpstmeV2ry_Proxy-fd2ee2f6
  type: vless
  server: 104.16.53.11
  port: 8443
  uuid: 7c9e3c1d-a360-4429-9189-e45a98de7fde
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: my.ski1plag.ir
  ws-opts:
    path: /Telegram@V2ray_Alpha
    headers:
      Host: my.ski1plag.ir
- name: httpstmeV2ry_Proxy-654d1150
  type: vless
  server: 104.16.53.11
  port: 8443
  uuid: 7c9e3c1d-a360-4429-9189-e45a98de7fde
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: my.ski1plag.ir
  ws-opts:
    path: /Telegram@Config_Rayegan
    headers:
      Host: my.ski1plag.ir
- name: مشتی_جوین_بده_ناموصا__xzjinx-abfcadc0
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: 49203d20-5f1b-4628-d526-9a6825c3f5f3
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-721051f0
  type: vless
  server: 5.160.197.120
  port: 16644
  uuid: c2d3a355-e556-40e0-cd5a-41dff6eb525d
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-12eb8af1
  type: vless
  server: 91.107.144.102
  port: 443
  uuid: edf3ab50-46b4-4046-eaf9-db12fe598cd1
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-7164fbc7
  type: vless
  server: chrom3.infospeedtest.com
  port: 13096
  uuid: bb497033-e322-4316-ce08-b8a9716b6a3d
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-a3363fa3
  type: vless
  server: esi.infospeedtest.com
  port: 13286
  uuid: 2ee55469-d026-410b-f4bc-844a63a1342d
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-32287477
  type: vless
  server: chrom3.infospeedtest.com
  port: 13096
  uuid: b8b81afb-c24b-43b7-e816-0b7dcaf4ce67
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-80afdbcd
  type: vless
  server: 91.107.144.102
  port: 443
  uuid: 75542618-2a4e-4e94-cd5d-f2866e284901
  udp: true
  network: tcp
- name: Sezar_Sec-8d076ac6
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-d2fc68a1
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-b5abfa2b
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: Sezar_Sec-4458f74b
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: Sezar_Sec-bb5b84be
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: barayeiranmahsang.sabzipolobamahi.dpdns.org
  ws-opts:
    path: /?ed=2560/?CHANEL@RK_VPS@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-78bdc90d
  - vless-a41fa107
  - vless-8c2871d1
  - vless-edaf744a
  - vless-9eabc911
  - vless-06d27722
  - vless-ea9f82da
  - vless-4d74082a
  - vless-3bd29d0d
  - vless-594c9727
  - vless-08aac2c0
  - vless-a8acf328
  - vless-f6c38bb6
  - vless-cde65998
  - vless-94b025a4
  - httpstmeV2ry_Proxy-c554f29c
  - httpstmeV2ry_Proxy-1f12f45c
  - httpstmeV2ry_Proxy-fd2ee2f6
  - httpstmeV2ry_Proxy-654d1150
  - مشتی_جوین_بده_ناموصا__xzjinx-abfcadc0
  - مشتیجوینبدهناموصاxzjinx-721051f0
  - مشتیجوینبدهناموصاxzjinx-12eb8af1
  - مشتیجوینبدهناموصاxzjinx-7164fbc7
  - مشتی_جوین_بده_ناموصا__xzjinx-a3363fa3
  - مشتی_جوین_بده_ناموصا__xzjinx-32287477
  - مشتی_جوین_بده_ناموصا__xzjinx-80afdbcd
  - Sezar_Sec-8d076ac6
  - Sezar_Sec-d2fc68a1
  - Sezar_Sec-b5abfa2b
  - Sezar_Sec-4458f74b
  - Sezar_Sec-bb5b84be
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
