mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-8f990786
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-ce10c17b
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-18b09d80
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-75d89b0b
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-13f786de
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-899dea06
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-01d38363
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-3b9bb637
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: 300گیگ_39تومان_تسترایگانTickV2bot-ca72ad6b
  type: vmess
  server: dn29.multi-panel.info
  port: 3264
  uuid: a13e6708-fc2f-4efd-84b1-7b50b1375617
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: 300گیگ_39تومان_تسترایگانTickV2bot-38010e4e
  type: vmess
  server: dn29.multi-panel.info
  port: 3264
  uuid: a13e6708-fc2f-4efd-84b1-7b50b1375617
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-2821ade6
  type: vless
  server: viop.fast.hosting-ip.com
  port: 80
  uuid: V2rayNGFreeeV2rayNGFreeee
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: M2M.global.ssl.fastly.net
- name: قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-7c255971
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: Germany_1-855d08b2
  type: vless
  server: 300232332.webnama.com.tr
  port: 1517
  uuid: 188f1242-b0c0-4992-b480-1da44dae1700
  udp: true
  network: tcp
- name: vless-292848b6
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  network: tcp
- name: vless-66d1e4a9
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-11082b19
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_281-e80ebfd5
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-d90cc538
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: nginx.nscl.ir
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_276-216a6097
  type: ss
  server: h110vpnnl.outlinekeys.net
  port: 52571
  cipher: chacha20-ietf-poly1305
  password: 2nvtG6pl4Om1G0cWlnyXHl
  udp: true
- name: vless-c1b88f4a
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 92f481b6-ad92-43e4-a683-2bb0aeaa9846
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: dw.alibichareh.dpdns.org
- name: vless-8c67e3a4
  type: vless
  server: 300232332.webnama.com.tr
  port: 1517
  uuid: 3d554bba-9c77-499f-9055-1eb42058ed00
  udp: true
  network: tcp
- name: net0n3_274-3f6815fb
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-726499ba
  type: vless
  server: www.speedtest.net
  port: 2096
  uuid: dc80ee7e-bad0-450c-a218-f12e05680885
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /?ed=2096
    headers:
      Host: arm1.dollardoon.com
- name: Sezar_Sec-e5992c72
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-34ea3f34
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: Sezar_Sec-e27c1e2a
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-1c3e2d54
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-a741f304
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-1b8ef1f0
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-cb8ad842
  type: vless
  server: 94.182.136.184
  port: 159
  uuid: 0af94a54-f5d8-43dd-8544-77a56559ea1c
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-4e670d69
  type: vless
  server: 31.47.45.173
  port: 777
  uuid: ce55d3ed-618b-45b7-d879-368fbb465efd
  udp: true
  network: tcp
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-8f990786
  - vless-ce10c17b
  - vless-18b09d80
  - vless-75d89b0b
  - vless-13f786de
  - vless-899dea06
  - vless-01d38363
  - vless-3b9bb637
  - 300گیگ_39تومان_تسترایگانTickV2bot-ca72ad6b
  - 300گیگ_39تومان_تسترایگانTickV2bot-38010e4e
  - نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-2821ade6
  - قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-7c255971
  - Germany_1-855d08b2
  - vless-292848b6
  - vless-66d1e4a9
  - vless-11082b19
  - net0n3_281-e80ebfd5
  - vless-d90cc538
  - net0n3_276-216a6097
  - vless-c1b88f4a
  - vless-8c67e3a4
  - net0n3_274-3f6815fb
  - vless-726499ba
  - Sezar_Sec-e5992c72
  - Sezar_Sec-34ea3f34
  - Sezar_Sec-e27c1e2a
  - Sezar_Sec-1c3e2d54
  - Sezar_Sec-a741f304
  - مشتی_جوین_بده_ناموصا__xzjinx-1b8ef1f0
  - مشتی_جوین_بده_ناموصا__xzjinx-cb8ad842
  - مشتی_جوین_بده_ناموصا__xzjinx-4e670d69
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
