port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: GheychiAmoozesh-11-82674ea1
  type: vless
  server: sp4.god-ping.net
  port: 2051
  uuid: 2725451d-5f83-4998-9f2f-193e656e3bc7
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-25-187dbf2f
  type: ss
  server: 131.145.33.92
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
- name: test-d9768dab
  type: trojan
  server: 108.162.196.109
  port: 443
  password: havij-koloche-holo
  udp: true
  sni: broken-queen-dfb7.mehdizx35.workers.dev
- name: vless-6c7d041a
  type: vless
  server: 5.75.197.120
  port: 2025
  uuid: 54b4c039-7be6-448f-b704-820251b079db
  udp: true
  tls: false
  network: grpc
  servername: www.cloudflare.com
  reality-opts:
    public-key: AUNIYov4R2TvNmC0cF0NiKWYGqzikosOu4g2wcCALlw
    short-id: 8d9c20be72b4
- name: vless-1d9ef202
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: Telegram-SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: عضو_شو__zibanabz-b7122021
  type: vless
  server: 172.67.145.189
  port: 2083
  uuid: ec7a6b6d-94b6-45df-9d62-491f53a508be
  udp: true
  tls: true
  network: ws
  servername: FrEEdoM.pAnOtOSU.sTORe
  ws-opts:
    path: /6fqYRq6DD1shcFIO/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=?ed=2560
    headers:
      Host: freedom.panotosu.store
- name: WS-All__ArV2ray-bef3eae6
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: telegram-id-Arfilter
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-Arfilter@Arfilter-TEL--@Arfilter-TEL--@Arfilter-TEL--@Arfilter-JOIN-@Arfilter-TEL--@Arfilter-JOIN-@Arfilter-TEL-@Arfilter-TEL--@Arfilter-JOIN-@Arfilter-TEL--@Arfilter?ed=80
    headers:
      Host: www.speedtest.net.a.4.speedtest2029.com.
- name: GheychiAmoozesh-17-d6261c32
  type: ss
  server: h110vpnch.outlinekeys.net
  port: 4248
  cipher: chacha20-ietf-poly1305
  password: SasawZo4g7WaqlK3a2mCol
  udp: true
- name: vless-8b0ff5ea
  type: vless
  server: 104.21.32.1
  port: 2096
  uuid: 8ca4ca74-fa0c-4c18-86c5-ce6d0382ff14
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: DO-iTforyOu-E1P.PAgeS.dEV
- name: GheychiAmoozesh-12-5bac93be
  type: vless
  server: 151.101.67.8
  port: 80
  uuid: 8088c605-e0c2-4774-9ee4-7fa7e47b6112
  udp: true
  tls: false
  network: tcp
- name: vless-d3312ad8
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: Telegram--SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: test2-e70b5556
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: 29cbae1c-0d29-4213-8220-d1302816c4b1
  udp: true
  tls: false
  network: xhttp
- name: GheychiAmoozesh-39-9260fd88
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 6f6e8f09-c1b3-48fd-ab00-18f921d875ef
  udp: true
  tls: true
  network: ws
  servername: profit.fullmargintraders.com
  ws-opts:
    path: /wsv/6f6e8f09-c1b3-48fd-ab00-18f921d875ef
    headers:
      Host: profit.fullmargintraders.com
- name: Sezar_Sec-a80e9554
  type: vless
  server: zzyd6dhd5.pet0er23mh21qq.com
  port: 8080
  uuid: 598a6cea-dfd2-4e97-9415-4571f742bf18
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-20-959cf924
  type: ss
  server: series-a1.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
- name: عضو_شو__zibanabz-a16f4d4e
  type: vless
  server: 104.18.29.253
  port: 443
  uuid: 9dd24d01-2b7a-4bd8-8c76-129d6ca89b8c
  udp: true
  tls: true
  network: ws
  servername: kawaiifreevpn-7ds.pages.dev
  ws-opts:
    path: /?ed=2560
    headers:
      Host: kawaiifreevpn-7ds.pages.dev
- name: GheychiAmoozesh-33-9bb1c571
  type: vless
  server: 104.21.112.1
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: GheychiAmoozesh-38-c5927efe
  type: vless
  server: 104.21.36.57
  port: 443
  uuid: 7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
  udp: true
  tls: true
  network: ws
  servername: avtice.fullmargintraders.com
  ws-opts:
    path: /wsv/7f1c42b8-069d-4fbe-8cdc-0fc1a131c8a8
    headers:
      Host: avtice.fullmargintraders.com
- name: GheychiAmoozesh-24-b9fb4875
  type: vless
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  port: 2096
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  udp: true
  tls: true
  network: ws
  servername: Ft77Ta8Q1m.EmShAbKhObE.oRg
  ws-opts:
    path: /
    headers:
      Host: Ft77Ta8Q1m.EmShAbKhObE.oRg
- name: vless-ac33195d
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN-
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: GheychiAmoozesh-37-5db522f9
  type: vless
  server: 104.22.24.195
  port: 443
  uuid: 96479a22-9333-4b03-9912-4dd26acef75e
  udp: true
  tls: true
  network: ws
  servername: NExtfilmtOmovies.sitE
  ws-opts:
    path: /9EkfcCDedhvB19xj?ed=2560
    headers:
      Host: nextfilmtomovies.site
- name: Viturey_2-38eb99f1
  type: vless
  server: 157.180.33.125
  port: 80
  uuid: 9603de7d-1248-a741-1d69-7e1a0fb9e693
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /Javid-SHAH-KingRezaPahlavi/
    headers:
      Host: null
- name: Sezar_Sec-f9530d3c
  type: vmess
  server: panel1.ipyar.org
  port: 42684
  uuid: c4bd9eba-8aea-4d5e-a2ee-b5de65ac14e1
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: GheychiAmoozesh-19-6d079c4f
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-b413d9bc
  type: vless
  server: 172.66.44.253
  port: 8443
  uuid: efed37ed-37e5-4100-a540-049dc7929984
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /dy26vBaDi5RTblzP?ed=2560
    headers:
      Host: net-aCcOUNt02.Pages.DEv
- name: vless-c8a4d33a
  type: vless
  server: 104.21.43.168
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /bDUGlAj9BFG7zebG?ed=2560
    headers:
      Host: 2.lINK-KoN.IR
- name: GheychiAmoozesh-35-777dad7e
  type: vless
  server: 91.99.239.156
  port: 443
  uuid: d2d29254-ad3b-495a-b209-5ccc4f12c0a4
  udp: true
  tls: false
  network: tcp
- name: Channel__CaptalVpn-91cecec1
  type: vless
  server: 104.16.34.128
  port: 443
  uuid: 267613d7-f53f-4005-b642-d6f1f687b7cf
  udp: true
  tls: true
  network: ws
  servername: ensHOLP-91s.pageS.DEv
  ws-opts:
    path: /dQMN2VQLkaE52qWD?ed=2560
    headers:
      Host: ensHOLP-91s.pageS.DEv
- name: Sezar_Sec-6b361ca7
  type: vmess
  server: panel3.ipyar.org
  port: 32017
  uuid: c0ccdeb9-784c-4d67-b904-20dcaac9902a
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  udp: true
- name: vless-4eb97535
  type: vless
  server: 85.234.65.120
  port: 443
  uuid: fdc0229d-2037-48c4-94d3-496e67cce5d8
  udp: true
  tls: false
  network: tcp
  servername: github.com
  reality-opts:
    public-key: 307pppp6s7XwguGbsjY3xaJPIubgj_D8zNJT5SmtsVA
    short-id: f90c
- name: vless-25d0d8ee
  type: vless
  server: 172.66.47.61
  port: 2053
  uuid: a396b860-11b7-4af3-9950-146caf79735e
  udp: true
  tls: true
  network: ws
  servername: gGHDFa.pAgeS.Dev
  ws-opts:
    path: /8WuhXm4QjK0L68Uf?ed=2560
    headers:
      Host: gghdfa.pages.dev
- name: Channelvmessorg-4dc9f8be
  type: vless
  server: 104.21.43.168
  port: 443
  uuid: e2c0a0ac-0270-4ebc-acbd-75df71153b0e
  udp: true
  tls: true
  network: ws
  servername: 2.link-kon.ir
  ws-opts:
    path: /bDUGlAj9BFG7zebG?ed=2560
    headers:
      Host: 2.lINK-KoN.IR
- name: vless-d16a33fe
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram-SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: عضو_شو__zibanabz-714185bd
  type: vless
  server: 188.114.99.16
  port: 2053
  uuid: 54f6e78c-b497-4db7-ba48-38c4cf81d5ef
  udp: true
  tls: true
  network: ws
  servername: 019309B7.XyZ0.PaGeS.dEV
  ws-opts:
    path: /yzejftqqvmhtztle?ed=2560
    headers:
      Host: 019309B7.XyZ0.PaGeS.dEV
- name: GheychiAmoozesh-23-c1838d27
  type: vless
  server: 135.148.152.106
  port: 443
  uuid: ea286109-d20f-415e-849e-4af20ab04b65
  udp: true
  tls: true
  network: tcp
  servername: 147135001195.sec22org.com
- name: عضو_شو__zibanabz-674140bd
  type: vless
  server: 141.101.121.243
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: GheychiAmoozesh-15-2e74e54f
  type: vless
  server: 108.162.198.20
  port: 8880
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: reedfree8mahsang2.redorg.ir
- name: عضو_شو__zibanabz-97ba3e55
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: GheychiAmoozesh-14-e9631c87
  type: ss
  server: series-a2-mec.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: vless-270ab1f3
  type: vless
  server: 88.99.87.227
  port: 2090
  uuid: Telegram--SRCVPN--
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: GheychiAmoozesh-21-9bf2967d
  type: ss
  server: series-a2.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: telegram_id__Viturey-205b26fb
  type: vless
  server: lingering-boat-0b47.vpnetwork3567.workers.dev
  port: 443
  uuid: 563B4029-2161-7E31-FA35-1B21441AE537
  udp: true
  tls: true
  network: ws
  servername: lingering-boat-0b47.vpnetwork3567.workers.dev
  ws-opts:
    path: /
    headers:
      Host: lingering-boat-0b47.vpnetwork3567.workers.dev
- name: GheychiAmoozesh-32-4679dcb7
  type: vless
  server: 188.114.96.3
  port: 8443
  uuid: 88d05a33-ff36-415d-9d2c-7e1e8468e7e8
  udp: true
  tls: true
  network: ws
  servername: w325.pAges.Dev
  ws-opts:
    path: /Tel-@V2ray_Alpha/?ed=2560
    headers:
      Host: w325.pages.dev
- name: GheychiAmoozesh-13-476d2364
  type: ss
  server: dl.2046.shield-web.ir
  port: 2046
  cipher: chacha20-ietf-poly1305
  password: YZbYU8NosZCi7zuUI5hDlw
  udp: true
- name: vless-7692f02c
  type: vless
  server: 104.21.112.1
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: test4-c8c2fb73
  type: vless
  server: end.fast.hosting-ip.com
  port: 80
  uuid: baf334b7-f07e-420d-8efb-060cb3fff630
  udp: true
  tls: false
  network: xhttp
- name: GheychiAmoozesh-16-6f2609b8
  type: vless
  server: c1.lightxpro.ir
  port: 35775
  uuid: 8c57716b-d545-47b3-981e-c3bbd5a09b3c
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: null
- name: GheychiAmoozesh-18-a5369d46
  type: ss
  server: h110vpnus.outlinekeys.net
  port: 9483
  cipher: chacha20-ietf-poly1305
  password: nLwAl3svNCBPtG9I2FrVYI
  udp: true
- name: Sezar_Sec-a7bfdc16
  type: vless
  server: 185.243.51.67
  port: 21760
  uuid: 73e10f2a-bb9a-40c1-8e2c-ebfe0dac1dac
  udp: true
  tls: false
  network: tcp
- name: test3-d81ec46f
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: baf334b7-f07e-420d-8efb-060cb3fff630
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: Channel__CaptalVpn-9311bdd2
  type: vless
  server: 104.21.112.1
  port: 80
  uuid: 2036e2c3-18a5-4eed-9db4-f91a7f02c7d5
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /193.123.81.105=443
    headers:
      Host: zoomgov.vipren.biz.id
- name: GheychiAmoozesh-31-c6aee83c
  type: vless
  server: 300232332.webnama.com.tr.privatepack.ir
  port: 1517
  uuid: 88f9173d-09b1-463a-99c8-e39852693cba
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__zibanabz-38882e8c
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: vless-d0c28c2f
  type: vless
  server: 91.99.141.177
  port: 443
  uuid: 1a827c35-7a17-48d8-a9f5-eeed323ca57b
  udp: true
  tls: false
  network: tcp
  servername: refersion.com
  reality-opts:
    public-key: SJt4jAvhiR5MVRnl-OPj2BWUXZT6p4oH-Ugl3B0b-VA
    short-id: 8ad4b0d652d3e8
- name: GheychiAmoozesh-22-ce184c8f
  type: ss
  server: admin.c2.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: WstuSnlu4ieA9M0L
  udp: true
- name: Channelvmessorg-b6066901
  type: vless
  server: 91.107.150.172
  port: 443
  uuid: 9767a982-d18d-4634-ad2b-c93489cbffae
  udp: true
  tls: false
  network: tcp
- name: عضو_شو__prroxyng-98ac4c97
  type: ss
  server: admin.c4.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 69MUii7VDwMqh7Hz
  udp: true
- name: test1-f0078a9f
  type: vless
  server: www.speedtest.net
  port: 8443
  uuid: 29cbae1c-0d29-4213-8220-d1302816c4b1
  udp: true
  tls: true
  network: ws
  servername: de2vipys.sevenploos.com
  ws-opts:
    path: /
    headers:
      Host: de2vipys.sevenploos.com
- name: GheychiAmoozesh-34-808616b0
  type: vless
  server: 95.164.45.85
  port: 8880
  uuid: df0680ca-e43c-498d-ed86-8e196eedd012
  udp: true
  tls: false
  network: grpc
- name: vless-8546e6c2
  type: vless
  server: 88.99.87.227
  port: 2080
  uuid: 63fa5580-1bb7-4cc1-a6ee-0ed4eaa52308
  udp: true
  tls: false
  network: grpc
  servername: journalofbigdata.springeropen.com
  reality-opts:
    public-key: MqY81IaljluV2NXyLqPzt7PL12knwUuBiX0ru_KSLCM
    short-id: aa0dd5ba
- name: قطع_شد_بیا_اینجا_بردارV2GaMaBot-583d2070
  type: vless
  server: 85.133.215.172
  port: 8080
  uuid: fd704838-af11-436e-84c3-5c89d649fbd4
  udp: true
  tls: false
  network: tcp
- name: GheychiAmoozesh-27-5dd07bcd
  type: ss
  server: series-a2-mec.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: u17T3BvpYaaiuW2c
  udp: true
- name: عضو_شو__zibanabz-5a9888d3
  type: vless
  server: 162.159.129.67
  port: 8443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet1-706.pages.dev
  ws-opts:
    path: /azadnet1-706.pages.dev/?ed=2560&PROT_TYPE=vless
    headers:
      Host: azadnet1-706.pages.dev
- name: عضو_شو__zibanabz-5ae3720a
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: GheychiAmoozesh-26-b8837e53
  type: ss
  server: freakconfig13.felafel.org
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1xO2cqPazqjGfCfd
  udp: true
- name: GheychiAmoozesh-36-0f7a439d
  type: vless
  server: 34.247.254.247
  port: 50768
  uuid: c7e4c202-cfdf-44df-85a7-a9e7b4545a74
  udp: true
  tls: false
  network: grpc
  servername: jetbrains.com
  reality-opts:
    public-key: 7kUu70kwGDQ65WQHCBXcQ-KLQa5V8VVxX3zMML7hSlQ
    short-id: 4e78519d
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - GheychiAmoozesh-11-82674ea1
  - GheychiAmoozesh-25-187dbf2f
  - test-d9768dab
  - vless-6c7d041a
  - vless-1d9ef202
  - عضو_شو__zibanabz-b7122021
  - WS-All__ArV2ray-bef3eae6
  - GheychiAmoozesh-17-d6261c32
  - vless-8b0ff5ea
  - GheychiAmoozesh-12-5bac93be
  - vless-d3312ad8
  - test2-e70b5556
  - GheychiAmoozesh-39-9260fd88
  - Sezar_Sec-a80e9554
  - GheychiAmoozesh-20-959cf924
  - عضو_شو__zibanabz-a16f4d4e
  - GheychiAmoozesh-33-9bb1c571
  - GheychiAmoozesh-38-c5927efe
  - GheychiAmoozesh-24-b9fb4875
  - vless-ac33195d
  - GheychiAmoozesh-37-5db522f9
  - Viturey_2-38eb99f1
  - Sezar_Sec-f9530d3c
  - GheychiAmoozesh-19-6d079c4f
  - vless-b413d9bc
  - vless-c8a4d33a
  - GheychiAmoozesh-35-777dad7e
  - Channel__CaptalVpn-91cecec1
  - Sezar_Sec-6b361ca7
  - vless-4eb97535
  - vless-25d0d8ee
  - Channelvmessorg-4dc9f8be
  - vless-d16a33fe
  - عضو_شو__zibanabz-714185bd
  - GheychiAmoozesh-23-c1838d27
  - عضو_شو__zibanabz-674140bd
  - GheychiAmoozesh-15-2e74e54f
  - عضو_شو__zibanabz-97ba3e55
  - GheychiAmoozesh-14-e9631c87
  - vless-270ab1f3
  - GheychiAmoozesh-21-9bf2967d
  - telegram_id__Viturey-205b26fb
  - GheychiAmoozesh-32-4679dcb7
  - GheychiAmoozesh-13-476d2364
  - vless-7692f02c
  - test4-c8c2fb73
  - GheychiAmoozesh-16-6f2609b8
  - GheychiAmoozesh-18-a5369d46
  - Sezar_Sec-a7bfdc16
  - test3-d81ec46f
  - Channel__CaptalVpn-9311bdd2
  - GheychiAmoozesh-31-c6aee83c
  - عضو_شو__zibanabz-38882e8c
  - vless-d0c28c2f
  - GheychiAmoozesh-22-ce184c8f
  - Channelvmessorg-b6066901
  - عضو_شو__prroxyng-98ac4c97
  - test1-f0078a9f
  - GheychiAmoozesh-34-808616b0
  - vless-8546e6c2
  - قطع_شد_بیا_اینجا_بردارV2GaMaBot-583d2070
  - GheychiAmoozesh-27-5dd07bcd
  - عضو_شو__zibanabz-5a9888d3
  - عضو_شو__zibanabz-5ae3720a
  - GheychiAmoozesh-26-b8837e53
  - GheychiAmoozesh-36-0f7a439d
- name: AUTO
  type: url-test
  proxies:
  - GheychiAmoozesh-11-82674ea1
  - GheychiAmoozesh-25-187dbf2f
  - test-d9768dab
  - vless-6c7d041a
  - vless-1d9ef202
  - عضو_شو__zibanabz-b7122021
  - WS-All__ArV2ray-bef3eae6
  - GheychiAmoozesh-17-d6261c32
  - vless-8b0ff5ea
  - GheychiAmoozesh-12-5bac93be
  - vless-d3312ad8
  - test2-e70b5556
  - GheychiAmoozesh-39-9260fd88
  - Sezar_Sec-a80e9554
  - GheychiAmoozesh-20-959cf924
  - عضو_شو__zibanabz-a16f4d4e
  - GheychiAmoozesh-33-9bb1c571
  - GheychiAmoozesh-38-c5927efe
  - GheychiAmoozesh-24-b9fb4875
  - vless-ac33195d
  - GheychiAmoozesh-37-5db522f9
  - Viturey_2-38eb99f1
  - Sezar_Sec-f9530d3c
  - GheychiAmoozesh-19-6d079c4f
  - vless-b413d9bc
  - vless-c8a4d33a
  - GheychiAmoozesh-35-777dad7e
  - Channel__CaptalVpn-91cecec1
  - Sezar_Sec-6b361ca7
  - vless-4eb97535
  - vless-25d0d8ee
  - Channelvmessorg-4dc9f8be
  - vless-d16a33fe
  - عضو_شو__zibanabz-714185bd
  - GheychiAmoozesh-23-c1838d27
  - عضو_شو__zibanabz-674140bd
  - GheychiAmoozesh-15-2e74e54f
  - عضو_شو__zibanabz-97ba3e55
  - GheychiAmoozesh-14-e9631c87
  - vless-270ab1f3
  - GheychiAmoozesh-21-9bf2967d
  - telegram_id__Viturey-205b26fb
  - GheychiAmoozesh-32-4679dcb7
  - GheychiAmoozesh-13-476d2364
  - vless-7692f02c
  - test4-c8c2fb73
  - GheychiAmoozesh-16-6f2609b8
  - GheychiAmoozesh-18-a5369d46
  - Sezar_Sec-a7bfdc16
  - test3-d81ec46f
  - Channel__CaptalVpn-9311bdd2
  - GheychiAmoozesh-31-c6aee83c
  - عضو_شو__zibanabz-38882e8c
  - vless-d0c28c2f
  - GheychiAmoozesh-22-ce184c8f
  - Channelvmessorg-b6066901
  - عضو_شو__prroxyng-98ac4c97
  - test1-f0078a9f
  - GheychiAmoozesh-34-808616b0
  - vless-8546e6c2
  - قطع_شد_بیا_اینجا_بردارV2GaMaBot-583d2070
  - GheychiAmoozesh-27-5dd07bcd
  - عضو_شو__zibanabz-5a9888d3
  - عضو_شو__zibanabz-5ae3720a
  - GheychiAmoozesh-26-b8837e53
  - GheychiAmoozesh-36-0f7a439d
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
