mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-1ab1d7ee
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-7d5bbf94
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-f25121eb
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-c3f8194d
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-c7c88bd9
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-93dddca7
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-68d5b0e0
  type: vless
  server: accounting.vinamarketcenter.ir
  port: 443
  uuid: 5cfba4ac-105a-452a-ac10-88b1adf784ee
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: T7Cwk-B3EvZqqRywIgN_TNotJiUOXYUI9bHqYKPnTi0
    short-id: 105e89ba3d2a1c3b
- name: SRCVPN-5c8863c2
  type: vless
  server: 150.241.65.211
  port: 443
  uuid: be5fab84-5edb-4800-927e-243f6e4309bf
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: LYJ37EcS5jyaezTVaVAVCkBWCrjXioiJHI7argkEnCU
    short-id: 236ac31d02
- name: SRCVPN-193a95fb
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: a812a015-a65b-4003-ac5f-266e141c6405
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: Www.speedtest.net.developsp.ir.vegaskala.com.
- name: vless-133e54fe
  type: vless
  server: 91.99.160.151
  port: 443
  uuid: 153ee04c-dcc1-4ef8-a146-8fb31cec1f48
  udp: true
  network: tcp
- name: vless-855c6436
  type: vless
  server: 62.60.223.6
  port: 2080
  uuid: bea34b73-3244-475b-b914-7bb80e1cda91
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: L3lJWdU7mHijSkNaNt-m29OYnKnHvHYRxg2Y8XXFdng
    short-id: bf517367267685
- name: vless-bf3b69be
  type: vless
  server: 91.99.195.6
  port: 80
  uuid: 91a5d5b3-4b88-4359-aeec-e1532f535fd6
  udp: true
  network: grpc
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZO276Z5WXIqCmNLXT8Lewzjhhgm365JUJXAKyKq8Rz4
    short-id: bc063769cb
  grpc-opts:
    grpc-service-name: refersion.com
- name: vless-3dcf73a2
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /zula.ir
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: vless-16796052
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-1afddd67
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-04763ece
  type: vless
  server: 91.99.184.231
  port: 45103
  uuid: 6bdc18b7-a33f-46ae-a5e3-df7cb21f36b2
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: vless-4a592b77
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: turboo-server
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: turboo-server1.game
- name: 300گیگ_39تومان_تسترایگانTickV2bot-30652ad6
  type: vmess
  server: 91.107.154.77
  port: 4001
  uuid: ca73250a-5395-4585-b1ec-6d2041e44aef
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: 300گیگ_39تومان_تسترایگانTickV2bot-b73ea2e2
  type: vmess
  server: 91.107.154.77
  port: 4001
  uuid: ca73250a-5395-4585-b1ec-6d2041e44aef
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-3377a58a
  type: vless
  server: 46.62.139.178
  port: 1111
  uuid: 98635c25-7ce5-416e-9a45-3fcadc878f93
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: Mgfghgjjf-15c72874
  type: vless
  server: cro.7gozar.xyz
  port: 11859
  uuid: 783963d5-969a-51a5-b449-4bb69ec6e0a1
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: aparat.com
- name: کانال_تلگرام_Club_Profsor-2b529b48
  type: vless
  server: asia7.novahomedesigntips.com
  port: 7850
  uuid: d2ec79c6-0319-4792-f2f4-d786df1b2d45
  udp: true
  network: ws
  ws-opts:
    path: /
- name: tel_melli1-29628afc
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: گپ_BLUE-873bd25f
  type: vless
  server: tunnel.aghamehdi52.ir
  port: 2000
  uuid: 1dff9598-083e-4bc2-8c91-d33df6481b3d
  udp: true
  network: tcp
- name: Sezar_Sec-6bc09e14
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-e95f8957
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-85f48f50
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: Sezar_Sec-08c8801d
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: Sezar_Sec-54b1ecc6
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: barayeiranmahsang.sabzipolobamahi.dpdns.org
  ws-opts:
    path: /?ed=2560/?CHANEL@RK_VPS@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: مشتی_جوین_بده_ناموصا__xzjinx-e60dad67
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: 49203d20-5f1b-4628-d526-9a6825c3f5f3
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-4b961bcb
  type: vless
  server: 5.160.197.120
  port: 16644
  uuid: c2d3a355-e556-40e0-cd5a-41dff6eb525d
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-a82ca0ff
  type: vless
  server: 91.107.144.102
  port: 443
  uuid: edf3ab50-46b4-4046-eaf9-db12fe598cd1
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-bf60ae89
  type: vless
  server: chrom3.infospeedtest.com
  port: 13096
  uuid: bb497033-e322-4316-ce08-b8a9716b6a3d
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-0de9f17c
  type: vless
  server: esi.infospeedtest.com
  port: 13286
  uuid: 2ee55469-d026-410b-f4bc-844a63a1342d
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-38a61271
  type: vless
  server: chrom3.infospeedtest.com
  port: 13096
  uuid: b8b81afb-c24b-43b7-e816-0b7dcaf4ce67
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-418dd8eb
  type: vless
  server: 91.107.144.102
  port: 443
  uuid: 75542618-2a4e-4e94-cd5d-f2866e284901
  udp: true
  network: tcp
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-1ab1d7ee
  - vless-7d5bbf94
  - vless-f25121eb
  - vless-c3f8194d
  - vless-c7c88bd9
  - vless-93dddca7
  - vless-68d5b0e0
  - SRCVPN-5c8863c2
  - SRCVPN-193a95fb
  - vless-133e54fe
  - vless-855c6436
  - vless-bf3b69be
  - vless-3dcf73a2
  - vless-16796052
  - vless-1afddd67
  - vless-04763ece
  - vless-4a592b77
  - 300گیگ_39تومان_تسترایگانTickV2bot-30652ad6
  - 300گیگ_39تومان_تسترایگانTickV2bot-b73ea2e2
  - V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-3377a58a
  - Mgfghgjjf-15c72874
  - کانال_تلگرام_Club_Profsor-2b529b48
  - tel_melli1-29628afc
  - گپ_BLUE-873bd25f
  - Sezar_Sec-6bc09e14
  - Sezar_Sec-e95f8957
  - Sezar_Sec-85f48f50
  - Sezar_Sec-08c8801d
  - Sezar_Sec-54b1ecc6
  - مشتی_جوین_بده_ناموصا__xzjinx-e60dad67
  - مشتیجوینبدهناموصاxzjinx-4b961bcb
  - مشتیجوینبدهناموصاxzjinx-a82ca0ff
  - مشتیجوینبدهناموصاxzjinx-bf60ae89
  - مشتی_جوین_بده_ناموصا__xzjinx-0de9f17c
  - مشتی_جوین_بده_ناموصا__xzjinx-38a61271
  - مشتی_جوین_بده_ناموصا__xzjinx-418dd8eb
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
