proxies:
- name: vless-2972cbcc
  type: vless
  server: gsoowjowj.toppho.ir
  port: 8443
  uuid: Anty_Vpn-Anty_Vpn-Anty_Vpn
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-da8457af
  type: vless
  server: rim.fullbodystore.com.tr
  port: 443
  uuid: 2406a224-ba26-43fb-99db-5da807253a5f
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: www.google.com
- name: vless-6b9af263
  type: vless
  server: 212.86.94.101
  port: 33177
  uuid: a8ed95a6-7f54-48d6-bdcf-6c272851b81f
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-3f9d2e24
  type: vless
  server: 5.255.124.97
  port: 26066
  uuid: 5e251be5-4736-49ff-80cf-b41639949a4d
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /
    headers:
      Host: /JOKERRVPNBIA_CHANEL@JOKERRVPN
- name: vless-04c2e90f
  type: vless
  server: 46.31.76.3
  port: 80
  uuid: 215d71a9-0047-4600-9240-7c3b86b62313
  tls: false
  skip-cert-verify: false
  udp: true
  network: xhttp
  servername: journalofbigdata.springeropen.com
- name: vless-a90b6aef
  type: vless
  server: 45.159.148.172
  port: 2092
  uuid: bd12cf37-bd2b-4f3b-be23-e91146bf1914
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-bf8f9820
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-c294bc34
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-86ffd9ac
  type: vless
  server: 188.245.181.233
  port: 8880
  uuid: a2eda8e1-4452-481b-9a71-aab18d3ed17e
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-9a625d43
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  tls: true
  skip-cert-verify: false
  udp: true
  network: ws
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /?ed=2560/?BIA_CHANEL@JOKERRVPN
    headers:
      Host: sub.divib.dynv6.net
- name: '%F0%9F%87%A9%F0%9F%87%AA%20%D9%88%DB%8C%DA%98%D9%87%207%20'
  type: vmess
  server: prthree.marfanet.com
  port: 56321
  uuid: b4f10c2d-4806-4829-8b59-7ad5dc5d9703
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: vless-6379bc39
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-8175e928
  type: vless
  server: pfwie.marfanet.com
  port: 55700
  uuid: 8d4a9bc5-27a2-4b79-9c7e-e02a37967b86
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: refersion.com
- name: 'Telegram:   @Rocket_vpnn'
  type: vmess
  server: 185.215.228.57
  port: 53773
  uuid: a8c44674-2c10-4fb9-f55c-f5586567fbf1
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: vless-d1d62a9c
  type: vless
  server: king.abcd.uno
  port: 13654
  uuid: 39c0a418-944e-4506-bc8a-147b19d71b1c
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-5616f5b9
  type: vless
  server: 91.99.150.28
  port: 443
  uuid: f46c96e3-6d0d-4099-e2dd-60008bc2ced6
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: eset.com
- name: vless-616a776c
  type: vless
  server: holkanas.atroart.ir
  port: 52928
  uuid: dc58f214-4227-4f58-8090-cbcedf1adeba
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-80ae6af8
  type: vless
  server: 172.67.17.195
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-6648faf3
  type: vless
  server: gsoowjowj.toppho.ir
  port: 8443
  uuid: Anty_Vpn-Anty_Vpn
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: L1-3431
  type: vmess
  server: l1.apland.ir
  port: 45090
  uuid: bbb70415-df31-4906-aee3-2f785fab7ca3
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: '@Golestan_VPN - 👈 خرید کانفیگ'
  type: vmess
  server: 62.146.233.112
  port: 36712
  uuid: 9266df42-0830-48c2-8509-4c57b30fe29d
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: vless-fd036908
  type: vless
  server: 199.34.229.63
  port: 443
  uuid: 9ca79e0a-2c5c-4ac8-90e6-6642e41e6189
  tls: true
  skip-cert-verify: false
  udp: true
  network: httpupgrade
  servername: uk1.blackismyfavorite.ir
- name: '%40Golestan_VPN%20-%20%F0%9F%91%88%20%D8%AE%D8%B1%DB%8C%D8%AF%20%DA%A9%D8%A7%D9%86%D9%81%DB%8C%DA%AF'
  type: ss
  server: 62.133.63.212
  port: 57456
  password: c40641c1f89e7acb
  cipher: chacha20-ietf-poly1305
  udp: true
- name: vless-5337b5d6
  type: vless
  server: 172.67.144.232
  port: 443
  uuid: 1e610976-fef5-4ca4-a447-f3530e70603e
  tls: true
  skip-cert-verify: false
  udp: true
  network: ws
  servername: escoffier.changli.ddns-ip.net
  ws-opts:
    path: /proxyip=ayaka.shorekeeper.ir
    headers:
      Host: escoffier.changli.ddns-ip.net
- name: vless-8fba2a0f
  type: vless
  server: 172.67.67.92
  port: 80
  uuid: f78ce1bb-0fa6-4ef4-b4c9-b91014a7055d
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: delam.ahaysiahzangi.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: delam.ahaysiahzangi.dpdns.org
- name: '%40Golestan_VPN%20-%20%F0%9F%91%88%20%D8%AE%D8%B1%DB%8C%D8%AF%20%DA%A9%D8%A7%D9%86%D9%81%DB%8C%DA%AF'
  type: ss
  server: 147.45.178.200
  port: 57456
  password: c40641c1f89e7acb
  cipher: chacha20-ietf-poly1305
  udp: true
- name: Turk-ygaas9wx
  type: vmess
  server: 185.226.93.30
  port: 443
  uuid: 01e893da-1226-4f12-b3e4-724d24c1f53f
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: vless-9ac4f8f1
  type: vless
  server: 193.24.120.249
  port: 1717
  uuid: fa31c2f2-75e2-4d9a-a60a-a445e8f5c445
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-27724d5a
  type: vless
  server: 193.24.120.249
  port: 1717
  uuid: fa31c2f2-75e2-4d9a-a60a-a445e8f5c445
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-c190ce59
  type: vless
  server: 5.160.197.120
  port: 13048
  uuid: f2c0cc0a-f19f-4d9f-c67b-1283bbaadc4b
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-7140101b
  type: vless
  server: 46.31.76.3
  port: 80
  uuid: 215d71a9-0047-4600-9240-7c3b86b62313
  tls: false
  skip-cert-verify: false
  udp: true
  network: xhttp
  servername: journalofbigdata.springeropen.com
- name: vless-28971a6a
  type: vless
  server: 46.31.76.3
  port: 80
  uuid: 215d71a9-0047-4600-9240-7c3b86b62313
  tls: false
  skip-cert-verify: false
  udp: true
  network: xhttp
  servername: journalofbigdata.springeropen.com
- name: vless-1281f08a
  type: vless
  server: 159.69.118.125
  port: 443
  uuid: b3164e0a-f76a-4bb2-83b9-8f385488e836
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: www.psnapptapsi.ir
  flow: xtls-rprx-vision
- name: vless-a9eb2e00
  type: vless
  server: dev.loadbalance.iranstars-shop.ir
  port: 5629
  uuid: 88b7cfdc-1cbb-4f0c-880d-876ace69134e
  tls: false
  skip-cert-verify: false
  udp: true
  network: grpc
  servername: refersion.com
  grpc-opts:
    grpc-service-name: nama
- name: vless-50c27557
  type: vless
  server: xpanel-ir.panelfreedom.com
  port: 2092
  uuid: 39d0b8cc-bfdb-4e30-9f6e-afc171f8a6a2
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-1586a00e
  type: vless
  server: 46.62.154.63
  port: 55555
  uuid: 3ab9cb9a-4ed8-426c-b42d-b3079c89df84
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: stackoverflow.com
- name: https%3A%2F%2Ft.me%2FKANFIG_Poroksi%20%20%D9%84%DB%8C%D9%86%DA%A9%20%DA%86%D9%86%D9%84%D9%85%D9%88%D9%86
  type: ss
  server: series-a2.varzesh360.co
  port: 443
  password: mps3FwmDjLrWaOVg
  cipher: chacha20-ietf-poly1305
  udp: true
- name: vless-06c014d9
  type: vless
  server: 85.133.253.219
  port: 443
  uuid: 24cf00a0-f150-44b7-a2af-1f788d36c491
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: '@vpnv2rayNGv 👈 سرورهای بیشتر در تلگرام'
  type: vmess
  server: npmjs.com
  port: 8080
  uuid: spcmpkl14a
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /hetzner/cdn
    headers:
      Host: spcmpkl14a-9199150242.khastehnabashi.com
- name: vless-1e477d25
  type: vless
  server: 85.133.253.219
  port: 443
  uuid: 24cf00a0-f150-44b7-a2af-1f788d36c491
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-1779accb
  type: vless
  server: 185.215.228.92
  port: 8080
  uuid: 348b8a0c-e28e-4aa4-8f0f-046e3473d7e9
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-bbaa6251
  type: vless
  server: 5.160.197.120
  port: 13048
  uuid: 6dfabd34-8793-4875-cac3-7edb11058310
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-a2515f86
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: b2bb37ae-918a-4c7b-8cfb-3bcf35cf9c7e
  tls: false
  skip-cert-verify: false
  udp: true
  network: httpupgrade
  servername: ''
- name: vless-04921f0b
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: ec833494-665d-4616-92f5-5cb397771f24
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /telegram-NUFiLTER%2Ctelegram-NUFiLTER%2Ctelegram-NUFiLTER%2Ctelegram-NUFiLTER%2Ctelegram-NUFiLTER%2Ctelegram-NUFiLTER%2Ctelegram-NUFiLTER%2Ctelegram-NUFiLTER?ed=80
    headers:
      Host: kk103.4qwertyuiopasdfghjklzxcvbnmmnbvcxzlkjhgfdsapoiuytrewq1234567890.pro.
- name: vless-bdf0e36b
  type: vless
  server: 5.160.197.120
  port: 13048
  uuid: e46b4d13-0d4e-4965-d7f6-aec6869c945c
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-2221ffc8
  type: vless
  server: 185.133.125.4
  port: 19151
  uuid: 84e7d7ea-fbb8-4a62-b3c6-a22165a21bee
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: 🇮🇷 VM-TCP - @TheRainIsHere
  type: vmess
  server: 79.175.131.5
  port: 5006
  uuid: 6dbc3cadefec498bbfc8b4da8d8dc16c
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: vless-0165f36e
  type: vless
  server: 185.133.125.4
  port: 19151
  uuid: 84e7d7ea-fbb8-4a62-b3c6-a22165a21bee
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-7353a18c
  type: vless
  server: 108.162.194.178
  port: 80
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: Telegram:@ShadowProxy66/?ed=2560
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
- name: vless-2be1288d
  type: vless
  server: 172.67.17.195
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-46546ea0
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-77495456
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: f78ce1bb-0fa6-4ef4-b4c9-b91014a7055d
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /TELEGRAM-MARAMBASHI_MARAMBASHI_MARAMBASHI?ed=512
    headers:
      Host: delam.ahaysiahzangi.dpdns.org
- name: vless-58a951d8
  type: vless
  server: 172.67.17.195
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-00b37bdb
  type: vless
  server: 172.66.135.5
  port: 80
  uuid: 5459f68e-d914-4b31-93a3-ecdf638b7a5b
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: abcd.taraneh.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: abcd.taraneh.dpdns.org
- name: vless-ceab7177
  type: vless
  server: 45.131.208.130
  port: 80
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: Telegram@V2ray_Alpha/?ed=2560
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
- name: vless-816a7909
  type: vless
  server: 141.101.121.108
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: '/telegram: @Eternal_Connect - telegram: @Eternal_Connect - telegram: @Eternal_Connect
      - telegram: @Eternal_Connect /?ed=2048'
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: vless-cd82c052
  type: vless
  server: crm.xpersian.com
  port: 8443
  uuid: b8c24464-1925-4338-b431-1f3673434ccf
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: tgju.org
- name: vless-2c201ac5
  type: vless
  server: 62.60.193.203
  port: 49141
  uuid: c053d3eb-e68a-445d-9136-c6f9dd09e90f
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
proxy-groups:
- name: 🚀 Auto Select
  type: url-test
  proxies:
  - vless-2972cbcc
  - vless-da8457af
  - vless-6b9af263
  - vless-3f9d2e24
  - vless-04c2e90f
  - vless-a90b6aef
  - vless-bf8f9820
  - vless-c294bc34
  - vless-86ffd9ac
  - vless-9a625d43
  - '%F0%9F%87%A9%F0%9F%87%AA%20%D9%88%DB%8C%DA%98%D9%87%207%20'
  - vless-6379bc39
  - vless-8175e928
  - 'Telegram:   @Rocket_vpnn'
  - vless-d1d62a9c
  - vless-5616f5b9
  - vless-616a776c
  - vless-80ae6af8
  - vless-6648faf3
  - L1-3431
  - '@Golestan_VPN - 👈 خرید کانفیگ'
  - vless-fd036908
  - '%40Golestan_VPN%20-%20%F0%9F%91%88%20%D8%AE%D8%B1%DB%8C%D8%AF%20%DA%A9%D8%A7%D9%86%D9%81%DB%8C%DA%AF'
  - vless-5337b5d6
  - vless-8fba2a0f
  - '%40Golestan_VPN%20-%20%F0%9F%91%88%20%D8%AE%D8%B1%DB%8C%D8%AF%20%DA%A9%D8%A7%D9%86%D9%81%DB%8C%DA%AF'
  - Turk-ygaas9wx
  - vless-9ac4f8f1
  - vless-27724d5a
  - vless-c190ce59
  - vless-7140101b
  - vless-28971a6a
  - vless-1281f08a
  - vless-a9eb2e00
  - vless-50c27557
  - vless-1586a00e
  - https%3A%2F%2Ft.me%2FKANFIG_Poroksi%20%20%D9%84%DB%8C%D9%86%DA%A9%20%DA%86%D9%86%D9%84%D9%85%D9%88%D9%86
  - vless-06c014d9
  - '@vpnv2rayNGv 👈 سرورهای بیشتر در تلگرام'
  - vless-1e477d25
  - vless-1779accb
  - vless-bbaa6251
  - vless-a2515f86
  - vless-04921f0b
  - vless-bdf0e36b
  - vless-2221ffc8
  - 🇮🇷 VM-TCP - @TheRainIsHere
  - vless-0165f36e
  - vless-7353a18c
  - vless-2be1288d
  - vless-46546ea0
  - vless-77495456
  - vless-58a951d8
  - vless-00b37bdb
  - vless-ceab7177
  - vless-816a7909
  - vless-cd82c052
  - vless-2c201ac5
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 Proxy
  type: select
  proxies:
  - 🚀 Auto Select
  - DIRECT
- name: 🎯 Domestic
  type: select
  proxies:
  - DIRECT
rules:
- DOMAIN-SUFFIX,ir,🎯 Domestic
- GEOIP,IR,🎯 Domestic
- MATCH,🔮 Proxy
