mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 8.8.8.8
  - 1.1.1.1
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
proxies:
- name: vless-fb2477ff
  type: vless
  server: bam.erfann.shop
  port: 15807
  uuid: 8e4d0dba-884f-4bbd-9f1d-ea5ec78efe7d
  udp: true
  network: tcp
- name: net0n3_283-e6955115
  type: ss
  server: 45.87.175.165
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: QCXDxuDlTTMD7jtgHUjIoj
  udp: true
- name: vless-4bd990bb
  type: vless
  server: hell.dl101movis.ir
  port: 80
  uuid: d601250a-e54f-46fe-a984-fb0f1d6d48ce
  udp: true
  network: xhttp
- name: vless-0a0a2194
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  network: tcp
- name: vless-d3f069e4
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  servername: NGINX.NSCl.IR
  skip-cert-verify: true
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-b131060f
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  servername: NGINX.NSCl.IR
  skip-cert-verify: true
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_281-9b484acd
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-0b12d3f9
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  servername: nginx.nscl.ir
  skip-cert-verify: true
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: net0n3_276-c457c4ce
  type: ss
  server: h110vpnnl.outlinekeys.net
  port: 52571
  cipher: chacha20-ietf-poly1305
  password: 2nvtG6pl4Om1G0cWlnyXHl
  udp: true
- name: vless-227b6e55
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-9cec480f
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-d331d66a
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-6108041a
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-7b0b1c07
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-1fe33d7e
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-8e35b9e7
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
    fingerprint: chrome
- name: vless-5c6327b9
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: GB-415812420-0280-734a95ed
  type: ss
  server: series-a2.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: iProxy_Channel_Wifi_36-d89ddcda
  type: vless
  server: 141.101.121.108
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: LexerNet-f689c991
  type: ss
  server: series-a2-me.varzesh360.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: Bog0ELmMM9DSxDdQ
  udp: true
- name: قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-ab8ad27d
  type: vless
  server: test.fast.hosting-ip.com
  port: 80
  uuid: ipcloudflaretamiz
  udp: true
  network: xhttp
- name: نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-0ee531c5
  type: vless
  server: it.panelmarzban.com
  port: 3037
  uuid: a0a3e34d-87e4-4ff3-b04a-875c85325d62
  udp: true
  network: tcp
  tls: true
  servername: refersion.com
  reality-opts:
    public-key: 21V_VkMUD2XRbyRDg7hjpblUAwxHvlLmbarATdhhJQI
    fingerprint: firefox
- name: مشتی_جوین_بده_ناموصا__xzjinx-44480b00
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-cdc052b3
  type: vless
  server: 94.182.136.184
  port: 159
  uuid: 0af94a54-f5d8-43dd-8544-77a56559ea1c
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-8bd2b485
  type: vless
  server: 31.47.45.173
  port: 777
  uuid: ce55d3ed-618b-45b7-d879-368fbb465efd
  udp: true
  network: tcp
- name: Unknown_-_0709_Config724-faf8398e
  type: vless
  server: 141.101.121.55
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: Sezar_sec-948ef6aa
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
    fingerprint: chrome
- name: Sezar_sec-0b68e5b1
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: false
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: Sezar_sec-02a548ae
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
  skip-cert-verify: true
- name: G0Dv2ray-419f2ee2
  type: vless
  server: 172.66.137.85
  port: 80
  uuid: 26bc13af-e442-4956-afd4-b8f85744d26f
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: fggerlad.gerald81.dpdns.org
- name: V2ray1_Ng-de66cc12
  type: vless
  server: 45.131.208.130
  port: 80
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  udp: true
  network: ws
  ws-opts:
    path: Telegram@V2ray_Alpha/?ed=2560
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
- name: V2ray1_Ng-67e52470
  type: vless
  server: 104.16.0.113
  port: 80
  uuid: bbd2882a-c158-4ae6-b53a-5ae6be8dbcb0
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560/?JOKERRVPN
    headers:
      Host: barayeiran.nastaranh.dpdns.org
- name: G0Dv2ray-69fbb61e
  type: vless
  server: 99823232.webnama.com.tr
  port: 1517
  uuid: 3d554bba-9c77-499f-9055-1eb42058ed00
  udp: true
  network: tcp
proxy-groups:
- name: 🚀 PROXY
  type: select
  proxies:
  - ♻️ AUTO
  - DIRECT
  - vless-fb2477ff
  - net0n3_283-e6955115
  - vless-4bd990bb
  - vless-0a0a2194
  - vless-d3f069e4
  - vless-b131060f
  - net0n3_281-9b484acd
  - vless-0b12d3f9
  - net0n3_276-c457c4ce
  - vless-227b6e55
  - vless-9cec480f
  - vless-d331d66a
  - vless-6108041a
  - vless-7b0b1c07
  - vless-1fe33d7e
  - vless-8e35b9e7
  - vless-5c6327b9
  - GB-415812420-0280-734a95ed
  - iProxy_Channel_Wifi_36-d89ddcda
  - LexerNet-f689c991
  - قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-ab8ad27d
  - نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-0ee531c5
  - مشتی_جوین_بده_ناموصا__xzjinx-44480b00
  - مشتی_جوین_بده_ناموصا__xzjinx-cdc052b3
  - مشتی_جوین_بده_ناموصا__xzjinx-8bd2b485
  - Unknown_-_0709_Config724-faf8398e
  - Sezar_sec-948ef6aa
  - Sezar_sec-0b68e5b1
  - Sezar_sec-02a548ae
  - G0Dv2ray-419f2ee2
  - V2ray1_Ng-de66cc12
  - V2ray1_Ng-67e52470
  - G0Dv2ray-69fbb61e
- name: ♻️ AUTO
  type: url-test
  proxies:
  - vless-fb2477ff
  - net0n3_283-e6955115
  - vless-4bd990bb
  - vless-0a0a2194
  - vless-d3f069e4
  - vless-b131060f
  - net0n3_281-9b484acd
  - vless-0b12d3f9
  - net0n3_276-c457c4ce
  - vless-227b6e55
  - vless-9cec480f
  - vless-d331d66a
  - vless-6108041a
  - vless-7b0b1c07
  - vless-1fe33d7e
  - vless-8e35b9e7
  - vless-5c6327b9
  - GB-415812420-0280-734a95ed
  - iProxy_Channel_Wifi_36-d89ddcda
  - LexerNet-f689c991
  - قطع_شدی_بیا_گروه_گوگولی_ProxyOrbit-ab8ad27d
  - نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-0ee531c5
  - مشتی_جوین_بده_ناموصا__xzjinx-44480b00
  - مشتی_جوین_بده_ناموصا__xzjinx-cdc052b3
  - مشتی_جوین_بده_ناموصا__xzjinx-8bd2b485
  - Unknown_-_0709_Config724-faf8398e
  - Sezar_sec-948ef6aa
  - Sezar_sec-0b68e5b1
  - Sezar_sec-02a548ae
  - G0Dv2ray-419f2ee2
  - V2ray1_Ng-de66cc12
  - V2ray1_Ng-67e52470
  - G0Dv2ray-69fbb61e
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- GEOIP,IR,DIRECT
- MATCH,🚀 PROXY
