port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: قطع_شدی_بیا_چنل_proxygodratmand-9a6e7c1f
  type: vmess
  server: 0.numberfive.sbs
  port: 80
  uuid: 4e259c24-53d1-4db4-bc01-5c74cea872a6
  alterId: 0
  cipher: chacha20-poly1305
  tls: false
  network: tcp
  udp: true
- name: vless-24fee467
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-e680e429
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-3d4b4e6d
  type: vless
  server: de6.razercompany.com
  port: 33200
  uuid: c4389c70-1e5a-4bd2-934f-44fb2e62ccf5
  udp: true
  tls: false
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-a502dcaf
  type: vless
  server: 94.182.136.184
  port: 159
  uuid: 0af94a54-f5d8-43dd-8544-77a56559ea1c
  udp: true
  tls: false
  network: tcp
- name: vless-55e9fddd
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: Sezar_Sec-9be2e44f
  type: vless
  server: 3bd9.55dca.e048.f8-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: vless-d37b0b9d
  type: vless
  server: de1.cowjuice.me
  port: 443
  uuid: 955827fc-c729-4a1e-ba6c-d85754c8e937
  udp: true
  tls: false
  network: tcp
  servername: thelocal.de
  reality-opts:
    public-key: O9DMPpwicRcMofaplcvpQStNRogPS_HJY0s5_4EaKQc
    short-id: aabbccdd
- name: vless-2ac2d1d2
  type: vless
  server: marz.querenciavib.xyz
  port: 8443
  uuid: 5c087b17-c044-42c3-8ff4-615dc53feee1
  udp: true
  tls: false
  network: tcp
- name: vless-be5d3d68
  type: vless
  server: bam.erfann.shop
  port: 15807
  uuid: 8e4d0dba-884f-4bbd-9f1d-ea5ec78efe7d
  udp: true
  tls: false
  network: tcp
- name: vless-96b3fd52
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: vless-8b44e0ed
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram-SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: Sezar_Sec-4c3a4ca1
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-b1822428
  type: vless
  server: 91.99.172.196
  port: 28041
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: WpvjPUZ5x3SIvDzSr5q9v0bfhzo36obh3CXIqJVmnkY
    short-id: 91355b9b818617
- name: vpnv2rayNGv_سرورای_بیشتر_با_پینگ_پایین_داخل_چنل-05301a7e
  type: vmess
  server: 0.numberfive.sbs
  port: 80
  uuid: 4e259c24-53d1-4db4-bc01-5c74cea872a6
  alterId: 0
  cipher: chacha20-poly1305
  tls: false
  network: tcp
  udp: true
- name: vless-4e807ef9
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-3b9fe7f9
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-7bd2c61a
  type: vless
  server: real-all3.sdcards.ir
  port: 8501
  uuid: 9666ee62-d1f3-4f6e-8881-c17fee524e31
  udp: true
  tls: false
  network: tcp
  servername: tgju.org
  reality-opts:
    public-key: OJ0wA5wp55uZdD16dutlTZvx1x-rbMMXmiO9D_MMCHI
    short-id: e701a013553059ba
- name: Sezar_Sec-417896c0
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  tls: false
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-aab864ad
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: b54eaa6b-d4fc-4bb3-b3c6-9d0b61da00f7
  udp: true
  tls: false
  network: tcp
- name: Sezar_sec-fadba7a9
  type: vmess
  server: 107.148.6.67
  port: 30001
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  udp: true
  ws-opts:
    path: /path/170733132233
    headers:
      Host: www.53865734.xyz
- name: vless-5edf0017
  type: vless
  server: compose.fast.hosting-ip.com
  port: 80
  uuid: ab80613b-e04b-4af5-bad9-9ca5c448266e
  udp: true
  tls: false
  network: xhttp
- name: vless-51a29a56
  type: vless
  server: hell.dl101movis.ir
  port: 80
  uuid: d601250a-e54f-46fe-a984-fb0f1d6d48ce
  udp: true
  tls: false
  network: xhttp
- name: Sezar_sec-2ad83f42
  type: vless
  server: 92.60.78.221
  port: 443
  uuid: 6897c181-24b1-4880-8660-e6c5c7ee13c7
  udp: true
  tls: false
  network: tcp
  servername: www.tradingview.com
  reality-opts:
    public-key: pkIWxbuPAasjatPaHnAaTnCxVj1RkDFsJEWpLUTOcWY
    short-id: 9917d2350096
- name: vless-63043f83
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sub.divib.dynv6.net
- name: مشتی_جوین_بده_ناموصا__xzjinx-2d3067c8
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: 09694965-369f-48b5-82fa-40aae0236746
  udp: true
  tls: false
  network: tcp
- name: vless-846d0e2f
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: nginx.nscl.ir
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-e786b6c6
  type: vless
  server: 198.62.62.4
  port: 443
  uuid: d0298536-d670-4045-bbb1-ddd5ea68683e
  udp: true
  tls: true
  network: ws
  servername: azadnet-7py.pages.dev
  ws-opts:
    path: /azadnet-7py.pages.dev/?ed=2560
    headers:
      Host: azadnet-7py.pages.dev
- name: قطع_شد_بیا_اینجا_بردارWorldwar_clan-84479ae6
  type: vmess
  server: 0.numberfive.sbs
  port: 80
  uuid: 4e259c24-53d1-4db4-bc01-5c74cea872a6
  alterId: 0
  cipher: chacha20-poly1305
  tls: false
  network: tcp
  udp: true
- name: vless-a097edd5
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-a5e9d3af
  type: vless
  server: 194.135.46.24
  port: 443
  uuid: 49eb1e7a-2b76-4915-ba85-977c0e0d2ab8
  udp: true
  tls: false
  network: tcp
- name: vless-319b239d
  type: vless
  server: fastlyeeeeee.fast.hosting-ip.com
  port: 80
  uuid: cdnfastlycash
  udp: true
  tls: false
  network: xhttp
- name: Sezar_sec-47c15f8f
  type: trojan
  server: 155.117.228.70
  port: 26193
  password: 7367d04e-4c59-4dff-a50e-12e730a09891
  udp: true
- name: Sezar_Sec-de2de82f
  type: vless
  server: 3bd9.55dca.e048.f9-fef1f.yfjcs.com
  port: 443
  uuid: 627712cf-d0e1-4545-81fb-241e7fda0284
  udp: true
  tls: true
  network: tcp
  servername: yfsg-1.xn--4gq62f52gppi29k.com
- name: vless-618ca403
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN--
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: مشتی_جوین_بده_ناموصا__xzjinx-6a4adff4
  type: vless
  server: 37.202.226.148
  port: 443
  uuid: e6daaeba-5a7c-4933-89b0-0078c14c50f1
  udp: true
  tls: false
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-793a6027
  type: vless
  server: 94.182.136.184
  port: 80
  uuid: 3d9e229a-e6b6-48a3-9336-4c88d1bff82e
  udp: true
  tls: false
  network: tcp
- name: vless-060bdc63
  type: vless
  server: vpconnect.ahadbala.ir
  port: 80
  uuid: 3f0c3cef-75c0-4253-a62e-d89f5a45dcc1
  udp: true
  tls: false
  network: tcp
- name: 1قطع_شد_بیا_اینجا_بردارvpn_mmdparsa-1e985b2f
  type: vless
  server: 91.107.141.97
  port: 39466
  uuid: 40eaefca-ede1-4ff6-8f3a-807dc36c9b74
  udp: true
  tls: false
  network: tcp
- name: net0n3_283-083930c9
  type: ss
  server: 45.87.175.165
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: QCXDxuDlTTMD7jtgHUjIoj
  udp: true
- name: user-Fast-17d7b0e2
  type: vless
  server: fast.sanaei1.milxbywkaiwnx.xyz
  port: 3333
  uuid: 41811b66-2948-422e-8e72-06148b0bc97d
  udp: true
  tls: false
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-68c05b0e
  type: vless
  server: 31.47.45.173
  port: 777
  uuid: ce55d3ed-618b-45b7-d879-368fbb465efd
  udp: true
  tls: false
  network: tcp
- name: Sezar_Sec-2c6abd8d
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  tls: true
  network: ws
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: vless-7b276a91
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-251e5394
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-4645d9a0
  type: vless
  server: 104.18.26.90
  port: 443
  uuid: b28eb861-1748-4200-ba72-278669edc33b
  udp: true
  tls: true
  network: ws
  servername: barayeiranmahsang.mahmoodchitooz.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: barayeiranmahsang.mahmoodchitooz.dpdns.org
- name: net0n3_281-31ef4882
  type: ss
  server: 131.145.123.5
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: vless-09c1869c
  type: vless
  server: 172.67.92.147
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  tls: true
  network: ws
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: vless-8b8c728d
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  tls: false
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
    headers:
      Host: null
- name: vless-23ee7589
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: stripe.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-5e1053f7
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  tls: false
  network: tcp
  servername: yahoo.com
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
  - قطع_شدی_بیا_چنل_proxygodratmand-9a6e7c1f
  - vless-24fee467
  - vless-e680e429
  - vless-3d4b4e6d
  - مشتی_جوین_بده_ناموصا__xzjinx-a502dcaf
  - vless-55e9fddd
  - Sezar_Sec-9be2e44f
  - vless-d37b0b9d
  - vless-2ac2d1d2
  - vless-be5d3d68
  - vless-96b3fd52
  - vless-8b44e0ed
  - Sezar_Sec-4c3a4ca1
  - vless-b1822428
  - vpnv2rayNGv_سرورای_بیشتر_با_پینگ_پایین_داخل_چنل-05301a7e
  - vless-4e807ef9
  - vless-3b9fe7f9
  - vless-7bd2c61a
  - Sezar_Sec-417896c0
  - مشتی_جوین_بده_ناموصا__xzjinx-aab864ad
  - Sezar_sec-fadba7a9
  - vless-5edf0017
  - vless-51a29a56
  - Sezar_sec-2ad83f42
  - vless-63043f83
  - مشتی_جوین_بده_ناموصا__xzjinx-2d3067c8
  - vless-846d0e2f
  - vless-e786b6c6
  - قطع_شد_بیا_اینجا_بردارWorldwar_clan-84479ae6
  - vless-a097edd5
  - نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-a5e9d3af
  - vless-319b239d
  - Sezar_sec-47c15f8f
  - Sezar_Sec-de2de82f
  - vless-618ca403
  - مشتی_جوین_بده_ناموصا__xzjinx-6a4adff4
  - مشتی_جوین_بده_ناموصا__xzjinx-793a6027
  - vless-060bdc63
  - 1قطع_شد_بیا_اینجا_بردارvpn_mmdparsa-1e985b2f
  - net0n3_283-083930c9
  - user-Fast-17d7b0e2
  - مشتی_جوین_بده_ناموصا__xzjinx-68c05b0e
  - Sezar_Sec-2c6abd8d
  - vless-7b276a91
  - vless-251e5394
  - vless-4645d9a0
  - net0n3_281-31ef4882
  - vless-09c1869c
  - vless-8b8c728d
  - vless-23ee7589
  - vless-5e1053f7
- name: AUTO
  type: url-test
  proxies:
  - قطع_شدی_بیا_چنل_proxygodratmand-9a6e7c1f
  - vless-24fee467
  - vless-e680e429
  - vless-3d4b4e6d
  - مشتی_جوین_بده_ناموصا__xzjinx-a502dcaf
  - vless-55e9fddd
  - Sezar_Sec-9be2e44f
  - vless-d37b0b9d
  - vless-2ac2d1d2
  - vless-be5d3d68
  - vless-96b3fd52
  - vless-8b44e0ed
  - Sezar_Sec-4c3a4ca1
  - vless-b1822428
  - vpnv2rayNGv_سرورای_بیشتر_با_پینگ_پایین_داخل_چنل-05301a7e
  - vless-4e807ef9
  - vless-3b9fe7f9
  - vless-7bd2c61a
  - Sezar_Sec-417896c0
  - مشتی_جوین_بده_ناموصا__xzjinx-aab864ad
  - Sezar_sec-fadba7a9
  - vless-5edf0017
  - vless-51a29a56
  - Sezar_sec-2ad83f42
  - vless-63043f83
  - مشتی_جوین_بده_ناموصا__xzjinx-2d3067c8
  - vless-846d0e2f
  - vless-e786b6c6
  - قطع_شد_بیا_اینجا_بردارWorldwar_clan-84479ae6
  - vless-a097edd5
  - نیم_ساعت_دیگه_قطع_میکنم_قطع_شدی_بیا_چنل_proxygodratmand-a5e9d3af
  - vless-319b239d
  - Sezar_sec-47c15f8f
  - Sezar_Sec-de2de82f
  - vless-618ca403
  - مشتی_جوین_بده_ناموصا__xzjinx-6a4adff4
  - مشتی_جوین_بده_ناموصا__xzjinx-793a6027
  - vless-060bdc63
  - 1قطع_شد_بیا_اینجا_بردارvpn_mmdparsa-1e985b2f
  - net0n3_283-083930c9
  - user-Fast-17d7b0e2
  - مشتی_جوین_بده_ناموصا__xzjinx-68c05b0e
  - Sezar_Sec-2c6abd8d
  - vless-7b276a91
  - vless-251e5394
  - vless-4645d9a0
  - net0n3_281-31ef4882
  - vless-09c1869c
  - vless-8b8c728d
  - vless-23ee7589
  - vless-5e1053f7
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,PROXY
