mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: vless-d2475725
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-6d16b602
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN--SRCVPN-
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-0f0b50bf
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-86f951c8
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN--SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-bec99a97
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-e957c544
  type: vless
  server: 91.99.176.57
  port: 2060
  uuid: Telegram--SRCVPN
  udp: true
  network: ws
  ws-opts:
    path: /-@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN---@SRCVPN
- name: vless-9e082419
  type: vless
  server: 91.99.176.57
  port: 2025
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-9597ee99
  type: vless
  server: 91.99.176.57
  port: 2026
  uuid: Telegram--SRCVPN-SRCVPN-SRCVPN
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZYOJiXfnupbX7P2IG8VmWZrZCA9QOY39GYYiTyZ21UE
    short-id: 85decdebbcf6c7bb
- name: vless-9c3ccc0b
  type: vless
  server: accounting.vinamarketcenter.ir
  port: 443
  uuid: 5cfba4ac-105a-452a-ac10-88b1adf784ee
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: T7Cwk-B3EvZqqRywIgN_TNotJiUOXYUI9bHqYKPnTi0
    short-id: 105e89ba3d2a1c3b
- name: vless-a532f8b3
  type: vless
  server: 91.99.160.151
  port: 443
  uuid: 153ee04c-dcc1-4ef8-a146-8fb31cec1f48
  udp: true
  network: tcp
- name: vless-6e231f7b
  type: vless
  server: 62.60.223.6
  port: 2080
  uuid: bea34b73-3244-475b-b914-7bb80e1cda91
  udp: true
  network: tcp
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: L3lJWdU7mHijSkNaNt-m29OYnKnHvHYRxg2Y8XXFdng
    short-id: bf517367267685
- name: vless-6fde149e
  type: vless
  server: 91.99.195.6
  port: 80
  uuid: 91a5d5b3-4b88-4359-aeec-e1532f535fd6
  udp: true
  network: grpc
  tls: true
  skip-cert-verify: true
  reality-opts:
    public-key: ZO276Z5WXIqCmNLXT8Lewzjhhgm365JUJXAKyKq8Rz4
    short-id: bc063769cb
  grpc-opts:
    grpc-service-name: refersion.com
- name: vless-b365f58c
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /zula.ir
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: vless-02cfd418
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-72664e88
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /zula.ir
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-fc1e7f83
  type: vless
  server: 91.99.184.231
  port: 45103
  uuid: 6bdc18b7-a33f-46ae-a5e3-df7cb21f36b2
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: vless-8f158fd1
  type: vless
  server: 151.101.3.8
  port: 80
  uuid: turboo-server
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: turboo-server1.game
- name: Sezar_Sec-46647199
  type: vless
  server: 104.16.243.59
  port: 443
  uuid: 75fde681-ec64-4654-86fa-30732e8e179c
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: NGINX.NSCl.IR
  ws-opts:
    path: /assets
    headers:
      Host: nginx.nscl.ir
- name: Sezar_Sec-58c4611b
  type: vless
  server: 162.159.129.11
  port: 2053
  uuid: b1a8ceea-6601-45b5-a674-7e5b64ab6f6f
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: sub.divib.dynv6.net
  ws-opts:
    path: /Telegram@mtmvpn?ed=2560
    headers:
      Host: sub.divib.dynv6.net
- name: Sezar_Sec-de2075ca
  type: vless
  server: 91.99.187.13
  port: 443
  uuid: 7a66b8ef-9713-4b69-b839-6bb45070af35
  udp: true
  network: tcp
- name: Sezar_Sec-8a04c157
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: Sezar_Sec-b3ecda7f
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: barayeiranmahsang.sabzipolobamahi.dpdns.org
  ws-opts:
    path: /?ed=2560/?CHANEL@RK_VPS@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps----@Rk_Vps
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: Golestan_VPN_-__خرید_کانفیگ-8cf9eb72
  type: vless
  server: 45.82.251.147
  port: 8880
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: Golestan_VPN_-__خرید_کانفیگ-841d6336
  type: vmess
  server: 37.221.125.159
  port: 33940
  uuid: 353e0787-71bc-442d-9c9d-902f90359eb5
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: Golestan_VPN_-__خرید_کانفیگ-56795763
  type: vmess
  server: 37.221.125.159
  port: 33940
  uuid: 353e0787-71bc-442d-9c9d-902f90359eb5
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-68350cd2
  type: vless
  server: 104.18.26.90
  port: 80
  uuid: 92f481b6-ad92-43e4-a683-2bb0aeaa9846
  udp: true
  network: ws
  ws-opts:
    path: /?ed=2590
    headers:
      Host: dw.alibichareh.dpdns.org
- name: V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-ef9d810e
  type: vless
  server: 101reel.com
  port: 443
  uuid: b55ec078-3b17-4ed1-a697-71f464cdcaaa
  udp: true
  network: ws
  tls: true
  skip-cert-verify: true
  servername: barayeiranmahsang.sabzipolobamahi.dpdns.org
  ws-opts:
    path: /?ed=2560/?JOKERRVPNBIA_CHANEL@JOKERRVPN
    headers:
      Host: barayeiranmahsang.sabzipolobamahi.dpdns.org
- name: Channelalammzar-91b8b30d
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: mps3FwmDjLrWaOVg
  udp: true
- name: کانال_تلگرامی_irproxyblue-ca43125c
  type: vless
  server: tunnel.aghamehdi52.ir
  port: 2000
  uuid: 16f4a1c4-905e-4816-b825-443ec775bbc4
  udp: true
  network: tcp
- name: 300گیگ_39تومان_تسترایگانTickV2bot-956a2fe4
  type: vmess
  server: 91.107.154.77
  port: 4001
  uuid: ca73250a-5395-4585-b1ec-6d2041e44aef
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: 300گیگ_39تومان_تسترایگانTickV2bot-f914986e
  type: vmess
  server: 91.107.154.77
  port: 4001
  uuid: ca73250a-5395-4585-b1ec-6d2041e44aef
  alterId: 0
  cipher: aes-128-gcm
  tls: false
  skip-cert-verify: false
  network: tcp
  udp: true
- name: V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-56865bb0
  type: vless
  server: 46.62.139.178
  port: 1111
  uuid: 98635c25-7ce5-416e-9a45-3fcadc878f93
  udp: true
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: مشتی_جوین_بده_ناموصا__xzjinx-6243ba3a
  type: vless
  server: 87.107.144.71
  port: 54465
  uuid: 49203d20-5f1b-4628-d526-9a6825c3f5f3
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-b64915d0
  type: vless
  server: 5.160.197.120
  port: 16644
  uuid: c2d3a355-e556-40e0-cd5a-41dff6eb525d
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-ecf29801
  type: vless
  server: 91.107.144.102
  port: 443
  uuid: edf3ab50-46b4-4046-eaf9-db12fe598cd1
  udp: true
  network: tcp
- name: مشتیجوینبدهناموصاxzjinx-80c033a2
  type: vless
  server: chrom3.infospeedtest.com
  port: 13096
  uuid: bb497033-e322-4316-ce08-b8a9716b6a3d
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-df7c6eaa
  type: vless
  server: esi.infospeedtest.com
  port: 13286
  uuid: 2ee55469-d026-410b-f4bc-844a63a1342d
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-fb2d52c6
  type: vless
  server: chrom3.infospeedtest.com
  port: 13096
  uuid: b8b81afb-c24b-43b7-e816-0b7dcaf4ce67
  udp: true
  network: tcp
- name: مشتی_جوین_بده_ناموصا__xzjinx-d3769b45
  type: vless
  server: 91.107.144.102
  port: 443
  uuid: 75542618-2a4e-4e94-cd5d-f2866e284901
  udp: true
  network: tcp
proxy-groups:
- name: 🚀 Proxy
  type: select
  proxies:
  - ♻️ Auto
  - 🔯 Fallback
  - 🔮 LoadBalance
  - DIRECT
- name: ♻️ Auto
  type: url-test
  proxies: &id001
  - vless-d2475725
  - vless-6d16b602
  - vless-0f0b50bf
  - vless-86f951c8
  - vless-bec99a97
  - vless-e957c544
  - vless-9e082419
  - vless-9597ee99
  - vless-9c3ccc0b
  - vless-a532f8b3
  - vless-6e231f7b
  - vless-6fde149e
  - vless-b365f58c
  - vless-02cfd418
  - vless-72664e88
  - vless-fc1e7f83
  - vless-8f158fd1
  - Sezar_Sec-46647199
  - Sezar_Sec-58c4611b
  - Sezar_Sec-de2075ca
  - Sezar_Sec-8a04c157
  - Sezar_Sec-b3ecda7f
  - Golestan_VPN_-__خرید_کانفیگ-8cf9eb72
  - Golestan_VPN_-__خرید_کانفیگ-841d6336
  - Golestan_VPN_-__خرید_کانفیگ-56795763
  - V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-68350cd2
  - V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-ef9d810e
  - Channelalammzar-91b8b30d
  - کانال_تلگرامی_irproxyblue-ca43125c
  - 300گیگ_39تومان_تسترایگانTickV2bot-956a2fe4
  - 300گیگ_39تومان_تسترایگانTickV2bot-f914986e
  - V2rayePro_عضو_کانال_تلگرام_نباشی_سرور_قطع_میشه-56865bb0
  - مشتی_جوین_بده_ناموصا__xzjinx-6243ba3a
  - مشتیجوینبدهناموصاxzjinx-b64915d0
  - مشتیجوینبدهناموصاxzjinx-ecf29801
  - مشتیجوینبدهناموصاxzjinx-80c033a2
  - مشتی_جوین_بده_ناموصا__xzjinx-df7c6eaa
  - مشتی_جوین_بده_ناموصا__xzjinx-fb2d52c6
  - مشتی_جوین_بده_ناموصا__xzjinx-d3769b45
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 🔯 Fallback
  type: fallback
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Global
  type: select
  proxies:
  - 🚀 Proxy
  - DIRECT
- name: 🍃 Hijacking
  type: select
  proxies:
  - REJECT
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- DOMAIN-KEYWORD,ads,🍃 Hijacking
- DOMAIN-KEYWORD,analytics,🍃 Hijacking
- DOMAIN-KEYWORD,facebook,🌍 Global
- DOMAIN-KEYWORD,google,🌍 Global
- DOMAIN-KEYWORD,instagram,🌍 Global
- DOMAIN-KEYWORD,telegram,🌍 Global
- DOMAIN-KEYWORD,twitter,🌍 Global
- DOMAIN-KEYWORD,youtube,🌍 Global
- MATCH,🚀 Proxy
