proxies:
- name: vless-5f371f61
  type: vless
  server: 104.17.147.22
  port: 443
  uuid: 4d91916f-a7fd-419b-8b90-640bb8d1b9f4
  tls: true
  skip-cert-verify: false
  udp: true
  network: ws
  servername: TITanTabLOmaNAHaMRaH.IR
  ws-opts:
    path: /L4h47GkKWsH8we4z/MzUuMTgwLjIyOS4x?ed=2560
    headers:
      Host: titantablomanahamrah.ir
- name: vless-c90c708c
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: a812a015-a65b-4003-ac5f-266e141c6405
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2048
    headers:
      Host: Www.speedtest.net.developsp.ir.vegaskala.com.
- name: vless-fd0211d0
  type: vless
  server: 104.17.147.22
  port: 2053
  uuid: 704198c4-37b9-473d-a5de-0333276f2f6c
  tls: true
  skip-cert-verify: false
  udp: true
  network: ws
  servername: maHsA2.cFFoRM.sIte
  ws-opts:
    path: /dG8nlHvMhylFIEQ3/c2hpcmVuLnlhZW1pa28uZ2dmZi5uZXQ=
    headers:
      Host: mahsa2.cfform.site
- name: vless-fffdf4cd
  type: vless
  server: srcvpn.fast.hosting-ip.com
  port: 80
  uuid: '%54%45%4C%45%47%52%41%4D%2D%4E%55%46%69%4C%54%45%52'
  tls: false
  skip-cert-verify: false
  udp: true
  network: xhttp
  servername: ''
- name: vless-7c6763c6
  type: vless
  server: srcvpn.fast.hosting-ip.com
  port: 80
  uuid: 3ec5186b-d636-48b0-9a0a-30d824f63078
  tls: false
  skip-cert-verify: false
  udp: true
  network: xhttp
  servername: ''
proxy-groups:
- name: 🚀 Auto Select
  type: url-test
  proxies:
  - vless-5f371f61
  - vless-c90c708c
  - vless-fd0211d0
  - vless-fffdf4cd
  - vless-7c6763c6
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 Proxy
  type: select
  proxies:
  - 🚀 Auto Select
  - DIRECT
- name: 🎯 Domestic
  type: select
  proxies:
  - DIRECT
rules:
- DOMAIN-SUFFIX,ir,🎯 Domestic
- GEOIP,IR,🎯 Domestic
- MATCH,🔮 Proxy
