proxies:
- name: vless-65331caa
  type: vless
  server: 81.12.30.51
  port: 58045
  uuid: 9deda4f9-a9b9-4614-b840-ece9998ec6db
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /
    headers: {}
- name: vless-d99475df
  type: vless
  server: 212.33.201.222
  port: 2054
  uuid: d843b700-0e0d-5ad9-72d9-46ced5785cd1
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-e11ee247
  type: vless
  server: 141.101.121.55
  port: 8080
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2048
    headers:
      Host: 1750293123492.china.baidu.bilibili.china.aeko.cn
- name: vless-694dfc12
  type: vless
  server: 104.24.56.187
  port: 80
  uuid: e6236ebc-7334-4bed-977f-0c20bcdfcc00
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560
    headers:
      Host: a1.ghormehsabzi.dpdns.org
- name: vless-231f676c
  type: vless
  server: 77.83.175.102
  port: 443
  uuid: f09771b9-939d-4e54-bedf-e427d8f38db9
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: arvancloud.ir
  flow: xtls-rprx-vision
- name: vless-5f4bc5f3
  type: vless
  server: 91.99.203.69
  port: 51615
  uuid: 2eaef053-5fd6-4def-b234-d760690355ff
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: ''
- name: vless-233c9f2b
  type: vless
  server: 104.16.180.35
  port: 80
  uuid: 92f481b6-ad92-43e4-a683-2bb0aeaa9846
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: dw.alibichareh.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: dw.alibichareh.dpdns.org
- name: vless-847c6fd0
  type: vless
  server: 104.17.209.145
  port: 80
  uuid: 92f481b6-ad92-43e4-a683-2bb0aeaa9846
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: dw.alibichareh.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: dw.alibichareh.dpdns.org
- name: vless-dbf20461
  type: vless
  server: www.speedtest.net
  port: 80
  uuid: a812a015-a65b-4003-ac5f-266e141c6405
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2048
    headers:
      Host: Www.speedtest.net.developsp.ir.vegaskala.com.
- name: vless-15eff956
  type: vless
  server: 172.67.17.195
  port: 80
  uuid: 6f690965-3be3-43bb-9331-3ead6efb20aa
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: ''
  ws-opts:
    path: /?ed=2560
    headers:
      Host: sib.sibzamini.dpdns.org
- name: vless-eb430cc1
  type: vless
  server: srcvpn.fast.hosting-ip.com
  port: 80
  uuid: 3ec5186b-d636-48b0-9a0a-30d824f63078
  tls: false
  skip-cert-verify: false
  udp: true
  network: xhttp
  servername: ''
- name: vless-5da473fd
  type: vless
  server: 172.67.78.196
  port: 80
  uuid: dfdf1c0a-5e52-4746-88bd-19d4e4ac7853
  tls: false
  skip-cert-verify: false
  udp: true
  network: ws
  servername: tannaz.juveitaly.dpdns.org
  ws-opts:
    path: /?ed=2560
    headers:
      Host: tannaz.juveitaly.dpdns.org
- name: vless-21d2ca9b
  type: vless
  server: srcvpn.fast.hosting-ip.com
  port: 80
  uuid: '%54%45%4C%45%47%52%41%4D%2D%4E%55%46%69%4C%54%45%52'
  tls: false
  skip-cert-verify: false
  udp: true
  network: xhttp
  servername: ''
- name: vless-27cf008c
  type: vless
  server: 150.241.65.211
  port: 443
  uuid: be5fab84-5edb-4800-927e-243f6e4309bf
  tls: false
  skip-cert-verify: false
  udp: true
  network: tcp
  servername: www.latimes.com
proxy-groups:
- name: 🚀 Auto Select
  type: url-test
  proxies:
  - vless-65331caa
  - vless-d99475df
  - vless-e11ee247
  - vless-694dfc12
  - vless-231f676c
  - vless-5f4bc5f3
  - vless-233c9f2b
  - vless-847c6fd0
  - vless-dbf20461
  - vless-15eff956
  - vless-eb430cc1
  - vless-5da473fd
  - vless-21d2ca9b
  - vless-27cf008c
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🔮 Proxy
  type: select
  proxies:
  - 🚀 Auto Select
  - DIRECT
- name: 🎯 Domestic
  type: select
  proxies:
  - DIRECT
rules:
- DOMAIN-SUFFIX,ir,🎯 Domestic
- GEOIP,IR,🎯 Domestic
- MATCH,🔮 Proxy
