name: Extract VPN Configs (User Client)
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Set up Telegram API credentials and Session
        run: |
          echo "API_ID=${{ secrets.API_ID }}" >> $GITHUB_ENV
          echo "API_HASH=${{ secrets.API_HASH }}" >> $GITHUB_ENV
          echo "CHANNELS_JSON=${{ secrets.CHANNELS_LIST }}" >> $GITHUB_ENV
          echo "GROUPS_JSON=${{ secrets.GROUPS_LIST }}" >> $GITHUB_ENV
          echo "SESSION_STRING=${{ secrets.PYROGRAM_SESSION }}" >> $GITHUB_ENV
          
          # Decode the Base64 session string and write to file
          echo "${{ secrets.PYROGRAM_SESSION }}" | base64 --decode > my_account.session
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}

      - name: Run main.py
        run: python main.py

      - name: Commit and Push new configs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Config-jo.yaml Config_jo.txt
          git diff --staged --quiet || git commit -m "Update VPN configs (GitHub Actions)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
