name: Extract and Test VPN Configs (User Client)

on:
  schedule:
    - cron: '0 6,14,22 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install tgcrypto # اضافه کردن این خط برای جلوگیری از هشدار سرعت

      - name: Set up Telegram API credentials and Session
        run: |
          echo "API_ID=${{ secrets.API_ID }}" >> $GITHUB_ENV
          echo "API_HASH=${{ secrets.API_HASH }}" >> $GITHUB_ENV

          # Create the session file from secret using EOF marker
          cat <<EOF > my_account.session
          ${{ secrets.PYROGRAM_SESSION }}
          EOF
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}

      - name: Run main.py
        run: python main.py

      - name: Commit and Push new configs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Config-jo.yaml Config_jo.txt
          git diff --staged --quiet || git commit -m "Update VPN configs (GitHub Actions)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
