name: Extract and Test VPN Configs (User Client)

on:
  schedule:
    - cron: '0 6,14,22 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions: # این بلاک را اضافه کنید
      contents: write # این مجوز را اضافه کنید
      # issues: write # اگر می‌خواهید Issues را هم مدیریت کنید (اختیاری)
      # pull-requests: write # اگر می‌خواهید Pull Requests را هم مدیریت کنید (اختیاری)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install tgcrypto

      - name: Set up Telegram API credentials and Session
        run: |
          echo "API_ID=${{ secrets.API_ID }}" >> $GITHUB_ENV
          echo "API_HASH=${{ secrets.API_HASH }}" >> $GITHUB_ENV

          echo "${{ secrets.PYROGRAM_SESSION }}" | base64 --decode > v2rayTrack.session # نام فایل رو اینجا هم چک کنید

      - name: Run main.py
        run: python main.py

      - name: Commit and Push new configs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Config-jo.yaml Config_jo.txt
          git diff --staged --quiet || git commit -m "Update VPN configs (GitHub Actions)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
