name: Extract and Commit VPN Configs

on:
  schedule:
    # اجرا هر 2 ساعت
    - cron: '0 */2 * * *'
  # اجازه اجرای دستی
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyrogram tgcrypto pyyaml

      - name: 4. Run Python Script
        # ✨ مهمترین بخش: تمام سکرت‌ها اینجا به اسکریپت پاس داده می‌شوند
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
        # مطمئن شوید که نام اسکریپت شما 'main.py' است
        run: python main.py

      - name: 5. Commit and Push new configs
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add Config-jo.yaml Config_jo.txt
          # فقط در صورتی که تغییری وجود داشته باشد، کامیت و پوش کن
          git diff --staged --quiet || git commit -m "Update VPN configs"
          git push
