name: Extract VPN Configs (User Client)

on:
  schedule:
    # زمان‌بندی اجرا در ساعت‌های 06:00، 14:00، 22:00 UTC هر روز
    # برای مثال: 06:00 UTC = 09:30 IRT
    # 14:00 UTC = 17:30 IRT
    # 22:00 UTC = 01:30 IRT (روز بعد)
    - cron: '0 */2 * * *'

  workflow_dispatch: # اجازه اجرای دستی از رابط کاربری گیت‌هاب

jobs:
  run-script:
    runs-on: ubuntu-latest # سیستم عامل Runner
    permissions:
      contents: write # این مجوز برای push کردن تغییرات به مخزن ضروری است

    steps:
      - name: Checkout repository # دانلود کد مخزن
        uses: actions/checkout@v4

      - name: Set up Python # نصب پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # نسخه پایتون

      - name: Install Python dependencies # نصب کتابخانه‌های پایتون از requirements.txt
        run: pip install -r requirements.txt

      - name: Set up Telegram API credentials and Session # تنظیم اطلاعات API تلگرام و ایجاد فایل سشن
        run: |
          echo "API_ID=${{ secrets.API_ID }}" >> $GITHUB_ENV
          echo "API_HASH=${{ secrets.API_HASH }}" >> $GITHUB_ENV
          echo "SESSION_STRING=${{ secrets.SESSION_STRING }}" >> $GITHUB_ENV
          echo "CHANNELS=${{ secrets.CHANNELS }}" >> $GITHUB_ENV
          echo "GROUPS=${{ secrets.GROUPS }}" >> $GITHUB_ENV
          echo "CHANNEL_SEARCH_LIMIT=${{ secrets.CHANNEL_SEARCH_LIMIT }}" >> $GITHUB_ENV
          echo "GROUP_SEARCH_LIMIT=${{ secrets.GROUP_SEARCH_LIMIT }}" >> $GITHUB_ENV

      - name: Run main.py # اجرای اسکریپت اصلی پایتون
        run: python main.py

      - name: Commit and Push new configs # کامیت و پوش کردن کانفیگ‌های جدید
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Config-jo.yaml Config_jo.txt
          git diff --staged --quiet || git commit -m "Update VPN configs (GitHub Actions)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
