name: Extract and Commit VPN Configs

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyrogram tgcrypto pyyaml

      - name: 4. Run Python Script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          # ✨✨ مهم: نام سکرت شما از عکس خوانده شد و اینجا اصلاح گردید
          SESSION_STRING: ${{ secrets.PYROGRAM_SESSION }}
        
        run: python main.py

      - name: 5. Commit and Push new configs
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add Config-jo.yaml Config_jo.txt
          git diff --staged --quiet || git commit -m "Update VPN configs"
          git push
